In [1]:
from utils import *
import numpy as np
import torch, os
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV

In [2]:
set_random_seed(42)

Seed: 42


In [3]:
# def scaling_embeddings(embeddings):
#     for i in range(len(embeddings)):
#         embeddings[i] = StandardScaler().fit_transform(embeddings[i])
#     return embeddings

def reshape_embeddings(embeddings):
    if embeddings.shape[1] == 1:
        embeddings = embeddings.squeeze(1)
    return embeddings

In [4]:
def add_2_embeddings(embeddings1, embeddings2):
    embeddings1 = reshape_embeddings(embeddings1)
    embeddings2 = reshape_embeddings(embeddings2)
    # Numpy Add
    return embeddings1 + embeddings2

def add_3_embeddings(embeddings1, embeddings2, embeddings3):
    embeddings1 = reshape_embeddings(embeddings1)
    embeddings2 = reshape_embeddings(embeddings2)
    embeddings3 = reshape_embeddings(embeddings3)
    return embeddings1 + embeddings2 + embeddings3

In [5]:
bert_hatebert_added_dynahate_train = add_2_embeddings(bert_dynahate_train_embeddings, hatebert_dynahate_train_embeddings)
bert_hatebert_added_dynahate_dev = add_2_embeddings(bert_dynahate_dev_embeddings, hatebert_dynahate_dev_embeddings)
bert_hatebert_added_dynahate_test = add_2_embeddings(bert_dynahate_test_embeddings, hatebert_dynahate_test_embeddings)

bert_bertweet_added_dynahate_train = add_2_embeddings(bert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
bert_bertweet_added_dynahate_dev = add_2_embeddings(bert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
bert_bertweet_added_dynahate_test = add_2_embeddings(bert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

hatebert_bertweet_added_dynahate_train = add_2_embeddings(hatebert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
hatebert_bertweet_added_dynahate_dev = add_2_embeddings(hatebert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
hatebert_bertweet_added_dynahate_test = add_2_embeddings(hatebert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

bert_hatebert_bertweet_added_dynahate_train = add_3_embeddings(bert_dynahate_train_embeddings, hatebert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
bert_hatebert_bertweet_added_dynahate_dev = add_3_embeddings(bert_dynahate_dev_embeddings, hatebert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
bert_hatebert_bertweet_added_dynahate_test = add_3_embeddings(bert_dynahate_test_embeddings, hatebert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

bert_hatebert_added_olid_train = add_2_embeddings(bert_olid_train_embeddings, hatebert_olid_train_embeddings)
bert_hatebert_added_olid_dev = add_2_embeddings(bert_olid_dev_embeddings, hatebert_olid_dev_embeddings)
bert_hatebert_added_olid_test = add_2_embeddings(bert_olid_test_embeddings, hatebert_olid_test_embeddings)

bert_bertweet_added_olid_train = add_2_embeddings(bert_olid_train_embeddings, bertweet_olid_train_embeddings)
bert_bertweet_added_olid_dev = add_2_embeddings(bert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
bert_bertweet_added_olid_test = add_2_embeddings(bert_olid_test_embeddings, bertweet_olid_test_embeddings)

hatebert_bertweet_added_olid_train = add_2_embeddings(hatebert_olid_train_embeddings, bertweet_olid_train_embeddings)
hatebert_bertweet_added_olid_dev = add_2_embeddings(hatebert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
hatebert_bertweet_added_olid_test = add_2_embeddings(hatebert_olid_test_embeddings, bertweet_olid_test_embeddings)

bert_hatebert_bertweet_added_olid_train = add_3_embeddings(bert_olid_train_embeddings, hatebert_olid_train_embeddings, bertweet_olid_train_embeddings)
bert_hatebert_bertweet_added_olid_dev = add_3_embeddings(bert_olid_dev_embeddings, hatebert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
bert_hatebert_bertweet_added_olid_test = add_3_embeddings(bert_olid_test_embeddings, hatebert_olid_test_embeddings, bertweet_olid_test_embeddings)

bert_hatebert_added_latenthatred_train = add_2_embeddings(bert_latenthatred_train_embeddings, hatebert_latenthatred_train_embeddings)
bert_hatebert_added_latenthatred_dev = add_2_embeddings(bert_latenthatred_dev_embeddings, hatebert_latenthatred_dev_embeddings)
bert_hatebert_added_latenthatred_test = add_2_embeddings(bert_latenthatred_test_embeddings, hatebert_latenthatred_test_embeddings)

bert_bertweet_added_latenthatred_train = add_2_embeddings(bert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
bert_bertweet_added_latenthatred_dev = add_2_embeddings(bert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
bert_bertweet_added_latenthatred_test = add_2_embeddings(bert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

hatebert_bertweet_added_latenthatred_train = add_2_embeddings(hatebert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
hatebert_bertweet_added_latenthatred_dev = add_2_embeddings(hatebert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
hatebert_bertweet_added_latenthatred_test = add_2_embeddings(hatebert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

bert_hatebert_bertweet_added_latenthatred_train = add_3_embeddings(bert_latenthatred_train_embeddings, hatebert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
bert_hatebert_bertweet_added_latenthatred_dev = add_3_embeddings(bert_latenthatred_dev_embeddings, hatebert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
bert_hatebert_bertweet_added_latenthatred_test = add_3_embeddings(bert_latenthatred_test_embeddings, hatebert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

In [6]:
dynahate_labels_train = process_labels(read_labels("dynahate", "train"))
dynahate_labels_dev = process_labels(read_labels("dynahate", "dev"))
dynahate_labels_test = process_labels(read_labels("dynahate", "test"))

latenthatred_labels_train = read_labels("latenthatred", "train")
latenthatred_labels_dev = read_labels("latenthatred", "dev")
latenthatred_labels_test = read_labels("latenthatred", "test")

olid_labels_train = read_labels("olid", "train")
olid_labels_dev = read_labels("olid", "dev")
olid_labels_test = read_labels("olid", "test")

In [7]:
mlp = MLPClassifier(random_state=42)
gridsearch = GridSearchCV(
    mlp,
    param_grid={
        "hidden_layer_sizes": [(128), (128,64)],
        "activation": ["relu"],
        "solver": ["adam"],
        "learning_rate_init": [0.001, 0.0001],
        "learning_rate": ["adaptive"],
        "early_stopping": [True],
        "max_iter": [10000]
    },
    verbose=4,
    n_jobs=os.cpu_count()//3,
    cv=5,
)

In [8]:
dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))
latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))
olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

### BERT-BERTweet

#### DynaHate

In [9]:
bert_bertweet_added_dynahate_train_dev = np.concatenate((bert_bertweet_added_dynahate_train, bert_bertweet_added_dynahate_dev))
bert_bertweet_added_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_added_dynahate_train_dev, bert_bertweet_added_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_added_dynahate_train_dev)
test_preds = mlp.predict(bert_bertweet_added_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_bertweet_added_dynahate_seed_42")
save_model(mlp, "Saves/bert_bertweet_added_dynahate_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7039757994814174
Accuracy Test:  0.6740291262135922
Weighted F1 Train Dev:  0.7005768535887725
Weighted F1 Test:  0.6699180670455863
Macro F1 Train Dev:  0.6971508929527614
Macro F1 Test:  0.6640812048821376
Micro F1 Train Dev:  0.7039757994814174
Micro F1 Test:  0.6740291262135922
Weighted Recall Train Dev:  0.7039757994814174
Weighted Recall Test:  0.6740291262135922
Macro Recall Train Dev:  0.6966191910218587
Macro Recall Test:  0.6634169266458683
Micro Recall Train Dev:  0.7039757994814174
Micro Recall Test:  0.6740291262135922
Confusion Matrix Train Dev: 
[[10253  6864]
 [ 4096 15811]]
Confusion Matrix Test: 
[[1034  818]
 [ 525 1743]]


#### LatentHatred

In [10]:
bert_bertweet_added_latenthatred_train_dev = np.concatenate((bert_bertweet_added_latenthatred_train, bert_bertweet_added_latenthatred_dev))
bert_bertweet_added_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_added_latenthatred_train_dev, bert_bertweet_added_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_added_latenthatred_train_dev)
test_preds = mlp.predict(bert_bertweet_added_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_bertweet_added_latenthatred_seed_42")
save_model(mlp, "Saves/bert_bertweet_added_latenthatred_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.6911235257603973
Accuracy Test:  0.686219739292365
Weighted F1 Train Dev:  0.6422056502029477
Weighted F1 Test:  0.6341633390050112
Macro F1 Train Dev:  0.43549378889002255
Macro F1 Test:  0.4194936827160978
Micro F1 Train Dev:  0.6911235257603973
Micro F1 Test:  0.686219739292365
Weighted Recall Train Dev:  0.6911235257603973
Weighted Recall Test:  0.686219739292365
Macro Recall Train Dev:  0.434210669319875
Macro Recall Test:  0.4226358753805486
Micro Recall Train Dev:  0.6911235257603973
Micro Recall Test:  0.686219739292365
Confusion Matrix Train Dev: 
[[9376  565    4]
 [3609 1728   10]
 [ 529  259   30]]
Confusion Matrix Test: 
[[3152  193    1]
 [1221  526    6]
 [ 175   89    7]]


#### OLID

In [11]:
bert_bertweet_added_olid_train_dev = np.concatenate((bert_bertweet_added_olid_train, bert_bertweet_added_olid_dev))
bert_bertweet_added_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_added_olid_train_dev, bert_bertweet_added_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_added_olid_train_dev)
test_preds = mlp.predict(bert_bertweet_added_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_bertweet_added_olid_seed_42")

save_model(mlp, "Saves/bert_bertweet_added_olid_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7562688821752266
Accuracy Test:  0.7930232558139535
Weighted F1 Train Dev:  0.7357197794047654
Weighted F1 Test:  0.7630366965242587
Macro F1 Train Dev:  0.6858356808258439
Macro F1 Test:  0.6780001851057207
Micro F1 Train Dev:  0.7562688821752266
Micro F1 Test:  0.7930232558139535
Weighted Recall Train Dev:  0.7562688821752266
Weighted Recall Test:  0.7930232558139535
Macro Recall Train Dev:  0.6731910736322501
Macro Recall Test:  0.657258064516129
Micro Recall Train Dev:  0.7562688821752266
Micro Recall Test:  0.7930232558139535
Confusion Matrix Train Dev: 
[[8141  699]
 [2528 1872]]
Confusion Matrix Test: 
[[598  22]
 [156  84]]


### BERT-HateBERT

#### DynaHate

In [12]:
bert_hatebert_added_dynahate_train_dev = np.concatenate((bert_hatebert_added_dynahate_train, bert_hatebert_added_dynahate_dev))
bert_hatebert_added_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_added_dynahate_train_dev, bert_hatebert_added_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_added_dynahate_train_dev)
test_preds = mlp.predict(bert_hatebert_added_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_hatebert_added_dynahate_seed_42")

save_model(mlp, "Saves/bert_hatebert_added_dynahate_seed_42")



Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7307422212618842
Accuracy Test:  0.6898058252427185
Weighted F1 Train Dev:  0.730346425550903
Weighted F1 Test:  0.6898952788683063
Macro F1 Train Dev:  0.7284779483366264
Macro F1 Test:  0.6867942198479298
Micro F1 Train Dev:  0.7307422212618843
Micro F1 Test:  0.6898058252427185
Weighted Recall Train Dev:  0.7307422212618842
Weighted Recall Test:  0.6898058252427185
Macro Recall Train Dev:  0.7279947229877445
Macro Recall Test:  0.6869079045104962
Micro Recall Train Dev:  0.7307422212618842
Micro Recall Test:  0.6898058252427185
Confusion Matrix Train Dev: 
[[11837  5280]
 [ 4689 15218]]
Confusion Matrix Test: 
[[1219  633]
 [ 645 1623]]


#### LatentHatred

In [13]:
bert_hatebert_added_latenthatred_train_dev = np.concatenate((bert_hatebert_added_latenthatred_train, bert_hatebert_added_latenthatred_dev))
bert_hatebert_added_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_added_latenthatred_train_dev, bert_hatebert_added_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_added_latenthatred_train_dev)
test_preds = mlp.predict(bert_hatebert_added_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_hatebert_added_latenthatred_seed_42")

save_model(mlp, "Saves/bert_hatebert_added_latenthatred_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7013035381750465
Accuracy Test:  0.6942271880819367
Weighted F1 Train Dev:  0.6781613387093881
Weighted F1 Test:  0.6696661791860608
Macro F1 Train Dev:  0.47404062606784275
Macro F1 Test:  0.46601914384122073
Micro F1 Train Dev:  0.7013035381750465
Micro F1 Test:  0.6942271880819367
Weighted Recall Train Dev:  0.7013035381750465
Weighted Recall Test:  0.6942271880819367
Macro Recall Train Dev:  0.46930549827395684
Macro Recall Test:  0.4601828294878889
Micro Recall Train Dev:  0.7013035381750465
Micro Recall Test:  0.6942271880819367
Confusion Matrix Train Dev: 
[[8561 1370   14]
 [2621 2703   23]
 [ 339  445   34]]
Confusion Matrix Test: 
[[2885  455    6]
 [ 913  831    9]
 [ 124  135   12]]


#### OLID

In [14]:
bert_hatebert_added_olid_train_dev = np.concatenate((bert_hatebert_added_olid_train, bert_hatebert_added_olid_dev))
bert_hatebert_added_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_added_olid_train_dev, bert_hatebert_added_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_added_olid_train_dev)
test_preds = mlp.predict(bert_hatebert_added_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_hatebert_added_olid_seed_42")

save_model(mlp, "Saves/bert_hatebert_added_olid_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7530211480362538
Accuracy Test:  0.7837209302325582
Weighted F1 Train Dev:  0.7357062189044321
Weighted F1 Test:  0.7565554174948875
Macro F1 Train Dev:  0.6878963399583573
Macro F1 Test:  0.6719415253611596
Micro F1 Train Dev:  0.7530211480362538
Micro F1 Test:  0.7837209302325583
Weighted Recall Train Dev:  0.7530211480362538
Weighted Recall Test:  0.7837209302325582
Macro Recall Train Dev:  0.6758386466474702
Macro Recall Test:  0.6533602150537634
Micro Recall Train Dev:  0.7530211480362538
Micro Recall Test:  0.7837209302325582
Confusion Matrix Train Dev: 
[[8009  831]
 [2439 1961]]
Confusion Matrix Test: 
[[588  32]
 [154  86]]


### BERTweet-HateBERT

#### DynaHate

In [15]:
hatebert_bertweet_added_dynahate_train_dev = np.concatenate((hatebert_bertweet_added_dynahate_train, hatebert_bertweet_added_dynahate_dev))
hatebert_bertweet_added_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_added_dynahate_train_dev, hatebert_bertweet_added_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_added_dynahate_train_dev)
test_preds = mlp.predict(hatebert_bertweet_added_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/hatebert_bertweet_added_dynahate_seed_42")

save_model(mlp, "Saves/hatebert_bertweet_added_dynahate_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7341184096802075
Accuracy Test:  0.6895631067961165
Weighted F1 Train Dev:  0.7324781437258846
Weighted F1 Test:  0.6880207280392453
Macro F1 Train Dev:  0.7299497779730886
Macro F1 Test:  0.683655901081025
Micro F1 Train Dev:  0.7341184096802075
Micro F1 Test:  0.6895631067961165
Weighted Recall Train Dev:  0.7341184096802075
Weighted Recall Test:  0.6895631067961165
Macro Recall Train Dev:  0.7288949407230624
Macro Recall Test:  0.6827258581218265
Micro Recall Train Dev:  0.7341184096802075
Micro Recall Test:  0.6895631067961165
Confusion Matrix Train Dev: 
[[11290  5827]
 [ 4017 15890]]
Confusion Matrix Test: 
[[1139  713]
 [ 566 1702]]


#### LatentHatred

In [16]:
hatebert_bertweet_added_latenthatred_train_dev = np.concatenate((hatebert_bertweet_added_latenthatred_train, hatebert_bertweet_added_latenthatred_dev))
hatebert_bertweet_added_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_added_latenthatred_train_dev, hatebert_bertweet_added_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_added_latenthatred_train_dev)
test_preds = mlp.predict(hatebert_bertweet_added_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/hatebert_bertweet_added_latenthatred_seed_42")

save_model(mlp, "Saves/hatebert_bertweet_added_latenthatred_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7186840471756673
Accuracy Test:  0.6981378026070764
Weighted F1 Train Dev:  0.689421598912144
Weighted F1 Test:  0.6653996769101245
Macro F1 Train Dev:  0.47576169349141306
Macro F1 Test:  0.4508961223446077
Micro F1 Train Dev:  0.7186840471756674
Micro F1 Test:  0.6981378026070764
Weighted Recall Train Dev:  0.7186840471756673
Weighted Recall Test:  0.6981378026070764
Macro Recall Train Dev:  0.4720964981751834
Macro Recall Test:  0.44919956541773415
Micro Recall Train Dev:  0.7186840471756673
Micro Recall Test:  0.6981378026070764
Confusion Matrix Train Dev: 
[[8962  978    5]
 [2752 2591    4]
 [ 373  420   25]]
Confusion Matrix Test: 
[[2993  351    2]
 [1002  749    2]
 [ 135  129    7]]


#### OLID

In [17]:
hatebert_bertweet_added_olid_train_dev = np.concatenate((hatebert_bertweet_added_olid_train, hatebert_bertweet_added_olid_dev))
hatebert_bertweet_added_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_added_olid_train_dev, hatebert_bertweet_added_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_added_olid_train_dev)
test_preds = mlp.predict(hatebert_bertweet_added_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/hatebert_bertweet_added_olid_seed_42")

save_model(mlp, "Saves/hatebert_bertweet_added_olid_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7588368580060423
Accuracy Test:  0.7813953488372093
Weighted F1 Train Dev:  0.7494330421722601
Weighted F1 Test:  0.7624796470303228
Macro F1 Train Dev:  0.7090920351171941
Macro F1 Test:  0.6860119163216319
Micro F1 Train Dev:  0.7588368580060423
Micro F1 Test:  0.7813953488372093
Weighted Recall Train Dev:  0.7588368580060423
Weighted Recall Test:  0.7813953488372093
Macro Recall Train Dev:  0.6987433155080214
Macro Recall Test:  0.6683467741935484
Micro Recall Train Dev:  0.7588368580060423
Micro Recall Test:  0.7813953488372093
Confusion Matrix Train Dev: 
[[7761 1079]
 [2114 2286]]
Confusion Matrix Test: 
[[573  47]
 [141  99]]


### BERT-BERTweet-HateBERT

#### DynaHate

In [18]:
bert_bertweet_hatebert_added_dynahate_train_dev = np.concatenate((bert_hatebert_bertweet_added_dynahate_train, bert_hatebert_bertweet_added_dynahate_dev))
bert_bertweet_hatebert_added_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_added_dynahate_train_dev, bert_bertweet_hatebert_added_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_added_dynahate_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_added_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_bertweet_hatebert_added_dynahate_seed_42")

save_model(mlp, "Saves/bert_bertweet_hatebert_added_dynahate_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7330920484010371
Accuracy Test:  0.6851941747572815
Weighted F1 Train Dev:  0.7319943721390364
Weighted F1 Test:  0.6844799261630087
Macro F1 Train Dev:  0.7297190996494507
Macro F1 Test:  0.6806211285627801
Micro F1 Train Dev:  0.7330920484010371
Micro F1 Test:  0.6851941747572815
Weighted Recall Train Dev:  0.7330920484010371
Weighted Recall Test:  0.6851941747572815
Macro Recall Train Dev:  0.7288125103340629
Macro Recall Test:  0.6800451201999078
Micro Recall Train Dev:  0.7330920484010371
Micro Recall Test:  0.6851941747572815
Confusion Matrix Train Dev: 
[[11503  5614]
 [ 4268 15639]]
Confusion Matrix Test: 
[[1165  687]
 [ 610 1658]]


#### LatentHatred

In [19]:
bert_bertweet_hatebert_added_latenthatred_train_dev = np.concatenate((bert_hatebert_bertweet_added_latenthatred_train, bert_hatebert_bertweet_added_latenthatred_dev))
bert_bertweet_hatebert_added_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_added_latenthatred_train_dev, bert_bertweet_hatebert_added_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_added_latenthatred_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_added_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_bertweet_hatebert_added_latenthatred_seed_42")

save_model(mlp, "Saves/bert_bertweet_hatebert_added_latenthatred_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7148355058969584
Accuracy Test:  0.7003724394785847
Weighted F1 Train Dev:  0.6841834416919412
Weighted F1 Test:  0.6675045616823247
Macro F1 Train Dev:  0.4794526969027984
Macro F1 Test:  0.4609250761790001
Micro F1 Train Dev:  0.7148355058969585
Micro F1 Test:  0.7003724394785847
Weighted Recall Train Dev:  0.7148355058969584
Weighted Recall Test:  0.7003724394785847
Macro Recall Train Dev:  0.470988385192823
Macro Recall Test:  0.45432693016543974
Micro Recall Train Dev:  0.7148355058969584
Micro Recall Test:  0.7003724394785847
Confusion Matrix Train Dev: 
[[9034  900   11]
 [2891 2443   13]
 [ 389  390   39]]
Confusion Matrix Test: 
[[3019  321    6]
 [1015  730    8]
 [ 133  126   12]]


#### OLID

In [20]:
bert_bertweet_hatebert_added_olid_train_dev = np.concatenate((bert_hatebert_bertweet_added_olid_train, bert_hatebert_bertweet_added_olid_dev))
bert_bertweet_hatebert_added_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_added_olid_train_dev, bert_bertweet_hatebert_added_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_added_olid_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_added_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_bertweet_hatebert_added_olid_seed_42")

save_model(mlp, "Saves/bert_bertweet_hatebert_added_olid_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7667673716012084
Accuracy Test:  0.8058139534883721
Weighted F1 Train Dev:  0.759193506153039
Weighted F1 Test:  0.7906856342703289
Macro F1 Train Dev:  0.7215783354708555
Macro F1 Test:  0.7246079181455425
Micro F1 Train Dev:  0.7667673716012083
Micro F1 Test:  0.805813953488372
Weighted Recall Train Dev:  0.7667673716012084
Weighted Recall Test:  0.8058139534883721
Macro Recall Train Dev:  0.7117024886877827
Macro Recall Test:  0.7031586021505376
Micro Recall Train Dev:  0.7667673716012084
Micro Recall Test:  0.8058139534883721
Confusion Matrix Train Dev: 
[[7743 1097]
 [1991 2409]]
Confusion Matrix Test: 
[[580  40]
 [127 113]]
