In [1]:
from utils import *
import numpy as np
import torch, os
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV

c:\Kyode\PersonalProjects\HateSpeechModelCombination\venv\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:
set_random_seed(3)

In [2]:
# def scaling_embeddings(embeddings):
#     for i in range(len(embeddings)):
#         embeddings[i] = StandardScaler().fit_transform(embeddings[i])
#     return embeddings

def reshape_embeddings(embeddings):
    if embeddings.shape[1] == 1:
        embeddings = embeddings.squeeze(1)
    return embeddings

In [3]:
def add_2_embeddings(embeddings1, embeddings2):
    embeddings1 = reshape_embeddings(embeddings1)
    embeddings2 = reshape_embeddings(embeddings2)
    # Numpy Add
    return embeddings1 + embeddings2

def add_3_embeddings(embeddings1, embeddings2, embeddings3):
    embeddings1 = reshape_embeddings(embeddings1)
    embeddings2 = reshape_embeddings(embeddings2)
    embeddings3 = reshape_embeddings(embeddings3)
    return embeddings1 + embeddings2 + embeddings3

In [4]:
bert_hatebert_added_dynahate_train = add_2_embeddings(bert_dynahate_train_embeddings, hatebert_dynahate_train_embeddings)
bert_hatebert_added_dynahate_dev = add_2_embeddings(bert_dynahate_dev_embeddings, hatebert_dynahate_dev_embeddings)
bert_hatebert_added_dynahate_test = add_2_embeddings(bert_dynahate_test_embeddings, hatebert_dynahate_test_embeddings)

bert_bertweet_added_dynahate_train = add_2_embeddings(bert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
bert_bertweet_added_dynahate_dev = add_2_embeddings(bert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
bert_bertweet_added_dynahate_test = add_2_embeddings(bert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

hatebert_bertweet_added_dynahate_train = add_2_embeddings(hatebert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
hatebert_bertweet_added_dynahate_dev = add_2_embeddings(hatebert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
hatebert_bertweet_added_dynahate_test = add_2_embeddings(hatebert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

bert_hatebert_bertweet_added_dynahate_train = add_3_embeddings(bert_dynahate_train_embeddings, hatebert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
bert_hatebert_bertweet_added_dynahate_dev = add_3_embeddings(bert_dynahate_dev_embeddings, hatebert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
bert_hatebert_bertweet_added_dynahate_test = add_3_embeddings(bert_dynahate_test_embeddings, hatebert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

bert_hatebert_added_olid_train = add_2_embeddings(bert_olid_train_embeddings, hatebert_olid_train_embeddings)
bert_hatebert_added_olid_dev = add_2_embeddings(bert_olid_dev_embeddings, hatebert_olid_dev_embeddings)
bert_hatebert_added_olid_test = add_2_embeddings(bert_olid_test_embeddings, hatebert_olid_test_embeddings)

bert_bertweet_added_olid_train = add_2_embeddings(bert_olid_train_embeddings, bertweet_olid_train_embeddings)
bert_bertweet_added_olid_dev = add_2_embeddings(bert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
bert_bertweet_added_olid_test = add_2_embeddings(bert_olid_test_embeddings, bertweet_olid_test_embeddings)

hatebert_bertweet_added_olid_train = add_2_embeddings(hatebert_olid_train_embeddings, bertweet_olid_train_embeddings)
hatebert_bertweet_added_olid_dev = add_2_embeddings(hatebert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
hatebert_bertweet_added_olid_test = add_2_embeddings(hatebert_olid_test_embeddings, bertweet_olid_test_embeddings)

bert_hatebert_bertweet_added_olid_train = add_3_embeddings(bert_olid_train_embeddings, hatebert_olid_train_embeddings, bertweet_olid_train_embeddings)
bert_hatebert_bertweet_added_olid_dev = add_3_embeddings(bert_olid_dev_embeddings, hatebert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
bert_hatebert_bertweet_added_olid_test = add_3_embeddings(bert_olid_test_embeddings, hatebert_olid_test_embeddings, bertweet_olid_test_embeddings)

bert_hatebert_added_latenthatred_train = add_2_embeddings(bert_latenthatred_train_embeddings, hatebert_latenthatred_train_embeddings)
bert_hatebert_added_latenthatred_dev = add_2_embeddings(bert_latenthatred_dev_embeddings, hatebert_latenthatred_dev_embeddings)
bert_hatebert_added_latenthatred_test = add_2_embeddings(bert_latenthatred_test_embeddings, hatebert_latenthatred_test_embeddings)

bert_bertweet_added_latenthatred_train = add_2_embeddings(bert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
bert_bertweet_added_latenthatred_dev = add_2_embeddings(bert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
bert_bertweet_added_latenthatred_test = add_2_embeddings(bert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

hatebert_bertweet_added_latenthatred_train = add_2_embeddings(hatebert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
hatebert_bertweet_added_latenthatred_dev = add_2_embeddings(hatebert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
hatebert_bertweet_added_latenthatred_test = add_2_embeddings(hatebert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

bert_hatebert_bertweet_added_latenthatred_train = add_3_embeddings(bert_latenthatred_train_embeddings, hatebert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
bert_hatebert_bertweet_added_latenthatred_dev = add_3_embeddings(bert_latenthatred_dev_embeddings, hatebert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
bert_hatebert_bertweet_added_latenthatred_test = add_3_embeddings(bert_latenthatred_test_embeddings, hatebert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

In [5]:
dynahate_labels_train = process_labels(read_labels("dynahate", "train"))
dynahate_labels_dev = process_labels(read_labels("dynahate", "dev"))
dynahate_labels_test = process_labels(read_labels("dynahate", "test"))

latenthatred_labels_train = read_labels("latenthatred", "train")
latenthatred_labels_dev = read_labels("latenthatred", "dev")
latenthatred_labels_test = read_labels("latenthatred", "test")

olid_labels_train = read_labels("olid", "train")
olid_labels_dev = read_labels("olid", "dev")
olid_labels_test = read_labels("olid", "test")

In [6]:
mlp = MLPClassifier(random_state=3)
gridsearch = GridSearchCV(
    mlp,
    param_grid={
        "hidden_layer_sizes": [(128), (128,64)],
        "activation": ["relu"],
        "solver": ["adam"],
        "learning_rate_init": [0.001, 0.0001],
        "learning_rate": ["adaptive"],
        "early_stopping": [True],
        "max_iter": [10000]
    },
    verbose=4,
    n_jobs=os.cpu_count()//3,
    cv=5,
)

In [7]:
dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))
latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))
olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

### BERT-BERTweet

#### DynaHate

In [8]:
bert_bertweet_added_dynahate_train_dev = np.concatenate((bert_bertweet_added_dynahate_train, bert_bertweet_added_dynahate_dev))
bert_bertweet_added_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_added_dynahate_train_dev, bert_bertweet_added_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_added_dynahate_train_dev)
test_preds = mlp.predict(bert_bertweet_added_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_bertweet_added_dynahate_seed_3")
save_model(mlp, "Saves/bert_bertweet_added_dynahate_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7048401037165082
Accuracy Test:  0.6837378640776699
Weighted F1 Train Dev:  0.7021714315930774
Weighted F1 Test:  0.6800571656365202
Macro F1 Train Dev:  0.6990165183624111
Macro F1 Test:  0.6745294741147938
Micro F1 Train Dev:  0.7048401037165082
Micro F1 Test:  0.6837378640776699
Weighted Recall Train Dev:  0.7048401037165082
Weighted Recall Test:  0.6837378640776699
Macro Recall Train Dev:  0.6983235936806448
Macro Recall Test:  0.6736218245397512
Micro Recall Train Dev:  0.7048401037165082
Micro Recall Test:  0.6837378640776699
Confusion Matrix Train Dev: 
[[10473  6644]
 [ 4284 15623]]
Confusion Matrix Test: 
[[1062  790]
 [ 513 1755]]


#### LatentHatred

In [9]:
bert_bertweet_added_latenthatred_train_dev = np.concatenate((bert_bertweet_added_latenthatred_train, bert_bertweet_added_latenthatred_dev))
bert_bertweet_added_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_added_latenthatred_train_dev, bert_bertweet_added_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_added_latenthatred_train_dev)
test_preds = mlp.predict(bert_bertweet_added_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_bertweet_added_latenthatred_seed_3")
save_model(mlp, "Saves/bert_bertweet_added_latenthatred_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.6903786468032278
Accuracy Test:  0.6823091247672253
Weighted F1 Train Dev:  0.6532117284006504
Weighted F1 Test:  0.6424140228233458
Macro F1 Train Dev:  0.4290168555996197
Macro F1 Test:  0.41562477253219726
Micro F1 Train Dev:  0.6903786468032278
Micro F1 Test:  0.6823091247672253
Weighted Recall Train Dev:  0.6903786468032278
Weighted Recall Test:  0.6823091247672253
Macro Recall Train Dev:  0.4359043640405708
Macro Recall Test:  0.4240377154377541
Micro Recall Train Dev:  0.6903786468032278
Micro Recall Test:  0.6823091247672253
Confusion Matrix Train Dev: 
[[8944 1001    0]
 [3169 2177    1]
 [ 461  356    1]]
Confusion Matrix Test: 
[[3012  334    0]
 [1100  652    1]
 [ 134  137    0]]


#### OLID

In [10]:
bert_bertweet_added_olid_train_dev = np.concatenate((bert_bertweet_added_olid_train, bert_bertweet_added_olid_dev))
bert_bertweet_added_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_added_olid_train_dev, bert_bertweet_added_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_added_olid_train_dev)
test_preds = mlp.predict(bert_bertweet_added_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_bertweet_added_olid_seed_3")

save_model(mlp, "Saves/bert_bertweet_added_olid_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7723564954682779
Accuracy Test:  0.7988372093023256
Weighted F1 Train Dev:  0.7585292315955761
Weighted F1 Test:  0.7726319755143863
Macro F1 Train Dev:  0.7161891960129583
Macro F1 Test:  0.6929680647990507
Micro F1 Train Dev:  0.7723564954682779
Micro F1 Test:  0.7988372093023256
Weighted Recall Train Dev:  0.7723564954682779
Weighted Recall Test:  0.7988372093023256
Macro Recall Train Dev:  0.7021328671328672
Macro Recall Test:  0.6702284946236559
Micro Recall Train Dev:  0.7723564954682779
Micro Recall Test:  0.7988372093023256
Confusion Matrix Train Dev: 
[[8058  782]
 [2232 2168]]
Confusion Matrix Test: 
[[596  24]
 [149  91]]


### BERT-HateBERT

#### DynaHate

In [8]:
bert_hatebert_added_dynahate_train_dev = np.concatenate((bert_hatebert_added_dynahate_train, bert_hatebert_added_dynahate_dev))
bert_hatebert_added_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_added_dynahate_train_dev, bert_hatebert_added_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_added_dynahate_train_dev)
test_preds = mlp.predict(bert_hatebert_added_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_hatebert_added_dynahate_seed_3")

save_model(mlp, "Saves/bert_hatebert_added_dynahate_seed_3")



Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7104040622299049
Accuracy Test:  0.6876213592233009
Weighted F1 Train Dev:  0.7086972226622503
Weighted F1 Test:  0.6860693330621649
Macro F1 Train Dev:  0.7059791391041703
Macro F1 Test:  0.6816772046061605
Micro F1 Train Dev:  0.7104040622299049
Micro F1 Test:  0.6876213592233009
Weighted Recall Train Dev:  0.7104040622299049
Weighted Recall Test:  0.6876213592233009
Macro Recall Train Dev:  0.705163883824697
Macro Recall Test:  0.6807641102997475
Micro Recall Train Dev:  0.7104040622299049
Micro Recall Test:  0.6876213592233009
Confusion Matrix Train Dev: 
[[10880  6237]
 [ 4485 15422]]
Confusion Matrix Test: 
[[1135  717]
 [ 570 1698]]


#### LatentHatred

In [9]:
bert_hatebert_added_latenthatred_train_dev = np.concatenate((bert_hatebert_added_latenthatred_train, bert_hatebert_added_latenthatred_dev))
bert_hatebert_added_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_added_latenthatred_train_dev, bert_hatebert_added_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_added_latenthatred_train_dev)
test_preds = mlp.predict(bert_hatebert_added_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_hatebert_added_latenthatred_seed_3")

save_model(mlp, "Saves/bert_hatebert_added_latenthatred_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7162631905648665
Accuracy Test:  0.6919925512104284
Weighted F1 Train Dev:  0.6925040729171136
Weighted F1 Test:  0.6650906121217168
Macro F1 Train Dev:  0.5022443323200018
Macro F1 Test:  0.4589741079486607
Micro F1 Train Dev:  0.7162631905648665
Micro F1 Test:  0.6919925512104284
Weighted Recall Train Dev:  0.7162631905648665
Weighted Recall Test:  0.6919925512104284
Macro Recall Train Dev:  0.4875362325674826
Macro Recall Test:  0.45405477259805105
Micro Recall Train Dev:  0.7162631905648665
Micro Recall Test:  0.6919925512104284
Confusion Matrix Train Dev: 
[[8809 1118   18]
 [2649 2666   32]
 [ 363  391   64]]
Confusion Matrix Test: 
[[2916  420   10]
 [ 950  789   14]
 [ 136  124   11]]


#### OLID

In [10]:
bert_hatebert_added_olid_train_dev = np.concatenate((bert_hatebert_added_olid_train, bert_hatebert_added_olid_dev))
bert_hatebert_added_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_added_olid_train_dev, bert_hatebert_added_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_added_olid_train_dev)
test_preds = mlp.predict(bert_hatebert_added_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_hatebert_added_olid_seed_3")

save_model(mlp, "Saves/bert_hatebert_added_olid_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.765785498489426
Accuracy Test:  0.7930232558139535
Weighted F1 Train Dev:  0.7597481094565556
Weighted F1 Test:  0.7771463388620887
Macro F1 Train Dev:  0.7234747572157649
Macro F1 Test:  0.706992519772454
Micro F1 Train Dev:  0.765785498489426
Micro F1 Test:  0.7930232558139535
Weighted Recall Train Dev:  0.765785498489426
Weighted Recall Test:  0.7930232558139535
Macro Recall Train Dev:  0.7150195392842451
Macro Recall Test:  0.6879032258064516
Micro Recall Train Dev:  0.765785498489426
Micro Recall Test:  0.7930232558139535
Confusion Matrix Train Dev: 
[[7659 1181]
 [1920 2480]]
Confusion Matrix Test: 
[[574  46]
 [132 108]]


### BERTweet-HateBERT

#### DynaHate

In [11]:
hatebert_bertweet_added_dynahate_train_dev = np.concatenate((hatebert_bertweet_added_dynahate_train, hatebert_bertweet_added_dynahate_dev))
hatebert_bertweet_added_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_added_dynahate_train_dev, hatebert_bertweet_added_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_added_dynahate_train_dev)
test_preds = mlp.predict(hatebert_bertweet_added_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/hatebert_bertweet_added_dynahate_seed_3")

save_model(mlp, "Saves/hatebert_bertweet_added_dynahate_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7140773552290406
Accuracy Test:  0.6900485436893203
Weighted F1 Train Dev:  0.7100476048825624
Weighted F1 Test:  0.6853385404548508
Macro F1 Train Dev:  0.7064919428121403
Macro F1 Test:  0.679454572450228
Micro F1 Train Dev:  0.7140773552290406
Micro F1 Test:  0.6900485436893203
Weighted Recall Train Dev:  0.7140773552290406
Weighted Recall Test:  0.6900485436893203
Macro Recall Train Dev:  0.7059719323058098
Macro Recall Test:  0.6786109492193005
Micro Recall Train Dev:  0.7140773552290406
Micro Recall Test:  0.6900485436893203
Confusion Matrix Train Dev: 
[[10243  6874]
 [ 3712 16195]]
Confusion Matrix Test: 
[[1047  805]
 [ 472 1796]]


#### LatentHatred

In [12]:
hatebert_bertweet_added_latenthatred_train_dev = np.concatenate((hatebert_bertweet_added_latenthatred_train, hatebert_bertweet_added_latenthatred_dev))
hatebert_bertweet_added_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_added_latenthatred_train_dev, hatebert_bertweet_added_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_added_latenthatred_train_dev)
test_preds = mlp.predict(hatebert_bertweet_added_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/hatebert_bertweet_added_latenthatred_seed_3")

save_model(mlp, "Saves/hatebert_bertweet_added_latenthatred_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7262569832402235
Accuracy Test:  0.6975791433891992
Weighted F1 Train Dev:  0.7046068835154048
Weighted F1 Test:  0.6746825214261521
Macro F1 Train Dev:  0.5161522092417578
Macro F1 Test:  0.48533240998450533
Micro F1 Train Dev:  0.7262569832402235
Micro F1 Test:  0.6975791433891992
Weighted Recall Train Dev:  0.7262569832402235
Weighted Recall Test:  0.6975791433891992
Macro Recall Train Dev:  0.49981760816930487
Macro Recall Test:  0.47205900435565895
Micro Recall Train Dev:  0.7262569832402235
Micro Recall Test:  0.6975791433891992
Confusion Matrix Train Dev: 
[[8791 1145    9]
 [2480 2840   27]
 [ 349  400   69]]
Confusion Matrix Test: 
[[2895  442    9]
 [ 908  830   15]
 [ 127  123   21]]


#### OLID

In [13]:
hatebert_bertweet_added_olid_train_dev = np.concatenate((hatebert_bertweet_added_olid_train, hatebert_bertweet_added_olid_dev))
hatebert_bertweet_added_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_added_olid_train_dev, hatebert_bertweet_added_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_added_olid_train_dev)
test_preds = mlp.predict(hatebert_bertweet_added_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/hatebert_bertweet_added_olid_seed_3")

save_model(mlp, "Saves/hatebert_bertweet_added_olid_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7671450151057402
Accuracy Test:  0.7941860465116279
Weighted F1 Train Dev:  0.7583744389563151
Weighted F1 Test:  0.7805405004659259
Macro F1 Train Dev:  0.7197037754970822
Macro F1 Test:  0.7131988446559686
Micro F1 Train Dev:  0.7671450151057402
Micro F1 Test:  0.7941860465116279
Weighted Recall Train Dev:  0.7671450151057402
Weighted Recall Test:  0.7941860465116279
Macro Recall Train Dev:  0.7089032291238173
Macro Recall Test:  0.6950940860215054
Micro Recall Train Dev:  0.7671450151057402
Micro Recall Test:  0.7941860465116279
Confusion Matrix Train Dev: 
[[7802 1038]
 [2045 2355]]
Confusion Matrix Test: 
[[570  50]
 [127 113]]


### BERT-BERTweet-HateBERT

#### DynaHate

In [14]:
bert_bertweet_hatebert_added_dynahate_train_dev = np.concatenate((bert_hatebert_bertweet_added_dynahate_train, bert_hatebert_bertweet_added_dynahate_dev))
bert_bertweet_hatebert_added_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_added_dynahate_train_dev, bert_bertweet_hatebert_added_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_added_dynahate_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_added_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_bertweet_hatebert_added_dynahate_seed_3")

save_model(mlp, "Saves/bert_bertweet_hatebert_added_dynahate_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.712942955920484
Accuracy Test:  0.6803398058252427
Weighted F1 Train Dev:  0.7086008693037876
Weighted F1 Test:  0.6759861761476528
Macro F1 Train Dev:  0.7049387103979284
Macro F1 Test:  0.6701249789118034
Micro F1 Train Dev:  0.712942955920484
Micro F1 Test:  0.6803398058252427
Weighted Recall Train Dev:  0.712942955920484
Weighted Recall Test:  0.6803398058252427
Macro Recall Train Dev:  0.704532197285585
Macro Recall Test:  0.6693964482841372
Micro Recall Train Dev:  0.712942955920484
Micro Recall Test:  0.6803398058252427
Confusion Matrix Train Dev: 
[[10149  6968]
 [ 3660 16247]]
Confusion Matrix Test: 
[[1039  813]
 [ 504 1764]]


#### LatentHatred

In [15]:
bert_bertweet_hatebert_added_latenthatred_train_dev = np.concatenate((bert_hatebert_bertweet_added_latenthatred_train, bert_hatebert_bertweet_added_latenthatred_dev))
bert_bertweet_hatebert_added_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_added_latenthatred_train_dev, bert_bertweet_hatebert_added_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_added_latenthatred_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_added_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_bertweet_hatebert_added_latenthatred_seed_3")

save_model(mlp, "Saves/bert_bertweet_hatebert_added_latenthatred_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7141527001862198
Accuracy Test:  0.6972067039106146
Weighted F1 Train Dev:  0.6846465945723406
Weighted F1 Test:  0.6640145574831627
Macro F1 Train Dev:  0.47551137467369897
Macro F1 Test:  0.44930319495735027
Micro F1 Train Dev:  0.7141527001862197
Micro F1 Test:  0.6972067039106146
Weighted Recall Train Dev:  0.7141527001862198
Weighted Recall Test:  0.6972067039106146
Macro Recall Train Dev:  0.46987600910795607
Macro Recall Test:  0.44770564164353527
Micro Recall Train Dev:  0.7141527001862198
Micro Recall Test:  0.6972067039106146
Confusion Matrix Train Dev: 
[[8953  986    6]
 [2816 2521   10]
 [ 379  408   31]]
Confusion Matrix Test: 
[[2999  344    3]
 [1009  738    6]
 [ 139  125    7]]


#### OLID

In [16]:
bert_bertweet_hatebert_added_olid_train_dev = np.concatenate((bert_hatebert_bertweet_added_olid_train, bert_hatebert_bertweet_added_olid_dev))
bert_bertweet_hatebert_added_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_added_olid_train_dev, bert_bertweet_hatebert_added_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_added_olid_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_added_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_bertweet_hatebert_added_olid_seed_3")

save_model(mlp, "Saves/bert_bertweet_hatebert_added_olid_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7681268882175226
Accuracy Test:  0.7988372093023256
Weighted F1 Train Dev:  0.7564901078882278
Weighted F1 Test:  0.780138449312451
Macro F1 Train Dev:  0.7154191184907168
Macro F1 Test:  0.7083654311694981
Micro F1 Train Dev:  0.7681268882175226
Micro F1 Test:  0.7988372093023256
Weighted Recall Train Dev:  0.7681268882175226
Weighted Recall Test:  0.7988372093023256
Macro Recall Train Dev:  0.7028465651995064
Macro Recall Test:  0.6868279569892473
Micro Recall Train Dev:  0.7681268882175226
Micro Recall Test:  0.7988372093023256
Confusion Matrix Train Dev: 
[[7934  906]
 [2164 2236]]
Confusion Matrix Test: 
[[583  37]
 [136 104]]
