In [1]:
from utils import *
import numpy as np
import torch, os
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV

In [2]:
set_random_seed(3)

Seed: 3


In [3]:
# def scaling_embeddings(embeddings):
#     for i in range(len(embeddings)):
#         embeddings[i] = StandardScaler().fit_transform(embeddings[i])
#     return embeddings

def reshape_embeddings(embeddings):
    if embeddings.shape[1] == 1:
        embeddings = embeddings.squeeze(1)
    return embeddings

In [4]:
def add_2_embeddings(embeddings1, embeddings2):
    embeddings1 = reshape_embeddings(embeddings1)
    embeddings2 = reshape_embeddings(embeddings2)
    # Numpy Add
    return embeddings1 + embeddings2

def add_3_embeddings(embeddings1, embeddings2, embeddings3):
    embeddings1 = reshape_embeddings(embeddings1)
    embeddings2 = reshape_embeddings(embeddings2)
    embeddings3 = reshape_embeddings(embeddings3)
    return embeddings1 + embeddings2 + embeddings3

In [5]:
bert_hatebert_added_dynahate_train = add_2_embeddings(bert_dynahate_train_embeddings, hatebert_dynahate_train_embeddings)
bert_hatebert_added_dynahate_dev = add_2_embeddings(bert_dynahate_dev_embeddings, hatebert_dynahate_dev_embeddings)
bert_hatebert_added_dynahate_test = add_2_embeddings(bert_dynahate_test_embeddings, hatebert_dynahate_test_embeddings)

bert_bertweet_added_dynahate_train = add_2_embeddings(bert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
bert_bertweet_added_dynahate_dev = add_2_embeddings(bert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
bert_bertweet_added_dynahate_test = add_2_embeddings(bert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

hatebert_bertweet_added_dynahate_train = add_2_embeddings(hatebert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
hatebert_bertweet_added_dynahate_dev = add_2_embeddings(hatebert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
hatebert_bertweet_added_dynahate_test = add_2_embeddings(hatebert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

bert_hatebert_bertweet_added_dynahate_train = add_3_embeddings(bert_dynahate_train_embeddings, hatebert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
bert_hatebert_bertweet_added_dynahate_dev = add_3_embeddings(bert_dynahate_dev_embeddings, hatebert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
bert_hatebert_bertweet_added_dynahate_test = add_3_embeddings(bert_dynahate_test_embeddings, hatebert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

bert_hatebert_added_olid_train = add_2_embeddings(bert_olid_train_embeddings, hatebert_olid_train_embeddings)
bert_hatebert_added_olid_dev = add_2_embeddings(bert_olid_dev_embeddings, hatebert_olid_dev_embeddings)
bert_hatebert_added_olid_test = add_2_embeddings(bert_olid_test_embeddings, hatebert_olid_test_embeddings)

bert_bertweet_added_olid_train = add_2_embeddings(bert_olid_train_embeddings, bertweet_olid_train_embeddings)
bert_bertweet_added_olid_dev = add_2_embeddings(bert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
bert_bertweet_added_olid_test = add_2_embeddings(bert_olid_test_embeddings, bertweet_olid_test_embeddings)

hatebert_bertweet_added_olid_train = add_2_embeddings(hatebert_olid_train_embeddings, bertweet_olid_train_embeddings)
hatebert_bertweet_added_olid_dev = add_2_embeddings(hatebert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
hatebert_bertweet_added_olid_test = add_2_embeddings(hatebert_olid_test_embeddings, bertweet_olid_test_embeddings)

bert_hatebert_bertweet_added_olid_train = add_3_embeddings(bert_olid_train_embeddings, hatebert_olid_train_embeddings, bertweet_olid_train_embeddings)
bert_hatebert_bertweet_added_olid_dev = add_3_embeddings(bert_olid_dev_embeddings, hatebert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
bert_hatebert_bertweet_added_olid_test = add_3_embeddings(bert_olid_test_embeddings, hatebert_olid_test_embeddings, bertweet_olid_test_embeddings)

bert_hatebert_added_latenthatred_train = add_2_embeddings(bert_latenthatred_train_embeddings, hatebert_latenthatred_train_embeddings)
bert_hatebert_added_latenthatred_dev = add_2_embeddings(bert_latenthatred_dev_embeddings, hatebert_latenthatred_dev_embeddings)
bert_hatebert_added_latenthatred_test = add_2_embeddings(bert_latenthatred_test_embeddings, hatebert_latenthatred_test_embeddings)

bert_bertweet_added_latenthatred_train = add_2_embeddings(bert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
bert_bertweet_added_latenthatred_dev = add_2_embeddings(bert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
bert_bertweet_added_latenthatred_test = add_2_embeddings(bert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

hatebert_bertweet_added_latenthatred_train = add_2_embeddings(hatebert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
hatebert_bertweet_added_latenthatred_dev = add_2_embeddings(hatebert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
hatebert_bertweet_added_latenthatred_test = add_2_embeddings(hatebert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

bert_hatebert_bertweet_added_latenthatred_train = add_3_embeddings(bert_latenthatred_train_embeddings, hatebert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
bert_hatebert_bertweet_added_latenthatred_dev = add_3_embeddings(bert_latenthatred_dev_embeddings, hatebert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
bert_hatebert_bertweet_added_latenthatred_test = add_3_embeddings(bert_latenthatred_test_embeddings, hatebert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

In [6]:
dynahate_labels_train = process_labels(read_labels("dynahate", "train"))
dynahate_labels_dev = process_labels(read_labels("dynahate", "dev"))
dynahate_labels_test = process_labels(read_labels("dynahate", "test"))

latenthatred_labels_train = read_labels("latenthatred", "train")
latenthatred_labels_dev = read_labels("latenthatred", "dev")
latenthatred_labels_test = read_labels("latenthatred", "test")

olid_labels_train = read_labels("olid", "train")
olid_labels_dev = read_labels("olid", "dev")
olid_labels_test = read_labels("olid", "test")

In [7]:
mlp = MLPClassifier(random_state=3)
gridsearch = GridSearchCV(
    mlp,
    param_grid={
        "hidden_layer_sizes": [(128), (128,64)],
        "activation": ["relu"],
        "solver": ["adam"],
        "learning_rate_init": [0.001, 0.0001],
        "learning_rate": ["adaptive"],
        "early_stopping": [True],
        "max_iter": [10000]
    },
    verbose=4,
    n_jobs=os.cpu_count()//3,
    cv=5,
)

In [8]:
dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))
latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))
olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

### BERT-BERTweet

#### DynaHate

In [9]:
bert_bertweet_added_dynahate_train_dev = np.concatenate((bert_bertweet_added_dynahate_train, bert_bertweet_added_dynahate_dev))
bert_bertweet_added_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_added_dynahate_train_dev, bert_bertweet_added_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_added_dynahate_train_dev)
test_preds = mlp.predict(bert_bertweet_added_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_bertweet_added_dynahate_seed_3")
save_model(mlp, "Saves/bert_bertweet_added_dynahate_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7013018582541054
Accuracy Test:  0.6742718446601942
Weighted F1 Train Dev:  0.6995032865054512
Weighted F1 Test:  0.6717557235001604
Macro F1 Train Dev:  0.6966825921947458
Macro F1 Test:  0.6666746244585386
Micro F1 Train Dev:  0.7013018582541054
Micro F1 Test:  0.6742718446601942
Weighted Recall Train Dev:  0.7013018582541054
Weighted Recall Test:  0.6742718446601942
Macro Recall Train Dev:  0.695954428731564
Macro Recall Test:  0.6658162585088432
Micro Recall Train Dev:  0.7013018582541054
Micro Recall Test:  0.6742718446601942
Confusion Matrix Train Dev: 
[[10698  6419]
 [ 4640 15267]]
Confusion Matrix Test: 
[[1078  774]
 [ 568 1700]]


#### LatentHatred

In [10]:
bert_bertweet_added_latenthatred_train_dev = np.concatenate((bert_bertweet_added_latenthatred_train, bert_bertweet_added_latenthatred_dev))
bert_bertweet_added_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_added_latenthatred_train_dev, bert_bertweet_added_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_added_latenthatred_train_dev)
test_preds = mlp.predict(bert_bertweet_added_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_bertweet_added_latenthatred_seed_3")
save_model(mlp, "Saves/bert_bertweet_added_latenthatred_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7128491620111732
Accuracy Test:  0.6921787709497207
Weighted F1 Train Dev:  0.6897682583500261
Weighted F1 Test:  0.6657062914755787
Macro F1 Train Dev:  0.5095405775167801
Macro F1 Test:  0.47210074978256555
Micro F1 Train Dev:  0.7128491620111732
Micro F1 Test:  0.6921787709497207
Weighted Recall Train Dev:  0.7128491620111732
Weighted Recall Test:  0.6921787709497207
Macro Recall Train Dev:  0.4908103411491855
Macro Recall Test:  0.4610248302059598
Micro Recall Train Dev:  0.7128491620111732
Micro Recall Test:  0.6921787709497207
Confusion Matrix Train Dev: 
[[8792 1121   32]
 [2699 2610   38]
 [ 390  346   82]]
Confusion Matrix Test: 
[[2933  403   10]
 [ 969  765   19]
 [ 118  134   19]]


#### OLID

In [11]:
bert_bertweet_added_olid_train_dev = np.concatenate((bert_bertweet_added_olid_train, bert_bertweet_added_olid_dev))
bert_bertweet_added_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_added_olid_train_dev, bert_bertweet_added_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_added_olid_train_dev)
test_preds = mlp.predict(bert_bertweet_added_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_bertweet_added_olid_seed_3")

save_model(mlp, "Saves/bert_bertweet_added_olid_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7756042296072507
Accuracy Test:  0.8069767441860465
Weighted F1 Train Dev:  0.7646133560361167
Weighted F1 Test:  0.7872236511504099
Macro F1 Train Dev:  0.7250996081366549
Macro F1 Test:  0.7164106761169955
Micro F1 Train Dev:  0.7756042296072507
Micro F1 Test:  0.8069767441860464
Weighted Recall Train Dev:  0.7756042296072507
Weighted Recall Test:  0.8069767441860465
Macro Recall Train Dev:  0.7119277046482929
Macro Recall Test:  0.6924731182795699
Micro Recall Train Dev:  0.7756042296072507
Micro Recall Test:  0.8069767441860465
Confusion Matrix Train Dev: 
[[7972  868]
 [2103 2297]]
Confusion Matrix Test: 
[[590  30]
 [136 104]]


### BERT-HateBERT

#### DynaHate

In [12]:
bert_hatebert_added_dynahate_train_dev = np.concatenate((bert_hatebert_added_dynahate_train, bert_hatebert_added_dynahate_dev))
bert_hatebert_added_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_added_dynahate_train_dev, bert_hatebert_added_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_added_dynahate_train_dev)
test_preds = mlp.predict(bert_hatebert_added_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_hatebert_added_dynahate_seed_3")

save_model(mlp, "Saves/bert_hatebert_added_dynahate_seed_3")



Fitting 5 folds for each of 4 candidates, totalling 20 fits


#### LatentHatred

In [ ]:
bert_hatebert_added_latenthatred_train_dev = np.concatenate((bert_hatebert_added_latenthatred_train, bert_hatebert_added_latenthatred_dev))
bert_hatebert_added_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_added_latenthatred_train_dev, bert_hatebert_added_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_added_latenthatred_train_dev)
test_preds = mlp.predict(bert_hatebert_added_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_hatebert_added_latenthatred_seed_3")

save_model(mlp, "Saves/bert_hatebert_added_latenthatred_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7162631905648665
Accuracy Test:  0.6919925512104284
Weighted F1 Train Dev:  0.6925040729171136
Weighted F1 Test:  0.6650906121217168
Macro F1 Train Dev:  0.5022443323200018
Macro F1 Test:  0.4589741079486607
Micro F1 Train Dev:  0.7162631905648665
Micro F1 Test:  0.6919925512104284
Weighted Recall Train Dev:  0.7162631905648665
Weighted Recall Test:  0.6919925512104284
Macro Recall Train Dev:  0.4875362325674826
Macro Recall Test:  0.45405477259805105
Micro Recall Train Dev:  0.7162631905648665
Micro Recall Test:  0.6919925512104284
Confusion Matrix Train Dev: 
[[8809 1118   18]
 [2649 2666   32]
 [ 363  391   64]]
Confusion Matrix Test: 
[[2916  420   10]
 [ 950  789   14]
 [ 136  124   11]]


#### OLID

In [ ]:
bert_hatebert_added_olid_train_dev = np.concatenate((bert_hatebert_added_olid_train, bert_hatebert_added_olid_dev))
bert_hatebert_added_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_added_olid_train_dev, bert_hatebert_added_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_added_olid_train_dev)
test_preds = mlp.predict(bert_hatebert_added_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_hatebert_added_olid_seed_3")

save_model(mlp, "Saves/bert_hatebert_added_olid_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.765785498489426
Accuracy Test:  0.7930232558139535
Weighted F1 Train Dev:  0.7597481094565556
Weighted F1 Test:  0.7771463388620887
Macro F1 Train Dev:  0.7234747572157649
Macro F1 Test:  0.706992519772454
Micro F1 Train Dev:  0.765785498489426
Micro F1 Test:  0.7930232558139535
Weighted Recall Train Dev:  0.765785498489426
Weighted Recall Test:  0.7930232558139535
Macro Recall Train Dev:  0.7150195392842451
Macro Recall Test:  0.6879032258064516
Micro Recall Train Dev:  0.765785498489426
Micro Recall Test:  0.7930232558139535
Confusion Matrix Train Dev: 
[[7659 1181]
 [1920 2480]]
Confusion Matrix Test: 
[[574  46]
 [132 108]]


### BERTweet-HateBERT

#### DynaHate

In [ ]:
hatebert_bertweet_added_dynahate_train_dev = np.concatenate((hatebert_bertweet_added_dynahate_train, hatebert_bertweet_added_dynahate_dev))
hatebert_bertweet_added_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_added_dynahate_train_dev, hatebert_bertweet_added_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_added_dynahate_train_dev)
test_preds = mlp.predict(hatebert_bertweet_added_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/hatebert_bertweet_added_dynahate_seed_3")

save_model(mlp, "Saves/hatebert_bertweet_added_dynahate_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7140773552290406
Accuracy Test:  0.6900485436893203
Weighted F1 Train Dev:  0.7100476048825624
Weighted F1 Test:  0.6853385404548508
Macro F1 Train Dev:  0.7064919428121403
Macro F1 Test:  0.679454572450228
Micro F1 Train Dev:  0.7140773552290406
Micro F1 Test:  0.6900485436893203
Weighted Recall Train Dev:  0.7140773552290406
Weighted Recall Test:  0.6900485436893203
Macro Recall Train Dev:  0.7059719323058098
Macro Recall Test:  0.6786109492193005
Micro Recall Train Dev:  0.7140773552290406
Micro Recall Test:  0.6900485436893203
Confusion Matrix Train Dev: 
[[10243  6874]
 [ 3712 16195]]
Confusion Matrix Test: 
[[1047  805]
 [ 472 1796]]


#### LatentHatred

In [ ]:
hatebert_bertweet_added_latenthatred_train_dev = np.concatenate((hatebert_bertweet_added_latenthatred_train, hatebert_bertweet_added_latenthatred_dev))
hatebert_bertweet_added_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_added_latenthatred_train_dev, hatebert_bertweet_added_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_added_latenthatred_train_dev)
test_preds = mlp.predict(hatebert_bertweet_added_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/hatebert_bertweet_added_latenthatred_seed_3")

save_model(mlp, "Saves/hatebert_bertweet_added_latenthatred_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7262569832402235
Accuracy Test:  0.6975791433891992
Weighted F1 Train Dev:  0.7046068835154048
Weighted F1 Test:  0.6746825214261521
Macro F1 Train Dev:  0.5161522092417578
Macro F1 Test:  0.48533240998450533
Micro F1 Train Dev:  0.7262569832402235
Micro F1 Test:  0.6975791433891992
Weighted Recall Train Dev:  0.7262569832402235
Weighted Recall Test:  0.6975791433891992
Macro Recall Train Dev:  0.49981760816930487
Macro Recall Test:  0.47205900435565895
Micro Recall Train Dev:  0.7262569832402235
Micro Recall Test:  0.6975791433891992
Confusion Matrix Train Dev: 
[[8791 1145    9]
 [2480 2840   27]
 [ 349  400   69]]
Confusion Matrix Test: 
[[2895  442    9]
 [ 908  830   15]
 [ 127  123   21]]


#### OLID

In [ ]:
hatebert_bertweet_added_olid_train_dev = np.concatenate((hatebert_bertweet_added_olid_train, hatebert_bertweet_added_olid_dev))
hatebert_bertweet_added_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_added_olid_train_dev, hatebert_bertweet_added_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_added_olid_train_dev)
test_preds = mlp.predict(hatebert_bertweet_added_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/hatebert_bertweet_added_olid_seed_3")

save_model(mlp, "Saves/hatebert_bertweet_added_olid_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7671450151057402
Accuracy Test:  0.7941860465116279
Weighted F1 Train Dev:  0.7583744389563151
Weighted F1 Test:  0.7805405004659259
Macro F1 Train Dev:  0.7197037754970822
Macro F1 Test:  0.7131988446559686
Micro F1 Train Dev:  0.7671450151057402
Micro F1 Test:  0.7941860465116279
Weighted Recall Train Dev:  0.7671450151057402
Weighted Recall Test:  0.7941860465116279
Macro Recall Train Dev:  0.7089032291238173
Macro Recall Test:  0.6950940860215054
Micro Recall Train Dev:  0.7671450151057402
Micro Recall Test:  0.7941860465116279
Confusion Matrix Train Dev: 
[[7802 1038]
 [2045 2355]]
Confusion Matrix Test: 
[[570  50]
 [127 113]]


### BERT-BERTweet-HateBERT

#### DynaHate

In [ ]:
bert_bertweet_hatebert_added_dynahate_train_dev = np.concatenate((bert_hatebert_bertweet_added_dynahate_train, bert_hatebert_bertweet_added_dynahate_dev))
bert_bertweet_hatebert_added_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_added_dynahate_train_dev, bert_bertweet_hatebert_added_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_added_dynahate_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_added_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_bertweet_hatebert_added_dynahate_seed_3")

save_model(mlp, "Saves/bert_bertweet_hatebert_added_dynahate_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.712942955920484
Accuracy Test:  0.6803398058252427
Weighted F1 Train Dev:  0.7086008693037876
Weighted F1 Test:  0.6759861761476528
Macro F1 Train Dev:  0.7049387103979284
Macro F1 Test:  0.6701249789118034
Micro F1 Train Dev:  0.712942955920484
Micro F1 Test:  0.6803398058252427
Weighted Recall Train Dev:  0.712942955920484
Weighted Recall Test:  0.6803398058252427
Macro Recall Train Dev:  0.704532197285585
Macro Recall Test:  0.6693964482841372
Micro Recall Train Dev:  0.712942955920484
Micro Recall Test:  0.6803398058252427
Confusion Matrix Train Dev: 
[[10149  6968]
 [ 3660 16247]]
Confusion Matrix Test: 
[[1039  813]
 [ 504 1764]]


#### LatentHatred

In [ ]:
bert_bertweet_hatebert_added_latenthatred_train_dev = np.concatenate((bert_hatebert_bertweet_added_latenthatred_train, bert_hatebert_bertweet_added_latenthatred_dev))
bert_bertweet_hatebert_added_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_added_latenthatred_train_dev, bert_bertweet_hatebert_added_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_added_latenthatred_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_added_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_bertweet_hatebert_added_latenthatred_seed_3")

save_model(mlp, "Saves/bert_bertweet_hatebert_added_latenthatred_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7141527001862198
Accuracy Test:  0.6972067039106146
Weighted F1 Train Dev:  0.6846465945723406
Weighted F1 Test:  0.6640145574831627
Macro F1 Train Dev:  0.47551137467369897
Macro F1 Test:  0.44930319495735027
Micro F1 Train Dev:  0.7141527001862197
Micro F1 Test:  0.6972067039106146
Weighted Recall Train Dev:  0.7141527001862198
Weighted Recall Test:  0.6972067039106146
Macro Recall Train Dev:  0.46987600910795607
Macro Recall Test:  0.44770564164353527
Micro Recall Train Dev:  0.7141527001862198
Micro Recall Test:  0.6972067039106146
Confusion Matrix Train Dev: 
[[8953  986    6]
 [2816 2521   10]
 [ 379  408   31]]
Confusion Matrix Test: 
[[2999  344    3]
 [1009  738    6]
 [ 139  125    7]]


#### OLID

In [ ]:
bert_bertweet_hatebert_added_olid_train_dev = np.concatenate((bert_hatebert_bertweet_added_olid_train, bert_hatebert_bertweet_added_olid_dev))
bert_bertweet_hatebert_added_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_added_olid_train_dev, bert_bertweet_hatebert_added_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_added_olid_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_added_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_bertweet_hatebert_added_olid_seed_3")

save_model(mlp, "Saves/bert_bertweet_hatebert_added_olid_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7681268882175226
Accuracy Test:  0.7988372093023256
Weighted F1 Train Dev:  0.7564901078882278
Weighted F1 Test:  0.780138449312451
Macro F1 Train Dev:  0.7154191184907168
Macro F1 Test:  0.7083654311694981
Micro F1 Train Dev:  0.7681268882175226
Micro F1 Test:  0.7988372093023256
Weighted Recall Train Dev:  0.7681268882175226
Weighted Recall Test:  0.7988372093023256
Macro Recall Train Dev:  0.7028465651995064
Macro Recall Test:  0.6868279569892473
Micro Recall Train Dev:  0.7681268882175226
Micro Recall Test:  0.7988372093023256
Confusion Matrix Train Dev: 
[[7934  906]
 [2164 2236]]
Confusion Matrix Test: 
[[583  37]
 [136 104]]
