In [1]:
from utils import *
import numpy as np
import torch, os
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV

In [2]:
set_random_seed(7)

Seed: 7


In [3]:
# def scaling_embeddings(embeddings):
#     for i in range(len(embeddings)):
#         embeddings[i] = StandardScaler().fit_transform(embeddings[i])
#     return embeddings

def reshape_embeddings(embeddings):
    if embeddings.shape[1] == 1:
        embeddings = embeddings.squeeze(1)
    return embeddings

In [4]:
def add_2_embeddings(embeddings1, embeddings2):
    embeddings1 = reshape_embeddings(embeddings1)
    embeddings2 = reshape_embeddings(embeddings2)
    # Numpy Add
    return embeddings1 + embeddings2

def add_3_embeddings(embeddings1, embeddings2, embeddings3):
    embeddings1 = reshape_embeddings(embeddings1)
    embeddings2 = reshape_embeddings(embeddings2)
    embeddings3 = reshape_embeddings(embeddings3)
    return embeddings1 + embeddings2 + embeddings3

In [5]:
bert_hatebert_added_dynahate_train = add_2_embeddings(bert_dynahate_train_embeddings, hatebert_dynahate_train_embeddings)
bert_hatebert_added_dynahate_dev = add_2_embeddings(bert_dynahate_dev_embeddings, hatebert_dynahate_dev_embeddings)
bert_hatebert_added_dynahate_test = add_2_embeddings(bert_dynahate_test_embeddings, hatebert_dynahate_test_embeddings)

bert_bertweet_added_dynahate_train = add_2_embeddings(bert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
bert_bertweet_added_dynahate_dev = add_2_embeddings(bert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
bert_bertweet_added_dynahate_test = add_2_embeddings(bert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

hatebert_bertweet_added_dynahate_train = add_2_embeddings(hatebert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
hatebert_bertweet_added_dynahate_dev = add_2_embeddings(hatebert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
hatebert_bertweet_added_dynahate_test = add_2_embeddings(hatebert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

bert_hatebert_bertweet_added_dynahate_train = add_3_embeddings(bert_dynahate_train_embeddings, hatebert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
bert_hatebert_bertweet_added_dynahate_dev = add_3_embeddings(bert_dynahate_dev_embeddings, hatebert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
bert_hatebert_bertweet_added_dynahate_test = add_3_embeddings(bert_dynahate_test_embeddings, hatebert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

bert_hatebert_added_olid_train = add_2_embeddings(bert_olid_train_embeddings, hatebert_olid_train_embeddings)
bert_hatebert_added_olid_dev = add_2_embeddings(bert_olid_dev_embeddings, hatebert_olid_dev_embeddings)
bert_hatebert_added_olid_test = add_2_embeddings(bert_olid_test_embeddings, hatebert_olid_test_embeddings)

bert_bertweet_added_olid_train = add_2_embeddings(bert_olid_train_embeddings, bertweet_olid_train_embeddings)
bert_bertweet_added_olid_dev = add_2_embeddings(bert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
bert_bertweet_added_olid_test = add_2_embeddings(bert_olid_test_embeddings, bertweet_olid_test_embeddings)

hatebert_bertweet_added_olid_train = add_2_embeddings(hatebert_olid_train_embeddings, bertweet_olid_train_embeddings)
hatebert_bertweet_added_olid_dev = add_2_embeddings(hatebert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
hatebert_bertweet_added_olid_test = add_2_embeddings(hatebert_olid_test_embeddings, bertweet_olid_test_embeddings)

bert_hatebert_bertweet_added_olid_train = add_3_embeddings(bert_olid_train_embeddings, hatebert_olid_train_embeddings, bertweet_olid_train_embeddings)
bert_hatebert_bertweet_added_olid_dev = add_3_embeddings(bert_olid_dev_embeddings, hatebert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
bert_hatebert_bertweet_added_olid_test = add_3_embeddings(bert_olid_test_embeddings, hatebert_olid_test_embeddings, bertweet_olid_test_embeddings)

bert_hatebert_added_latenthatred_train = add_2_embeddings(bert_latenthatred_train_embeddings, hatebert_latenthatred_train_embeddings)
bert_hatebert_added_latenthatred_dev = add_2_embeddings(bert_latenthatred_dev_embeddings, hatebert_latenthatred_dev_embeddings)
bert_hatebert_added_latenthatred_test = add_2_embeddings(bert_latenthatred_test_embeddings, hatebert_latenthatred_test_embeddings)

bert_bertweet_added_latenthatred_train = add_2_embeddings(bert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
bert_bertweet_added_latenthatred_dev = add_2_embeddings(bert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
bert_bertweet_added_latenthatred_test = add_2_embeddings(bert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

hatebert_bertweet_added_latenthatred_train = add_2_embeddings(hatebert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
hatebert_bertweet_added_latenthatred_dev = add_2_embeddings(hatebert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
hatebert_bertweet_added_latenthatred_test = add_2_embeddings(hatebert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

bert_hatebert_bertweet_added_latenthatred_train = add_3_embeddings(bert_latenthatred_train_embeddings, hatebert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
bert_hatebert_bertweet_added_latenthatred_dev = add_3_embeddings(bert_latenthatred_dev_embeddings, hatebert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
bert_hatebert_bertweet_added_latenthatred_test = add_3_embeddings(bert_latenthatred_test_embeddings, hatebert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

In [6]:
dynahate_labels_train = process_labels(read_labels("dynahate", "train"))
dynahate_labels_dev = process_labels(read_labels("dynahate", "dev"))
dynahate_labels_test = process_labels(read_labels("dynahate", "test"))

latenthatred_labels_train = read_labels("latenthatred", "train")
latenthatred_labels_dev = read_labels("latenthatred", "dev")
latenthatred_labels_test = read_labels("latenthatred", "test")

olid_labels_train = read_labels("olid", "train")
olid_labels_dev = read_labels("olid", "dev")
olid_labels_test = read_labels("olid", "test")

In [7]:
mlp = MLPClassifier(random_state=7)
gridsearch = GridSearchCV(
    mlp,
    param_grid={
        "hidden_layer_sizes": [(128), (128,64)],
        "activation": ["relu"],
        "solver": ["adam"],
        "learning_rate_init": [0.001, 0.0001],
        "learning_rate": ["adaptive"],
        "early_stopping": [True],
        "max_iter": [10000]
    },
    verbose=4,
    n_jobs=os.cpu_count()//3,
    cv=5,
)

In [8]:
dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))
latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))
olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

### BERT-BERTweet

#### DynaHate

In [9]:
bert_bertweet_added_dynahate_train_dev = np.concatenate((bert_bertweet_added_dynahate_train, bert_bertweet_added_dynahate_dev))
bert_bertweet_added_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_added_dynahate_train_dev, bert_bertweet_added_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_added_dynahate_train_dev)
test_preds = mlp.predict(bert_bertweet_added_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_bertweet_added_dynahate_seed_7")
save_model(mlp, "Saves/bert_bertweet_added_dynahate_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.6845559636992221
Accuracy Test:  0.6558252427184466
Weighted F1 Train Dev:  0.6849292034077074
Weighted F1 Test:  0.6566832712814794
Macro F1 Train Dev:  0.6843992600048199
Macro F1 Test:  0.6551960217722227
Micro F1 Train Dev:  0.6845559636992221
Micro F1 Test:  0.6558252427184466
Weighted Recall Train Dev:  0.6845559636992221
Weighted Recall Test:  0.6558252427184466
Macro Recall Train Dev:  0.6867767405049123
Macro Recall Test:  0.658222580288815
Micro Recall Train Dev:  0.6845559636992221
Micro Recall Test:  0.6558252427184466
Confusion Matrix Train Dev: 
[[12260  4857]
 [ 6822 13085]]
Confusion Matrix Test: 
[[1263  589]
 [ 829 1439]]


#### LatentHatred

In [10]:
bert_bertweet_added_latenthatred_train_dev = np.concatenate((bert_bertweet_added_latenthatred_train, bert_bertweet_added_latenthatred_dev))
bert_bertweet_added_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_added_latenthatred_train_dev, bert_bertweet_added_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_added_latenthatred_train_dev)
test_preds = mlp.predict(bert_bertweet_added_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_bertweet_added_latenthatred_seed_7")
save_model(mlp, "Saves/bert_bertweet_added_latenthatred_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7108007448789572
Accuracy Test:  0.6919925512104284
Weighted F1 Train Dev:  0.6802273425698766
Weighted F1 Test:  0.6585531139015959
Macro F1 Train Dev:  0.4919276626529383
Macro F1 Test:  0.46469431738408584
Micro F1 Train Dev:  0.7108007448789571
Micro F1 Test:  0.6919925512104284
Weighted Recall Train Dev:  0.7108007448789572
Weighted Recall Test:  0.6919925512104284
Macro Recall Train Dev:  0.47585129771902746
Macro Recall Test:  0.4534113200158744
Micro Recall Train Dev:  0.7108007448789572
Micro Recall Test:  0.6919925512104284
Confusion Matrix Train Dev: 
[[9060  863   22]
 [2993 2324   30]
 [ 428  323   67]]
Confusion Matrix Test: 
[[3015  320   11]
 [1058  682   13]
 [ 133  119   19]]


#### OLID

In [11]:
bert_bertweet_added_olid_train_dev = np.concatenate((bert_bertweet_added_olid_train, bert_bertweet_added_olid_dev))
bert_bertweet_added_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_added_olid_train_dev, bert_bertweet_added_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_added_olid_train_dev)
test_preds = mlp.predict(bert_bertweet_added_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_bertweet_added_olid_seed_7")

save_model(mlp, "Saves/bert_bertweet_added_olid_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7571752265861027
Accuracy Test:  0.7906976744186046
Weighted F1 Train Dev:  0.7489945158548368
Weighted F1 Test:  0.7751384426716402
Macro F1 Train Dev:  0.7095565618409168
Macro F1 Test:  0.7047514419115628
Micro F1 Train Dev:  0.7571752265861027
Micro F1 Test:  0.7906976744186046
Weighted Recall Train Dev:  0.7571752265861027
Weighted Recall Test:  0.7906976744186046
Macro Recall Train Dev:  0.7001244343891403
Macro Recall Test:  0.6862903225806452
Micro Recall Train Dev:  0.7571752265861027
Micro Recall Test:  0.7906976744186046
Confusion Matrix Train Dev: 
[[7693 1147]
 [2068 2332]]
Confusion Matrix Test: 
[[572  48]
 [132 108]]


### BERT-HateBERT

#### DynaHate

In [12]:
bert_hatebert_added_dynahate_train_dev = np.concatenate((bert_hatebert_added_dynahate_train, bert_hatebert_added_dynahate_dev))
bert_hatebert_added_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_added_dynahate_train_dev, bert_hatebert_added_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_added_dynahate_train_dev)
test_preds = mlp.predict(bert_hatebert_added_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_hatebert_added_dynahate_seed_7")

save_model(mlp, "Saves/bert_hatebert_added_dynahate_seed_7")



Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7159680207433017
Accuracy Test:  0.6866504854368932
Weighted F1 Train Dev:  0.7123051783403864
Weighted F1 Test:  0.6834058017776935
Macro F1 Train Dev:  0.7088827636370596
Macro F1 Test:  0.6781125139258222
Micro F1 Train Dev:  0.7159680207433018
Micro F1 Test:  0.6866504854368932
Weighted Recall Train Dev:  0.7159680207433017
Weighted Recall Test:  0.6866504854368932
Macro Recall Train Dev:  0.7082336615921275
Macro Recall Test:  0.6771091646001652
Micro Recall Train Dev:  0.7159680207433017
Micro Recall Test:  0.6866504854368932
Confusion Matrix Train Dev: 
[[10366  6751]
 [ 3765 16142]]
Confusion Matrix Test: 
[[1079  773]
 [ 518 1750]]


#### LatentHatred

In [13]:
bert_hatebert_added_latenthatred_train_dev = np.concatenate((bert_hatebert_added_latenthatred_train, bert_hatebert_added_latenthatred_dev))
bert_hatebert_added_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_added_latenthatred_train_dev, bert_hatebert_added_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_added_latenthatred_train_dev)
test_preds = mlp.predict(bert_hatebert_added_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_hatebert_added_latenthatred_seed_7")

save_model(mlp, "Saves/bert_hatebert_added_latenthatred_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.6901924270639355
Accuracy Test:  0.6849162011173184
Weighted F1 Train Dev:  0.6627801669222751
Weighted F1 Test:  0.6557919989248809
Macro F1 Train Dev:  0.45474413345367193
Macro F1 Test:  0.44450423545990136
Micro F1 Train Dev:  0.6901924270639355
Micro F1 Test:  0.6849162011173184
Weighted Recall Train Dev:  0.6901924270639355
Weighted Recall Test:  0.6849162011173184
Macro Recall Train Dev:  0.4528503712331185
Macro Recall Test:  0.44357490376407743
Micro Recall Train Dev:  0.6901924270639355
Micro Recall Test:  0.6849162011173184
Confusion Matrix Train Dev: 
[[8625 1306   14]
 [2868 2470    9]
 [ 387  407   24]]
Confusion Matrix Test: 
[[2906  436    4]
 [ 985  765    3]
 [ 130  134    7]]


#### OLID

In [14]:
bert_hatebert_added_olid_train_dev = np.concatenate((bert_hatebert_added_olid_train, bert_hatebert_added_olid_dev))
bert_hatebert_added_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_added_olid_train_dev, bert_hatebert_added_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_added_olid_train_dev)
test_preds = mlp.predict(bert_hatebert_added_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_hatebert_added_olid_seed_7")

save_model(mlp, "Saves/bert_hatebert_added_olid_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7657099697885197
Accuracy Test:  0.791860465116279
Weighted F1 Train Dev:  0.7476069264580056
Weighted F1 Test:  0.7647463792894517
Macro F1 Train Dev:  0.700930089996053
Macro F1 Test:  0.6823195583758964
Micro F1 Train Dev:  0.7657099697885197
Micro F1 Test:  0.791860465116279
Weighted Recall Train Dev:  0.7657099697885197
Weighted Recall Test:  0.791860465116279
Macro Recall Train Dev:  0.686881941587824
Macro Recall Test:  0.6615591397849462
Micro Recall Train Dev:  0.7657099697885197
Micro Recall Test:  0.791860465116279
Confusion Matrix Train Dev: 
[[8150  690]
 [2412 1988]]
Confusion Matrix Test: 
[[593  27]
 [152  88]]


### BERTweet-HateBERT

#### DynaHate

In [15]:
hatebert_bertweet_added_dynahate_train_dev = np.concatenate((hatebert_bertweet_added_dynahate_train, hatebert_bertweet_added_dynahate_dev))
hatebert_bertweet_added_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_added_dynahate_train_dev, hatebert_bertweet_added_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_added_dynahate_train_dev)
test_preds = mlp.predict(hatebert_bertweet_added_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/hatebert_bertweet_added_dynahate_seed_7")

save_model(mlp, "Saves/hatebert_bertweet_added_dynahate_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7416540622299049
Accuracy Test:  0.6851941747572815
Weighted F1 Train Dev:  0.736636143309997
Weighted F1 Test:  0.6785765520012732
Macro F1 Train Dev:  0.7330176388420355
Macro F1 Test:  0.6719108593463108
Micro F1 Train Dev:  0.7416540622299049
Micro F1 Test:  0.6851941747572815
Weighted Recall Train Dev:  0.7416540622299049
Weighted Recall Test:  0.6851941747572815
Macro Recall Train Dev:  0.732258925543768
Macro Recall Test:  0.6717257857466641
Micro Recall Train Dev:  0.7416540622299049
Micro Recall Test:  0.6851941747572815
Confusion Matrix Train Dev: 
[[10400  6717]
 [ 2848 17059]]
Confusion Matrix Test: 
[[ 997  855]
 [ 442 1826]]


#### LatentHatred

In [16]:
hatebert_bertweet_added_latenthatred_train_dev = np.concatenate((hatebert_bertweet_added_latenthatred_train, hatebert_bertweet_added_latenthatred_dev))
hatebert_bertweet_added_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_added_latenthatred_train_dev, hatebert_bertweet_added_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_added_latenthatred_train_dev)
test_preds = mlp.predict(hatebert_bertweet_added_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/hatebert_bertweet_added_latenthatred_seed_7")

save_model(mlp, "Saves/hatebert_bertweet_added_latenthatred_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7080074487895717
Accuracy Test:  0.6873370577281191
Weighted F1 Train Dev:  0.6815333478051822
Weighted F1 Test:  0.6551559634026566
Macro F1 Train Dev:  0.530265123671371
Macro F1 Test:  0.494625822729519
Micro F1 Train Dev:  0.7080074487895716
Micro F1 Test:  0.6873370577281191
Weighted Recall Train Dev:  0.7080074487895717
Weighted Recall Test:  0.6873370577281191
Macro Recall Train Dev:  0.5084819401084658
Macro Recall Test:  0.47831443773019705
Micro Recall Train Dev:  0.7080074487895717
Micro Recall Test:  0.6873370577281191
Confusion Matrix Train Dev: 
[[9064  804   77]
 [3009 2172  166]
 [ 362  286  170]]
Confusion Matrix Test: 
[[3032  283   31]
 [1085  610   58]
 [ 131   91   49]]


#### OLID

In [17]:
hatebert_bertweet_added_olid_train_dev = np.concatenate((hatebert_bertweet_added_olid_train, hatebert_bertweet_added_olid_dev))
hatebert_bertweet_added_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_added_olid_train_dev, hatebert_bertweet_added_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_added_olid_train_dev)
test_preds = mlp.predict(hatebert_bertweet_added_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/hatebert_bertweet_added_olid_seed_7")

save_model(mlp, "Saves/hatebert_bertweet_added_olid_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.747583081570997
Accuracy Test:  0.7790697674418605
Weighted F1 Train Dev:  0.7302870115601867
Weighted F1 Test:  0.7519949840401278
Macro F1 Train Dev:  0.6817443119091138
Macro F1 Test:  0.6662581699346406
Micro F1 Train Dev:  0.7475830815709968
Micro F1 Test:  0.7790697674418605
Weighted Recall Train Dev:  0.747583081570997
Weighted Recall Test:  0.7790697674418605
Macro Recall Train Dev:  0.6704535170711641
Macro Recall Test:  0.6488575268817205
Micro Recall Train Dev:  0.747583081570997
Micro Recall Test:  0.7790697674418605
Confusion Matrix Train Dev: 
[[7960  880]
 [2462 1938]]
Confusion Matrix Test: 
[[585  35]
 [155  85]]


### BERT-BERTweet-HateBERT

#### DynaHate

In [18]:
bert_bertweet_hatebert_added_dynahate_train_dev = np.concatenate((bert_hatebert_bertweet_added_dynahate_train, bert_hatebert_bertweet_added_dynahate_dev))
bert_bertweet_hatebert_added_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_added_dynahate_train_dev, bert_bertweet_hatebert_added_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_added_dynahate_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_added_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_bertweet_hatebert_added_dynahate_seed_7")

save_model(mlp, "Saves/bert_bertweet_hatebert_added_dynahate_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7267448141745895
Accuracy Test:  0.6878640776699029
Weighted F1 Train Dev:  0.7264863812328877
Weighted F1 Test:  0.6882148758182516
Macro F1 Train Dev:  0.7246972300980286
Macro F1 Test:  0.685408490631463
Micro F1 Train Dev:  0.7267448141745895
Micro F1 Test:  0.6878640776699029
Weighted Recall Train Dev:  0.7267448141745895
Weighted Recall Test:  0.6878640776699029
Macro Recall Train Dev:  0.7243593162725573
Macro Recall Test:  0.6859365536471368
Micro Recall Train Dev:  0.7267448141745895
Micro Recall Test:  0.6878640776699029
Confusion Matrix Train Dev: 
[[11857  5260]
 [ 4857 15050]]
Confusion Matrix Test: 
[[1235  617]
 [ 669 1599]]


#### LatentHatred

In [19]:
bert_bertweet_hatebert_added_latenthatred_train_dev = np.concatenate((bert_hatebert_bertweet_added_latenthatred_train, bert_hatebert_bertweet_added_latenthatred_dev))
bert_bertweet_hatebert_added_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_added_latenthatred_train_dev, bert_bertweet_hatebert_added_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_added_latenthatred_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_added_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_bertweet_hatebert_added_latenthatred_seed_7")

save_model(mlp, "Saves/bert_bertweet_hatebert_added_latenthatred_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7189944134078212
Accuracy Test:  0.6953445065176909
Weighted F1 Train Dev:  0.7008776874515674
Weighted F1 Test:  0.6762814964384937
Macro F1 Train Dev:  0.5195109576237402
Macro F1 Test:  0.4948286738372311
Micro F1 Train Dev:  0.7189944134078212
Micro F1 Test:  0.6953445065176909
Weighted Recall Train Dev:  0.7189944134078212
Weighted Recall Test:  0.6953445065176909
Macro Recall Train Dev:  0.5025743184369523
Macro Recall Test:  0.4795934799259353
Micro Recall Train Dev:  0.7189944134078212
Micro Recall Test:  0.6953445065176909
Confusion Matrix Train Dev: 
[[8586 1330   29]
 [2391 2916   40]
 [ 328  409   81]]
Confusion Matrix Test: 
[[2844  487   15]
 [ 871  864   18]
 [ 114  131   26]]


#### OLID

In [20]:
bert_bertweet_hatebert_added_olid_train_dev = np.concatenate((bert_hatebert_bertweet_added_olid_train, bert_hatebert_bertweet_added_olid_dev))
bert_bertweet_hatebert_added_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_added_olid_train_dev, bert_bertweet_hatebert_added_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_added_olid_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_added_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_bertweet_hatebert_added_olid_seed_7")

save_model(mlp, "Saves/bert_bertweet_hatebert_added_olid_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7552870090634441
Accuracy Test:  0.7930232558139535
Weighted F1 Train Dev:  0.7398857875304635
Weighted F1 Test:  0.7657341910731423
Macro F1 Train Dev:  0.6939305297304406
Macro F1 Test:  0.6834338370929184
Micro F1 Train Dev:  0.7552870090634441
Micro F1 Test:  0.7930232558139535
Weighted Recall Train Dev:  0.7552870090634441
Weighted Recall Test:  0.7930232558139535
Macro Recall Train Dev:  0.6818161250514192
Macro Recall Test:  0.6623655913978495
Micro Recall Train Dev:  0.7552870090634441
Micro Recall Test:  0.7930232558139535
Confusion Matrix Train Dev: 
[[7964  876]
 [2364 2036]]
Confusion Matrix Test: 
[[594  26]
 [152  88]]
