In [1]:
from utils import *
import numpy as np
import torch, os
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV

In [2]:
set_random_seed(3)

Seed: 3


In [3]:
# def scaling_embeddings(embeddings):
#     for i in range(len(embeddings)):
#         embeddings[i] = StandardScaler().fit_transform(embeddings[i])
#     return embeddings

def reshape_embeddings(embeddings):
    if embeddings.shape[1] == 1:
        embeddings = embeddings.squeeze(1)
    return embeddings

In [4]:
def add_2_embeddings(embeddings1, embeddings2):
    embeddings1 = reshape_embeddings(embeddings1)
    embeddings2 = reshape_embeddings(embeddings2)
    # Numpy Add
    return embeddings1 + embeddings2

def add_3_embeddings(embeddings1, embeddings2, embeddings3):
    embeddings1 = reshape_embeddings(embeddings1)
    embeddings2 = reshape_embeddings(embeddings2)
    embeddings3 = reshape_embeddings(embeddings3)
    return embeddings1 + embeddings2 + embeddings3

In [5]:
bert_hatebert_added_dynahate_train = add_2_embeddings(bert_dynahate_train_embeddings, hatebert_dynahate_train_embeddings)
bert_hatebert_added_dynahate_dev = add_2_embeddings(bert_dynahate_dev_embeddings, hatebert_dynahate_dev_embeddings)
bert_hatebert_added_dynahate_test = add_2_embeddings(bert_dynahate_test_embeddings, hatebert_dynahate_test_embeddings)

bert_bertweet_added_dynahate_train = add_2_embeddings(bert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
bert_bertweet_added_dynahate_dev = add_2_embeddings(bert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
bert_bertweet_added_dynahate_test = add_2_embeddings(bert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

hatebert_bertweet_added_dynahate_train = add_2_embeddings(hatebert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
hatebert_bertweet_added_dynahate_dev = add_2_embeddings(hatebert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
hatebert_bertweet_added_dynahate_test = add_2_embeddings(hatebert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

bert_hatebert_bertweet_added_dynahate_train = add_3_embeddings(bert_dynahate_train_embeddings, hatebert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
bert_hatebert_bertweet_added_dynahate_dev = add_3_embeddings(bert_dynahate_dev_embeddings, hatebert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
bert_hatebert_bertweet_added_dynahate_test = add_3_embeddings(bert_dynahate_test_embeddings, hatebert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

bert_hatebert_added_olid_train = add_2_embeddings(bert_olid_train_embeddings, hatebert_olid_train_embeddings)
bert_hatebert_added_olid_dev = add_2_embeddings(bert_olid_dev_embeddings, hatebert_olid_dev_embeddings)
bert_hatebert_added_olid_test = add_2_embeddings(bert_olid_test_embeddings, hatebert_olid_test_embeddings)

bert_bertweet_added_olid_train = add_2_embeddings(bert_olid_train_embeddings, bertweet_olid_train_embeddings)
bert_bertweet_added_olid_dev = add_2_embeddings(bert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
bert_bertweet_added_olid_test = add_2_embeddings(bert_olid_test_embeddings, bertweet_olid_test_embeddings)

hatebert_bertweet_added_olid_train = add_2_embeddings(hatebert_olid_train_embeddings, bertweet_olid_train_embeddings)
hatebert_bertweet_added_olid_dev = add_2_embeddings(hatebert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
hatebert_bertweet_added_olid_test = add_2_embeddings(hatebert_olid_test_embeddings, bertweet_olid_test_embeddings)

bert_hatebert_bertweet_added_olid_train = add_3_embeddings(bert_olid_train_embeddings, hatebert_olid_train_embeddings, bertweet_olid_train_embeddings)
bert_hatebert_bertweet_added_olid_dev = add_3_embeddings(bert_olid_dev_embeddings, hatebert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
bert_hatebert_bertweet_added_olid_test = add_3_embeddings(bert_olid_test_embeddings, hatebert_olid_test_embeddings, bertweet_olid_test_embeddings)

bert_hatebert_added_latenthatred_train = add_2_embeddings(bert_latenthatred_train_embeddings, hatebert_latenthatred_train_embeddings)
bert_hatebert_added_latenthatred_dev = add_2_embeddings(bert_latenthatred_dev_embeddings, hatebert_latenthatred_dev_embeddings)
bert_hatebert_added_latenthatred_test = add_2_embeddings(bert_latenthatred_test_embeddings, hatebert_latenthatred_test_embeddings)

bert_bertweet_added_latenthatred_train = add_2_embeddings(bert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
bert_bertweet_added_latenthatred_dev = add_2_embeddings(bert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
bert_bertweet_added_latenthatred_test = add_2_embeddings(bert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

hatebert_bertweet_added_latenthatred_train = add_2_embeddings(hatebert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
hatebert_bertweet_added_latenthatred_dev = add_2_embeddings(hatebert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
hatebert_bertweet_added_latenthatred_test = add_2_embeddings(hatebert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

bert_hatebert_bertweet_added_latenthatred_train = add_3_embeddings(bert_latenthatred_train_embeddings, hatebert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
bert_hatebert_bertweet_added_latenthatred_dev = add_3_embeddings(bert_latenthatred_dev_embeddings, hatebert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
bert_hatebert_bertweet_added_latenthatred_test = add_3_embeddings(bert_latenthatred_test_embeddings, hatebert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

In [6]:
dynahate_labels_train = process_labels(read_labels("dynahate", "train"))
dynahate_labels_dev = process_labels(read_labels("dynahate", "dev"))
dynahate_labels_test = process_labels(read_labels("dynahate", "test"))

latenthatred_labels_train = read_labels("latenthatred", "train")
latenthatred_labels_dev = read_labels("latenthatred", "dev")
latenthatred_labels_test = read_labels("latenthatred", "test")

olid_labels_train = read_labels("olid", "train")
olid_labels_dev = read_labels("olid", "dev")
olid_labels_test = read_labels("olid", "test")

In [7]:
mlp = MLPClassifier(random_state=3)
gridsearch = GridSearchCV(
    mlp,
    param_grid={
        "hidden_layer_sizes": [(128), (128,64)],
        "activation": ["relu"],
        "solver": ["adam"],
        "learning_rate_init": [0.001, 0.0001],
        "learning_rate": ["adaptive"],
        "early_stopping": [True],
        "max_iter": [10000]
    },
    verbose=4,
    n_jobs=os.cpu_count()//3,
    cv=5,
)

In [8]:
dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))
latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))
olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

### BERT-BERTweet

#### DynaHate

In [9]:
bert_bertweet_added_dynahate_train_dev = np.concatenate((bert_bertweet_added_dynahate_train, bert_bertweet_added_dynahate_dev))
bert_bertweet_added_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_added_dynahate_train_dev, bert_bertweet_added_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_added_dynahate_train_dev)
test_preds = mlp.predict(bert_bertweet_added_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_bertweet_added_dynahate_seed_3")
save_model(mlp, "Saves/bert_bertweet_added_dynahate_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7013018582541054
Accuracy Test:  0.6742718446601942
Weighted F1 Train Dev:  0.6995032865054512
Weighted F1 Test:  0.6717557235001604
Macro F1 Train Dev:  0.6966825921947458
Macro F1 Test:  0.6666746244585386
Micro F1 Train Dev:  0.7013018582541054
Micro F1 Test:  0.6742718446601942
Weighted Recall Train Dev:  0.7013018582541054
Weighted Recall Test:  0.6742718446601942
Macro Recall Train Dev:  0.695954428731564
Macro Recall Test:  0.6658162585088432
Micro Recall Train Dev:  0.7013018582541054
Micro Recall Test:  0.6742718446601942
Confusion Matrix Train Dev: 
[[10698  6419]
 [ 4640 15267]]
Confusion Matrix Test: 
[[1078  774]
 [ 568 1700]]


#### LatentHatred

In [10]:
bert_bertweet_added_latenthatred_train_dev = np.concatenate((bert_bertweet_added_latenthatred_train, bert_bertweet_added_latenthatred_dev))
bert_bertweet_added_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_added_latenthatred_train_dev, bert_bertweet_added_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_added_latenthatred_train_dev)
test_preds = mlp.predict(bert_bertweet_added_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_bertweet_added_latenthatred_seed_3")
save_model(mlp, "Saves/bert_bertweet_added_latenthatred_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7128491620111732
Accuracy Test:  0.6921787709497207
Weighted F1 Train Dev:  0.6897682583500261
Weighted F1 Test:  0.6657062914755787
Macro F1 Train Dev:  0.5095405775167801
Macro F1 Test:  0.47210074978256555
Micro F1 Train Dev:  0.7128491620111732
Micro F1 Test:  0.6921787709497207
Weighted Recall Train Dev:  0.7128491620111732
Weighted Recall Test:  0.6921787709497207
Macro Recall Train Dev:  0.4908103411491855
Macro Recall Test:  0.4610248302059598
Micro Recall Train Dev:  0.7128491620111732
Micro Recall Test:  0.6921787709497207
Confusion Matrix Train Dev: 
[[8792 1121   32]
 [2699 2610   38]
 [ 390  346   82]]
Confusion Matrix Test: 
[[2933  403   10]
 [ 969  765   19]
 [ 118  134   19]]


#### OLID

In [11]:
bert_bertweet_added_olid_train_dev = np.concatenate((bert_bertweet_added_olid_train, bert_bertweet_added_olid_dev))
bert_bertweet_added_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_added_olid_train_dev, bert_bertweet_added_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_added_olid_train_dev)
test_preds = mlp.predict(bert_bertweet_added_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_bertweet_added_olid_seed_3")

save_model(mlp, "Saves/bert_bertweet_added_olid_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7756042296072507
Accuracy Test:  0.8069767441860465
Weighted F1 Train Dev:  0.7646133560361167
Weighted F1 Test:  0.7872236511504099
Macro F1 Train Dev:  0.7250996081366549
Macro F1 Test:  0.7164106761169955
Micro F1 Train Dev:  0.7756042296072507
Micro F1 Test:  0.8069767441860464
Weighted Recall Train Dev:  0.7756042296072507
Weighted Recall Test:  0.8069767441860465
Macro Recall Train Dev:  0.7119277046482929
Macro Recall Test:  0.6924731182795699
Micro Recall Train Dev:  0.7756042296072507
Micro Recall Test:  0.8069767441860465
Confusion Matrix Train Dev: 
[[7972  868]
 [2103 2297]]
Confusion Matrix Test: 
[[590  30]
 [136 104]]


### BERT-HateBERT

#### DynaHate

In [12]:
bert_hatebert_added_dynahate_train_dev = np.concatenate((bert_hatebert_added_dynahate_train, bert_hatebert_added_dynahate_dev))
bert_hatebert_added_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_added_dynahate_train_dev, bert_hatebert_added_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_added_dynahate_train_dev)
test_preds = mlp.predict(bert_hatebert_added_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_hatebert_added_dynahate_seed_3")

save_model(mlp, "Saves/bert_hatebert_added_dynahate_seed_3")



Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.69754753673293
Accuracy Test:  0.6851941747572815
Weighted F1 Train Dev:  0.6949482481174867
Weighted F1 Test:  0.682215621662376
Macro F1 Train Dev:  0.6917675396801679
Macro F1 Test:  0.6770311945181053
Micro F1 Train Dev:  0.69754753673293
Micro F1 Test:  0.6851941747572815
Weighted Recall Train Dev:  0.69754753673293
Weighted Recall Test:  0.6851941747572815
Macro Recall Train Dev:  0.6911531359032975
Macro Recall Test:  0.6760340125170938
Micro Recall Train Dev:  0.69754753673293
Micro Recall Test:  0.6851941747572815
Confusion Matrix Train Dev: 
[[10378  6739]
 [ 4459 15448]]
Confusion Matrix Test: 
[[1084  768]
 [ 529 1739]]


#### LatentHatred

In [13]:
bert_hatebert_added_latenthatred_train_dev = np.concatenate((bert_hatebert_added_latenthatred_train, bert_hatebert_added_latenthatred_dev))
bert_hatebert_added_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_added_latenthatred_train_dev, bert_hatebert_added_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_added_latenthatred_train_dev)
test_preds = mlp.predict(bert_hatebert_added_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_hatebert_added_latenthatred_seed_3")

save_model(mlp, "Saves/bert_hatebert_added_latenthatred_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7046554934823092
Accuracy Test:  0.6888268156424581
Weighted F1 Train Dev:  0.6869687383285341
Weighted F1 Test:  0.6703258073536941
Macro F1 Train Dev:  0.4960037599153202
Macro F1 Test:  0.4796308318671249
Micro F1 Train Dev:  0.7046554934823092
Micro F1 Test:  0.6888268156424581
Weighted Recall Train Dev:  0.7046554934823092
Weighted Recall Test:  0.6888268156424581
Macro Recall Train Dev:  0.4860867880375708
Macro Recall Test:  0.4698235115886394
Micro Recall Train Dev:  0.7046554934823092
Micro Recall Test:  0.6888268156424581
Confusion Matrix Train Dev: 
[[8371 1546   28]
 [2389 2924   34]
 [ 318  443   57]]
Confusion Matrix Test: 
[[2798  535   13]
 [ 854  882   17]
 [ 115  137   19]]


#### OLID

In [14]:
bert_hatebert_added_olid_train_dev = np.concatenate((bert_hatebert_added_olid_train, bert_hatebert_added_olid_dev))
bert_hatebert_added_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_added_olid_train_dev, bert_hatebert_added_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_added_olid_train_dev)
test_preds = mlp.predict(bert_hatebert_added_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_hatebert_added_olid_seed_3")

save_model(mlp, "Saves/bert_hatebert_added_olid_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7623111782477341
Accuracy Test:  0.8011627906976744
Weighted F1 Train Dev:  0.7471715785082806
Weighted F1 Test:  0.7776906101590105
Macro F1 Train Dev:  0.7023882188526018
Macro F1 Test:  0.7014561776402735
Micro F1 Train Dev:  0.7623111782477341
Micro F1 Test:  0.8011627906976744
Weighted Recall Train Dev:  0.7623111782477341
Weighted Recall Test:  0.8011627906976744
Macro Recall Train Dev:  0.6893593171534348
Macro Recall Test:  0.6782258064516129
Micro Recall Train Dev:  0.7623111782477341
Micro Recall Test:  0.8011627906976744
Confusion Matrix Train Dev: 
[[8017  823]
 [2324 2076]]
Confusion Matrix Test: 
[[593  27]
 [144  96]]


### BERTweet-HateBERT

#### DynaHate

In [15]:
hatebert_bertweet_added_dynahate_train_dev = np.concatenate((hatebert_bertweet_added_dynahate_train, hatebert_bertweet_added_dynahate_dev))
hatebert_bertweet_added_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_added_dynahate_train_dev, hatebert_bertweet_added_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_added_dynahate_train_dev)
test_preds = mlp.predict(hatebert_bertweet_added_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/hatebert_bertweet_added_dynahate_seed_3")

save_model(mlp, "Saves/hatebert_bertweet_added_dynahate_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7363061797752809
Accuracy Test:  0.6871359223300971
Weighted F1 Train Dev:  0.7364168311335747
Weighted F1 Test:  0.6875270824912421
Macro F1 Train Dev:  0.735032448668824
Macro F1 Test:  0.684769071863508
Micro F1 Train Dev:  0.7363061797752809
Micro F1 Test:  0.6871359223300971
Weighted Recall Train Dev:  0.7363061797752809
Weighted Recall Test:  0.6871359223300971
Macro Recall Train Dev:  0.7352566882401484
Macro Recall Test:  0.6853742176816331
Micro Recall Train Dev:  0.7363061797752809
Micro Recall Test:  0.6871359223300971
Confusion Matrix Train Dev: 
[[12347  4770]
 [ 4993 14914]]
Confusion Matrix Test: 
[[1237  615]
 [ 674 1594]]


#### LatentHatred

In [16]:
hatebert_bertweet_added_latenthatred_train_dev = np.concatenate((hatebert_bertweet_added_latenthatred_train, hatebert_bertweet_added_latenthatred_dev))
hatebert_bertweet_added_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_added_latenthatred_train_dev, hatebert_bertweet_added_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_added_latenthatred_train_dev)
test_preds = mlp.predict(hatebert_bertweet_added_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/hatebert_bertweet_added_latenthatred_seed_3")

save_model(mlp, "Saves/hatebert_bertweet_added_latenthatred_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7171322160148976
Accuracy Test:  0.6949720670391062
Weighted F1 Train Dev:  0.6889861841262455
Weighted F1 Test:  0.6642795938842224
Macro F1 Train Dev:  0.5014444776769665
Macro F1 Test:  0.4813579715065985
Micro F1 Train Dev:  0.7171322160148976
Micro F1 Test:  0.6949720670391062
Weighted Recall Train Dev:  0.7171322160148976
Weighted Recall Test:  0.6949720670391062
Macro Recall Train Dev:  0.4844257758153406
Macro Recall Test:  0.4648191034464603
Micro Recall Train Dev:  0.7171322160148976
Micro Recall Test:  0.6949720670391062
Confusion Matrix Train Dev: 
[[9043  882   20]
 [2865 2438   44]
 [ 385  361   72]]
Confusion Matrix Test: 
[[3003  331   12]
 [1033  703   17]
 [ 139  106   26]]


#### OLID

In [17]:
hatebert_bertweet_added_olid_train_dev = np.concatenate((hatebert_bertweet_added_olid_train, hatebert_bertweet_added_olid_dev))
hatebert_bertweet_added_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_added_olid_train_dev, hatebert_bertweet_added_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_added_olid_train_dev)
test_preds = mlp.predict(hatebert_bertweet_added_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/hatebert_bertweet_added_olid_seed_3")

save_model(mlp, "Saves/hatebert_bertweet_added_olid_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7398791540785499
Accuracy Test:  0.7697674418604651
Weighted F1 Train Dev:  0.7151062478357538
Weighted F1 Test:  0.7332331374488524
Macro F1 Train Dev:  0.6597227112204397
Macro F1 Test:  0.6354652805727057
Micro F1 Train Dev:  0.7398791540785499
Micro F1 Test:  0.7697674418604652
Weighted Recall Train Dev:  0.7398791540785499
Weighted Recall Test:  0.7697674418604651
Macro Recall Train Dev:  0.6502442410530646
Macro Recall Test:  0.623252688172043
Micro Recall Train Dev:  0.7398791540785499
Micro Recall Test:  0.7697674418604651
Confusion Matrix Train Dev: 
[[8111  729]
 [2715 1685]]
Confusion Matrix Test: 
[[592  28]
 [170  70]]


### BERT-BERTweet-HateBERT

#### DynaHate

In [18]:
bert_bertweet_hatebert_added_dynahate_train_dev = np.concatenate((bert_hatebert_bertweet_added_dynahate_train, bert_hatebert_bertweet_added_dynahate_dev))
bert_bertweet_hatebert_added_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_added_dynahate_train_dev, bert_bertweet_hatebert_added_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_added_dynahate_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_added_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_bertweet_hatebert_added_dynahate_seed_3")

save_model(mlp, "Saves/bert_bertweet_hatebert_added_dynahate_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7297968885047537
Accuracy Test:  0.6893203883495146
Weighted F1 Train Dev:  0.7287075986470872
Weighted F1 Test:  0.6884741123912591
Macro F1 Train Dev:  0.726415653923943
Macro F1 Test:  0.6845624368508785
Micro F1 Train Dev:  0.7297968885047535
Micro F1 Test:  0.6893203883495146
Weighted Recall Train Dev:  0.7297968885047537
Weighted Recall Test:  0.6893203883495146
Macro Recall Train Dev:  0.7255394709897136
Macro Recall Test:  0.6838919553102418
Micro Recall Train Dev:  0.7297968885047537
Micro Recall Test:  0.6893203883495146
Confusion Matrix Train Dev: 
[[11452  5665]
 [ 4339 15568]]
Confusion Matrix Test: 
[[1167  685]
 [ 595 1673]]


#### LatentHatred

In [19]:
bert_bertweet_hatebert_added_latenthatred_train_dev = np.concatenate((bert_hatebert_bertweet_added_latenthatred_train, bert_hatebert_bertweet_added_latenthatred_dev))
bert_bertweet_hatebert_added_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_added_latenthatred_train_dev, bert_bertweet_hatebert_added_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_added_latenthatred_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_added_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_bertweet_hatebert_added_latenthatred_seed_3")

save_model(mlp, "Saves/bert_bertweet_hatebert_added_latenthatred_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7147113594040968
Accuracy Test:  0.6957169459962756
Weighted F1 Train Dev:  0.6981935332727894
Weighted F1 Test:  0.6788497079671774
Macro F1 Train Dev:  0.49882002672952636
Macro F1 Test:  0.47825869159005446
Micro F1 Train Dev:  0.7147113594040968
Micro F1 Test:  0.6957169459962756
Weighted Recall Train Dev:  0.7147113594040968
Weighted Recall Test:  0.6957169459962756
Macro Recall Train Dev:  0.4939765552080475
Macro Recall Test:  0.47424104839639697
Micro Recall Train Dev:  0.7147113594040968
Micro Recall Test:  0.6957169459962756
Confusion Matrix Train Dev: 
[[8280 1650   15]
 [2143 3191   13]
 [ 298  477   43]]
Confusion Matrix Test: 
[[2758  581    7]
 [ 779  965    9]
 [  98  160   13]]


#### OLID

In [20]:
bert_bertweet_hatebert_added_olid_train_dev = np.concatenate((bert_hatebert_bertweet_added_olid_train, bert_hatebert_bertweet_added_olid_dev))
bert_bertweet_hatebert_added_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_added_olid_train_dev, bert_bertweet_hatebert_added_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_added_olid_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_added_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_bertweet_hatebert_added_olid_seed_3")

save_model(mlp, "Saves/bert_bertweet_hatebert_added_olid_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7641238670694864
Accuracy Test:  0.8081395348837209
Weighted F1 Train Dev:  0.7457918705816169
Weighted F1 Test:  0.7854909396271156
Macro F1 Train Dev:  0.6987160669921773
Macro F1 Test:  0.711931399477457
Micro F1 Train Dev:  0.7641238670694863
Micro F1 Test:  0.8081395348837209
Weighted Recall Train Dev:  0.7641238670694864
Weighted Recall Test:  0.8081395348837209
Macro Recall Train Dev:  0.6848951048951049
Macro Recall Test:  0.6868951612903226
Micro Recall Train Dev:  0.7641238670694864
Micro Recall Test:  0.8081395348837209
Confusion Matrix Train Dev: 
[[8143  697]
 [2426 1974]]
Confusion Matrix Test: 
[[596  24]
 [141  99]]
