In [1]:
from utils import *
import numpy as np
import torch, os
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV

In [2]:
set_random_seed(7)

Seed: 7


In [3]:
# def scaling_embeddings(embeddings):
#     for i in range(len(embeddings)):
#         embeddings[i] = StandardScaler().fit_transform(embeddings[i])
#     return embeddings

def reshape_embeddings(embeddings):
    if embeddings.shape[1] == 1:
        embeddings = embeddings.squeeze(1)
    return embeddings

In [4]:
dynahate_labels_train = process_labels(read_labels("dynahate", "train"))
dynahate_labels_dev = process_labels(read_labels("dynahate", "dev"))
dynahate_labels_test = process_labels(read_labels("dynahate", "test"))

latenthatred_labels_train = read_labels("latenthatred", "train")
latenthatred_labels_dev = read_labels("latenthatred", "dev")
latenthatred_labels_test = read_labels("latenthatred", "test")

olid_labels_train = read_labels("olid", "train")
olid_labels_dev = read_labels("olid", "dev")
olid_labels_test = read_labels("olid", "test")

In [5]:
mlp = MLPClassifier(random_state=7)
gridsearch = GridSearchCV(
    mlp,
    param_grid={
        "hidden_layer_sizes": [(128), (128,64)],
        "activation": ["relu"],
        "solver": ["adam"],
        "learning_rate_init": [0.001, 0.0001],
        "learning_rate": ["adaptive"],
        "early_stopping": [True],
        "max_iter": [10000]
    },
    verbose=4,
    n_jobs=os.cpu_count()//3,
    cv=5,
)

In [6]:
dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))
latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))
olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

In [7]:
bertweet_dynahate_train_embeddings = reshape_embeddings(bertweet_dynahate_train_embeddings)
bertweet_dynahate_dev_embeddings = reshape_embeddings(bertweet_dynahate_dev_embeddings)
bertweet_dynahate_test_embeddings = reshape_embeddings(bertweet_dynahate_test_embeddings)

bertweet_latenthatred_train_embeddings = reshape_embeddings(bertweet_latenthatred_train_embeddings)
bertweet_latenthatred_dev_embeddings = reshape_embeddings(bertweet_latenthatred_dev_embeddings)
bertweet_latenthatred_test_embeddings = reshape_embeddings(bertweet_latenthatred_test_embeddings)

bertweet_olid_train_embeddings = reshape_embeddings(bertweet_olid_train_embeddings)
bertweet_olid_dev_embeddings = reshape_embeddings(bertweet_olid_dev_embeddings)
bertweet_olid_test_embeddings = reshape_embeddings(bertweet_olid_test_embeddings)

### BERTweet

#### DynaHate

In [8]:
bertweet_dynahate_train_dev = np.concatenate((bertweet_dynahate_train_embeddings, bertweet_dynahate_dev_embeddings))

grid_results = gridsearch.fit(bertweet_dynahate_train_dev, dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bertweet_dynahate_train_dev)
test_preds = mlp.predict(bertweet_dynahate_test_embeddings)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bertweet_dynahate_seed_7")
save_model(mlp, "Saves/bertweet_dynahate_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7189660760587727
Accuracy Test:  0.6490291262135922
Weighted F1 Train Dev:  0.7174229976600248
Weighted F1 Test:  0.6474485283768414
Macro F1 Train Dev:  0.7148372987215823
Macro F1 Test:  0.6426137585232508
Micro F1 Train Dev:  0.7189660760587728
Micro F1 Test:  0.6490291262135922
Weighted Recall Train Dev:  0.7189660760587727
Weighted Recall Test:  0.6490291262135922
Macro Recall Train Dev:  0.7139528817178885
Macro Recall Test:  0.6420467314995753
Micro Recall Train Dev:  0.7189660760587727
Micro Recall Test:  0.6490291262135922
Confusion Matrix Train Dev: 
[[11082  6035]
 [ 4370 15537]]
Confusion Matrix Test: 
[[1061  791]
 [ 655 1613]]


#### LatentHatred

In [9]:
bertweet_latenthatred_train_dev = np.concatenate((bertweet_latenthatred_train_embeddings, bertweet_latenthatred_dev_embeddings))

grid_results = gridsearch.fit(bertweet_latenthatred_train_dev, latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bertweet_latenthatred_train_dev)
test_preds = mlp.predict(bertweet_latenthatred_test_embeddings)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bertweet_latenthatred_seed_7")
save_model(mlp, "Saves/bertweet_latenthatred_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7189944134078212
Accuracy Test:  0.6966480446927374
Weighted F1 Train Dev:  0.6979058410015163
Weighted F1 Test:  0.6747323313805393
Macro F1 Train Dev:  0.5078646098184173
Macro F1 Test:  0.481650541792886
Micro F1 Train Dev:  0.7189944134078212
Micro F1 Test:  0.6966480446927374
Weighted Recall Train Dev:  0.7189944134078212
Weighted Recall Test:  0.6966480446927374
Macro Recall Train Dev:  0.4937371992460459
Macro Recall Test:  0.4706580471418999
Micro Recall Train Dev:  0.7189944134078212
Micro Recall Test:  0.6966480446927374
Confusion Matrix Train Dev: 
[[8701 1219   25]
 [2497 2817   33]
 [ 353  400   65]]
Confusion Matrix Test: 
[[2877  459   10]
 [ 891  845   17]
 [ 115  137   19]]


#### OLID

In [10]:
bertweet_olid_train_dev = np.concatenate((bertweet_olid_train_embeddings, bertweet_olid_dev_embeddings))

grid_results = gridsearch.fit(bertweet_olid_train_dev, olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bertweet_olid_train_dev)
test_preds = mlp.predict(bertweet_olid_test_embeddings)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bertweet_olid_seed_7")

save_model(mlp, "Saves/bertweet_olid_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7402567975830816
Accuracy Test:  0.7813953488372093
Weighted F1 Train Dev:  0.7030452702215332
Weighted F1 Test:  0.7467062113150721
Macro F1 Train Dev:  0.638882481295213
Macro F1 Test:  0.6538761249882257
Micro F1 Train Dev:  0.7402567975830816
Micro F1 Test:  0.7813953488372093
Weighted Recall Train Dev:  0.7402567975830816
Weighted Recall Test:  0.7813953488372093
Macro Recall Train Dev:  0.633861065405183
Macro Recall Test:  0.6377016129032258
Micro Recall Train Dev:  0.7402567975830816
Micro Recall Test:  0.7813953488372093
Confusion Matrix Train Dev: 
[[8408  432]
 [3007 1393]]
Confusion Matrix Test: 
[[597  23]
 [165  75]]
