In [1]:
from utils import *
import numpy as np
import torch, os
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV

In [2]:
set_random_seed(42)

Seed: 42


In [3]:
# def scaling_embeddings(embeddings):
#     for i in range(len(embeddings)):
#         embeddings[i] = StandardScaler().fit_transform(embeddings[i])
#     return embeddings

def reshape_embeddings(embeddings):
    if embeddings.shape[1] == 1:
        embeddings = embeddings.squeeze(1)
    return embeddings

In [4]:
dynahate_labels_train = process_labels(read_labels("dynahate", "train"))
dynahate_labels_dev = process_labels(read_labels("dynahate", "dev"))
dynahate_labels_test = process_labels(read_labels("dynahate", "test"))

latenthatred_labels_train = read_labels("latenthatred", "train")
latenthatred_labels_dev = read_labels("latenthatred", "dev")
latenthatred_labels_test = read_labels("latenthatred", "test")

olid_labels_train = read_labels("olid", "train")
olid_labels_dev = read_labels("olid", "dev")
olid_labels_test = read_labels("olid", "test")

In [5]:
mlp = MLPClassifier(random_state=42)
gridsearch = GridSearchCV(
    mlp,
    param_grid={
        "hidden_layer_sizes": [(128), (128,64)],
        "activation": ["relu"],
        "solver": ["adam"],
        "learning_rate_init": [0.001, 0.0001],
        "learning_rate": ["adaptive"],
        "early_stopping": [True],
        "max_iter": [10000]
    },
    verbose=4,
    n_jobs=os.cpu_count()//3,
    cv=5,
)

In [6]:
dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))
latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))
olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

In [7]:
bertweet_dynahate_train_embeddings = reshape_embeddings(bertweet_dynahate_train_embeddings)
bertweet_dynahate_dev_embeddings = reshape_embeddings(bertweet_dynahate_dev_embeddings)
bertweet_dynahate_test_embeddings = reshape_embeddings(bertweet_dynahate_test_embeddings)

bertweet_latenthatred_train_embeddings = reshape_embeddings(bertweet_latenthatred_train_embeddings)
bertweet_latenthatred_dev_embeddings = reshape_embeddings(bertweet_latenthatred_dev_embeddings)
bertweet_latenthatred_test_embeddings = reshape_embeddings(bertweet_latenthatred_test_embeddings)

bertweet_olid_train_embeddings = reshape_embeddings(bertweet_olid_train_embeddings)
bertweet_olid_dev_embeddings = reshape_embeddings(bertweet_olid_dev_embeddings)
bertweet_olid_test_embeddings = reshape_embeddings(bertweet_olid_test_embeddings)

### BERTweet

#### DynaHate

In [8]:
bertweet_dynahate_train_dev = np.concatenate((bertweet_dynahate_train_embeddings, bertweet_dynahate_dev_embeddings))

grid_results = gridsearch.fit(bertweet_dynahate_train_dev, dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bertweet_dynahate_train_dev)
test_preds = mlp.predict(bertweet_dynahate_test_embeddings)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bertweet_dynahate_seed_42")
save_model(mlp, "Saves/bertweet_dynahate_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7467318496110631
Accuracy Test:  0.6393203883495145
Weighted F1 Train Dev:  0.7460606929651759
Weighted F1 Test:  0.6390733580614165
Macro F1 Train Dev:  0.7441081100225004
Macro F1 Test:  0.6351208734518479
Micro F1 Train Dev:  0.7467318496110632
Micro F1 Test:  0.6393203883495145
Weighted Recall Train Dev:  0.7467318496110631
Weighted Recall Test:  0.6393203883495145
Macro Recall Train Dev:  0.7433223850019257
Macro Recall Test:  0.6349615840256589
Micro Recall Train Dev:  0.7467318496110631
Micro Recall Test:  0.6393203883495145
Confusion Matrix Train Dev: 
[[11949  5168]
 [ 4209 15698]]
Confusion Matrix Test: 
[[1096  756]
 [ 730 1538]]


#### LatentHatred

In [9]:
bertweet_latenthatred_train_dev = np.concatenate((bertweet_latenthatred_train_embeddings, bertweet_latenthatred_dev_embeddings))

grid_results = gridsearch.fit(bertweet_latenthatred_train_dev, latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bertweet_latenthatred_train_dev)
test_preds = mlp.predict(bertweet_latenthatred_test_embeddings)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bertweet_latenthatred_seed_42")
save_model(mlp, "Saves/bertweet_latenthatred_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7246430788330229
Accuracy Test:  0.7061452513966481
Weighted F1 Train Dev:  0.6984257644919438
Weighted F1 Test:  0.677392429756284
Macro F1 Train Dev:  0.5196885190032641
Macro F1 Test:  0.4945078615033271
Micro F1 Train Dev:  0.724643078833023
Micro F1 Test:  0.7061452513966481
Weighted Recall Train Dev:  0.7246430788330229
Weighted Recall Test:  0.7061452513966481
Macro Recall Train Dev:  0.4979786008805159
Macro Recall Test:  0.4765877939070815
Micro Recall Train Dev:  0.7246430788330229
Micro Recall Test:  0.7061452513966481
Confusion Matrix Train Dev: 
[[9074  844   27]
 [2786 2508   53]
 [ 405  321   92]]
Confusion Matrix Test: 
[[3022  311   13]
 [ 989  742   22]
 [ 133  110   28]]


#### OLID

In [10]:
bertweet_olid_train_dev = np.concatenate((bertweet_olid_train_embeddings, bertweet_olid_dev_embeddings))

grid_results = gridsearch.fit(bertweet_olid_train_dev, olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bertweet_olid_train_dev)
test_preds = mlp.predict(bertweet_olid_test_embeddings)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bertweet_olid_seed_42")

save_model(mlp, "Saves/bertweet_olid_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.756797583081571
Accuracy Test:  0.7872093023255814
Weighted F1 Train Dev:  0.7449236052437894
Weighted F1 Test:  0.7716402789417176
Macro F1 Train Dev:  0.7021310227764601
Macro F1 Test:  0.7003604128469187
Micro F1 Train Dev:  0.756797583081571
Micro F1 Test:  0.7872093023255814
Weighted Recall Train Dev:  0.756797583081571
Weighted Recall Test:  0.7872093023255814
Macro Recall Train Dev:  0.690823735088441
Macro Recall Test:  0.6825940860215054
Micro Recall Train Dev:  0.756797583081571
Micro Recall Test:  0.7872093023255814
Confusion Matrix Train Dev: 
[[7846  994]
 [2226 2174]]
Confusion Matrix Test: 
[[570  50]
 [133 107]]
