In [1]:
from utils import *
import numpy as np
import torch, os
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV

In [2]:
# def scaling_embeddings(embeddings):
#     for i in range(len(embeddings)):
#         embeddings[i] = StandardScaler().fit_transform(embeddings[i])
#     return embeddings

def reshape_embeddings(embeddings):
    if embeddings.shape[1] == 1:
        embeddings = embeddings.squeeze(1)
    return embeddings

In [3]:
dynahate_labels_train = process_labels(read_labels("dynahate", "train"))
dynahate_labels_dev = process_labels(read_labels("dynahate", "dev"))
dynahate_labels_test = process_labels(read_labels("dynahate", "test"))

latenthatred_labels_train = read_labels("latenthatred", "train")
latenthatred_labels_dev = read_labels("latenthatred", "dev")
latenthatred_labels_test = read_labels("latenthatred", "test")

olid_labels_train = read_labels("olid", "train")
olid_labels_dev = read_labels("olid", "dev")
olid_labels_test = read_labels("olid", "test")

In [4]:
mlp = MLPClassifier()
gridsearch = GridSearchCV(
    mlp,
    param_grid={
        "hidden_layer_sizes": [(128), (128,64)],
        "activation": ["relu"],
        "solver": ["adam"],
        "learning_rate_init": [0.001, 0.0001],
        "learning_rate": ["adaptive"],
        "early_stopping": [True],
        "max_iter": [10000]
    },
    verbose=4,
    n_jobs=os.cpu_count()//3,
    cv=5,
)

In [5]:
dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))
latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))
olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

In [6]:
bertweet_dynahate_train_embeddings = reshape_embeddings(bertweet_dynahate_train_embeddings)
bertweet_dynahate_dev_embeddings = reshape_embeddings(bertweet_dynahate_dev_embeddings)
bertweet_dynahate_test_embeddings = reshape_embeddings(bertweet_dynahate_test_embeddings)

bertweet_latenthatred_train_embeddings = reshape_embeddings(bertweet_latenthatred_train_embeddings)
bertweet_latenthatred_dev_embeddings = reshape_embeddings(bertweet_latenthatred_dev_embeddings)
bertweet_latenthatred_test_embeddings = reshape_embeddings(bertweet_latenthatred_test_embeddings)

bertweet_olid_train_embeddings = reshape_embeddings(bertweet_olid_train_embeddings)
bertweet_olid_dev_embeddings = reshape_embeddings(bertweet_olid_dev_embeddings)
bertweet_olid_test_embeddings = reshape_embeddings(bertweet_olid_test_embeddings)

### BERTweet

#### DynaHate

In [7]:
bertweet_dynahate_train_dev = np.concatenate((bertweet_dynahate_train_embeddings, bertweet_dynahate_dev_embeddings))

grid_results = gridsearch.fit(bertweet_dynahate_train_dev, dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bertweet_dynahate_train_dev)
test_preds = mlp.predict(bertweet_dynahate_test_embeddings)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bertweet_dynahate")
save_model(mlp, "Saves/bertweet_dynahate")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7304181071737251
Accuracy Test:  0.6509708737864077
Weighted F1 Train Dev:  0.7287511364287667
Weighted F1 Test:  0.6498670057737984
Macro F1 Train Dev:  0.7261858587793271
Macro F1 Test:  0.645364955840019
Micro F1 Train Dev:  0.7304181071737251
Micro F1 Test:  0.6509708737864077
Weighted Recall Train Dev:  0.7304181071737251
Weighted Recall Test:  0.6509708737864077
Macro Recall Train Dev:  0.72516736475367
Macro Recall Test:  0.6448503167365658
Micro Recall Train Dev:  0.7304181071737251
Micro Recall Test:  0.6509708737864077
Confusion Matrix Train Dev: 
[[11220  5897]
 [ 4084 15823]]
Confusion Matrix Test: 
[[1082  770]
 [ 668 1600]]


#### LatentHatred

In [8]:
bertweet_latenthatred_train_dev = np.concatenate((bertweet_latenthatred_train_embeddings, bertweet_latenthatred_dev_embeddings))

grid_results = gridsearch.fit(bertweet_latenthatred_train_dev, latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bertweet_latenthatred_train_dev)
test_preds = mlp.predict(bertweet_latenthatred_test_embeddings)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bertweet_latenthatred")
save_model(mlp, "Saves/bertweet_latenthatred")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.6893234016139044
Accuracy Test:  0.6851024208566108
Weighted F1 Train Dev:  0.6622075764139792
Weighted F1 Test:  0.6567015249706182
Macro F1 Train Dev:  0.46226313050038875
Macro F1 Test:  0.45128273623264553
Micro F1 Train Dev:  0.6893234016139044
Micro F1 Test:  0.6851024208566108
Weighted Recall Train Dev:  0.6893234016139044
Weighted Recall Test:  0.6851024208566108
Macro Recall Train Dev:  0.4559170290340389
Macro Recall Test:  0.4470656977873792
Micro Recall Train Dev:  0.6893234016139044
Micro Recall Test:  0.6851024208566108
Confusion Matrix Train Dev: 
[[8644 1280   21]
 [2897 2424   26]
 [ 445  336   37]]
Confusion Matrix Test: 
[[2904  438    4]
 [ 981  765    7]
 [ 143  118   10]]


#### OLID

In [9]:
bertweet_olid_train_dev = np.concatenate((bertweet_olid_train_embeddings, bertweet_olid_dev_embeddings))

grid_results = gridsearch.fit(bertweet_olid_train_dev, olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bertweet_olid_train_dev)
test_preds = mlp.predict(bertweet_olid_test_embeddings)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bertweet_olid")

save_model(mlp, "Saves/bertweet_olid")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7803625377643505
Accuracy Test:  0.7953488372093023
Weighted F1 Train Dev:  0.764639622098148
Weighted F1 Test:  0.7720922348658694
Macro F1 Train Dev:  0.7218640427121553
Macro F1 Test:  0.6945702270544268
Micro F1 Train Dev:  0.7803625377643505
Micro F1 Test:  0.7953488372093023
Weighted Recall Train Dev:  0.7803625377643505
Weighted Recall Test:  0.7953488372093023
Macro Recall Train Dev:  0.7059594816947758
Macro Recall Test:  0.6729166666666666
Micro Recall Train Dev:  0.7803625377643505
Micro Recall Test:  0.7953488372093023
Confusion Matrix Train Dev: 
[[8202  638]
 [2270 2130]]
Confusion Matrix Test: 
[[589  31]
 [145  95]]
