In [1]:
from utils import *
import numpy as np
import torch, os
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV

In [2]:
set_random_seed(42)

Seed: 42


In [3]:
# def scaling_embeddings(embeddings):
#     for i in range(len(embeddings)):
#         embeddings[i] = StandardScaler().fit_transform(embeddings[i])
#     return embeddings

def reshape_embeddings(embeddings):
    if embeddings.shape[1] == 1:
        embeddings = embeddings.squeeze(1)
    return embeddings

In [4]:
def concat_2_embeddings(embeddings1, embeddings2):
    embeddings1 = reshape_embeddings(embeddings1)
    embeddings2 = reshape_embeddings(embeddings2)
    # Numpy concat
    return np.concatenate((embeddings1, embeddings2), axis=1)

def concat_3_embeddings(embeddings1, embeddings2, embeddings3):
    embeddings1 = reshape_embeddings(embeddings1)
    embeddings2 = reshape_embeddings(embeddings2)
    embeddings3 = reshape_embeddings(embeddings3)
    return np.concatenate((embeddings1, embeddings2, embeddings3), axis=1)

In [5]:
bert_hatebert_concat_dynahate_train = concat_2_embeddings(bert_dynahate_train_embeddings, hatebert_dynahate_train_embeddings)
bert_hatebert_concat_dynahate_dev = concat_2_embeddings(bert_dynahate_dev_embeddings, hatebert_dynahate_dev_embeddings)
bert_hatebert_concat_dynahate_test = concat_2_embeddings(bert_dynahate_test_embeddings, hatebert_dynahate_test_embeddings)

bert_bertweet_concat_dynahate_train = concat_2_embeddings(bert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
bert_bertweet_concat_dynahate_dev = concat_2_embeddings(bert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
bert_bertweet_concat_dynahate_test = concat_2_embeddings(bert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

hatebert_bertweet_concat_dynahate_train = concat_2_embeddings(hatebert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
hatebert_bertweet_concat_dynahate_dev = concat_2_embeddings(hatebert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
hatebert_bertweet_concat_dynahate_test = concat_2_embeddings(hatebert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

bert_hatebert_bertweet_concat_dynahate_train = concat_3_embeddings(bert_dynahate_train_embeddings, hatebert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
bert_hatebert_bertweet_concat_dynahate_dev = concat_3_embeddings(bert_dynahate_dev_embeddings, hatebert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
bert_hatebert_bertweet_concat_dynahate_test = concat_3_embeddings(bert_dynahate_test_embeddings, hatebert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

bert_hatebert_concat_olid_train = concat_2_embeddings(bert_olid_train_embeddings, hatebert_olid_train_embeddings)
bert_hatebert_concat_olid_dev = concat_2_embeddings(bert_olid_dev_embeddings, hatebert_olid_dev_embeddings)
bert_hatebert_concat_olid_test = concat_2_embeddings(bert_olid_test_embeddings, hatebert_olid_test_embeddings)

bert_bertweet_concat_olid_train = concat_2_embeddings(bert_olid_train_embeddings, bertweet_olid_train_embeddings)
bert_bertweet_concat_olid_dev = concat_2_embeddings(bert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
bert_bertweet_concat_olid_test = concat_2_embeddings(bert_olid_test_embeddings, bertweet_olid_test_embeddings)

hatebert_bertweet_concat_olid_train = concat_2_embeddings(hatebert_olid_train_embeddings, bertweet_olid_train_embeddings)
hatebert_bertweet_concat_olid_dev = concat_2_embeddings(hatebert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
hatebert_bertweet_concat_olid_test = concat_2_embeddings(hatebert_olid_test_embeddings, bertweet_olid_test_embeddings)

bert_hatebert_bertweet_concat_olid_train = concat_3_embeddings(bert_olid_train_embeddings, hatebert_olid_train_embeddings, bertweet_olid_train_embeddings)
bert_hatebert_bertweet_concat_olid_dev = concat_3_embeddings(bert_olid_dev_embeddings, hatebert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
bert_hatebert_bertweet_concat_olid_test = concat_3_embeddings(bert_olid_test_embeddings, hatebert_olid_test_embeddings, bertweet_olid_test_embeddings)

bert_hatebert_concat_latenthatred_train = concat_2_embeddings(bert_latenthatred_train_embeddings, hatebert_latenthatred_train_embeddings)
bert_hatebert_concat_latenthatred_dev = concat_2_embeddings(bert_latenthatred_dev_embeddings, hatebert_latenthatred_dev_embeddings)
bert_hatebert_concat_latenthatred_test = concat_2_embeddings(bert_latenthatred_test_embeddings, hatebert_latenthatred_test_embeddings)

bert_bertweet_concat_latenthatred_train = concat_2_embeddings(bert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
bert_bertweet_concat_latenthatred_dev = concat_2_embeddings(bert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
bert_bertweet_concat_latenthatred_test = concat_2_embeddings(bert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

hatebert_bertweet_concat_latenthatred_train = concat_2_embeddings(hatebert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
hatebert_bertweet_concat_latenthatred_dev = concat_2_embeddings(hatebert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
hatebert_bertweet_concat_latenthatred_test = concat_2_embeddings(hatebert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

bert_hatebert_bertweet_concat_latenthatred_train = concat_3_embeddings(bert_latenthatred_train_embeddings, hatebert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
bert_hatebert_bertweet_concat_latenthatred_dev = concat_3_embeddings(bert_latenthatred_dev_embeddings, hatebert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
bert_hatebert_bertweet_concat_latenthatred_test = concat_3_embeddings(bert_latenthatred_test_embeddings, hatebert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

In [6]:
dynahate_labels_train = process_labels(read_labels("dynahate", "train"))
dynahate_labels_dev = process_labels(read_labels("dynahate", "dev"))
dynahate_labels_test = process_labels(read_labels("dynahate", "test"))

latenthatred_labels_train = read_labels("latenthatred", "train")
latenthatred_labels_dev = read_labels("latenthatred", "dev")
latenthatred_labels_test = read_labels("latenthatred", "test")

olid_labels_train = read_labels("olid", "train")
olid_labels_dev = read_labels("olid", "dev")
olid_labels_test = read_labels("olid", "test")

In [7]:
mlp = MLPClassifier(random_state=42)
gridsearch = GridSearchCV(
    mlp,
    param_grid={
        "hidden_layer_sizes": [(128), (128,64)],
        "activation": ["relu"],
        "solver": ["adam"],
        "learning_rate_init": [0.001, 0.0001],
        "learning_rate": ["adaptive"],
        "early_stopping": [True],
        "max_iter": [10000]
    },
    verbose=4,
    n_jobs=os.cpu_count()//3,
    cv=5,
)

In [8]:
dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))
latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))
olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

### BERT-BERTweet

#### DynaHate

In [9]:
bert_bertweet_concat_dynahate_train_dev = np.concatenate((bert_bertweet_concat_dynahate_train, bert_bertweet_concat_dynahate_dev))
bert_bertweet_concat_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_concat_dynahate_train_dev, bert_bertweet_concat_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_concat_dynahate_train_dev)
test_preds = mlp.predict(bert_bertweet_concat_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_bertweet_concat_dynahate_seed_42")
save_model(mlp, "Saves/bert_bertweet_concat_dynahate_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7290676318063959
Accuracy Test:  0.6730582524271844
Weighted F1 Train Dev:  0.7285946351627042
Weighted F1 Test:  0.6730501375127786
Macro F1 Train Dev:  0.7266624819622656
Macro F1 Test:  0.6696743331199866
Micro F1 Train Dev:  0.7290676318063959
Micro F1 Test:  0.6730582524271844
Weighted Recall Train Dev:  0.7290676318063959
Weighted Recall Test:  0.6730582524271844
Macro Recall Train Dev:  0.7261222489683061
Macro Recall Test:  0.6696659505334812
Micro Recall Train Dev:  0.7290676318063959
Micro Recall Test:  0.6730582524271844
Confusion Matrix Train Dev: 
[[11760  5357]
 [ 4674 15233]]
Confusion Matrix Test: 
[[1178  674]
 [ 673 1595]]


#### LatentHatred

In [10]:
bert_bertweet_concat_latenthatred_train_dev = np.concatenate((bert_bertweet_concat_latenthatred_train, bert_bertweet_concat_latenthatred_dev))
bert_bertweet_concat_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_concat_latenthatred_train_dev, bert_bertweet_concat_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_concat_latenthatred_train_dev)
test_preds = mlp.predict(bert_bertweet_concat_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_bertweet_concat_latenthatred_seed_42")
save_model(mlp, "Saves/bert_bertweet_concat_latenthatred_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7054003724394786
Accuracy Test:  0.695903165735568
Weighted F1 Train Dev:  0.682249724829152
Weighted F1 Test:  0.671539072225558
Macro F1 Train Dev:  0.49380931836260206
Macro F1 Test:  0.47856019260538735
Micro F1 Train Dev:  0.7054003724394786
Micro F1 Test:  0.695903165735568
Weighted Recall Train Dev:  0.7054003724394786
Weighted Recall Test:  0.695903165735568
Macro Recall Train Dev:  0.479914601025245
Macro Recall Test:  0.466909996522616
Micro Recall Train Dev:  0.7054003724394786
Micro Recall Test:  0.695903165735568
Confusion Matrix Train Dev: 
[[8659 1268   18]
 [2684 2644   19]
 [ 391  366   61]]
Confusion Matrix Test: 
[[2910  424   12]
 [ 934  808   11]
 [ 114  138   19]]


#### OLID

In [11]:
bert_bertweet_concat_olid_train_dev = np.concatenate((bert_bertweet_concat_olid_train, bert_bertweet_concat_olid_dev))
bert_bertweet_concat_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_concat_olid_train_dev, bert_bertweet_concat_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_concat_olid_train_dev)
test_preds = mlp.predict(bert_bertweet_concat_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_bertweet_concat_olid_seed_42")

save_model(mlp, "Saves/bert_bertweet_concat_olid_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7705438066465257
Accuracy Test:  0.8093023255813954
Weighted F1 Train Dev:  0.764771943179381
Weighted F1 Test:  0.8004580888757631
Macro F1 Train Dev:  0.7293754324140186
Macro F1 Test:  0.7425130897698975
Micro F1 Train Dev:  0.7705438066465257
Micro F1 Test:  0.8093023255813954
Weighted Recall Train Dev:  0.7705438066465257
Weighted Recall Test:  0.8093023255813954
Macro Recall Train Dev:  0.7208088235294118
Macro Recall Test:  0.7260080645161291
Micro Recall Train Dev:  0.7705438066465257
Micro Recall Test:  0.8093023255813954
Confusion Matrix Train Dev: 
[[7683 1157]
 [1881 2519]]
Confusion Matrix Test: 
[[567  53]
 [111 129]]


### BERT-HateBERT

#### DynaHate

In [12]:
bert_hatebert_concat_dynahate_train_dev = np.concatenate((bert_hatebert_concat_dynahate_train, bert_hatebert_concat_dynahate_dev))
bert_hatebert_concat_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_concat_dynahate_train_dev, bert_hatebert_concat_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_concat_dynahate_train_dev)
test_preds = mlp.predict(bert_hatebert_concat_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_hatebert_concat_dynahate_seed_42")

save_model(mlp, "Saves/bert_hatebert_concat_dynahate_seed_42")


Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.730039974070873
Accuracy Test:  0.6881067961165048
Weighted F1 Train Dev:  0.730270195989603
Weighted F1 Test:  0.6887393359563769
Macro F1 Train Dev:  0.729013211345265
Macro F1 Test:  0.6864106937140158
Micro F1 Train Dev:  0.730039974070873
Micro F1 Test:  0.6881067961165048
Weighted Recall Train Dev:  0.730039974070873
Weighted Recall Test:  0.6881067961165048
Macro Recall Train Dev:  0.7295442223703075
Macro Recall Test:  0.6876921274869439
Micro Recall Train Dev:  0.730039974070873
Micro Recall Test:  0.6881067961165048
Confusion Matrix Train Dev: 
[[12375  4742]
 [ 5253 14654]]
Confusion Matrix Test: 
[[1266  586]
 [ 699 1569]]


#### LatentHatred

In [13]:
bert_hatebert_concat_latenthatred_train_dev = np.concatenate((bert_hatebert_concat_latenthatred_train, bert_hatebert_concat_latenthatred_dev))
bert_hatebert_concat_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_concat_latenthatred_train_dev, bert_hatebert_concat_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_concat_latenthatred_train_dev)
test_preds = mlp.predict(bert_hatebert_concat_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_hatebert_concat_latenthatred_seed_42")

save_model(mlp, "Saves/bert_hatebert_concat_latenthatred_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7184978274363749
Accuracy Test:  0.6981378026070764
Weighted F1 Train Dev:  0.6941655246881774
Weighted F1 Test:  0.6708684483032371
Macro F1 Train Dev:  0.5125039883036244
Macro F1 Test:  0.4794746175716493
Micro F1 Train Dev:  0.7184978274363749
Micro F1 Test:  0.6981378026070764
Weighted Recall Train Dev:  0.7184978274363749
Weighted Recall Test:  0.6981378026070764
Macro Recall Train Dev:  0.4933697531878334
Macro Recall Test:  0.46638296918207384
Micro Recall Train Dev:  0.7184978274363749
Micro Recall Test:  0.6981378026070764
Confusion Matrix Train Dev: 
[[8912 1008   25]
 [2718 2580   49]
 [ 379  356   83]]
Confusion Matrix Test: 
[[2964  371   11]
 [ 969  764   20]
 [ 135  115   21]]


#### OLID

In [14]:
bert_hatebert_concat_olid_train_dev = np.concatenate((bert_hatebert_concat_olid_train, bert_hatebert_concat_olid_dev))
bert_hatebert_concat_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_concat_olid_train_dev, bert_hatebert_concat_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_concat_olid_train_dev)
test_preds = mlp.predict(bert_hatebert_concat_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_hatebert_concat_olid_seed_42")

save_model(mlp, "Saves/bert_hatebert_concat_olid_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.766465256797583
Accuracy Test:  0.7976744186046512
Weighted F1 Train Dev:  0.757724054715453
Weighted F1 Test:  0.7764096068527517
Macro F1 Train Dev:  0.7189905844114034
Macro F1 Test:  0.7015889729108834
Micro F1 Train Dev:  0.766465256797583
Micro F1 Test:  0.7976744186046512
Weighted Recall Train Dev:  0.766465256797583
Weighted Recall Test:  0.7976744186046512
Macro Recall Train Dev:  0.7082800287947346
Macro Recall Test:  0.6796370967741936
Micro Recall Train Dev:  0.766465256797583
Micro Recall Test:  0.7976744186046512
Confusion Matrix Train Dev: 
[[7795 1045]
 [2047 2353]]
Confusion Matrix Test: 
[[587  33]
 [141  99]]


### BERTweet-HateBERT

#### DynaHate

In [9]:
hatebert_bertweet_concat_dynahate_train_dev = np.concatenate((hatebert_bertweet_concat_dynahate_train, hatebert_bertweet_concat_dynahate_dev))
hatebert_bertweet_concat_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_concat_dynahate_train_dev, hatebert_bertweet_concat_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_concat_dynahate_train_dev)
test_preds = mlp.predict(hatebert_bertweet_concat_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/hatebert_bertweet_concat_dynahate_seed_42")

save_model(mlp, "Saves/hatebert_bertweet_concat_dynahate_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7184528954191876
Accuracy Test:  0.6881067961165048
Weighted F1 Train Dev:  0.7172441169227889
Weighted F1 Test:  0.6869658149516107
Macro F1 Train Dev:  0.7148178636818158
Macro F1 Test:  0.6828384396072977
Micro F1 Train Dev:  0.7184528954191874
Micro F1 Test:  0.6881067961165048
Weighted Recall Train Dev:  0.7184528954191876
Weighted Recall Test:  0.6881067961165048
Macro Recall Train Dev:  0.7139996860848408
Macro Recall Test:  0.6820468648222429
Micro Recall Train Dev:  0.7184528954191876
Micro Recall Test:  0.6881067961165048
Confusion Matrix Train Dev: 
[[11210  5907]
 [ 4517 15390]]
Confusion Matrix Test: 
[[1152  700]
 [ 585 1683]]


#### LatentHatred

In [10]:
hatebert_bertweet_concat_latenthatred_train_dev = np.concatenate((hatebert_bertweet_concat_latenthatred_train, hatebert_bertweet_concat_latenthatred_dev))
hatebert_bertweet_concat_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_concat_latenthatred_train_dev, hatebert_bertweet_concat_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_concat_latenthatred_train_dev)
test_preds = mlp.predict(hatebert_bertweet_concat_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/hatebert_bertweet_concat_latenthatred_seed_42")

save_model(mlp, "Saves/hatebert_bertweet_concat_latenthatred_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7237740533829919
Accuracy Test:  0.7018621973929237
Weighted F1 Train Dev:  0.6919429506811297
Weighted F1 Test:  0.6652894451532908
Macro F1 Train Dev:  0.5035285128411652
Macro F1 Test:  0.47105559390880264
Micro F1 Train Dev:  0.7237740533829919
Micro F1 Test:  0.7018621973929237
Weighted Recall Train Dev:  0.7237740533829919
Weighted Recall Test:  0.7018621973929237
Macro Recall Train Dev:  0.485187555529584
Macro Recall Test:  0.4583731866375163
Micro Recall Train Dev:  0.7237740533829919
Micro Recall Test:  0.7018621973929237
Confusion Matrix Train Dev: 
[[9248  685   12]
 [2973 2340   34]
 [ 411  335   72]]
Confusion Matrix Test: 
[[3083  257    6]
 [1072  666   15]
 [ 141  110   20]]


#### OLID

In [11]:
hatebert_bertweet_concat_olid_train_dev = np.concatenate((hatebert_bertweet_concat_olid_train, hatebert_bertweet_concat_olid_dev))
hatebert_bertweet_concat_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_concat_olid_train_dev, hatebert_bertweet_concat_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_concat_olid_train_dev)
test_preds = mlp.predict(hatebert_bertweet_concat_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/hatebert_bertweet_concat_olid_seed_42")

save_model(mlp, "Saves/hatebert_bertweet_concat_olid_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7690332326283988
Accuracy Test:  0.8069767441860465
Weighted F1 Train Dev:  0.7653551002021992
Weighted F1 Test:  0.7987704090182155
Macro F1 Train Dev:  0.731890124849072
Macro F1 Test:  0.7410221245038495
Micro F1 Train Dev:  0.7690332326283988
Micro F1 Test:  0.8069767441860464
Weighted Recall Train Dev:  0.7690332326283988
Weighted Recall Test:  0.8069767441860465
Macro Recall Train Dev:  0.7258417317976141
Macro Recall Test:  0.7256720430107526
Micro Recall Train Dev:  0.7690332326283988
Micro Recall Test:  0.8069767441860465
Confusion Matrix Train Dev: 
[[7555 1285]
 [1773 2627]]
Confusion Matrix Test: 
[[564  56]
 [110 130]]


### BERT-BERTweet-HateBERT

#### DynaHate

In [12]:
bert_bertweet_hatebert_concat_dynahate_train_dev = np.concatenate((bert_hatebert_bertweet_concat_dynahate_train, bert_hatebert_bertweet_concat_dynahate_dev))
bert_bertweet_hatebert_concat_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_concat_dynahate_train_dev, bert_bertweet_hatebert_concat_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_concat_dynahate_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_concat_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_bertweet_hatebert_concat_dynahate_seed_42")

save_model(mlp, "Saves/bert_bertweet_hatebert_concat_dynahate_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7522417891097667
Accuracy Test:  0.7048543689320388
Weighted F1 Train Dev:  0.7513325930653146
Weighted F1 Test:  0.7040923951583962
Macro F1 Train Dev:  0.7492786198150951
Macro F1 Test:  0.700406568532404
Micro F1 Train Dev:  0.7522417891097667
Micro F1 Test:  0.7048543689320388
Weighted Recall Train Dev:  0.7522417891097667
Weighted Recall Test:  0.7048543689320388
Macro Recall Train Dev:  0.7482988292005803
Macro Recall Test:  0.6996849775827457
Micro Recall Train Dev:  0.7522417891097667
Micro Recall Test:  0.7048543689320388
Confusion Matrix Train Dev: 
[[11913  5204]
 [ 3969 15938]]
Confusion Matrix Test: 
[[1201  651]
 [ 565 1703]]


#### LatentHatred

In [13]:
bert_bertweet_hatebert_concat_latenthatred_train_dev = np.concatenate((bert_hatebert_bertweet_concat_latenthatred_train, bert_hatebert_bertweet_concat_latenthatred_dev))
bert_bertweet_hatebert_concat_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_concat_latenthatred_train_dev, bert_bertweet_hatebert_concat_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_concat_latenthatred_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_concat_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_bertweet_hatebert_concat_latenthatred_seed_42")

save_model(mlp, "Saves/bert_bertweet_hatebert_concat_latenthatred_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7144630664183736
Accuracy Test:  0.6986964618249535
Weighted F1 Train Dev:  0.7013844492113639
Weighted F1 Test:  0.6847678302906718
Macro F1 Train Dev:  0.5431007947368226
Macro F1 Test:  0.5241980728365611
Micro F1 Train Dev:  0.7144630664183736
Micro F1 Test:  0.6986964618249535
Weighted Recall Train Dev:  0.7144630664183736
Weighted Recall Test:  0.6986964618249535
Macro Recall Train Dev:  0.5215892298486023
Macro Recall Test:  0.5036812889912919
Micro Recall Train Dev:  0.7144630664183736
Micro Recall Test:  0.6986964618249535
Confusion Matrix Train Dev: 
[[8439 1437   69]
 [2316 2934   97]
 [ 306  375  137]]
Confusion Matrix Test: 
[[2811  515   20]
 [ 820  898   35]
 [  98  130   43]]


#### OLID

In [14]:
bert_bertweet_hatebert_concat_olid_train_dev = np.concatenate((bert_hatebert_bertweet_concat_olid_train, bert_hatebert_bertweet_concat_olid_dev))
bert_bertweet_hatebert_concat_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_concat_olid_train_dev, bert_bertweet_hatebert_concat_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_concat_olid_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_concat_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_bertweet_hatebert_concat_olid_seed_42")

save_model(mlp, "Saves/bert_bertweet_hatebert_concat_olid_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7874622356495469
Accuracy Test:  0.8081395348837209
Weighted F1 Train Dev:  0.7837286961474602
Weighted F1 Test:  0.7936503352014264
Macro F1 Train Dev:  0.752569080754105
Macro F1 Test:  0.7288750895629329
Micro F1 Train Dev:  0.7874622356495469
Micro F1 Test:  0.8081395348837209
Weighted Recall Train Dev:  0.7874622356495469
Weighted Recall Test:  0.8081395348837209
Macro Recall Train Dev:  0.745350164541341
Macro Recall Test:  0.7073252688172043
Micro Recall Train Dev:  0.7874622356495469
Micro Recall Test:  0.8081395348837209
Confusion Matrix Train Dev: 
[[7699 1141]
 [1673 2727]]
Confusion Matrix Test: 
[[580  40]
 [125 115]]
