In [1]:
from utils import *
import numpy as np
import torch, os
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV

In [2]:
# def scaling_embeddings(embeddings):
#     for i in range(len(embeddings)):
#         embeddings[i] = StandardScaler().fit_transform(embeddings[i])
#     return embeddings

def reshape_embeddings(embeddings):
    if embeddings.shape[1] == 1:
        embeddings = embeddings.squeeze(1)
    return embeddings

In [3]:
def concat_2_embeddings(embeddings1, embeddings2):
    embeddings1 = reshape_embeddings(embeddings1)
    embeddings2 = reshape_embeddings(embeddings2)
    # Numpy concat
    return np.concatenate((embeddings1, embeddings2), axis=1)

def concat_3_embeddings(embeddings1, embeddings2, embeddings3):
    embeddings1 = reshape_embeddings(embeddings1)
    embeddings2 = reshape_embeddings(embeddings2)
    embeddings3 = reshape_embeddings(embeddings3)
    return np.concatenate((embeddings1, embeddings2, embeddings3), axis=1)

In [4]:
bert_hatebert_concat_dynahate_train = concat_2_embeddings(bert_dynahate_train_embeddings, hatebert_dynahate_train_embeddings)
bert_hatebert_concat_dynahate_dev = concat_2_embeddings(bert_dynahate_dev_embeddings, hatebert_dynahate_dev_embeddings)
bert_hatebert_concat_dynahate_test = concat_2_embeddings(bert_dynahate_test_embeddings, hatebert_dynahate_test_embeddings)

bert_bertweet_concat_dynahate_train = concat_2_embeddings(bert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
bert_bertweet_concat_dynahate_dev = concat_2_embeddings(bert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
bert_bertweet_concat_dynahate_test = concat_2_embeddings(bert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

hatebert_bertweet_concat_dynahate_train = concat_2_embeddings(hatebert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
hatebert_bertweet_concat_dynahate_dev = concat_2_embeddings(hatebert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
hatebert_bertweet_concat_dynahate_test = concat_2_embeddings(hatebert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

bert_hatebert_bertweet_concat_dynahate_train = concat_3_embeddings(bert_dynahate_train_embeddings, hatebert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
bert_hatebert_bertweet_concat_dynahate_dev = concat_3_embeddings(bert_dynahate_dev_embeddings, hatebert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
bert_hatebert_bertweet_concat_dynahate_test = concat_3_embeddings(bert_dynahate_test_embeddings, hatebert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

bert_hatebert_concat_olid_train = concat_2_embeddings(bert_olid_train_embeddings, hatebert_olid_train_embeddings)
bert_hatebert_concat_olid_dev = concat_2_embeddings(bert_olid_dev_embeddings, hatebert_olid_dev_embeddings)
bert_hatebert_concat_olid_test = concat_2_embeddings(bert_olid_test_embeddings, hatebert_olid_test_embeddings)

bert_bertweet_concat_olid_train = concat_2_embeddings(bert_olid_train_embeddings, bertweet_olid_train_embeddings)
bert_bertweet_concat_olid_dev = concat_2_embeddings(bert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
bert_bertweet_concat_olid_test = concat_2_embeddings(bert_olid_test_embeddings, bertweet_olid_test_embeddings)

hatebert_bertweet_concat_olid_train = concat_2_embeddings(hatebert_olid_train_embeddings, bertweet_olid_train_embeddings)
hatebert_bertweet_concat_olid_dev = concat_2_embeddings(hatebert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
hatebert_bertweet_concat_olid_test = concat_2_embeddings(hatebert_olid_test_embeddings, bertweet_olid_test_embeddings)

bert_hatebert_bertweet_concat_olid_train = concat_3_embeddings(bert_olid_train_embeddings, hatebert_olid_train_embeddings, bertweet_olid_train_embeddings)
bert_hatebert_bertweet_concat_olid_dev = concat_3_embeddings(bert_olid_dev_embeddings, hatebert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
bert_hatebert_bertweet_concat_olid_test = concat_3_embeddings(bert_olid_test_embeddings, hatebert_olid_test_embeddings, bertweet_olid_test_embeddings)

bert_hatebert_concat_latenthatred_train = concat_2_embeddings(bert_latenthatred_train_embeddings, hatebert_latenthatred_train_embeddings)
bert_hatebert_concat_latenthatred_dev = concat_2_embeddings(bert_latenthatred_dev_embeddings, hatebert_latenthatred_dev_embeddings)
bert_hatebert_concat_latenthatred_test = concat_2_embeddings(bert_latenthatred_test_embeddings, hatebert_latenthatred_test_embeddings)

bert_bertweet_concat_latenthatred_train = concat_2_embeddings(bert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
bert_bertweet_concat_latenthatred_dev = concat_2_embeddings(bert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
bert_bertweet_concat_latenthatred_test = concat_2_embeddings(bert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

hatebert_bertweet_concat_latenthatred_train = concat_2_embeddings(hatebert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
hatebert_bertweet_concat_latenthatred_dev = concat_2_embeddings(hatebert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
hatebert_bertweet_concat_latenthatred_test = concat_2_embeddings(hatebert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

bert_hatebert_bertweet_concat_latenthatred_train = concat_3_embeddings(bert_latenthatred_train_embeddings, hatebert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
bert_hatebert_bertweet_concat_latenthatred_dev = concat_3_embeddings(bert_latenthatred_dev_embeddings, hatebert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
bert_hatebert_bertweet_concat_latenthatred_test = concat_3_embeddings(bert_latenthatred_test_embeddings, hatebert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

In [5]:
dynahate_labels_train = process_labels(read_labels("dynahate", "train"))
dynahate_labels_dev = process_labels(read_labels("dynahate", "dev"))
dynahate_labels_test = process_labels(read_labels("dynahate", "test"))

latenthatred_labels_train = read_labels("latenthatred", "train")
latenthatred_labels_dev = read_labels("latenthatred", "dev")
latenthatred_labels_test = read_labels("latenthatred", "test")

olid_labels_train = read_labels("olid", "train")
olid_labels_dev = read_labels("olid", "dev")
olid_labels_test = read_labels("olid", "test")

In [6]:
mlp = MLPClassifier()
gridsearch = GridSearchCV(
    mlp,
    param_grid={
        "hidden_layer_sizes": [(128), (128,64)],
        "activation": ["relu"],
        "solver": ["adam"],
        "learning_rate_init": [0.001, 0.0001],
        "learning_rate": ["adaptive"],
        "early_stopping": [True],
        "max_iter": [10000]
    },
    verbose=4,
    n_jobs=os.cpu_count()//3,
    cv=5,
)

In [7]:
dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))
latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))
olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

### BERT-BERTweet

#### DynaHate

In [8]:
bert_bertweet_concat_dynahate_train_dev = np.concatenate((bert_bertweet_concat_dynahate_train, bert_bertweet_concat_dynahate_dev))
bert_bertweet_concat_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_concat_dynahate_train_dev, bert_bertweet_concat_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_concat_dynahate_train_dev)
test_preds = mlp.predict(bert_bertweet_concat_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_bertweet_concat_dynahate")
save_model(mlp, "Saves/bert_bertweet_concat_dynahate")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7177506482281764
Accuracy Test:  0.6817961165048544
Weighted F1 Train Dev:  0.7157674240197323
Weighted F1 Test:  0.6798165675674613
Macro F1 Train Dev:  0.7129785149766077
Macro F1 Test:  0.6751108969505724
Micro F1 Train Dev:  0.7177506482281762
Micro F1 Test:  0.6817961165048544
Weighted Recall Train Dev:  0.7177506482281764
Weighted Recall Test:  0.6817961165048544
Macro Recall Train Dev:  0.7120775302064103
Macro Recall Test:  0.6741855889624069
Micro Recall Train Dev:  0.7177506482281764
Micro Recall Test:  0.6817961165048544
Confusion Matrix Train Dev: 
[[10900  6217]
 [ 4233 15674]]
Confusion Matrix Test: 
[[1109  743]
 [ 568 1700]]


#### LatentHatred

In [9]:
bert_bertweet_concat_latenthatred_train_dev = np.concatenate((bert_bertweet_concat_latenthatred_train, bert_bertweet_concat_latenthatred_dev))
bert_bertweet_concat_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_concat_latenthatred_train_dev, bert_bertweet_concat_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_concat_latenthatred_train_dev)
test_preds = mlp.predict(bert_bertweet_concat_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_bertweet_concat_latenthatred")
save_model(mlp, "Saves/bert_bertweet_concat_latenthatred")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7286778398510242
Accuracy Test:  0.6988826815642458
Weighted F1 Train Dev:  0.7119909641619356
Weighted F1 Test:  0.6812212303382655
Macro F1 Train Dev:  0.5168873562457398
Macro F1 Test:  0.4816601083140402
Micro F1 Train Dev:  0.7286778398510242
Micro F1 Test:  0.6988826815642458
Weighted Recall Train Dev:  0.7286778398510242
Weighted Recall Test:  0.6988826815642458
Macro Recall Train Dev:  0.5074750347588459
Macro Recall Test:  0.4761597159116653
Micro Recall Train Dev:  0.7286778398510242
Micro Recall Test:  0.6988826815642458
Confusion Matrix Train Dev: 
[[8454 1482    9]
 [2098 3229   20]
 [ 287  475   56]]
Confusion Matrix Test: 
[[2784  555    7]
 [ 789  955    9]
 [ 104  153   14]]


#### OLID

In [10]:
bert_bertweet_concat_olid_train_dev = np.concatenate((bert_bertweet_concat_olid_train, bert_bertweet_concat_olid_dev))
bert_bertweet_concat_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_concat_olid_train_dev, bert_bertweet_concat_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_concat_olid_train_dev)
test_preds = mlp.predict(bert_bertweet_concat_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_bertweet_concat_olid")

save_model(mlp, "Saves/bert_bertweet_concat_olid")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7586858006042296
Accuracy Test:  0.8081395348837209
Weighted F1 Train Dev:  0.7506868818119321
Weighted F1 Test:  0.7892877495599382
Macro F1 Train Dev:  0.7116162553677061
Macro F1 Test:  0.7197374736081183
Micro F1 Train Dev:  0.7586858006042296
Micro F1 Test:  0.8081395348837209
Weighted Recall Train Dev:  0.7586858006042296
Weighted Recall Test:  0.8081395348837209
Macro Recall Train Dev:  0.7021688605512135
Macro Recall Test:  0.6958333333333333
Micro Recall Train Dev:  0.7586858006042296
Micro Recall Test:  0.8081395348837209
Confusion Matrix Train Dev: 
[[7697 1143]
 [2052 2348]]
Confusion Matrix Test: 
[[589  31]
 [134 106]]


### BERT-HateBERT

#### DynaHate

In [11]:
bert_hatebert_concat_dynahate_train_dev = np.concatenate((bert_hatebert_concat_dynahate_train, bert_hatebert_concat_dynahate_dev))
bert_hatebert_concat_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_concat_dynahate_train_dev, bert_hatebert_concat_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_concat_dynahate_train_dev)
test_preds = mlp.predict(bert_hatebert_concat_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_hatebert_concat_dynahate")

save_model(mlp, "Saves/bert_hatebert_concat_dynahate")


Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7358200086430423
Accuracy Test:  0.6973300970873786
Weighted F1 Train Dev:  0.7353588003714895
Weighted F1 Test:  0.6970275750251803
Macro F1 Train Dev:  0.7334748017219539
Macro F1 Test:  0.6936262458934364
Micro F1 Train Dev:  0.7358200086430422
Micro F1 Test:  0.6973300970873786
Weighted Recall Train Dev:  0.7358200086430423
Weighted Recall Test:  0.6973300970873786
Macro Recall Train Dev:  0.73291318887662
Macro Recall Test:  0.693296441046621
Micro Recall Train Dev:  0.7358200086430423
Micro Recall Test:  0.6973300970873786
Confusion Matrix Train Dev: 
[[11885  5232]
 [ 4549 15358]]
Confusion Matrix Test: 
[[1210  642]
 [ 605 1663]]


#### LatentHatred

In [12]:
bert_hatebert_concat_latenthatred_train_dev = np.concatenate((bert_hatebert_concat_latenthatred_train, bert_hatebert_concat_latenthatred_dev))
bert_hatebert_concat_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_concat_latenthatred_train_dev, bert_hatebert_concat_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_concat_latenthatred_train_dev)
test_preds = mlp.predict(bert_hatebert_concat_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_hatebert_concat_latenthatred")

save_model(mlp, "Saves/bert_hatebert_concat_latenthatred")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7187461204220981
Accuracy Test:  0.692364990689013
Weighted F1 Train Dev:  0.7021761540141129
Weighted F1 Test:  0.6751380172928965
Macro F1 Train Dev:  0.5398970011063146
Macro F1 Test:  0.50815237513305
Micro F1 Train Dev:  0.7187461204220981
Micro F1 Test:  0.692364990689013
Weighted Recall Train Dev:  0.7187461204220981
Weighted Recall Test:  0.692364990689013
Macro Recall Train Dev:  0.5166169705684788
Macro Recall Test:  0.4893010077449918
Micro Recall Train Dev:  0.7187461204220981
Micro Recall Test:  0.692364990689013
Confusion Matrix Train Dev: 
[[8641 1245   59]
 [2464 2811   72]
 [ 307  384  127]]
Confusion Matrix Test: 
[[2841  486   19]
 [ 877  839   37]
 [ 110  123   38]]


#### OLID

In [13]:
bert_hatebert_concat_olid_train_dev = np.concatenate((bert_hatebert_concat_olid_train, bert_hatebert_concat_olid_dev))
bert_hatebert_concat_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_concat_olid_train_dev, bert_hatebert_concat_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_concat_olid_train_dev)
test_preds = mlp.predict(bert_hatebert_concat_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_hatebert_concat_olid")

save_model(mlp, "Saves/bert_hatebert_concat_olid")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7858761329305136
Accuracy Test:  0.8
Weighted F1 Train Dev:  0.7807450390150636
Weighted F1 Test:  0.7766864404032546
Macro F1 Train Dev:  0.7479651009077288
Macro F1 Test:  0.7003144348277092
Micro F1 Train Dev:  0.7858761329305136
Micro F1 Test:  0.8000000000000002
Weighted Recall Train Dev:  0.7858761329305136
Weighted Recall Test:  0.8
Macro Recall Train Dev:  0.738911456190868
Macro Recall Test:  0.6774193548387097
Micro Recall Train Dev:  0.7858761329305136
Micro Recall Test:  0.8
Confusion Matrix Train Dev: 
[[7770 1070]
 [1765 2635]]
Confusion Matrix Test: 
[[592  28]
 [144  96]]


### BERTweet-HateBERT

#### DynaHate

In [14]:
hatebert_bertweet_concat_dynahate_train_dev = np.concatenate((hatebert_bertweet_concat_dynahate_train, hatebert_bertweet_concat_dynahate_dev))
hatebert_bertweet_concat_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_concat_dynahate_train_dev, hatebert_bertweet_concat_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_concat_dynahate_train_dev)
test_preds = mlp.predict(hatebert_bertweet_concat_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev dynahate_labels_test, "Results/hatebert_bertweet_concat_dynahate")

save_model(mlp, "Saves/hatebert_bertweet_concat_dynahate")

SyntaxError: invalid syntax (3837484848.py, line 14)

#### LatentHatred

In [ ]:
hatebert_bertweet_concat_latenthatred_train_dev = np.concatenate((hatebert_bertweet_concat_latenthatred_train, hatebert_bertweet_concat_latenthatred_dev))
hatebert_bertweet_concat_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_concat_latenthatred_train_dev, hatebert_bertweet_concat_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_concat_latenthatred_train_dev)
test_preds = mlp.predict(hatebert_bertweet_concat_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/hatebert_bertweet_concat_latenthatred")

save_model(mlp, "Saves/hatebert_bertweet_concat_latenthatred")

#### OLID

In [ ]:
hatebert_bertweet_concat_olid_train_dev = np.concatenate((hatebert_bertweet_concat_olid_train, hatebert_bertweet_concat_olid_dev))
hatebert_bertweet_concat_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_concat_olid_train_dev, hatebert_bertweet_concat_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_concat_olid_train_dev)
test_preds = mlp.predict(hatebert_bertweet_concat_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/hatebert_bertweet_concat_olid")

save_model(mlp, "Saves/hatebert_bertweet_concat_olid")

### BERT-BERTweet-HateBERT

#### DynaHate

In [ ]:
bert_bertweet_hatebert_concat_dynahate_train_dev = np.concatenate((bert_hatebert_bertweet_concat_dynahate_train, bert_hatebert_bertweet_concat_dynahate_dev))
bert_bertweet_hatebert_concat_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_concat_dynahate_train_dev, bert_bertweet_hatebert_concat_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_concat_dynahate_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_concat_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev dynahate_labels_test, "Results/bert_bertweet_hatebert_concat_dynahate")

save_model(mlp, "Saves/bert_bertweet_hatebert_concat_dynahate")

#### LatentHatred

In [ ]:
bert_bertweet_hatebert_concat_latenthatred_train_dev = np.concatenate((bert_hatebert_bertweet_concat_latenthatred_train, bert_hatebert_bertweet_concat_latenthatred_dev))
bert_bertweet_hatebert_concat_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_concat_latenthatred_train_dev, bert_bertweet_hatebert_concat_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_concat_latenthatred_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_concat_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_bertweet_hatebert_concat_latenthatred")

save_model(mlp, "Saves/bert_bertweet_hatebert_concat_latenthatred")

#### OLID

In [ ]:
bert_bertweet_hatebert_concat_olid_train_dev = np.concatenate((bert_hatebert_bertweet_concat_olid_train, bert_hatebert_bertweet_concat_olid_dev))
bert_bertweet_hatebert_concat_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_concat_olid_train_dev, bert_bertweet_hatebert_concat_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_concat_olid_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_concat_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_bertweet_hatebert_concat_olid")

save_model(mlp, "Saves/bert_bertweet_hatebert_concat_olid")