In [1]:
from utils import *
import numpy as np
import torch, os
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV

In [2]:
set_random_seed(3)

Seed: 3


In [3]:
# def scaling_embeddings(embeddings):
#     for i in range(len(embeddings)):
#         embeddings[i] = StandardScaler().fit_transform(embeddings[i])
#     return embeddings

def reshape_embeddings(embeddings):
    if embeddings.shape[1] == 1:
        embeddings = embeddings.squeeze(1)
    return embeddings

In [4]:
def concat_2_embeddings(embeddings1, embeddings2):
    embeddings1 = reshape_embeddings(embeddings1)
    embeddings2 = reshape_embeddings(embeddings2)
    # Numpy concat
    return np.concatenate((embeddings1, embeddings2), axis=1)

def concat_3_embeddings(embeddings1, embeddings2, embeddings3):
    embeddings1 = reshape_embeddings(embeddings1)
    embeddings2 = reshape_embeddings(embeddings2)
    embeddings3 = reshape_embeddings(embeddings3)
    return np.concatenate((embeddings1, embeddings2, embeddings3), axis=1)

In [5]:
bert_hatebert_concat_dynahate_train = concat_2_embeddings(bert_dynahate_train_embeddings, hatebert_dynahate_train_embeddings)
bert_hatebert_concat_dynahate_dev = concat_2_embeddings(bert_dynahate_dev_embeddings, hatebert_dynahate_dev_embeddings)
bert_hatebert_concat_dynahate_test = concat_2_embeddings(bert_dynahate_test_embeddings, hatebert_dynahate_test_embeddings)

bert_bertweet_concat_dynahate_train = concat_2_embeddings(bert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
bert_bertweet_concat_dynahate_dev = concat_2_embeddings(bert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
bert_bertweet_concat_dynahate_test = concat_2_embeddings(bert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

hatebert_bertweet_concat_dynahate_train = concat_2_embeddings(hatebert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
hatebert_bertweet_concat_dynahate_dev = concat_2_embeddings(hatebert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
hatebert_bertweet_concat_dynahate_test = concat_2_embeddings(hatebert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

bert_hatebert_bertweet_concat_dynahate_train = concat_3_embeddings(bert_dynahate_train_embeddings, hatebert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
bert_hatebert_bertweet_concat_dynahate_dev = concat_3_embeddings(bert_dynahate_dev_embeddings, hatebert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
bert_hatebert_bertweet_concat_dynahate_test = concat_3_embeddings(bert_dynahate_test_embeddings, hatebert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

bert_hatebert_concat_olid_train = concat_2_embeddings(bert_olid_train_embeddings, hatebert_olid_train_embeddings)
bert_hatebert_concat_olid_dev = concat_2_embeddings(bert_olid_dev_embeddings, hatebert_olid_dev_embeddings)
bert_hatebert_concat_olid_test = concat_2_embeddings(bert_olid_test_embeddings, hatebert_olid_test_embeddings)

bert_bertweet_concat_olid_train = concat_2_embeddings(bert_olid_train_embeddings, bertweet_olid_train_embeddings)
bert_bertweet_concat_olid_dev = concat_2_embeddings(bert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
bert_bertweet_concat_olid_test = concat_2_embeddings(bert_olid_test_embeddings, bertweet_olid_test_embeddings)

hatebert_bertweet_concat_olid_train = concat_2_embeddings(hatebert_olid_train_embeddings, bertweet_olid_train_embeddings)
hatebert_bertweet_concat_olid_dev = concat_2_embeddings(hatebert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
hatebert_bertweet_concat_olid_test = concat_2_embeddings(hatebert_olid_test_embeddings, bertweet_olid_test_embeddings)

bert_hatebert_bertweet_concat_olid_train = concat_3_embeddings(bert_olid_train_embeddings, hatebert_olid_train_embeddings, bertweet_olid_train_embeddings)
bert_hatebert_bertweet_concat_olid_dev = concat_3_embeddings(bert_olid_dev_embeddings, hatebert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
bert_hatebert_bertweet_concat_olid_test = concat_3_embeddings(bert_olid_test_embeddings, hatebert_olid_test_embeddings, bertweet_olid_test_embeddings)

bert_hatebert_concat_latenthatred_train = concat_2_embeddings(bert_latenthatred_train_embeddings, hatebert_latenthatred_train_embeddings)
bert_hatebert_concat_latenthatred_dev = concat_2_embeddings(bert_latenthatred_dev_embeddings, hatebert_latenthatred_dev_embeddings)
bert_hatebert_concat_latenthatred_test = concat_2_embeddings(bert_latenthatred_test_embeddings, hatebert_latenthatred_test_embeddings)

bert_bertweet_concat_latenthatred_train = concat_2_embeddings(bert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
bert_bertweet_concat_latenthatred_dev = concat_2_embeddings(bert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
bert_bertweet_concat_latenthatred_test = concat_2_embeddings(bert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

hatebert_bertweet_concat_latenthatred_train = concat_2_embeddings(hatebert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
hatebert_bertweet_concat_latenthatred_dev = concat_2_embeddings(hatebert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
hatebert_bertweet_concat_latenthatred_test = concat_2_embeddings(hatebert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

bert_hatebert_bertweet_concat_latenthatred_train = concat_3_embeddings(bert_latenthatred_train_embeddings, hatebert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
bert_hatebert_bertweet_concat_latenthatred_dev = concat_3_embeddings(bert_latenthatred_dev_embeddings, hatebert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
bert_hatebert_bertweet_concat_latenthatred_test = concat_3_embeddings(bert_latenthatred_test_embeddings, hatebert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

In [6]:
dynahate_labels_train = process_labels(read_labels("dynahate", "train"))
dynahate_labels_dev = process_labels(read_labels("dynahate", "dev"))
dynahate_labels_test = process_labels(read_labels("dynahate", "test"))

latenthatred_labels_train = read_labels("latenthatred", "train")
latenthatred_labels_dev = read_labels("latenthatred", "dev")
latenthatred_labels_test = read_labels("latenthatred", "test")

olid_labels_train = read_labels("olid", "train")
olid_labels_dev = read_labels("olid", "dev")
olid_labels_test = read_labels("olid", "test")

In [7]:
mlp = MLPClassifier(random_state=3)
gridsearch = GridSearchCV(
    mlp,
    param_grid={
        "hidden_layer_sizes": [(128), (128,64)],
        "activation": ["relu"],
        "solver": ["adam"],
        "learning_rate_init": [0.001, 0.0001],
        "learning_rate": ["adaptive"],
        "early_stopping": [True],
        "max_iter": [10000]
    },
    verbose=4,
    n_jobs=os.cpu_count()//3,
    cv=5,
)

In [8]:
dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))
latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))
olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

### BERT-BERTweet

#### DynaHate

In [9]:
bert_bertweet_concat_dynahate_train_dev = np.concatenate((bert_bertweet_concat_dynahate_train, bert_bertweet_concat_dynahate_dev))
bert_bertweet_concat_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_concat_dynahate_train_dev, bert_bertweet_concat_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_concat_dynahate_train_dev)
test_preds = mlp.predict(bert_bertweet_concat_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_bertweet_concat_dynahate_seed_3")
save_model(mlp, "Saves/bert_bertweet_concat_dynahate_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7392502160760588
Accuracy Test:  0.6966019417475728
Weighted F1 Train Dev:  0.7383882785867913
Weighted F1 Test:  0.6954802067287899
Macro F1 Train Dev:  0.736278799994637
Macro F1 Test:  0.6914574328683267
Micro F1 Train Dev:  0.7392502160760588
Micro F1 Test:  0.6966019417475728
Weighted Recall Train Dev:  0.7392502160760588
Weighted Recall Test:  0.6966019417475728
Macro Recall Train Dev:  0.735427522638797
Macro Recall Test:  0.6906047516198703
Micro Recall Train Dev:  0.7392502160760588
Micro Recall Test:  0.6966019417475728
Confusion Matrix Train Dev: 
[[11720  5397]
 [ 4257 15650]]
Confusion Matrix Test: 
[[1169  683]
 [ 567 1701]]


#### LatentHatred

In [10]:
bert_bertweet_concat_latenthatred_train_dev = np.concatenate((bert_bertweet_concat_latenthatred_train, bert_bertweet_concat_latenthatred_dev))
bert_bertweet_concat_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_concat_latenthatred_train_dev, bert_bertweet_concat_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_concat_latenthatred_train_dev)
test_preds = mlp.predict(bert_bertweet_concat_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_bertweet_concat_latenthatred_seed_3")
save_model(mlp, "Saves/bert_bertweet_concat_latenthatred_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7251396648044692
Accuracy Test:  0.7001862197392924
Weighted F1 Train Dev:  0.7030304798019015
Weighted F1 Test:  0.6749895484423731
Macro F1 Train Dev:  0.5332021974849913
Macro F1 Test:  0.49524250316720814
Micro F1 Train Dev:  0.7251396648044692
Micro F1 Test:  0.7001862197392924
Weighted Recall Train Dev:  0.7251396648044692
Weighted Recall Test:  0.7001862197392924
Macro Recall Train Dev:  0.509099302110108
Macro Recall Test:  0.47783338032052636
Micro Recall Train Dev:  0.7251396648044692
Micro Recall Test:  0.7001862197392924
Confusion Matrix Train Dev: 
[[8933  979   33]
 [2644 2638   65]
 [ 374  333  111]]
Confusion Matrix Test: 
[[2964  367   15]
 [ 956  766   31]
 [ 132  109   30]]


#### OLID

In [11]:
bert_bertweet_concat_olid_train_dev = np.concatenate((bert_bertweet_concat_olid_train, bert_bertweet_concat_olid_dev))
bert_bertweet_concat_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_concat_olid_train_dev, bert_bertweet_concat_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_concat_olid_train_dev)
test_preds = mlp.predict(bert_bertweet_concat_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_bertweet_concat_olid_seed_3")

save_model(mlp, "Saves/bert_bertweet_concat_olid_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7799848942598188
Accuracy Test:  0.8116279069767441
Weighted F1 Train Dev:  0.7745503621654941
Weighted F1 Test:  0.7962661573432689
Macro F1 Train Dev:  0.7407083951265028
Macro F1 Test:  0.7314054366685946
Micro F1 Train Dev:  0.7799848942598187
Micro F1 Test:  0.8116279069767441
Weighted Recall Train Dev:  0.7799848942598188
Weighted Recall Test:  0.8116279069767441
Macro Recall Train Dev:  0.731760078157137
Macro Recall Test:  0.7084677419354839
Micro Recall Train Dev:  0.7799848942598188
Micro Recall Test:  0.8116279069767441
Confusion Matrix Train Dev: 
[[7740 1100]
 [1813 2587]]
Confusion Matrix Test: 
[[584  36]
 [126 114]]


### BERT-HateBERT

#### DynaHate

In [12]:
bert_hatebert_concat_dynahate_train_dev = np.concatenate((bert_hatebert_concat_dynahate_train, bert_hatebert_concat_dynahate_dev))
bert_hatebert_concat_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_concat_dynahate_train_dev, bert_hatebert_concat_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_concat_dynahate_train_dev)
test_preds = mlp.predict(bert_hatebert_concat_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_hatebert_concat_dynahate_seed_3")

save_model(mlp, "Saves/bert_hatebert_concat_dynahate_seed_3")


Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7306341832324978
Accuracy Test:  0.6910194174757281
Weighted F1 Train Dev:  0.7272691370114065
Weighted F1 Test:  0.6881968140171718
Macro F1 Train Dev:  0.724059400615904
Macro F1 Test:  0.6831573159967448
Micro F1 Train Dev:  0.7306341832324977
Micro F1 Test:  0.6910194174757281
Weighted Recall Train Dev:  0.7306341832324978
Weighted Recall Test:  0.6910194174757281
Macro Recall Train Dev:  0.7231084480322546
Macro Recall Test:  0.6820678155271388
Micro Recall Train Dev:  0.7306341832324978
Micro Recall Test:  0.6910194174757281
Confusion Matrix Train Dev: 
[[10668  6449]
 [ 3524 16383]]
Confusion Matrix Test: 
[[1099  753]
 [ 520 1748]]


#### LatentHatred

In [13]:
bert_hatebert_concat_latenthatred_train_dev = np.concatenate((bert_hatebert_concat_latenthatred_train, bert_hatebert_concat_latenthatred_dev))
bert_hatebert_concat_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_concat_latenthatred_train_dev, bert_hatebert_concat_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_concat_latenthatred_train_dev)
test_preds = mlp.predict(bert_hatebert_concat_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_hatebert_concat_latenthatred_seed_3")

save_model(mlp, "Saves/bert_hatebert_concat_latenthatred_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7145872129112353
Accuracy Test:  0.6945996275605214
Weighted F1 Train Dev:  0.6913444521392624
Weighted F1 Test:  0.6689390929737381
Macro F1 Train Dev:  0.5245345684962105
Macro F1 Test:  0.4967820861264332
Micro F1 Train Dev:  0.7145872129112353
Micro F1 Test:  0.6945996275605214
Weighted Recall Train Dev:  0.7145872129112353
Weighted Recall Test:  0.6945996275605214
Macro Recall Train Dev:  0.5016950593460093
Macro Recall Test:  0.47827751746890607
Micro Recall Train Dev:  0.7145872129112353
Micro Recall Test:  0.6945996275605214
Confusion Matrix Train Dev: 
[[8918  977   50]
 [2784 2475   88]
 [ 362  337  119]]
Confusion Matrix Test: 
[[2965  364   17]
 [ 984  729   40]
 [ 127  108   36]]


#### OLID

In [14]:
bert_hatebert_concat_olid_train_dev = np.concatenate((bert_hatebert_concat_olid_train, bert_hatebert_concat_olid_dev))
bert_hatebert_concat_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_concat_olid_train_dev, bert_hatebert_concat_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_concat_olid_train_dev)
test_preds = mlp.predict(bert_hatebert_concat_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_hatebert_concat_olid_seed_3")

save_model(mlp, "Saves/bert_hatebert_concat_olid_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7643504531722054
Accuracy Test:  0.7930232558139535
Weighted F1 Train Dev:  0.7576686153725429
Weighted F1 Test:  0.7761442963401348
Macro F1 Train Dev:  0.7205844155844157
Macro F1 Test:  0.7048775785617891
Micro F1 Train Dev:  0.7643504531722054
Micro F1 Test:  0.7930232558139535
Weighted Recall Train Dev:  0.7643504531722054
Weighted Recall Test:  0.7930232558139535
Macro Recall Train Dev:  0.7116618675442206
Macro Recall Test:  0.6853494623655914
Micro Recall Train Dev:  0.7643504531722054
Micro Recall Test:  0.7930232558139535
Confusion Matrix Train Dev: 
[[7680 1160]
 [1960 2440]]
Confusion Matrix Test: 
[[576  44]
 [134 106]]


### BERTweet-HateBERT

#### DynaHate

In [15]:
hatebert_bertweet_concat_dynahate_train_dev = np.concatenate((hatebert_bertweet_concat_dynahate_train, hatebert_bertweet_concat_dynahate_dev))
hatebert_bertweet_concat_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_concat_dynahate_train_dev, hatebert_bertweet_concat_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_concat_dynahate_train_dev)
test_preds = mlp.predict(hatebert_bertweet_concat_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/hatebert_bertweet_concat_dynahate_seed_3")

save_model(mlp, "Saves/hatebert_bertweet_concat_dynahate_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7356579515989629
Accuracy Test:  0.7050970873786407
Weighted F1 Train Dev:  0.7340662505677593
Weighted F1 Test:  0.703925226901946
Macro F1 Train Dev:  0.7315699909404084
Macro F1 Test:  0.6999618613872709
Micro F1 Train Dev:  0.7356579515989629
Micro F1 Test:  0.7050970873786407
Weighted Recall Train Dev:  0.7356579515989629
Weighted Recall Test:  0.7050970873786407
Macro Recall Train Dev:  0.7305067309850652
Macro Recall Test:  0.69901407887369
Micro Recall Train Dev:  0.7356579515989629
Micro Recall Test:  0.7050970873786407
Confusion Matrix Train Dev: 
[[11334  5783]
 [ 4004 15903]]
Confusion Matrix Test: 
[[1183  669]
 [ 546 1722]]


#### LatentHatred

In [16]:
hatebert_bertweet_concat_latenthatred_train_dev = np.concatenate((hatebert_bertweet_concat_latenthatred_train, hatebert_bertweet_concat_latenthatred_dev))
hatebert_bertweet_concat_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_concat_latenthatred_train_dev, hatebert_bertweet_concat_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_concat_latenthatred_train_dev)
test_preds = mlp.predict(hatebert_bertweet_concat_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/hatebert_bertweet_concat_latenthatred_seed_3")

save_model(mlp, "Saves/hatebert_bertweet_concat_latenthatred_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7229050279329609
Accuracy Test:  0.7
Weighted F1 Train Dev:  0.6968657885859495
Weighted F1 Test:  0.6690922254544529
Macro F1 Train Dev:  0.5191857263346688
Macro F1 Test:  0.48006910738774405
Micro F1 Train Dev:  0.7229050279329609
Micro F1 Test:  0.7
Weighted Recall Train Dev:  0.7229050279329609
Weighted Recall Test:  0.7
Macro Recall Train Dev:  0.49744219551794205
Macro Recall Test:  0.4653851126240469
Micro Recall Train Dev:  0.7229050279329609
Micro Recall Test:  0.7
Confusion Matrix Train Dev: 
[[9056  867   22]
 [2792 2496   59]
 [ 381  343   94]]
Confusion Matrix Test: 
[[3019  316   11]
 [1018  717   18]
 [ 135  113   23]]


#### OLID

In [17]:
hatebert_bertweet_concat_olid_train_dev = np.concatenate((hatebert_bertweet_concat_olid_train, hatebert_bertweet_concat_olid_dev))
hatebert_bertweet_concat_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_concat_olid_train_dev, hatebert_bertweet_concat_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_concat_olid_train_dev)
test_preds = mlp.predict(hatebert_bertweet_concat_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/hatebert_bertweet_concat_olid_seed_3")

save_model(mlp, "Saves/hatebert_bertweet_concat_olid_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7669184290030211
Accuracy Test:  0.7988372093023256
Weighted F1 Train Dev:  0.7547002717653714
Weighted F1 Test:  0.7806608213350501
Macro F1 Train Dev:  0.7129705655075519
Macro F1 Test:  0.7094543530096413
Micro F1 Train Dev:  0.7669184290030211
Micro F1 Test:  0.7988372093023256
Weighted Recall Train Dev:  0.7669184290030211
Weighted Recall Test:  0.7988372093023256
Macro Recall Train Dev:  0.7002864047716989
Macro Recall Test:  0.6881048387096774
Micro Recall Train Dev:  0.7669184290030211
Micro Recall Test:  0.7988372093023256
Confusion Matrix Train Dev: 
[[7947  893]
 [2193 2207]]
Confusion Matrix Test: 
[[582  38]
 [135 105]]


### BERT-BERTweet-HateBERT

#### DynaHate

In [18]:
bert_bertweet_hatebert_concat_dynahate_train_dev = np.concatenate((bert_hatebert_bertweet_concat_dynahate_train, bert_hatebert_bertweet_concat_dynahate_dev))
bert_bertweet_hatebert_concat_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_concat_dynahate_train_dev, bert_bertweet_hatebert_concat_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_concat_dynahate_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_concat_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_bertweet_hatebert_concat_dynahate_seed_3")

save_model(mlp, "Saves/bert_bertweet_hatebert_concat_dynahate_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7490006482281764
Accuracy Test:  0.7063106796116505
Weighted F1 Train Dev:  0.7493358000358852
Weighted F1 Test:  0.7070607910952764
Macro F1 Train Dev:  0.7484444048561827
Macro F1 Test:  0.7055888742217464
Micro F1 Train Dev:  0.7490006482281764
Micro F1 Test:  0.7063106796116505
Weighted Recall Train Dev:  0.7490006482281764
Weighted Recall Test:  0.7063106796116505
Macro Recall Train Dev:  0.7497144496342767
Macro Recall Test:  0.7085347457917652
Micro Recall Train Dev:  0.7490006482281764
Micro Recall Test:  0.7063106796116505
Confusion Matrix Train Dev: 
[[12995  4122]
 [ 5171 14736]]
Confusion Matrix Test: 
[[1353  499]
 [ 711 1557]]


#### LatentHatred

In [19]:
bert_bertweet_hatebert_concat_latenthatred_train_dev = np.concatenate((bert_hatebert_bertweet_concat_latenthatred_train, bert_hatebert_bertweet_concat_latenthatred_dev))
bert_bertweet_hatebert_concat_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_concat_latenthatred_train_dev, bert_bertweet_hatebert_concat_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_concat_latenthatred_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_concat_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_bertweet_hatebert_concat_latenthatred_seed_3")

save_model(mlp, "Saves/bert_bertweet_hatebert_concat_latenthatred_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7225325884543762
Accuracy Test:  0.7007448789571694
Weighted F1 Train Dev:  0.70767207968422
Weighted F1 Test:  0.6855103592132524
Macro F1 Train Dev:  0.5144100443794969
Macro F1 Test:  0.49109162611960366
Micro F1 Train Dev:  0.7225325884543762
Micro F1 Test:  0.7007448789571694
Weighted Recall Train Dev:  0.7225325884543762
Weighted Recall Test:  0.7007448789571694
Macro Recall Train Dev:  0.5062601190152011
Macro Recall Test:  0.4840777253071973
Micro Recall Train Dev:  0.7225325884543762
Micro Recall Test:  0.7007448789571694
Confusion Matrix Train Dev: 
[[8294 1631   20]
 [2037 3289   21]
 [ 268  493   57]]
Confusion Matrix Test: 
[[2752  584   10]
 [ 752  994    7]
 [  88  166   17]]


#### OLID

In [20]:
bert_bertweet_hatebert_concat_olid_train_dev = np.concatenate((bert_hatebert_bertweet_concat_olid_train, bert_hatebert_bertweet_concat_olid_dev))
bert_bertweet_hatebert_concat_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_concat_olid_train_dev, bert_bertweet_hatebert_concat_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_concat_olid_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_concat_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_bertweet_hatebert_concat_olid_seed_3")

save_model(mlp, "Saves/bert_bertweet_hatebert_concat_olid_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7825528700906345
Accuracy Test:  0.8034883720930233
Weighted F1 Train Dev:  0.7689308972890205
Weighted F1 Test:  0.7814413592402251
Macro F1 Train Dev:  0.7281476476334803
Macro F1 Test:  0.7073009620361251
Micro F1 Train Dev:  0.7825528700906345
Micro F1 Test:  0.8034883720930233
Weighted Recall Train Dev:  0.7825528700906345
Weighted Recall Test:  0.8034883720930233
Macro Recall Train Dev:  0.7126794529000411
Macro Recall Test:  0.6836693548387096
Micro Recall Train Dev:  0.7825528700906345
Micro Recall Test:  0.8034883720930233
Confusion Matrix Train Dev: 
[[8142  698]
 [2181 2219]]
Confusion Matrix Test: 
[[592  28]
 [141  99]]
