In [1]:
from utils import *
import numpy as np
import torch, os
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV

c:\Kyode\PersonalProjects\HateSpeechModelCombination\venv\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:
set_random_seed(42)

In [2]:
# def scaling_embeddings(embeddings):
#     for i in range(len(embeddings)):
#         embeddings[i] = StandardScaler().fit_transform(embeddings[i])
#     return embeddings

def reshape_embeddings(embeddings):
    if embeddings.shape[1] == 1:
        embeddings = embeddings.squeeze(1)
    return embeddings

In [3]:
def concat_2_embeddings(embeddings1, embeddings2):
    embeddings1 = reshape_embeddings(embeddings1)
    embeddings2 = reshape_embeddings(embeddings2)
    # Numpy concat
    return np.concatenate((embeddings1, embeddings2), axis=1)

def concat_3_embeddings(embeddings1, embeddings2, embeddings3):
    embeddings1 = reshape_embeddings(embeddings1)
    embeddings2 = reshape_embeddings(embeddings2)
    embeddings3 = reshape_embeddings(embeddings3)
    return np.concatenate((embeddings1, embeddings2, embeddings3), axis=1)

In [4]:
bert_hatebert_concat_dynahate_train = concat_2_embeddings(bert_dynahate_train_embeddings, hatebert_dynahate_train_embeddings)
bert_hatebert_concat_dynahate_dev = concat_2_embeddings(bert_dynahate_dev_embeddings, hatebert_dynahate_dev_embeddings)
bert_hatebert_concat_dynahate_test = concat_2_embeddings(bert_dynahate_test_embeddings, hatebert_dynahate_test_embeddings)

bert_bertweet_concat_dynahate_train = concat_2_embeddings(bert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
bert_bertweet_concat_dynahate_dev = concat_2_embeddings(bert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
bert_bertweet_concat_dynahate_test = concat_2_embeddings(bert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

hatebert_bertweet_concat_dynahate_train = concat_2_embeddings(hatebert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
hatebert_bertweet_concat_dynahate_dev = concat_2_embeddings(hatebert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
hatebert_bertweet_concat_dynahate_test = concat_2_embeddings(hatebert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

bert_hatebert_bertweet_concat_dynahate_train = concat_3_embeddings(bert_dynahate_train_embeddings, hatebert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
bert_hatebert_bertweet_concat_dynahate_dev = concat_3_embeddings(bert_dynahate_dev_embeddings, hatebert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
bert_hatebert_bertweet_concat_dynahate_test = concat_3_embeddings(bert_dynahate_test_embeddings, hatebert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

bert_hatebert_concat_olid_train = concat_2_embeddings(bert_olid_train_embeddings, hatebert_olid_train_embeddings)
bert_hatebert_concat_olid_dev = concat_2_embeddings(bert_olid_dev_embeddings, hatebert_olid_dev_embeddings)
bert_hatebert_concat_olid_test = concat_2_embeddings(bert_olid_test_embeddings, hatebert_olid_test_embeddings)

bert_bertweet_concat_olid_train = concat_2_embeddings(bert_olid_train_embeddings, bertweet_olid_train_embeddings)
bert_bertweet_concat_olid_dev = concat_2_embeddings(bert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
bert_bertweet_concat_olid_test = concat_2_embeddings(bert_olid_test_embeddings, bertweet_olid_test_embeddings)

hatebert_bertweet_concat_olid_train = concat_2_embeddings(hatebert_olid_train_embeddings, bertweet_olid_train_embeddings)
hatebert_bertweet_concat_olid_dev = concat_2_embeddings(hatebert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
hatebert_bertweet_concat_olid_test = concat_2_embeddings(hatebert_olid_test_embeddings, bertweet_olid_test_embeddings)

bert_hatebert_bertweet_concat_olid_train = concat_3_embeddings(bert_olid_train_embeddings, hatebert_olid_train_embeddings, bertweet_olid_train_embeddings)
bert_hatebert_bertweet_concat_olid_dev = concat_3_embeddings(bert_olid_dev_embeddings, hatebert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
bert_hatebert_bertweet_concat_olid_test = concat_3_embeddings(bert_olid_test_embeddings, hatebert_olid_test_embeddings, bertweet_olid_test_embeddings)

bert_hatebert_concat_latenthatred_train = concat_2_embeddings(bert_latenthatred_train_embeddings, hatebert_latenthatred_train_embeddings)
bert_hatebert_concat_latenthatred_dev = concat_2_embeddings(bert_latenthatred_dev_embeddings, hatebert_latenthatred_dev_embeddings)
bert_hatebert_concat_latenthatred_test = concat_2_embeddings(bert_latenthatred_test_embeddings, hatebert_latenthatred_test_embeddings)

bert_bertweet_concat_latenthatred_train = concat_2_embeddings(bert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
bert_bertweet_concat_latenthatred_dev = concat_2_embeddings(bert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
bert_bertweet_concat_latenthatred_test = concat_2_embeddings(bert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

hatebert_bertweet_concat_latenthatred_train = concat_2_embeddings(hatebert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
hatebert_bertweet_concat_latenthatred_dev = concat_2_embeddings(hatebert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
hatebert_bertweet_concat_latenthatred_test = concat_2_embeddings(hatebert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

bert_hatebert_bertweet_concat_latenthatred_train = concat_3_embeddings(bert_latenthatred_train_embeddings, hatebert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
bert_hatebert_bertweet_concat_latenthatred_dev = concat_3_embeddings(bert_latenthatred_dev_embeddings, hatebert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
bert_hatebert_bertweet_concat_latenthatred_test = concat_3_embeddings(bert_latenthatred_test_embeddings, hatebert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

In [5]:
dynahate_labels_train = process_labels(read_labels("dynahate", "train"))
dynahate_labels_dev = process_labels(read_labels("dynahate", "dev"))
dynahate_labels_test = process_labels(read_labels("dynahate", "test"))

latenthatred_labels_train = read_labels("latenthatred", "train")
latenthatred_labels_dev = read_labels("latenthatred", "dev")
latenthatred_labels_test = read_labels("latenthatred", "test")

olid_labels_train = read_labels("olid", "train")
olid_labels_dev = read_labels("olid", "dev")
olid_labels_test = read_labels("olid", "test")

In [6]:
mlp = MLPClassifier(random_state=42)
gridsearch = GridSearchCV(
    mlp,
    param_grid={
        "hidden_layer_sizes": [(128), (128,64)],
        "activation": ["relu"],
        "solver": ["adam"],
        "learning_rate_init": [0.001, 0.0001],
        "learning_rate": ["adaptive"],
        "early_stopping": [True],
        "max_iter": [10000]
    },
    verbose=4,
    n_jobs=os.cpu_count()//3,
    cv=5,
)

In [7]:
dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))
latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))
olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

### BERT-BERTweet

#### DynaHate

In [8]:
bert_bertweet_concat_dynahate_train_dev = np.concatenate((bert_bertweet_concat_dynahate_train, bert_bertweet_concat_dynahate_dev))
bert_bertweet_concat_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_concat_dynahate_train_dev, bert_bertweet_concat_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_concat_dynahate_train_dev)
test_preds = mlp.predict(bert_bertweet_concat_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_bertweet_concat_dynahate_seed_42")
save_model(mlp, "Saves/bert_bertweet_concat_dynahate_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7177506482281764
Accuracy Test:  0.6817961165048544
Weighted F1 Train Dev:  0.7157674240197323
Weighted F1 Test:  0.6798165675674613
Macro F1 Train Dev:  0.7129785149766077
Macro F1 Test:  0.6751108969505724
Micro F1 Train Dev:  0.7177506482281762
Micro F1 Test:  0.6817961165048544
Weighted Recall Train Dev:  0.7177506482281764
Weighted Recall Test:  0.6817961165048544
Macro Recall Train Dev:  0.7120775302064103
Macro Recall Test:  0.6741855889624069
Micro Recall Train Dev:  0.7177506482281764
Micro Recall Test:  0.6817961165048544
Confusion Matrix Train Dev: 
[[10900  6217]
 [ 4233 15674]]
Confusion Matrix Test: 
[[1109  743]
 [ 568 1700]]


#### LatentHatred

In [9]:
bert_bertweet_concat_latenthatred_train_dev = np.concatenate((bert_bertweet_concat_latenthatred_train, bert_bertweet_concat_latenthatred_dev))
bert_bertweet_concat_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_concat_latenthatred_train_dev, bert_bertweet_concat_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_concat_latenthatred_train_dev)
test_preds = mlp.predict(bert_bertweet_concat_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_bertweet_concat_latenthatred_seed_42")
save_model(mlp, "Saves/bert_bertweet_concat_latenthatred_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7286778398510242
Accuracy Test:  0.6988826815642458
Weighted F1 Train Dev:  0.7119909641619356
Weighted F1 Test:  0.6812212303382655
Macro F1 Train Dev:  0.5168873562457398
Macro F1 Test:  0.4816601083140402
Micro F1 Train Dev:  0.7286778398510242
Micro F1 Test:  0.6988826815642458
Weighted Recall Train Dev:  0.7286778398510242
Weighted Recall Test:  0.6988826815642458
Macro Recall Train Dev:  0.5074750347588459
Macro Recall Test:  0.4761597159116653
Micro Recall Train Dev:  0.7286778398510242
Micro Recall Test:  0.6988826815642458
Confusion Matrix Train Dev: 
[[8454 1482    9]
 [2098 3229   20]
 [ 287  475   56]]
Confusion Matrix Test: 
[[2784  555    7]
 [ 789  955    9]
 [ 104  153   14]]


#### OLID

In [10]:
bert_bertweet_concat_olid_train_dev = np.concatenate((bert_bertweet_concat_olid_train, bert_bertweet_concat_olid_dev))
bert_bertweet_concat_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_concat_olid_train_dev, bert_bertweet_concat_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_concat_olid_train_dev)
test_preds = mlp.predict(bert_bertweet_concat_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_bertweet_concat_olid_seed_42")

save_model(mlp, "Saves/bert_bertweet_concat_olid_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7586858006042296
Accuracy Test:  0.8081395348837209
Weighted F1 Train Dev:  0.7506868818119321
Weighted F1 Test:  0.7892877495599382
Macro F1 Train Dev:  0.7116162553677061
Macro F1 Test:  0.7197374736081183
Micro F1 Train Dev:  0.7586858006042296
Micro F1 Test:  0.8081395348837209
Weighted Recall Train Dev:  0.7586858006042296
Weighted Recall Test:  0.8081395348837209
Macro Recall Train Dev:  0.7021688605512135
Macro Recall Test:  0.6958333333333333
Micro Recall Train Dev:  0.7586858006042296
Micro Recall Test:  0.8081395348837209
Confusion Matrix Train Dev: 
[[7697 1143]
 [2052 2348]]
Confusion Matrix Test: 
[[589  31]
 [134 106]]


### BERT-HateBERT

#### DynaHate

In [11]:
bert_hatebert_concat_dynahate_train_dev = np.concatenate((bert_hatebert_concat_dynahate_train, bert_hatebert_concat_dynahate_dev))
bert_hatebert_concat_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_concat_dynahate_train_dev, bert_hatebert_concat_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_concat_dynahate_train_dev)
test_preds = mlp.predict(bert_hatebert_concat_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_hatebert_concat_dynahate_seed_42")

save_model(mlp, "Saves/bert_hatebert_concat_dynahate_seed_42")


Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7358200086430423
Accuracy Test:  0.6973300970873786
Weighted F1 Train Dev:  0.7353588003714895
Weighted F1 Test:  0.6970275750251803
Macro F1 Train Dev:  0.7334748017219539
Macro F1 Test:  0.6936262458934364
Micro F1 Train Dev:  0.7358200086430422
Micro F1 Test:  0.6973300970873786
Weighted Recall Train Dev:  0.7358200086430423
Weighted Recall Test:  0.6973300970873786
Macro Recall Train Dev:  0.73291318887662
Macro Recall Test:  0.693296441046621
Micro Recall Train Dev:  0.7358200086430423
Micro Recall Test:  0.6973300970873786
Confusion Matrix Train Dev: 
[[11885  5232]
 [ 4549 15358]]
Confusion Matrix Test: 
[[1210  642]
 [ 605 1663]]


#### LatentHatred

In [12]:
bert_hatebert_concat_latenthatred_train_dev = np.concatenate((bert_hatebert_concat_latenthatred_train, bert_hatebert_concat_latenthatred_dev))
bert_hatebert_concat_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_concat_latenthatred_train_dev, bert_hatebert_concat_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_concat_latenthatred_train_dev)
test_preds = mlp.predict(bert_hatebert_concat_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_hatebert_concat_latenthatred_seed_42")

save_model(mlp, "Saves/bert_hatebert_concat_latenthatred_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7187461204220981
Accuracy Test:  0.692364990689013
Weighted F1 Train Dev:  0.7021761540141129
Weighted F1 Test:  0.6751380172928965
Macro F1 Train Dev:  0.5398970011063146
Macro F1 Test:  0.50815237513305
Micro F1 Train Dev:  0.7187461204220981
Micro F1 Test:  0.692364990689013
Weighted Recall Train Dev:  0.7187461204220981
Weighted Recall Test:  0.692364990689013
Macro Recall Train Dev:  0.5166169705684788
Macro Recall Test:  0.4893010077449918
Micro Recall Train Dev:  0.7187461204220981
Micro Recall Test:  0.692364990689013
Confusion Matrix Train Dev: 
[[8641 1245   59]
 [2464 2811   72]
 [ 307  384  127]]
Confusion Matrix Test: 
[[2841  486   19]
 [ 877  839   37]
 [ 110  123   38]]


#### OLID

In [13]:
bert_hatebert_concat_olid_train_dev = np.concatenate((bert_hatebert_concat_olid_train, bert_hatebert_concat_olid_dev))
bert_hatebert_concat_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_concat_olid_train_dev, bert_hatebert_concat_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_concat_olid_train_dev)
test_preds = mlp.predict(bert_hatebert_concat_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_hatebert_concat_olid_seed_42")

save_model(mlp, "Saves/bert_hatebert_concat_olid_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7858761329305136
Accuracy Test:  0.8
Weighted F1 Train Dev:  0.7807450390150636
Weighted F1 Test:  0.7766864404032546
Macro F1 Train Dev:  0.7479651009077288
Macro F1 Test:  0.7003144348277092
Micro F1 Train Dev:  0.7858761329305136
Micro F1 Test:  0.8000000000000002
Weighted Recall Train Dev:  0.7858761329305136
Weighted Recall Test:  0.8
Macro Recall Train Dev:  0.738911456190868
Macro Recall Test:  0.6774193548387097
Micro Recall Train Dev:  0.7858761329305136
Micro Recall Test:  0.8
Confusion Matrix Train Dev: 
[[7770 1070]
 [1765 2635]]
Confusion Matrix Test: 
[[592  28]
 [144  96]]


### BERTweet-HateBERT

#### DynaHate

In [9]:
hatebert_bertweet_concat_dynahate_train_dev = np.concatenate((hatebert_bertweet_concat_dynahate_train, hatebert_bertweet_concat_dynahate_dev))
hatebert_bertweet_concat_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_concat_dynahate_train_dev, hatebert_bertweet_concat_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_concat_dynahate_train_dev)
test_preds = mlp.predict(hatebert_bertweet_concat_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/hatebert_bertweet_concat_dynahate_seed_42")

save_model(mlp, "Saves/hatebert_bertweet_concat_dynahate_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7467858686257562
Accuracy Test:  0.7058252427184466
Weighted F1 Train Dev:  0.7468912523768161
Weighted F1 Test:  0.7063030303474152
Macro F1 Train Dev:  0.7455608421258794
Macro F1 Test:  0.7038791321321599
Micro F1 Train Dev:  0.7467858686257564
Micro F1 Test:  0.7058252427184466
Weighted Recall Train Dev:  0.7467858686257562
Weighted Recall Test:  0.7058252427184466
Macro Recall Train Dev:  0.7457921330447608
Macro Recall Test:  0.7048255187204071
Micro Recall Train Dev:  0.7467858686257562
Micro Recall Test:  0.7058252427184466
Confusion Matrix Train Dev: 
[[12540  4577]
 [ 4798 15109]]
Confusion Matrix Test: 
[[1287  565]
 [ 647 1621]]


#### LatentHatred

In [10]:
hatebert_bertweet_concat_latenthatred_train_dev = np.concatenate((hatebert_bertweet_concat_latenthatred_train, hatebert_bertweet_concat_latenthatred_dev))
hatebert_bertweet_concat_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_concat_latenthatred_train_dev, hatebert_bertweet_concat_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_concat_latenthatred_train_dev)
test_preds = mlp.predict(hatebert_bertweet_concat_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/hatebert_bertweet_concat_latenthatred_seed_42")

save_model(mlp, "Saves/hatebert_bertweet_concat_latenthatred_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7227188081936685
Accuracy Test:  0.7048417132216015
Weighted F1 Train Dev:  0.7072609562233675
Weighted F1 Test:  0.6880549652177467
Macro F1 Train Dev:  0.5343230394255972
Macro F1 Test:  0.5127804634128582
Micro F1 Train Dev:  0.7227188081936685
Micro F1 Test:  0.7048417132216015
Weighted Recall Train Dev:  0.7227188081936685
Weighted Recall Test:  0.7048417132216015
Macro Recall Train Dev:  0.5148888838567683
Macro Recall Test:  0.49498714088611195
Micro Recall Train Dev:  0.7227188081936685
Micro Recall Test:  0.7048417132216015
Confusion Matrix Train Dev: 
[[8540 1362   43]
 [2289 3001   57]
 [ 288  428  102]]
Confusion Matrix Test: 
[[2850  480   16]
 [ 825  903   25]
 [ 107  132   32]]


#### OLID

In [11]:
hatebert_bertweet_concat_olid_train_dev = np.concatenate((hatebert_bertweet_concat_olid_train, hatebert_bertweet_concat_olid_dev))
hatebert_bertweet_concat_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_concat_olid_train_dev, hatebert_bertweet_concat_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_concat_olid_train_dev)
test_preds = mlp.predict(hatebert_bertweet_concat_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/hatebert_bertweet_concat_olid_seed_42")

save_model(mlp, "Saves/hatebert_bertweet_concat_olid_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7669939577039275
Accuracy Test:  0.813953488372093
Weighted F1 Train Dev:  0.7582615842128477
Weighted F1 Test:  0.8018262277206726
Macro F1 Train Dev:  0.719605813225416
Macro F1 Test:  0.7411899244635709
Micro F1 Train Dev:  0.7669939577039275
Micro F1 Test:  0.8139534883720931
Weighted Recall Train Dev:  0.7669939577039275
Weighted Recall Test:  0.813953488372093
Macro Recall Train Dev:  0.7088471822295351
Macro Recall Test:  0.7202956989247311
Micro Recall Train Dev:  0.7669939577039275
Micro Recall Test:  0.813953488372093
Confusion Matrix Train Dev: 
[[7799 1041]
 [2044 2356]]
Confusion Matrix Test: 
[[578  42]
 [118 122]]


### BERT-BERTweet-HateBERT

#### DynaHate

In [13]:
bert_bertweet_hatebert_concat_dynahate_train_dev = np.concatenate((bert_hatebert_bertweet_concat_dynahate_train, bert_hatebert_bertweet_concat_dynahate_dev))
bert_bertweet_hatebert_concat_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_concat_dynahate_train_dev, bert_bertweet_hatebert_concat_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_concat_dynahate_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_concat_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_bertweet_hatebert_concat_dynahate_seed_42")

save_model(mlp, "Saves/bert_bertweet_hatebert_concat_dynahate_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7431125756266206
Accuracy Test:  0.7033980582524272
Weighted F1 Train Dev:  0.7430087635096067
Weighted F1 Test:  0.7038885438208567
Macro F1 Train Dev:  0.7414431645557211
Macro F1 Test:  0.7014594724343485
Micro F1 Train Dev:  0.7431125756266206
Micro F1 Test:  0.7033980582524272
Weighted Recall Train Dev:  0.7431125756266206
Weighted Recall Test:  0.7033980582524272
Macro Recall Train Dev:  0.7412667933172068
Macro Recall Test:  0.7024228537907444
Micro Recall Train Dev:  0.7431125756266206
Micro Recall Test:  0.7033980582524272
Confusion Matrix Train Dev: 
[[12269  4848]
 [ 4663 15244]]
Confusion Matrix Test: 
[[1283  569]
 [ 653 1615]]


#### LatentHatred

In [14]:
bert_bertweet_hatebert_concat_latenthatred_train_dev = np.concatenate((bert_hatebert_bertweet_concat_latenthatred_train, bert_hatebert_bertweet_concat_latenthatred_dev))
bert_bertweet_hatebert_concat_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_concat_latenthatred_train_dev, bert_bertweet_hatebert_concat_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_concat_latenthatred_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_concat_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_bertweet_hatebert_concat_latenthatred_seed_42")

save_model(mlp, "Saves/bert_bertweet_hatebert_concat_latenthatred_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7289882060831782
Accuracy Test:  0.7042830540037244
Weighted F1 Train Dev:  0.7104670306803296
Weighted F1 Test:  0.6855481001372478
Macro F1 Train Dev:  0.5316360646827442
Macro F1 Test:  0.5107186664249862
Micro F1 Train Dev:  0.7289882060831782
Micro F1 Test:  0.7042830540037244
Weighted Recall Train Dev:  0.7289882060831782
Weighted Recall Test:  0.7042830540037244
Macro Recall Train Dev:  0.5122278478127743
Macro Recall Test:  0.4917913556060576
Micro Recall Train Dev:  0.7289882060831782
Micro Recall Test:  0.7042830540037244
Confusion Matrix Train Dev: 
[[8743 1167   35]
 [2381 2908   58]
 [ 333  392   93]]
Confusion Matrix Test: 
[[2879  451   16]
 [ 861  871   21]
 [ 111  128   32]]


#### OLID

In [15]:
bert_bertweet_hatebert_concat_olid_train_dev = np.concatenate((bert_hatebert_bertweet_concat_olid_train, bert_hatebert_bertweet_concat_olid_dev))
bert_bertweet_hatebert_concat_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_concat_olid_train_dev, bert_bertweet_hatebert_concat_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_concat_olid_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_concat_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_bertweet_hatebert_concat_olid_seed_42")

save_model(mlp, "Saves/bert_bertweet_hatebert_concat_olid_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7802114803625377
Accuracy Test:  0.8081395348837209
Weighted F1 Train Dev:  0.7730938625674014
Weighted F1 Test:  0.7936503352014264
Macro F1 Train Dev:  0.7376653614346593
Macro F1 Test:  0.7288750895629329
Micro F1 Train Dev:  0.7802114803625377
Micro F1 Test:  0.8081395348837209
Weighted Recall Train Dev:  0.7802114803625377
Weighted Recall Test:  0.8081395348837209
Macro Recall Train Dev:  0.7269071369806663
Macro Recall Test:  0.7073252688172043
Micro Recall Train Dev:  0.7802114803625377
Micro Recall Test:  0.8081395348837209
Confusion Matrix Train Dev: 
[[7831 1009]
 [1901 2499]]
Confusion Matrix Test: 
[[580  40]
 [125 115]]
