In [1]:
from utils import *
import numpy as np
import torch, os
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV

In [2]:
set_random_seed(7)

Seed: 7


In [3]:
# def scaling_embeddings(embeddings):
#     for i in range(len(embeddings)):
#         embeddings[i] = StandardScaler().fit_transform(embeddings[i])
#     return embeddings

def reshape_embeddings(embeddings):
    if embeddings.shape[1] == 1:
        embeddings = embeddings.squeeze(1)
    return embeddings

In [4]:
def concat_2_embeddings(embeddings1, embeddings2):
    embeddings1 = reshape_embeddings(embeddings1)
    embeddings2 = reshape_embeddings(embeddings2)
    # Numpy concat
    return np.concatenate((embeddings1, embeddings2), axis=1)

def concat_3_embeddings(embeddings1, embeddings2, embeddings3):
    embeddings1 = reshape_embeddings(embeddings1)
    embeddings2 = reshape_embeddings(embeddings2)
    embeddings3 = reshape_embeddings(embeddings3)
    return np.concatenate((embeddings1, embeddings2, embeddings3), axis=1)

In [5]:
bert_hatebert_concat_dynahate_train = concat_2_embeddings(bert_dynahate_train_embeddings, hatebert_dynahate_train_embeddings)
bert_hatebert_concat_dynahate_dev = concat_2_embeddings(bert_dynahate_dev_embeddings, hatebert_dynahate_dev_embeddings)
bert_hatebert_concat_dynahate_test = concat_2_embeddings(bert_dynahate_test_embeddings, hatebert_dynahate_test_embeddings)

bert_bertweet_concat_dynahate_train = concat_2_embeddings(bert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
bert_bertweet_concat_dynahate_dev = concat_2_embeddings(bert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
bert_bertweet_concat_dynahate_test = concat_2_embeddings(bert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

hatebert_bertweet_concat_dynahate_train = concat_2_embeddings(hatebert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
hatebert_bertweet_concat_dynahate_dev = concat_2_embeddings(hatebert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
hatebert_bertweet_concat_dynahate_test = concat_2_embeddings(hatebert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

bert_hatebert_bertweet_concat_dynahate_train = concat_3_embeddings(bert_dynahate_train_embeddings, hatebert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
bert_hatebert_bertweet_concat_dynahate_dev = concat_3_embeddings(bert_dynahate_dev_embeddings, hatebert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
bert_hatebert_bertweet_concat_dynahate_test = concat_3_embeddings(bert_dynahate_test_embeddings, hatebert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

bert_hatebert_concat_olid_train = concat_2_embeddings(bert_olid_train_embeddings, hatebert_olid_train_embeddings)
bert_hatebert_concat_olid_dev = concat_2_embeddings(bert_olid_dev_embeddings, hatebert_olid_dev_embeddings)
bert_hatebert_concat_olid_test = concat_2_embeddings(bert_olid_test_embeddings, hatebert_olid_test_embeddings)

bert_bertweet_concat_olid_train = concat_2_embeddings(bert_olid_train_embeddings, bertweet_olid_train_embeddings)
bert_bertweet_concat_olid_dev = concat_2_embeddings(bert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
bert_bertweet_concat_olid_test = concat_2_embeddings(bert_olid_test_embeddings, bertweet_olid_test_embeddings)

hatebert_bertweet_concat_olid_train = concat_2_embeddings(hatebert_olid_train_embeddings, bertweet_olid_train_embeddings)
hatebert_bertweet_concat_olid_dev = concat_2_embeddings(hatebert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
hatebert_bertweet_concat_olid_test = concat_2_embeddings(hatebert_olid_test_embeddings, bertweet_olid_test_embeddings)

bert_hatebert_bertweet_concat_olid_train = concat_3_embeddings(bert_olid_train_embeddings, hatebert_olid_train_embeddings, bertweet_olid_train_embeddings)
bert_hatebert_bertweet_concat_olid_dev = concat_3_embeddings(bert_olid_dev_embeddings, hatebert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
bert_hatebert_bertweet_concat_olid_test = concat_3_embeddings(bert_olid_test_embeddings, hatebert_olid_test_embeddings, bertweet_olid_test_embeddings)

bert_hatebert_concat_latenthatred_train = concat_2_embeddings(bert_latenthatred_train_embeddings, hatebert_latenthatred_train_embeddings)
bert_hatebert_concat_latenthatred_dev = concat_2_embeddings(bert_latenthatred_dev_embeddings, hatebert_latenthatred_dev_embeddings)
bert_hatebert_concat_latenthatred_test = concat_2_embeddings(bert_latenthatred_test_embeddings, hatebert_latenthatred_test_embeddings)

bert_bertweet_concat_latenthatred_train = concat_2_embeddings(bert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
bert_bertweet_concat_latenthatred_dev = concat_2_embeddings(bert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
bert_bertweet_concat_latenthatred_test = concat_2_embeddings(bert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

hatebert_bertweet_concat_latenthatred_train = concat_2_embeddings(hatebert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
hatebert_bertweet_concat_latenthatred_dev = concat_2_embeddings(hatebert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
hatebert_bertweet_concat_latenthatred_test = concat_2_embeddings(hatebert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

bert_hatebert_bertweet_concat_latenthatred_train = concat_3_embeddings(bert_latenthatred_train_embeddings, hatebert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
bert_hatebert_bertweet_concat_latenthatred_dev = concat_3_embeddings(bert_latenthatred_dev_embeddings, hatebert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
bert_hatebert_bertweet_concat_latenthatred_test = concat_3_embeddings(bert_latenthatred_test_embeddings, hatebert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

In [6]:
dynahate_labels_train = process_labels(read_labels("dynahate", "train"))
dynahate_labels_dev = process_labels(read_labels("dynahate", "dev"))
dynahate_labels_test = process_labels(read_labels("dynahate", "test"))

latenthatred_labels_train = read_labels("latenthatred", "train")
latenthatred_labels_dev = read_labels("latenthatred", "dev")
latenthatred_labels_test = read_labels("latenthatred", "test")

olid_labels_train = read_labels("olid", "train")
olid_labels_dev = read_labels("olid", "dev")
olid_labels_test = read_labels("olid", "test")

In [7]:
mlp = MLPClassifier(random_state=7)
gridsearch = GridSearchCV(
    mlp,
    param_grid={
        "hidden_layer_sizes": [(128), (128,64)],
        "activation": ["relu"],
        "solver": ["adam"],
        "learning_rate_init": [0.001, 0.0001],
        "learning_rate": ["adaptive"],
        "early_stopping": [True],
        "max_iter": [10000]
    },
    verbose=4,
    n_jobs=os.cpu_count()//3,
    cv=5,
)

In [8]:
dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))
latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))
olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

### BERT-BERTweet

#### DynaHate

In [9]:
bert_bertweet_concat_dynahate_train_dev = np.concatenate((bert_bertweet_concat_dynahate_train, bert_bertweet_concat_dynahate_dev))
bert_bertweet_concat_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_concat_dynahate_train_dev, bert_bertweet_concat_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_concat_dynahate_train_dev)
test_preds = mlp.predict(bert_bertweet_concat_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_bertweet_concat_dynahate_seed_7")
save_model(mlp, "Saves/bert_bertweet_concat_dynahate_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.6930639585133967
Accuracy Test:  0.6643203883495146
Weighted F1 Train Dev:  0.6889238428969063
Weighted F1 Test:  0.659219421651573
Macro F1 Train Dev:  0.6851662233230584
Macro F1 Test:  0.6528470428337239
Micro F1 Train Dev:  0.6930639585133967
Micro F1 Test:  0.6643203883495146
Weighted Recall Train Dev:  0.6930639585133967
Weighted Recall Test:  0.6643203883495146
Macro Recall Train Dev:  0.6850186603671318
Macro Recall Test:  0.6526177905767538
Micro Recall Train Dev:  0.6930639585133967
Micro Recall Test:  0.6643203883495146
Confusion Matrix Train Dev: 
[[ 9898  7219]
 [ 4145 15762]]
Confusion Matrix Test: 
[[ 994  858]
 [ 525 1743]]


#### LatentHatred

In [10]:
bert_bertweet_concat_latenthatred_train_dev = np.concatenate((bert_bertweet_concat_latenthatred_train, bert_bertweet_concat_latenthatred_dev))
bert_bertweet_concat_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_concat_latenthatred_train_dev, bert_bertweet_concat_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_concat_latenthatred_train_dev)
test_preds = mlp.predict(bert_bertweet_concat_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_bertweet_concat_latenthatred_seed_7")
save_model(mlp, "Saves/bert_bertweet_concat_latenthatred_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7037864680322781
Accuracy Test:  0.6949720670391062
Weighted F1 Train Dev:  0.6719729008101402
Weighted F1 Test:  0.6597402541673847
Macro F1 Train Dev:  0.46249873677724196
Macro F1 Test:  0.4473027273200441
Micro F1 Train Dev:  0.7037864680322781
Micro F1 Test:  0.6949720670391062
Weighted Recall Train Dev:  0.7037864680322781
Weighted Recall Test:  0.6949720670391062
Macro Recall Train Dev:  0.4584016043001567
Macro Recall Test:  0.44483418305840733
Micro Recall Train Dev:  0.7037864680322781
Micro Recall Test:  0.6949720670391062
Confusion Matrix Train Dev: 
[[8942  992   11]
 [2966 2369   12]
 [ 442  349   27]]
Confusion Matrix Test: 
[[3017  328    1]
 [1041  707    5]
 [ 143  120    8]]


#### OLID

In [11]:
bert_bertweet_concat_olid_train_dev = np.concatenate((bert_bertweet_concat_olid_train, bert_bertweet_concat_olid_dev))
bert_bertweet_concat_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_concat_olid_train_dev, bert_bertweet_concat_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_concat_olid_train_dev)
test_preds = mlp.predict(bert_bertweet_concat_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_bertweet_concat_olid_seed_7")

save_model(mlp, "Saves/bert_bertweet_concat_olid_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7719788519637463
Accuracy Test:  0.8162790697674419
Weighted F1 Train Dev:  0.7651286465424271
Weighted F1 Test:  0.8021860760685957
Macro F1 Train Dev:  0.7288772614760904
Macro F1 Test:  0.739914708562066
Micro F1 Train Dev:  0.7719788519637462
Micro F1 Test:  0.8162790697674419
Weighted Recall Train Dev:  0.7719788519637463
Weighted Recall Test:  0.8162790697674419
Macro Recall Train Dev:  0.7191438708350473
Macro Recall Test:  0.7168010752688172
Micro Recall Train Dev:  0.7719788519637463
Micro Recall Test:  0.8162790697674419
Confusion Matrix Train Dev: 
[[7750 1090]
 [1929 2471]]
Confusion Matrix Test: 
[[584  36]
 [122 118]]


### BERT-HateBERT

#### DynaHate

In [12]:
bert_hatebert_concat_dynahate_train_dev = np.concatenate((bert_hatebert_concat_dynahate_train, bert_hatebert_concat_dynahate_dev))
bert_hatebert_concat_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_concat_dynahate_train_dev, bert_hatebert_concat_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_concat_dynahate_train_dev)
test_preds = mlp.predict(bert_hatebert_concat_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_hatebert_concat_dynahate_seed_7")

save_model(mlp, "Saves/bert_hatebert_concat_dynahate_seed_7")


Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7330650388936906
Accuracy Test:  0.6990291262135923
Weighted F1 Train Dev:  0.7303935024877725
Weighted F1 Test:  0.6962307600298425
Macro F1 Train Dev:  0.7274439233138464
Macro F1 Test:  0.6912980467567924
Micro F1 Train Dev:  0.7330650388936906
Micro F1 Test:  0.6990291262135923
Weighted Recall Train Dev:  0.7330650388936906
Weighted Recall Test:  0.6990291262135923
Macro Recall Train Dev:  0.7263678790843157
Macro Recall Test:  0.6900857455213107
Micro Recall Train Dev:  0.7330650388936906
Micro Recall Test:  0.6990291262135923
Confusion Matrix Train Dev: 
[[10912  6205]
 [ 3678 16229]]
Confusion Matrix Test: 
[[1114  738]
 [ 502 1766]]


#### LatentHatred

In [13]:
bert_hatebert_concat_latenthatred_train_dev = np.concatenate((bert_hatebert_concat_latenthatred_train, bert_hatebert_concat_latenthatred_dev))
bert_hatebert_concat_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_concat_latenthatred_train_dev, bert_hatebert_concat_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_concat_latenthatred_train_dev)
test_preds = mlp.predict(bert_hatebert_concat_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_hatebert_concat_latenthatred_seed_7")

save_model(mlp, "Saves/bert_hatebert_concat_latenthatred_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.6980757293606455
Accuracy Test:  0.6893854748603352
Weighted F1 Train Dev:  0.6626336263595646
Weighted F1 Test:  0.6506618387495098
Macro F1 Train Dev:  0.48464289170510505
Macro F1 Test:  0.46431753731155334
Micro F1 Train Dev:  0.6980757293606455
Micro F1 Test:  0.6893854748603352
Weighted Recall Train Dev:  0.6980757293606455
Weighted Recall Test:  0.6893854748603352
Macro Recall Train Dev:  0.46755289076842615
Macro Recall Test:  0.4516471914149458
Micro Recall Train Dev:  0.6980757293606455
Micro Recall Test:  0.6893854748603352
Confusion Matrix Train Dev: 
[[9156  758   31]
 [3275 2002   70]
 [ 427  303   88]]
Confusion Matrix Test: 
[[3074  258   14]
 [1124  603   26]
 [ 151   95   25]]


#### OLID

In [14]:
bert_hatebert_concat_olid_train_dev = np.concatenate((bert_hatebert_concat_olid_train, bert_hatebert_concat_olid_dev))
bert_hatebert_concat_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_concat_olid_train_dev, bert_hatebert_concat_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_concat_olid_train_dev)
test_preds = mlp.predict(bert_hatebert_concat_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_hatebert_concat_olid_seed_7")

save_model(mlp, "Saves/bert_hatebert_concat_olid_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7692598187311178
Accuracy Test:  0.7941860465116279
Weighted F1 Train Dev:  0.7601741571776652
Weighted F1 Test:  0.7739632222552065
Macro F1 Train Dev:  0.721496940209948
Macro F1 Test:  0.6993547444159816
Micro F1 Train Dev:  0.7692598187311178
Micro F1 Test:  0.7941860465116279
Weighted Recall Train Dev:  0.7692598187311178
Weighted Recall Test:  0.7941860465116279
Macro Recall Train Dev:  0.710258638420403
Macro Recall Test:  0.678494623655914
Micro Recall Train Dev:  0.7692598187311178
Micro Recall Test:  0.7941860465116279
Confusion Matrix Train Dev: 
[[7834 1006]
 [2049 2351]]
Confusion Matrix Test: 
[[583  37]
 [140 100]]


### BERTweet-HateBERT

#### DynaHate

In [15]:
hatebert_bertweet_concat_dynahate_train_dev = np.concatenate((hatebert_bertweet_concat_dynahate_train, hatebert_bertweet_concat_dynahate_dev))
hatebert_bertweet_concat_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_concat_dynahate_train_dev, hatebert_bertweet_concat_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_concat_dynahate_train_dev)
test_preds = mlp.predict(hatebert_bertweet_concat_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/hatebert_bertweet_concat_dynahate_seed_7")

save_model(mlp, "Saves/hatebert_bertweet_concat_dynahate_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.746542783059637
Accuracy Test:  0.7075242718446602
Weighted F1 Train Dev:  0.7449912898567735
Weighted F1 Test:  0.7060459283763534
Macro F1 Train Dev:  0.742586475392335
Macro F1 Test:  0.7019184727869867
Micro F1 Train Dev:  0.7465427830596371
Micro F1 Test:  0.7075242718446602
Weighted Recall Train Dev:  0.746542783059637
Weighted Recall Test:  0.7075242718446602
Macro Recall Train Dev:  0.741410739819814
Macro Recall Test:  0.7008225056281212
Micro Recall Train Dev:  0.746542783059637
Micro Recall Test:  0.7075242718446602
Confusion Matrix Train Dev: 
[[11525  5592]
 [ 3792 16115]]
Confusion Matrix Test: 
[[1175  677]
 [ 528 1740]]


#### LatentHatred

In [13]:
hatebert_bertweet_concat_latenthatred_train_dev = np.concatenate((hatebert_bertweet_concat_latenthatred_train, hatebert_bertweet_concat_latenthatred_dev))
hatebert_bertweet_concat_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_concat_latenthatred_train_dev, hatebert_bertweet_concat_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_concat_latenthatred_train_dev)
test_preds = mlp.predict(hatebert_bertweet_concat_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/hatebert_bertweet_concat_latenthatred_seed_7")

save_model(mlp, "Saves/hatebert_bertweet_concat_latenthatred_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7121663563004346
Accuracy Test:  0.6951582867783985
Weighted F1 Train Dev:  0.6822338779187935
Weighted F1 Test:  0.6610959299216783
Macro F1 Train Dev:  0.4742761381424028
Macro F1 Test:  0.44255708316619535
Micro F1 Train Dev:  0.7121663563004346
Micro F1 Test:  0.6951582867783985
Weighted Recall Train Dev:  0.7121663563004346
Weighted Recall Test:  0.6951582867783985
Macro Recall Train Dev:  0.46822627871811906
Macro Recall Test:  0.44335320751495616
Micro Recall Train Dev:  0.7121663563004346
Micro Recall Test:  0.6951582867783985
Confusion Matrix Train Dev: 
[[8953  982   10]
 [2854 2488    5]
 [ 392  394   32]]
Confusion Matrix Test: 
[[3001  338    7]
 [1022  727    4]
 [ 134  132    5]]


#### OLID

In [12]:
hatebert_bertweet_concat_olid_train_dev = np.concatenate((hatebert_bertweet_concat_olid_train, hatebert_bertweet_concat_olid_dev))
hatebert_bertweet_concat_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_concat_olid_train_dev, hatebert_bertweet_concat_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_concat_olid_train_dev)
test_preds = mlp.predict(hatebert_bertweet_concat_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/hatebert_bertweet_concat_olid_seed_7")

save_model(mlp, "Saves/hatebert_bertweet_concat_olid_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7808912386706949
Accuracy Test:  0.7988372093023256
Weighted F1 Train Dev:  0.7728645070903745
Weighted F1 Test:  0.7836455029687682
Macro F1 Train Dev:  0.7366830977333971
Macro F1 Test:  0.7157296393599235
Micro F1 Train Dev:  0.7808912386706949
Micro F1 Test:  0.7988372093023256
Weighted Recall Train Dev:  0.7808912386706949
Weighted Recall Test:  0.7988372093023256
Macro Recall Train Dev:  0.7250190250925546
Macro Recall Test:  0.6957661290322581
Micro Recall Train Dev:  0.7808912386706949
Micro Recall Test:  0.7988372093023256
Confusion Matrix Train Dev: 
[[7882  958]
 [1943 2457]]
Confusion Matrix Test: 
[[576  44]
 [129 111]]


### BERT-BERTweet-HateBERT

#### DynaHate

In [11]:
bert_bertweet_hatebert_concat_dynahate_train_dev = np.concatenate((bert_hatebert_bertweet_concat_dynahate_train, bert_hatebert_bertweet_concat_dynahate_dev))
bert_bertweet_hatebert_concat_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_concat_dynahate_train_dev, bert_bertweet_hatebert_concat_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_concat_dynahate_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_concat_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_bertweet_hatebert_concat_dynahate_seed_7")

save_model(mlp, "Saves/bert_bertweet_hatebert_concat_dynahate_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7464347450302506
Accuracy Test:  0.7048543689320388
Weighted F1 Train Dev:  0.7436027907962717
Weighted F1 Test:  0.7023928932461856
Macro F1 Train Dev:  0.7406958179070879
Macro F1 Test:  0.6976957653318968
Micro F1 Train Dev:  0.7464347450302505
Micro F1 Test:  0.7048543689320388
Weighted Recall Train Dev:  0.7464347450302506
Weighted Recall Test:  0.7048543689320388
Macro Recall Train Dev:  0.7394229694926063
Macro Recall Test:  0.6964166676189715
Micro Recall Train Dev:  0.7464347450302506
Micro Recall Test:  0.7048543689320388
Confusion Matrix Train Dev: 
[[11064  6053]
 [ 3335 16572]]
Confusion Matrix Test: 
[[1135  717]
 [ 499 1769]]


#### LatentHatred

In [10]:
bert_bertweet_hatebert_concat_latenthatred_train_dev = np.concatenate((bert_hatebert_bertweet_concat_latenthatred_train, bert_hatebert_bertweet_concat_latenthatred_dev))
bert_bertweet_hatebert_concat_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_concat_latenthatred_train_dev, bert_bertweet_hatebert_concat_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_concat_latenthatred_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_concat_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_bertweet_hatebert_concat_latenthatred_seed_7")

save_model(mlp, "Saves/bert_bertweet_hatebert_concat_latenthatred_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.716139044072005
Accuracy Test:  0.7018621973929237
Weighted F1 Train Dev:  0.7025819285794722
Weighted F1 Test:  0.6874450592515028
Macro F1 Train Dev:  0.544814954720557
Macro F1 Test:  0.5346778759197685
Micro F1 Train Dev:  0.716139044072005
Micro F1 Test:  0.7018621973929237
Weighted Recall Train Dev:  0.716139044072005
Weighted Recall Test:  0.7018621973929237
Macro Recall Train Dev:  0.5241011396766605
Macro Recall Test:  0.5121547608355986
Micro Recall Train Dev:  0.716139044072005
Micro Recall Test:  0.7018621973929237
Confusion Matrix Train Dev: 
[[8530 1332   83]
 [2359 2860  128]
 [ 301  370  147]]
Confusion Matrix Test: 
[[2845  479   22]
 [ 839  873   41]
 [  94  126   51]]


#### OLID

In [9]:
bert_bertweet_hatebert_concat_olid_train_dev = np.concatenate((bert_hatebert_bertweet_concat_olid_train, bert_hatebert_bertweet_concat_olid_dev))
bert_bertweet_hatebert_concat_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_concat_olid_train_dev, bert_bertweet_hatebert_concat_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_concat_olid_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_concat_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_bertweet_hatebert_concat_olid_seed_7")

save_model(mlp, "Saves/bert_bertweet_hatebert_concat_olid_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7768126888217523
Accuracy Test:  0.8034883720930233
Weighted F1 Train Dev:  0.7715007940322363
Weighted F1 Test:  0.7908967947521313
Macro F1 Train Dev:  0.7373693716509757
Macro F1 Test:  0.7270994695582782
Micro F1 Train Dev:  0.7768126888217523
Micro F1 Test:  0.8034883720930233
Weighted Recall Train Dev:  0.7768126888217523
Weighted Recall Test:  0.8034883720930233
Macro Recall Train Dev:  0.7288137597696421
Macro Recall Test:  0.7079301075268817
Micro Recall Train Dev:  0.7768126888217523
Micro Recall Test:  0.8034883720930233
Confusion Matrix Train Dev: 
[[7708 1132]
 [1823 2577]]
Confusion Matrix Test: 
[[573  47]
 [122 118]]
