In [4]:
from utils import *
import numpy as np
import torch, os
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV

In [5]:
set_random_seed(42)

Seed: 42


In [6]:
# def scaling_embeddings(embeddings):
#     for i in range(len(embeddings)):
#         embeddings[i] = StandardScaler().fit_transform(embeddings[i])
#     return embeddings

def reshape_embeddings(embeddings):
    if embeddings.shape[1] == 1:
        embeddings = embeddings.squeeze(1)
    return embeddings

In [7]:
def interleave_2_embeddings(embeddings1, embeddings2):
    embeddings1 = reshape_embeddings(embeddings1)
    embeddings2 = reshape_embeddings(embeddings2)
    new_embeddings = []
    for i in range(len(embeddings1)):
        embedding = []
        for j in range(len(embeddings1[i])):
            embedding.append(embeddings1[i][j])
            embedding.append(embeddings2[i][j])
        new_embeddings.append(np.array(embedding))
    return np.array(new_embeddings)
    

def interleave_3_embeddings(embeddings1, embeddings2, embeddings3):
    embeddings1 = reshape_embeddings(embeddings1)
    embeddings2 = reshape_embeddings(embeddings2)
    embeddings3 = reshape_embeddings(embeddings3)
    new_embeddings = []
    for i in range(len(embeddings1)):
        embedding = []
        for j in range(len(embeddings1[i])):
            embedding.append(embeddings1[i][j])
            embedding.append(embeddings2[i][j])
            embedding.append(embeddings3[i][j])
        new_embeddings.append(np.array(embedding))
    return np.array(new_embeddings)

In [8]:
bert_hatebert_interleaved_dynahate_train = interleave_2_embeddings(bert_dynahate_train_embeddings, hatebert_dynahate_train_embeddings)
bert_hatebert_interleaved_dynahate_dev = interleave_2_embeddings(bert_dynahate_dev_embeddings, hatebert_dynahate_dev_embeddings)
bert_hatebert_interleaved_dynahate_test = interleave_2_embeddings(bert_dynahate_test_embeddings, hatebert_dynahate_test_embeddings)

bert_bertweet_interleaved_dynahate_train = interleave_2_embeddings(bert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
bert_bertweet_interleaved_dynahate_dev = interleave_2_embeddings(bert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
bert_bertweet_interleaved_dynahate_test = interleave_2_embeddings(bert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

hatebert_bertweet_interleaved_dynahate_train = interleave_2_embeddings(hatebert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
hatebert_bertweet_interleaved_dynahate_dev = interleave_2_embeddings(hatebert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
hatebert_bertweet_interleaved_dynahate_test = interleave_2_embeddings(hatebert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

bert_hatebert_bertweet_interleaved_dynahate_train = interleave_3_embeddings(bert_dynahate_train_embeddings, hatebert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
bert_hatebert_bertweet_interleaved_dynahate_dev = interleave_3_embeddings(bert_dynahate_dev_embeddings, hatebert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
bert_hatebert_bertweet_interleaved_dynahate_test = interleave_3_embeddings(bert_dynahate_test_embeddings, hatebert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

bert_hatebert_interleaved_olid_train = interleave_2_embeddings(bert_olid_train_embeddings, hatebert_olid_train_embeddings)
bert_hatebert_interleaved_olid_dev = interleave_2_embeddings(bert_olid_dev_embeddings, hatebert_olid_dev_embeddings)
bert_hatebert_interleaved_olid_test = interleave_2_embeddings(bert_olid_test_embeddings, hatebert_olid_test_embeddings)

bert_bertweet_interleaved_olid_train = interleave_2_embeddings(bert_olid_train_embeddings, bertweet_olid_train_embeddings)
bert_bertweet_interleaved_olid_dev = interleave_2_embeddings(bert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
bert_bertweet_interleaved_olid_test = interleave_2_embeddings(bert_olid_test_embeddings, bertweet_olid_test_embeddings)

hatebert_bertweet_interleaved_olid_train = interleave_2_embeddings(hatebert_olid_train_embeddings, bertweet_olid_train_embeddings)
hatebert_bertweet_interleaved_olid_dev = interleave_2_embeddings(hatebert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
hatebert_bertweet_interleaved_olid_test = interleave_2_embeddings(hatebert_olid_test_embeddings, bertweet_olid_test_embeddings)

bert_hatebert_bertweet_interleaved_olid_train = interleave_3_embeddings(bert_olid_train_embeddings, hatebert_olid_train_embeddings, bertweet_olid_train_embeddings)
bert_hatebert_bertweet_interleaved_olid_dev = interleave_3_embeddings(bert_olid_dev_embeddings, hatebert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
bert_hatebert_bertweet_interleaved_olid_test = interleave_3_embeddings(bert_olid_test_embeddings, hatebert_olid_test_embeddings, bertweet_olid_test_embeddings)

bert_hatebert_interleaved_latenthatred_train = interleave_2_embeddings(bert_latenthatred_train_embeddings, hatebert_latenthatred_train_embeddings)
bert_hatebert_interleaved_latenthatred_dev = interleave_2_embeddings(bert_latenthatred_dev_embeddings, hatebert_latenthatred_dev_embeddings)
bert_hatebert_interleaved_latenthatred_test = interleave_2_embeddings(bert_latenthatred_test_embeddings, hatebert_latenthatred_test_embeddings)

bert_bertweet_interleaved_latenthatred_train = interleave_2_embeddings(bert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
bert_bertweet_interleaved_latenthatred_dev = interleave_2_embeddings(bert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
bert_bertweet_interleaved_latenthatred_test = interleave_2_embeddings(bert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

hatebert_bertweet_interleaved_latenthatred_train = interleave_2_embeddings(hatebert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
hatebert_bertweet_interleaved_latenthatred_dev = interleave_2_embeddings(hatebert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
hatebert_bertweet_interleaved_latenthatred_test = interleave_2_embeddings(hatebert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

bert_hatebert_bertweet_interleaved_latenthatred_train = interleave_3_embeddings(bert_latenthatred_train_embeddings, hatebert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
bert_hatebert_bertweet_interleaved_latenthatred_dev = interleave_3_embeddings(bert_latenthatred_dev_embeddings, hatebert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
bert_hatebert_bertweet_interleaved_latenthatred_test = interleave_3_embeddings(bert_latenthatred_test_embeddings, hatebert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

In [9]:
bert_hatebert_bertweet_interleaved_latenthatred_test.shape

(5370, 2304)

In [10]:
dynahate_labels_train = process_labels(read_labels("dynahate", "train"))
dynahate_labels_dev = process_labels(read_labels("dynahate", "dev"))
dynahate_labels_test = process_labels(read_labels("dynahate", "test"))

latenthatred_labels_train = read_labels("latenthatred", "train")
latenthatred_labels_dev = read_labels("latenthatred", "dev")
latenthatred_labels_test = read_labels("latenthatred", "test")

olid_labels_train = read_labels("olid", "train")
olid_labels_dev = read_labels("olid", "dev")
olid_labels_test = read_labels("olid", "test")

In [11]:
mlp = MLPClassifier(random_state=42)
gridsearch = GridSearchCV(
    mlp,
    param_grid={
        "hidden_layer_sizes": [(128), (128,64)],
        "activation": ["relu"],
        "solver": ["adam"],
        "learning_rate_init": [0.001, 0.0001],
        "learning_rate": ["adaptive"],
        "early_stopping": [True],
        "max_iter": [10000]
    },
    verbose=4,
    n_jobs=os.cpu_count()//3,
    cv=5,
)

In [12]:
dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))
latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))
olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

### BERT-BERTweet

#### DynaHate

In [13]:
bert_bertweet_interleaved_dynahate_train_dev = np.concatenate((bert_bertweet_interleaved_dynahate_train, bert_bertweet_interleaved_dynahate_dev))
bert_bertweet_interleaved_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_interleaved_dynahate_train_dev, bert_bertweet_interleaved_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_interleaved_dynahate_train_dev)
test_preds = mlp.predict(bert_bertweet_interleaved_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_bertweet_interleaved_dynahate")
save_model(mlp, "Saves/bert_bertweet_interleaved_dynahate")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.6999783923941227
Accuracy Test:  0.6716019417475728
Weighted F1 Train Dev:  0.6967974667355011
Weighted F1 Test:  0.668637336275552
Macro F1 Train Dev:  0.6934178846381844
Macro F1 Test:  0.6632984796679301
Micro F1 Train Dev:  0.6999783923941227
Micro F1 Test:  0.6716019417475728
Weighted Recall Train Dev:  0.6999783923941227
Weighted Recall Test:  0.6716019417475728
Macro Recall Train Dev:  0.6928896238455831
Macro Recall Test:  0.6624998571542848
Micro Recall Train Dev:  0.6999783923941227
Micro Recall Test:  0.6716019417475728
Confusion Matrix Train Dev: 
[[10250  6867]
 [ 4241 15666]]
Confusion Matrix Test: 
[[1060  792]
 [ 561 1707]]


#### LatentHatred

In [14]:
bert_bertweet_interleaved_latenthatred_train_dev = np.concatenate((bert_bertweet_interleaved_latenthatred_train, bert_bertweet_interleaved_latenthatred_dev))
bert_bertweet_interleaved_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_interleaved_latenthatred_train_dev, bert_bertweet_interleaved_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_interleaved_latenthatred_train_dev)
test_preds = mlp.predict(bert_bertweet_interleaved_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_bertweet_interleaved_latenthatred")
save_model(mlp, "Saves/bert_bertweet_interleaved_latenthatred")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.701179391682185
Accuracy Test:  0.6929236499068901
Weighted F1 Train Dev:  0.6810574215026872
Weighted F1 Test:  0.6711162653545641
Macro F1 Train Dev:  0.5020757024241409
Macro F1 Test:  0.4898922204008634
Micro F1 Train Dev:  0.701179391682185
Micro F1 Test:  0.6929236499068901
Weighted Recall Train Dev:  0.701179391682185
Weighted Recall Test:  0.6929236499068901
Macro Recall Train Dev:  0.48571956524684956
Macro Recall Test:  0.474268651618655
Micro Recall Train Dev:  0.701179391682185
Micro Recall Test:  0.6929236499068901
Confusion Matrix Train Dev: 
[[8562 1336   47]
 [2639 2652   56]
 [ 375  361   82]]
Confusion Matrix Test: 
[[2887  441   18]
 [ 925  807   21]
 [ 113  131   27]]


#### OLID

In [15]:
bert_bertweet_interleaved_olid_train_dev = np.concatenate((bert_bertweet_interleaved_olid_train, bert_bertweet_interleaved_olid_dev))
bert_bertweet_interleaved_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_interleaved_olid_train_dev, bert_bertweet_interleaved_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_interleaved_olid_train_dev)
test_preds = mlp.predict(bert_bertweet_interleaved_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_bertweet_interleaved_olid")

save_model(mlp, "Saves/bert_bertweet_interleaved_olid")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7703172205438067
Accuracy Test:  0.8127906976744186
Weighted F1 Train Dev:  0.7667525201495531
Weighted F1 Test:  0.8060487292454637
Macro F1 Train Dev:  0.7335716611338601
Macro F1 Test:  0.7515391972666798
Micro F1 Train Dev:  0.7703172205438068
Micro F1 Test:  0.8127906976744185
Weighted Recall Train Dev:  0.7703172205438067
Weighted Recall Test:  0.8127906976744186
Macro Recall Train Dev:  0.7276023241464418
Macro Recall Test:  0.7373655913978494
Micro Recall Train Dev:  0.7703172205438067
Micro Recall Test:  0.8127906976744186
Confusion Matrix Train Dev: 
[[7558 1282]
 [1759 2641]]
Confusion Matrix Test: 
[[563  57]
 [104 136]]


### BERT-HateBERT

#### DynaHate

In [16]:
bert_hatebert_interleaved_dynahate_train_dev = np.concatenate((bert_hatebert_interleaved_dynahate_train, bert_hatebert_interleaved_dynahate_dev))
bert_hatebert_interleaved_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_interleaved_dynahate_train_dev, bert_hatebert_interleaved_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_interleaved_dynahate_train_dev)
test_preds = mlp.predict(bert_hatebert_interleaved_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_hatebert_interleaved_dynahate")

save_model(mlp, "Saves/bert_hatebert_interleaved_dynahate")



Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.725340319792567
Accuracy Test:  0.6924757281553398
Weighted F1 Train Dev:  0.7224466339807245
Weighted F1 Test:  0.6897325318831925
Macro F1 Train Dev:  0.7193592980667511
Macro F1 Test:  0.6847492583058421
Micro F1 Train Dev:  0.725340319792567
Micro F1 Test:  0.6924757281553398
Weighted Recall Train Dev:  0.725340319792567
Weighted Recall Test:  0.6924757281553398
Macro Recall Train Dev:  0.7184189107732095
Macro Recall Test:  0.68363816608957
Micro Recall Train Dev:  0.725340319792567
Micro Recall Test:  0.6924757281553398
Confusion Matrix Train Dev: 
[[10725  6392]
 [ 3777 16130]]
Confusion Matrix Test: 
[[1104  748]
 [ 519 1749]]


#### LatentHatred

In [17]:
bert_hatebert_interleaved_latenthatred_train_dev = np.concatenate((bert_hatebert_interleaved_latenthatred_train, bert_hatebert_interleaved_latenthatred_dev))
bert_hatebert_interleaved_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_interleaved_latenthatred_train_dev, bert_hatebert_interleaved_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_interleaved_latenthatred_train_dev)
test_preds = mlp.predict(bert_hatebert_interleaved_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_hatebert_interleaved_latenthatred")

save_model(mlp, "Saves/bert_hatebert_interleaved_latenthatred")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7182495344506518
Accuracy Test:  0.6953445065176909
Weighted F1 Train Dev:  0.6977789109430059
Weighted F1 Test:  0.6719198234899995
Macro F1 Train Dev:  0.5219180001905266
Macro F1 Test:  0.48814001219909375
Micro F1 Train Dev:  0.7182495344506518
Micro F1 Test:  0.6953445065176909
Weighted Recall Train Dev:  0.7182495344506518
Weighted Recall Test:  0.6953445065176909
Macro Recall Train Dev:  0.5017009608571709
Macro Recall Test:  0.4726692471354384
Micro Recall Train Dev:  0.7182495344506518
Micro Recall Test:  0.6953445065176909
Confusion Matrix Train Dev: 
[[8758 1150   37]
 [2574 2718   55]
 [ 342  381   95]]
Confusion Matrix Test: 
[[2909  422   15]
 [ 936  800   17]
 [ 124  122   25]]


#### OLID

In [18]:
bert_hatebert_interleaved_olid_train_dev = np.concatenate((bert_hatebert_interleaved_olid_train, bert_hatebert_interleaved_olid_dev))
bert_hatebert_interleaved_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_interleaved_olid_train_dev, bert_hatebert_interleaved_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_interleaved_olid_train_dev)
test_preds = mlp.predict(bert_hatebert_interleaved_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_hatebert_interleaved_olid")

save_model(mlp, "Saves/bert_hatebert_interleaved_olid")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7608006042296073
Accuracy Test:  0.7965116279069767
Weighted F1 Train Dev:  0.759814110894104
Weighted F1 Test:  0.7834730123172956
Macro F1 Train Dev:  0.7283031007528467
Macro F1 Test:  0.7174106933295781
Micro F1 Train Dev:  0.7608006042296073
Micro F1 Test:  0.7965116279069767
Weighted Recall Train Dev:  0.7608006042296073
Weighted Recall Test:  0.7965116279069767
Macro Recall Train Dev:  0.7265256067461949
Macro Recall Test:  0.699260752688172
Micro Recall Train Dev:  0.7608006042296073
Micro Recall Test:  0.7965116279069767
Confusion Matrix Train Dev: 
[[7326 1514]
 [1653 2747]]
Confusion Matrix Test: 
[[570  50]
 [125 115]]


### BERTweet-HateBERT

#### DynaHate

In [19]:
hatebert_bertweet_interleaved_dynahate_train_dev = np.concatenate((hatebert_bertweet_interleaved_dynahate_train, hatebert_bertweet_interleaved_dynahate_dev))
hatebert_bertweet_interleaved_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_interleaved_dynahate_train_dev, hatebert_bertweet_interleaved_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_interleaved_dynahate_train_dev)
test_preds = mlp.predict(hatebert_bertweet_interleaved_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/hatebert_bertweet_interleaved_dynahate")

save_model(mlp, "Saves/hatebert_bertweet_interleaved_dynahate")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7615870786516854
Accuracy Test:  0.7050970873786407
Weighted F1 Train Dev:  0.7608773216880524
Weighted F1 Test:  0.7045464024305195
Macro F1 Train Dev:  0.7589931904525283
Macro F1 Test:  0.7010220187625436
Micro F1 Train Dev:  0.7615870786516853
Micro F1 Test:  0.7050970873786407
Weighted Recall Train Dev:  0.7615870786516854
Weighted Recall Test:  0.7050970873786407
Macro Recall Train Dev:  0.7580741318780397
Macro Recall Test:  0.7004501544638333
Micro Recall Train Dev:  0.7615870786516854
Micro Recall Test:  0.7050970873786407
Confusion Matrix Train Dev: 
[[12178  4939]
 [ 3888 16019]]
Confusion Matrix Test: 
[[1212  640]
 [ 575 1693]]


#### LatentHatred

In [20]:
hatebert_bertweet_interleaved_latenthatred_train_dev = np.concatenate((hatebert_bertweet_interleaved_latenthatred_train, hatebert_bertweet_interleaved_latenthatred_dev))
hatebert_bertweet_interleaved_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_interleaved_latenthatred_train_dev, hatebert_bertweet_interleaved_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_interleaved_latenthatred_train_dev)
test_preds = mlp.predict(hatebert_bertweet_interleaved_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/hatebert_bertweet_interleaved_latenthatred")

save_model(mlp, "Saves/hatebert_bertweet_interleaved_latenthatred")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7240223463687151
Accuracy Test:  0.7018621973929237
Weighted F1 Train Dev:  0.7010831796497873
Weighted F1 Test:  0.6757836337168567
Macro F1 Train Dev:  0.5272400974396984
Macro F1 Test:  0.500404580322109
Micro F1 Train Dev:  0.7240223463687151
Micro F1 Test:  0.7018621973929237
Weighted Recall Train Dev:  0.7240223463687151
Weighted Recall Test:  0.7018621973929237
Macro Recall Train Dev:  0.5045248872993043
Macro Recall Test:  0.48026652474939385
Micro Recall Train Dev:  0.7240223463687151
Micro Recall Test:  0.7018621973929237
Confusion Matrix Train Dev: 
[[8945  974   26]
 [2670 2617   60]
 [ 344  372  102]]
Confusion Matrix Test: 
[[2979  354   13]
 [ 974  758   21]
 [ 123  116   32]]


#### OLID

In [21]:
hatebert_bertweet_interleaved_olid_train_dev = np.concatenate((hatebert_bertweet_interleaved_olid_train, hatebert_bertweet_interleaved_olid_dev))
hatebert_bertweet_interleaved_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_interleaved_olid_train_dev, hatebert_bertweet_interleaved_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_interleaved_olid_train_dev)
test_preds = mlp.predict(hatebert_bertweet_interleaved_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/hatebert_bertweet_interleaved_olid")

save_model(mlp, "Saves/hatebert_bertweet_interleaved_olid")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.8073262839879154
Accuracy Test:  0.7976744186046512
Weighted F1 Train Dev:  0.8039634686037738
Weighted F1 Test:  0.7882908991730658
Macro F1 Train Dev:  0.7757387043209961
Macro F1 Test:  0.7268126684144034
Micro F1 Train Dev:  0.8073262839879155
Micro F1 Test:  0.7976744186046512
Weighted Recall Train Dev:  0.8073262839879154
Weighted Recall Test:  0.7976744186046512
Macro Recall Train Dev:  0.7678167420814479
Macro Recall Test:  0.7115591397849463
Micro Recall Train Dev:  0.8073262839879154
Micro Recall Test:  0.7976744186046512
Confusion Matrix Train Dev: 
[[7829 1011]
 [1540 2860]]
Confusion Matrix Test: 
[[562  58]
 [116 124]]


### BERT-BERTweet-HateBERT

#### DynaHate

In [22]:
bert_bertweet_hatebert_interleaved_dynahate_train_dev = np.concatenate((bert_hatebert_bertweet_interleaved_dynahate_train, bert_hatebert_bertweet_interleaved_dynahate_dev))
bert_bertweet_hatebert_interleaved_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_interleaved_dynahate_train_dev, bert_bertweet_hatebert_interleaved_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_interleaved_dynahate_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_interleaved_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_bertweet_hatebert_interleaved_dynahate")

save_model(mlp, "Saves/bert_bertweet_hatebert_interleaved_dynahate")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7362251512532412
Accuracy Test:  0.708252427184466
Weighted F1 Train Dev:  0.7363592880965537
Weighted F1 Test:  0.7086223139625583
Macro F1 Train Dev:  0.7350033395717641
Macro F1 Test:  0.7060577656344524
Micro F1 Train Dev:  0.7362251512532412
Micro F1 Test:  0.7082524271844659
Weighted Recall Train Dev:  0.7362251512532412
Weighted Recall Test:  0.708252427184466
Macro Recall Train Dev:  0.7352836861881547
Macro Recall Test:  0.7067329851707101
Micro Recall Train Dev:  0.7362251512532412
Micro Recall Test:  0.708252427184466
Confusion Matrix Train Dev: 
[[12372  4745]
 [ 5021 14886]]
Confusion Matrix Test: 
[[1281  571]
 [ 631 1637]]


#### LatentHatred

In [23]:
bert_bertweet_hatebert_interleaved_latenthatred_train_dev = np.concatenate((bert_hatebert_bertweet_interleaved_latenthatred_train, bert_hatebert_bertweet_interleaved_latenthatred_dev))
bert_bertweet_hatebert_interleaved_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_interleaved_latenthatred_train_dev, bert_bertweet_hatebert_interleaved_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_interleaved_latenthatred_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_interleaved_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_bertweet_hatebert_interleaved_latenthatred")

save_model(mlp, "Saves/bert_bertweet_hatebert_interleaved_latenthatred")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7135319677219119
Accuracy Test:  0.690316573556797
Weighted F1 Train Dev:  0.6897402807925079
Weighted F1 Test:  0.6648720723444846
Macro F1 Train Dev:  0.48240915189267874
Macro F1 Test:  0.4552791427252864
Micro F1 Train Dev:  0.713531967721912
Micro F1 Test:  0.690316573556797
Weighted Recall Train Dev:  0.7135319677219119
Weighted Recall Test:  0.690316573556797
Macro Recall Train Dev:  0.47766808459332905
Macro Recall Test:  0.4533881582720478
Micro Recall Train Dev:  0.7135319677219119
Micro Recall Test:  0.690316573556797
Confusion Matrix Train Dev: 
[[8673 1259   13]
 [2549 2790    8]
 [ 353  433   32]]
Confusion Matrix Test: 
[[2870  471    5]
 [ 922  829    2]
 [ 125  138    8]]


#### OLID

In [24]:
bert_bertweet_hatebert_interleaved_olid_train_dev = np.concatenate((bert_hatebert_bertweet_interleaved_olid_train, bert_hatebert_bertweet_interleaved_olid_dev))
bert_bertweet_hatebert_interleaved_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_interleaved_olid_train_dev, bert_bertweet_hatebert_interleaved_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_interleaved_olid_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_interleaved_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_bertweet_hatebert_interleaved_olid")

save_model(mlp, "Saves/bert_bertweet_hatebert_interleaved_olid")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7834592145015106
Accuracy Test:  0.8162790697674419
Weighted F1 Train Dev:  0.7802251391190109
Weighted F1 Test:  0.8077584026973816
Macro F1 Train Dev:  0.7490769944372341
Macro F1 Test:  0.751933342583194
Micro F1 Train Dev:  0.7834592145015106
Micro F1 Test:  0.8162790697674419
Weighted Recall Train Dev:  0.7834592145015106
Weighted Recall Test:  0.8162790697674419
Macro Recall Train Dev:  0.7428661044837516
Macro Recall Test:  0.7346774193548387
Micro Recall Train Dev:  0.7834592145015106
Micro Recall Test:  0.8162790697674419
Confusion Matrix Train Dev: 
[[7637 1203]
 [1664 2736]]
Confusion Matrix Test: 
[[570  50]
 [108 132]]
