In [4]:
from utils import *
import numpy as np
import torch, os
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV

In [5]:
set_random_seed(7)

Seed: 7


In [6]:
# def scaling_embeddings(embeddings):
#     for i in range(len(embeddings)):
#         embeddings[i] = StandardScaler().fit_transform(embeddings[i])
#     return embeddings

def reshape_embeddings(embeddings):
    if embeddings.shape[1] == 1:
        embeddings = embeddings.squeeze(1)
    return embeddings

In [7]:
def interleave_2_embeddings(embeddings1, embeddings2):
    embeddings1 = reshape_embeddings(embeddings1)
    embeddings2 = reshape_embeddings(embeddings2)
    new_embeddings = []
    for i in range(len(embeddings1)):
        embedding = []
        for j in range(len(embeddings1[i])):
            embedding.append(embeddings1[i][j])
            embedding.append(embeddings2[i][j])
        new_embeddings.append(np.array(embedding))
    return np.array(new_embeddings)
    

def interleave_3_embeddings(embeddings1, embeddings2, embeddings3):
    embeddings1 = reshape_embeddings(embeddings1)
    embeddings2 = reshape_embeddings(embeddings2)
    embeddings3 = reshape_embeddings(embeddings3)
    new_embeddings = []
    for i in range(len(embeddings1)):
        embedding = []
        for j in range(len(embeddings1[i])):
            embedding.append(embeddings1[i][j])
            embedding.append(embeddings2[i][j])
            embedding.append(embeddings3[i][j])
        new_embeddings.append(np.array(embedding))
    return np.array(new_embeddings)

In [8]:
bert_hatebert_interleaved_dynahate_train = interleave_2_embeddings(bert_dynahate_train_embeddings, hatebert_dynahate_train_embeddings)
bert_hatebert_interleaved_dynahate_dev = interleave_2_embeddings(bert_dynahate_dev_embeddings, hatebert_dynahate_dev_embeddings)
bert_hatebert_interleaved_dynahate_test = interleave_2_embeddings(bert_dynahate_test_embeddings, hatebert_dynahate_test_embeddings)

bert_bertweet_interleaved_dynahate_train = interleave_2_embeddings(bert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
bert_bertweet_interleaved_dynahate_dev = interleave_2_embeddings(bert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
bert_bertweet_interleaved_dynahate_test = interleave_2_embeddings(bert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

hatebert_bertweet_interleaved_dynahate_train = interleave_2_embeddings(hatebert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
hatebert_bertweet_interleaved_dynahate_dev = interleave_2_embeddings(hatebert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
hatebert_bertweet_interleaved_dynahate_test = interleave_2_embeddings(hatebert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

bert_hatebert_bertweet_interleaved_dynahate_train = interleave_3_embeddings(bert_dynahate_train_embeddings, hatebert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
bert_hatebert_bertweet_interleaved_dynahate_dev = interleave_3_embeddings(bert_dynahate_dev_embeddings, hatebert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
bert_hatebert_bertweet_interleaved_dynahate_test = interleave_3_embeddings(bert_dynahate_test_embeddings, hatebert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

bert_hatebert_interleaved_olid_train = interleave_2_embeddings(bert_olid_train_embeddings, hatebert_olid_train_embeddings)
bert_hatebert_interleaved_olid_dev = interleave_2_embeddings(bert_olid_dev_embeddings, hatebert_olid_dev_embeddings)
bert_hatebert_interleaved_olid_test = interleave_2_embeddings(bert_olid_test_embeddings, hatebert_olid_test_embeddings)

bert_bertweet_interleaved_olid_train = interleave_2_embeddings(bert_olid_train_embeddings, bertweet_olid_train_embeddings)
bert_bertweet_interleaved_olid_dev = interleave_2_embeddings(bert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
bert_bertweet_interleaved_olid_test = interleave_2_embeddings(bert_olid_test_embeddings, bertweet_olid_test_embeddings)

hatebert_bertweet_interleaved_olid_train = interleave_2_embeddings(hatebert_olid_train_embeddings, bertweet_olid_train_embeddings)
hatebert_bertweet_interleaved_olid_dev = interleave_2_embeddings(hatebert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
hatebert_bertweet_interleaved_olid_test = interleave_2_embeddings(hatebert_olid_test_embeddings, bertweet_olid_test_embeddings)

bert_hatebert_bertweet_interleaved_olid_train = interleave_3_embeddings(bert_olid_train_embeddings, hatebert_olid_train_embeddings, bertweet_olid_train_embeddings)
bert_hatebert_bertweet_interleaved_olid_dev = interleave_3_embeddings(bert_olid_dev_embeddings, hatebert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
bert_hatebert_bertweet_interleaved_olid_test = interleave_3_embeddings(bert_olid_test_embeddings, hatebert_olid_test_embeddings, bertweet_olid_test_embeddings)

bert_hatebert_interleaved_latenthatred_train = interleave_2_embeddings(bert_latenthatred_train_embeddings, hatebert_latenthatred_train_embeddings)
bert_hatebert_interleaved_latenthatred_dev = interleave_2_embeddings(bert_latenthatred_dev_embeddings, hatebert_latenthatred_dev_embeddings)
bert_hatebert_interleaved_latenthatred_test = interleave_2_embeddings(bert_latenthatred_test_embeddings, hatebert_latenthatred_test_embeddings)

bert_bertweet_interleaved_latenthatred_train = interleave_2_embeddings(bert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
bert_bertweet_interleaved_latenthatred_dev = interleave_2_embeddings(bert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
bert_bertweet_interleaved_latenthatred_test = interleave_2_embeddings(bert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

hatebert_bertweet_interleaved_latenthatred_train = interleave_2_embeddings(hatebert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
hatebert_bertweet_interleaved_latenthatred_dev = interleave_2_embeddings(hatebert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
hatebert_bertweet_interleaved_latenthatred_test = interleave_2_embeddings(hatebert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

bert_hatebert_bertweet_interleaved_latenthatred_train = interleave_3_embeddings(bert_latenthatred_train_embeddings, hatebert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
bert_hatebert_bertweet_interleaved_latenthatred_dev = interleave_3_embeddings(bert_latenthatred_dev_embeddings, hatebert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
bert_hatebert_bertweet_interleaved_latenthatred_test = interleave_3_embeddings(bert_latenthatred_test_embeddings, hatebert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

In [9]:
bert_hatebert_bertweet_interleaved_latenthatred_test.shape

(5370, 2304)

In [10]:
dynahate_labels_train = process_labels(read_labels("dynahate", "train"))
dynahate_labels_dev = process_labels(read_labels("dynahate", "dev"))
dynahate_labels_test = process_labels(read_labels("dynahate", "test"))

latenthatred_labels_train = read_labels("latenthatred", "train")
latenthatred_labels_dev = read_labels("latenthatred", "dev")
latenthatred_labels_test = read_labels("latenthatred", "test")

olid_labels_train = read_labels("olid", "train")
olid_labels_dev = read_labels("olid", "dev")
olid_labels_test = read_labels("olid", "test")

In [11]:
mlp = MLPClassifier(random_state=7)
gridsearch = GridSearchCV(
    mlp,
    param_grid={
        "hidden_layer_sizes": [(128), (128,64)],
        "activation": ["relu"],
        "solver": ["adam"],
        "learning_rate_init": [0.001, 0.0001],
        "learning_rate": ["adaptive"],
        "early_stopping": [True],
        "max_iter": [10000]
    },
    verbose=4,
    n_jobs=os.cpu_count()//3,
    cv=5,
)

In [12]:
dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))
latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))
olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

### BERT-BERTweet

#### DynaHate

In [13]:
bert_bertweet_interleaved_dynahate_train_dev = np.concatenate((bert_bertweet_interleaved_dynahate_train, bert_bertweet_interleaved_dynahate_dev))
bert_bertweet_interleaved_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_interleaved_dynahate_train_dev, bert_bertweet_interleaved_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_interleaved_dynahate_train_dev)
test_preds = mlp.predict(bert_bertweet_interleaved_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_bertweet_interleaved_dynahate")
save_model(mlp, "Saves/bert_bertweet_interleaved_dynahate")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.6973314606741573
Accuracy Test:  0.6699029126213593
Weighted F1 Train Dev:  0.6975788570311768
Weighted F1 Test:  0.6703772585928595
Macro F1 Train Dev:  0.6961527499318289
Macro F1 Test:  0.6675582882479434
Micro F1 Train Dev:  0.6973314606741573
Micro F1 Test:  0.6699029126213593
Weighted Recall Train Dev:  0.6973314606741573
Weighted Recall Test:  0.6699029126213593
Macro Recall Train Dev:  0.6965936413577092
Macro Recall Test:  0.6682360649243299
Micro Recall Train Dev:  0.6973314606741573
Micro Recall Test:  0.6699029126213593
Confusion Matrix Train Dev: 
[[11756  5361]
 [ 5845 14062]]
Confusion Matrix Test: 
[[1207  645]
 [ 715 1553]]


#### LatentHatred

In [14]:
bert_bertweet_interleaved_latenthatred_train_dev = np.concatenate((bert_bertweet_interleaved_latenthatred_train, bert_bertweet_interleaved_latenthatred_dev))
bert_bertweet_interleaved_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_interleaved_latenthatred_train_dev, bert_bertweet_interleaved_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_interleaved_latenthatred_train_dev)
test_preds = mlp.predict(bert_bertweet_interleaved_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_bertweet_interleaved_latenthatred")
save_model(mlp, "Saves/bert_bertweet_interleaved_latenthatred")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7202979515828678
Accuracy Test:  0.7044692737430167
Weighted F1 Train Dev:  0.6948439832954735
Weighted F1 Test:  0.6760859648391471
Macro F1 Train Dev:  0.4853464659246973
Macro F1 Test:  0.45857413952010906
Micro F1 Train Dev:  0.7202979515828678
Micro F1 Test:  0.7044692737430167
Weighted Recall Train Dev:  0.7202979515828678
Weighted Recall Test:  0.7044692737430167
Macro Recall Train Dev:  0.4801404994635365
Macro Recall Test:  0.4581554331965854
Micro Recall Train Dev:  0.7202979515828678
Micro Recall Test:  0.7044692737430167
Confusion Matrix Train Dev: 
[[8811 1128    6]
 [2573 2762   12]
 [ 380  407   31]]
Confusion Matrix Test: 
[[2954  390    2]
 [ 924  823    6]
 [ 121  144    6]]


#### OLID

In [15]:
bert_bertweet_interleaved_olid_train_dev = np.concatenate((bert_bertweet_interleaved_olid_train, bert_bertweet_interleaved_olid_dev))
bert_bertweet_interleaved_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_interleaved_olid_train_dev, bert_bertweet_interleaved_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_interleaved_olid_train_dev)
test_preds = mlp.predict(bert_bertweet_interleaved_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_bertweet_interleaved_olid")

save_model(mlp, "Saves/bert_bertweet_interleaved_olid")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7707703927492447
Accuracy Test:  0.8174418604651162
Weighted F1 Train Dev:  0.7646696195903286
Weighted F1 Test:  0.8045084985053871
Macro F1 Train Dev:  0.7289813022970655
Macro F1 Test:  0.7438334670893737
Micro F1 Train Dev:  0.7707703927492449
Micro F1 Test:  0.8174418604651161
Weighted Recall Train Dev:  0.7707703927492447
Weighted Recall Test:  0.8174418604651162
Macro Recall Train Dev:  0.7200653023447141
Macro Recall Test:  0.7214381720430108
Micro Recall Train Dev:  0.7707703927492447
Micro Recall Test:  0.8174418604651162
Confusion Matrix Train Dev: 
[[7702 1138]
 [1897 2503]]
Confusion Matrix Test: 
[[582  38]
 [119 121]]


### BERT-HateBERT

#### DynaHate

In [16]:
bert_hatebert_interleaved_dynahate_train_dev = np.concatenate((bert_hatebert_interleaved_dynahate_train, bert_hatebert_interleaved_dynahate_dev))
bert_hatebert_interleaved_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_interleaved_dynahate_train_dev, bert_hatebert_interleaved_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_interleaved_dynahate_train_dev)
test_preds = mlp.predict(bert_hatebert_interleaved_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_hatebert_interleaved_dynahate")

save_model(mlp, "Saves/bert_hatebert_interleaved_dynahate")



Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.707460025929127
Accuracy Test:  0.6861650485436893
Weighted F1 Train Dev:  0.7049990512931114
Weighted F1 Test:  0.683973961579324
Macro F1 Train Dev:  0.7019433685007286
Macro F1 Test:  0.6792017512276172
Micro F1 Train Dev:  0.707460025929127
Micro F1 Test:  0.6861650485436893
Weighted Recall Train Dev:  0.707460025929127
Weighted Recall Test:  0.6861650485436893
Macro Recall Train Dev:  0.7011897855847005
Macro Recall Test:  0.6782033627785968
Micro Recall Train Dev:  0.707460025929127
Micro Recall Test:  0.6861650485436893
Confusion Matrix Train Dev: 
[[10578  6539]
 [ 4292 15615]]
Confusion Matrix Test: 
[[1110  742]
 [ 551 1717]]


#### LatentHatred

In [17]:
bert_hatebert_interleaved_latenthatred_train_dev = np.concatenate((bert_hatebert_interleaved_latenthatred_train, bert_hatebert_interleaved_latenthatred_dev))
bert_hatebert_interleaved_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_interleaved_latenthatred_train_dev, bert_hatebert_interleaved_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_interleaved_latenthatred_train_dev)
test_preds = mlp.predict(bert_hatebert_interleaved_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_hatebert_interleaved_latenthatred")

save_model(mlp, "Saves/bert_hatebert_interleaved_latenthatred")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7127870887647424
Accuracy Test:  0.6918063314711359
Weighted F1 Train Dev:  0.6836828246129403
Weighted F1 Test:  0.6616025896052177
Macro F1 Train Dev:  0.4716090898739498
Macro F1 Test:  0.45251182566969855
Micro F1 Train Dev:  0.7127870887647423
Micro F1 Test:  0.6918063314711359
Weighted Recall Train Dev:  0.7127870887647424
Weighted Recall Test:  0.6918063314711359
Macro Recall Train Dev:  0.4680181056112525
Macro Recall Test:  0.4490690348123025
Micro Recall Train Dev:  0.7127870887647424
Micro Recall Test:  0.6918063314711359
Confusion Matrix Train Dev: 
[[8910 1027    8]
 [2794 2547    6]
 [ 356  436   26]]
Confusion Matrix Test: 
[[2946  396    4]
 [ 991  760    2]
 [ 129  133    9]]


#### OLID

In [18]:
bert_hatebert_interleaved_olid_train_dev = np.concatenate((bert_hatebert_interleaved_olid_train, bert_hatebert_interleaved_olid_dev))
bert_hatebert_interleaved_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_interleaved_olid_train_dev, bert_hatebert_interleaved_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_interleaved_olid_train_dev)
test_preds = mlp.predict(bert_hatebert_interleaved_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_hatebert_interleaved_olid")

save_model(mlp, "Saves/bert_hatebert_interleaved_olid")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7639728096676737
Accuracy Test:  0.7872093023255814
Weighted F1 Train Dev:  0.755719618351784
Weighted F1 Test:  0.76271734364365
Macro F1 Train Dev:  0.7171061626694332
Macro F1 Test:  0.6817873932163979
Micro F1 Train Dev:  0.7639728096676736
Micro F1 Test:  0.7872093023255814
Weighted Recall Train Dev:  0.7639728096676737
Weighted Recall Test:  0.7872093023255814
Macro Recall Train Dev:  0.7069842657342658
Macro Recall Test:  0.6621639784946236
Micro Recall Train Dev:  0.7639728096676737
Micro Recall Test:  0.7872093023255814
Confusion Matrix Train Dev: 
[[7752 1088]
 [2037 2363]]
Confusion Matrix Test: 
[[586  34]
 [149  91]]


### BERTweet-HateBERT

#### DynaHate

In [19]:
hatebert_bertweet_interleaved_dynahate_train_dev = np.concatenate((hatebert_bertweet_interleaved_dynahate_train, hatebert_bertweet_interleaved_dynahate_dev))
hatebert_bertweet_interleaved_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_interleaved_dynahate_train_dev, hatebert_bertweet_interleaved_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_interleaved_dynahate_train_dev)
test_preds = mlp.predict(hatebert_bertweet_interleaved_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/hatebert_bertweet_interleaved_dynahate")

save_model(mlp, "Saves/hatebert_bertweet_interleaved_dynahate")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7410868625756266
Accuracy Test:  0.7048543689320388
Weighted F1 Train Dev:  0.7412176779633145
Weighted F1 Test:  0.7054289816262611
Macro F1 Train Dev:  0.7398856526653244
Macro F1 Test:  0.703173897845162
Micro F1 Train Dev:  0.7410868625756265
Micro F1 Test:  0.7048543689320388
Weighted Recall Train Dev:  0.7410868625756266
Weighted Recall Test:  0.7048543689320388
Macro Recall Train Dev:  0.7401690689890499
Macro Recall Test:  0.7044388829845993
Micro Recall Train Dev:  0.7410868625756266
Micro Recall Test:  0.7048543689320388
Confusion Matrix Train Dev: 
[[12461  4656]
 [ 4930 14977]]
Confusion Matrix Test: 
[[1297  555]
 [ 661 1607]]


#### LatentHatred

In [20]:
hatebert_bertweet_interleaved_latenthatred_train_dev = np.concatenate((hatebert_bertweet_interleaved_latenthatred_train, hatebert_bertweet_interleaved_latenthatred_dev))
hatebert_bertweet_interleaved_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_interleaved_latenthatred_train_dev, hatebert_bertweet_interleaved_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_interleaved_latenthatred_train_dev)
test_preds = mlp.predict(hatebert_bertweet_interleaved_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/hatebert_bertweet_interleaved_latenthatred")

save_model(mlp, "Saves/hatebert_bertweet_interleaved_latenthatred")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7150217256362508
Accuracy Test:  0.6964618249534451
Weighted F1 Train Dev:  0.6934980136822416
Weighted F1 Test:  0.6727028038051881
Macro F1 Train Dev:  0.5186072721279694
Macro F1 Test:  0.4972429294388078
Micro F1 Train Dev:  0.7150217256362508
Micro F1 Test:  0.6964618249534451
Weighted Recall Train Dev:  0.7150217256362508
Weighted Recall Test:  0.6964618249534451
Macro Recall Train Dev:  0.4982560833664416
Macro Recall Test:  0.478735434734008
Micro Recall Train Dev:  0.7150217256362508
Micro Recall Test:  0.6964618249534451
Confusion Matrix Train Dev: 
[[8789 1112   44]
 [2654 2633   60]
 [ 365  356   97]]
Confusion Matrix Test: 
[[2935  393   18]
 [ 955  773   25]
 [ 118  121   32]]


#### OLID

In [21]:
hatebert_bertweet_interleaved_olid_train_dev = np.concatenate((hatebert_bertweet_interleaved_olid_train, hatebert_bertweet_interleaved_olid_dev))
hatebert_bertweet_interleaved_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_interleaved_olid_train_dev, hatebert_bertweet_interleaved_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_interleaved_olid_train_dev)
test_preds = mlp.predict(hatebert_bertweet_interleaved_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/hatebert_bertweet_interleaved_olid")

save_model(mlp, "Saves/hatebert_bertweet_interleaved_olid")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7789274924471299
Accuracy Test:  0.7988372093023256
Weighted F1 Train Dev:  0.7625355651690972
Weighted F1 Test:  0.7744889173685495
Macro F1 Train Dev:  0.7190327814784423
Macro F1 Test:  0.6967380691766595
Micro F1 Train Dev:  0.7789274924471299
Micro F1 Test:  0.7988372093023256
Weighted Recall Train Dev:  0.7789274924471299
Weighted Recall Test:  0.7988372093023256
Macro Recall Train Dev:  0.7031725627313863
Macro Recall Test:  0.6740591397849462
Micro Recall Train Dev:  0.7789274924471299
Micro Recall Test:  0.7988372093023256
Confusion Matrix Train Dev: 
[[8213  627]
 [2300 2100]]
Confusion Matrix Test: 
[[593  27]
 [146  94]]


### BERT-BERTweet-HateBERT

#### DynaHate

In [22]:
bert_bertweet_hatebert_interleaved_dynahate_train_dev = np.concatenate((bert_hatebert_bertweet_interleaved_dynahate_train, bert_hatebert_bertweet_interleaved_dynahate_dev))
bert_bertweet_hatebert_interleaved_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_interleaved_dynahate_train_dev, bert_bertweet_hatebert_interleaved_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_interleaved_dynahate_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_interleaved_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_bertweet_hatebert_interleaved_dynahate")

save_model(mlp, "Saves/bert_bertweet_hatebert_interleaved_dynahate")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7430585566119274
Accuracy Test:  0.6990291262135923
Weighted F1 Train Dev:  0.7419861189171056
Weighted F1 Test:  0.6981876634219085
Macro F1 Train Dev:  0.7397876610416076
Macro F1 Test:  0.6943827881899478
Micro F1 Train Dev:  0.7430585566119273
Micro F1 Test:  0.6990291262135923
Weighted Recall Train Dev:  0.7430585566119274
Weighted Recall Test:  0.6990291262135923
Macro Recall Train Dev:  0.7388052331405532
Macro Recall Test:  0.6936511745727009
Micro Recall Train Dev:  0.7430585566119274
Micro Recall Test:  0.6990291262135923
Confusion Matrix Train Dev: 
[[11680  5437]
 [ 4076 15831]]
Confusion Matrix Test: 
[[1186  666]
 [ 574 1694]]


#### LatentHatred

In [23]:
bert_bertweet_hatebert_interleaved_latenthatred_train_dev = np.concatenate((bert_hatebert_bertweet_interleaved_latenthatred_train, bert_hatebert_bertweet_interleaved_latenthatred_dev))
bert_bertweet_hatebert_interleaved_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_interleaved_latenthatred_train_dev, bert_bertweet_hatebert_interleaved_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_interleaved_latenthatred_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_interleaved_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_bertweet_hatebert_interleaved_latenthatred")

save_model(mlp, "Saves/bert_bertweet_hatebert_interleaved_latenthatred")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7118559900682806
Accuracy Test:  0.6899441340782123
Weighted F1 Train Dev:  0.6911149051770351
Weighted F1 Test:  0.6685199868851459
Macro F1 Train Dev:  0.47505176525570153
Macro F1 Test:  0.4482138528985112
Micro F1 Train Dev:  0.7118559900682806
Micro F1 Test:  0.6899441340782123
Weighted Recall Train Dev:  0.7118559900682806
Weighted Recall Test:  0.6899441340782123
Macro Recall Train Dev:  0.47818682384572986
Macro Recall Test:  0.4550973331188053
Micro Recall Train Dev:  0.7118559900682806
Micro Recall Test:  0.6899441340782123
Confusion Matrix Train Dev: 
[[8405 1534    6]
 [2298 3047    2]
 [ 323  479   16]]
Confusion Matrix Test: 
[[2778  568    0]
 [ 826  925    2]
 [ 106  163    2]]


#### OLID

In [24]:
bert_bertweet_hatebert_interleaved_olid_train_dev = np.concatenate((bert_hatebert_bertweet_interleaved_olid_train, bert_hatebert_bertweet_interleaved_olid_dev))
bert_bertweet_hatebert_interleaved_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_interleaved_olid_train_dev, bert_bertweet_hatebert_interleaved_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_interleaved_olid_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_interleaved_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_bertweet_hatebert_interleaved_olid")

save_model(mlp, "Saves/bert_bertweet_hatebert_interleaved_olid")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7802114803625377
Accuracy Test:  0.8046511627906977
Weighted F1 Train Dev:  0.7698445597774969
Weighted F1 Test:  0.7830155377794796
Macro F1 Train Dev:  0.7314869536128457
Macro F1 Test:  0.7096089529199897
Micro F1 Train Dev:  0.7802114803625377
Micro F1 Test:  0.8046511627906977
Weighted Recall Train Dev:  0.7802114803625377
Weighted Recall Test:  0.8046511627906977
Macro Recall Train Dev:  0.7181175442204855
Macro Recall Test:  0.685752688172043
Micro Recall Train Dev:  0.7802114803625377
Micro Recall Test:  0.8046511627906977
Confusion Matrix Train Dev: 
[[7985  855]
 [2055 2345]]
Confusion Matrix Test: 
[[592  28]
 [140 100]]
