In [1]:
from utils import *
import numpy as np
import torch, os
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV

In [2]:
set_random_seed(7)

Seed: 7


In [3]:
# def scaling_embeddings(embeddings):
#     for i in range(len(embeddings)):
#         embeddings[i] = StandardScaler().fit_transform(embeddings[i])
#     return embeddings

def reshape_embeddings(embeddings):
    if embeddings.shape[1] == 1:
        embeddings = embeddings.squeeze(1)
    return embeddings

In [4]:
def interleave_2_embeddings(embeddings1, embeddings2):
    embeddings1 = reshape_embeddings(embeddings1)
    embeddings2 = reshape_embeddings(embeddings2)
    new_embeddings = []
    for i in range(len(embeddings1)):
        embedding = []
        for j in range(len(embeddings1[i])):
            embedding.append(embeddings1[i][j])
            embedding.append(embeddings2[i][j])
        new_embeddings.append(np.array(embedding))
    return np.array(new_embeddings)
    

def interleave_3_embeddings(embeddings1, embeddings2, embeddings3):
    embeddings1 = reshape_embeddings(embeddings1)
    embeddings2 = reshape_embeddings(embeddings2)
    embeddings3 = reshape_embeddings(embeddings3)
    new_embeddings = []
    for i in range(len(embeddings1)):
        embedding = []
        for j in range(len(embeddings1[i])):
            embedding.append(embeddings1[i][j])
            embedding.append(embeddings2[i][j])
            embedding.append(embeddings3[i][j])
        new_embeddings.append(np.array(embedding))
    return np.array(new_embeddings)

In [5]:
bert_hatebert_interleaved_dynahate_train = interleave_2_embeddings(bert_dynahate_train_embeddings, hatebert_dynahate_train_embeddings)
bert_hatebert_interleaved_dynahate_dev = interleave_2_embeddings(bert_dynahate_dev_embeddings, hatebert_dynahate_dev_embeddings)
bert_hatebert_interleaved_dynahate_test = interleave_2_embeddings(bert_dynahate_test_embeddings, hatebert_dynahate_test_embeddings)

bert_bertweet_interleaved_dynahate_train = interleave_2_embeddings(bert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
bert_bertweet_interleaved_dynahate_dev = interleave_2_embeddings(bert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
bert_bertweet_interleaved_dynahate_test = interleave_2_embeddings(bert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

hatebert_bertweet_interleaved_dynahate_train = interleave_2_embeddings(hatebert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
hatebert_bertweet_interleaved_dynahate_dev = interleave_2_embeddings(hatebert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
hatebert_bertweet_interleaved_dynahate_test = interleave_2_embeddings(hatebert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

bert_hatebert_bertweet_interleaved_dynahate_train = interleave_3_embeddings(bert_dynahate_train_embeddings, hatebert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
bert_hatebert_bertweet_interleaved_dynahate_dev = interleave_3_embeddings(bert_dynahate_dev_embeddings, hatebert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
bert_hatebert_bertweet_interleaved_dynahate_test = interleave_3_embeddings(bert_dynahate_test_embeddings, hatebert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

bert_hatebert_interleaved_olid_train = interleave_2_embeddings(bert_olid_train_embeddings, hatebert_olid_train_embeddings)
bert_hatebert_interleaved_olid_dev = interleave_2_embeddings(bert_olid_dev_embeddings, hatebert_olid_dev_embeddings)
bert_hatebert_interleaved_olid_test = interleave_2_embeddings(bert_olid_test_embeddings, hatebert_olid_test_embeddings)

bert_bertweet_interleaved_olid_train = interleave_2_embeddings(bert_olid_train_embeddings, bertweet_olid_train_embeddings)
bert_bertweet_interleaved_olid_dev = interleave_2_embeddings(bert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
bert_bertweet_interleaved_olid_test = interleave_2_embeddings(bert_olid_test_embeddings, bertweet_olid_test_embeddings)

hatebert_bertweet_interleaved_olid_train = interleave_2_embeddings(hatebert_olid_train_embeddings, bertweet_olid_train_embeddings)
hatebert_bertweet_interleaved_olid_dev = interleave_2_embeddings(hatebert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
hatebert_bertweet_interleaved_olid_test = interleave_2_embeddings(hatebert_olid_test_embeddings, bertweet_olid_test_embeddings)

bert_hatebert_bertweet_interleaved_olid_train = interleave_3_embeddings(bert_olid_train_embeddings, hatebert_olid_train_embeddings, bertweet_olid_train_embeddings)
bert_hatebert_bertweet_interleaved_olid_dev = interleave_3_embeddings(bert_olid_dev_embeddings, hatebert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
bert_hatebert_bertweet_interleaved_olid_test = interleave_3_embeddings(bert_olid_test_embeddings, hatebert_olid_test_embeddings, bertweet_olid_test_embeddings)

bert_hatebert_interleaved_latenthatred_train = interleave_2_embeddings(bert_latenthatred_train_embeddings, hatebert_latenthatred_train_embeddings)
bert_hatebert_interleaved_latenthatred_dev = interleave_2_embeddings(bert_latenthatred_dev_embeddings, hatebert_latenthatred_dev_embeddings)
bert_hatebert_interleaved_latenthatred_test = interleave_2_embeddings(bert_latenthatred_test_embeddings, hatebert_latenthatred_test_embeddings)

bert_bertweet_interleaved_latenthatred_train = interleave_2_embeddings(bert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
bert_bertweet_interleaved_latenthatred_dev = interleave_2_embeddings(bert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
bert_bertweet_interleaved_latenthatred_test = interleave_2_embeddings(bert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

hatebert_bertweet_interleaved_latenthatred_train = interleave_2_embeddings(hatebert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
hatebert_bertweet_interleaved_latenthatred_dev = interleave_2_embeddings(hatebert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
hatebert_bertweet_interleaved_latenthatred_test = interleave_2_embeddings(hatebert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

bert_hatebert_bertweet_interleaved_latenthatred_train = interleave_3_embeddings(bert_latenthatred_train_embeddings, hatebert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
bert_hatebert_bertweet_interleaved_latenthatred_dev = interleave_3_embeddings(bert_latenthatred_dev_embeddings, hatebert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
bert_hatebert_bertweet_interleaved_latenthatred_test = interleave_3_embeddings(bert_latenthatred_test_embeddings, hatebert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

In [6]:
bert_hatebert_bertweet_interleaved_latenthatred_test.shape

(5370, 2304)

In [7]:
dynahate_labels_train = process_labels(read_labels("dynahate", "train"))
dynahate_labels_dev = process_labels(read_labels("dynahate", "dev"))
dynahate_labels_test = process_labels(read_labels("dynahate", "test"))

latenthatred_labels_train = read_labels("latenthatred", "train")
latenthatred_labels_dev = read_labels("latenthatred", "dev")
latenthatred_labels_test = read_labels("latenthatred", "test")

olid_labels_train = read_labels("olid", "train")
olid_labels_dev = read_labels("olid", "dev")
olid_labels_test = read_labels("olid", "test")

In [8]:
mlp = MLPClassifier(random_state=7)
gridsearch = GridSearchCV(
    mlp,
    param_grid={
        "hidden_layer_sizes": [(128), (128,64)],
        "activation": ["relu"],
        "solver": ["adam"],
        "learning_rate_init": [0.001, 0.0001],
        "learning_rate": ["adaptive"],
        "early_stopping": [True],
        "max_iter": [10000]
    },
    verbose=4,
    n_jobs=os.cpu_count()//3,
    cv=5,
)

In [9]:
dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))
latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))
olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

### BERT-BERTweet

#### DynaHate

In [10]:
bert_bertweet_interleaved_dynahate_train_dev = np.concatenate((bert_bertweet_interleaved_dynahate_train, bert_bertweet_interleaved_dynahate_dev))
bert_bertweet_interleaved_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_interleaved_dynahate_train_dev, bert_bertweet_interleaved_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_interleaved_dynahate_train_dev)
test_preds = mlp.predict(bert_bertweet_interleaved_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_bertweet_interleaved_dynahate_seed_7")
save_model(mlp, "Saves/bert_bertweet_interleaved_dynahate_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7371974935177182
Accuracy Test:  0.679126213592233
Weighted F1 Train Dev:  0.7335191262739957
Weighted F1 Test:  0.6753726389118929
Macro F1 Train Dev:  0.7302590739836572
Macro F1 Test:  0.6697557789585784
Micro F1 Train Dev:  0.7371974935177182
Micro F1 Test:  0.679126213592233
Weighted Recall Train Dev:  0.7371974935177182
Weighted Recall Test:  0.679126213592233
Macro Recall Train Dev:  0.7292527680835121
Macro Recall Test:  0.6689379135383455
Micro Recall Train Dev:  0.7371974935177182
Micro Recall Test:  0.679126213592233
Confusion Matrix Train Dev: 
[[10678  6439]
 [ 3291 16616]]
Confusion Matrix Test: 
[[1052  800]
 [ 522 1746]]


#### LatentHatred

In [11]:
bert_bertweet_interleaved_latenthatred_train_dev = np.concatenate((bert_bertweet_interleaved_latenthatred_train, bert_bertweet_interleaved_latenthatred_dev))
bert_bertweet_interleaved_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_interleaved_latenthatred_train_dev, bert_bertweet_interleaved_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_interleaved_latenthatred_train_dev)
test_preds = mlp.predict(bert_bertweet_interleaved_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_bertweet_interleaved_latenthatred_seed_7")
save_model(mlp, "Saves/bert_bertweet_interleaved_latenthatred_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7247672253258846
Accuracy Test:  0.7052141527001862
Weighted F1 Train Dev:  0.6995769438064068
Weighted F1 Test:  0.6764869245017987
Macro F1 Train Dev:  0.5278686573917292
Macro F1 Test:  0.4936954179870709
Micro F1 Train Dev:  0.7247672253258846
Micro F1 Test:  0.7052141527001862
Weighted Recall Train Dev:  0.7247672253258846
Weighted Recall Test:  0.7052141527001862
Macro Recall Train Dev:  0.5042584750110266
Macro Recall Test:  0.47590862915413523
Micro Recall Train Dev:  0.7247672253258846
Micro Recall Test:  0.7052141527001862
Confusion Matrix Train Dev: 
[[9076  838   31]
 [2777 2490   80]
 [ 390  318  110]]
Confusion Matrix Test: 
[[3019  320    7]
 [ 985  740   28]
 [ 136  107   28]]


#### OLID

In [12]:
bert_bertweet_interleaved_olid_train_dev = np.concatenate((bert_bertweet_interleaved_olid_train, bert_bertweet_interleaved_olid_dev))
bert_bertweet_interleaved_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_interleaved_olid_train_dev, bert_bertweet_interleaved_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_interleaved_olid_train_dev)
test_preds = mlp.predict(bert_bertweet_interleaved_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_bertweet_interleaved_olid_seed_7")

save_model(mlp, "Saves/bert_bertweet_interleaved_olid_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7707703927492447
Accuracy Test:  0.8174418604651162
Weighted F1 Train Dev:  0.7646696195903286
Weighted F1 Test:  0.8045084985053871
Macro F1 Train Dev:  0.7289813022970655
Macro F1 Test:  0.7438334670893737
Micro F1 Train Dev:  0.7707703927492449
Micro F1 Test:  0.8174418604651161
Weighted Recall Train Dev:  0.7707703927492447
Weighted Recall Test:  0.8174418604651162
Macro Recall Train Dev:  0.7200653023447141
Macro Recall Test:  0.7214381720430108
Micro Recall Train Dev:  0.7707703927492447
Micro Recall Test:  0.8174418604651162
Confusion Matrix Train Dev: 
[[7702 1138]
 [1897 2503]]
Confusion Matrix Test: 
[[582  38]
 [119 121]]


### BERT-HateBERT

#### DynaHate

In [13]:
bert_hatebert_interleaved_dynahate_train_dev = np.concatenate((bert_hatebert_interleaved_dynahate_train, bert_hatebert_interleaved_dynahate_dev))
bert_hatebert_interleaved_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_interleaved_dynahate_train_dev, bert_hatebert_interleaved_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_interleaved_dynahate_train_dev)
test_preds = mlp.predict(bert_hatebert_interleaved_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_hatebert_interleaved_dynahate_seed_7")

save_model(mlp, "Saves/bert_hatebert_interleaved_dynahate_seed_7")



Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7344695332757131
Accuracy Test:  0.6953883495145631
Weighted F1 Train Dev:  0.733813453817286
Weighted F1 Test:  0.6952547784031643
Macro F1 Train Dev:  0.7317953042152885
Macro F1 Test:  0.6919862147359928
Micro F1 Train Dev:  0.7344695332757131
Micro F1 Test:  0.6953883495145631
Weighted Recall Train Dev:  0.7344695332757131
Weighted Recall Test:  0.6953883495145631
Macro Recall Train Dev:  0.7310964803887883
Macro Recall Test:  0.6918298917039017
Micro Recall Train Dev:  0.7344695332757131
Micro Recall Test:  0.6953883495145631
Confusion Matrix Train Dev: 
[[11748  5369]
 [ 4462 15445]]
Confusion Matrix Test: 
[[1216  636]
 [ 619 1649]]


#### LatentHatred

In [14]:
bert_hatebert_interleaved_latenthatred_train_dev = np.concatenate((bert_hatebert_interleaved_latenthatred_train, bert_hatebert_interleaved_latenthatred_dev))
bert_hatebert_interleaved_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_interleaved_latenthatred_train_dev, bert_hatebert_interleaved_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_interleaved_latenthatred_train_dev)
test_preds = mlp.predict(bert_hatebert_interleaved_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_hatebert_interleaved_latenthatred_seed_7")

save_model(mlp, "Saves/bert_hatebert_interleaved_latenthatred_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.6916821849782744
Accuracy Test:  0.6819366852886406
Weighted F1 Train Dev:  0.6665318435975793
Weighted F1 Test:  0.6558178421108103
Macro F1 Train Dev:  0.44325696811768206
Macro F1 Test:  0.43228656295650764
Micro F1 Train Dev:  0.6916821849782744
Micro F1 Test:  0.6819366852886406
Weighted Recall Train Dev:  0.6916821849782744
Weighted Recall Test:  0.6819366852886406
Macro Recall Train Dev:  0.45165433135157773
Macro Recall Test:  0.44040523932615677
Micro Recall Train Dev:  0.6916821849782744
Micro Recall Test:  0.6819366852886406
Confusion Matrix Train Dev: 
[[8431 1514    0]
 [2635 2712    0]
 [ 362  456    0]]
Confusion Matrix Test: 
[[2827  519    0]
 [ 918  835    0]
 [ 124  147    0]]


#### OLID

In [15]:
bert_hatebert_interleaved_olid_train_dev = np.concatenate((bert_hatebert_interleaved_olid_train, bert_hatebert_interleaved_olid_dev))
bert_hatebert_interleaved_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_interleaved_olid_train_dev, bert_hatebert_interleaved_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_interleaved_olid_train_dev)
test_preds = mlp.predict(bert_hatebert_interleaved_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_hatebert_interleaved_olid_seed_7")

save_model(mlp, "Saves/bert_hatebert_interleaved_olid_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7615558912386707
Accuracy Test:  0.7883720930232558
Weighted F1 Train Dev:  0.7494002087988924
Weighted F1 Test:  0.761790784860589
Macro F1 Train Dev:  0.7070033273907106
Macro F1 Test:  0.6789965463211347
Micro F1 Train Dev:  0.7615558912386707
Micro F1 Test:  0.7883720930232558
Weighted Recall Train Dev:  0.7615558912386707
Weighted Recall Test:  0.7883720930232558
Macro Recall Train Dev:  0.6950149115590292
Macro Recall Test:  0.6591397849462366
Micro Recall Train Dev:  0.7615558912386707
Micro Recall Test:  0.7883720930232558
Confusion Matrix Train Dev: 
[[7898  942]
 [2215 2185]]
Confusion Matrix Test: 
[[590  30]
 [152  88]]


### BERTweet-HateBERT

#### DynaHate

In [16]:
hatebert_bertweet_interleaved_dynahate_train_dev = np.concatenate((hatebert_bertweet_interleaved_dynahate_train, hatebert_bertweet_interleaved_dynahate_dev))
hatebert_bertweet_interleaved_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_interleaved_dynahate_train_dev, hatebert_bertweet_interleaved_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_interleaved_dynahate_train_dev)
test_preds = mlp.predict(hatebert_bertweet_interleaved_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/hatebert_bertweet_interleaved_dynahate_seed_7")

save_model(mlp, "Saves/hatebert_bertweet_interleaved_dynahate_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7521607605877269
Accuracy Test:  0.704611650485437
Weighted F1 Train Dev:  0.7493927575997645
Weighted F1 Test:  0.700812815642872
Macro F1 Train Dev:  0.7465514300293397
Macro F1 Test:  0.6954918887253401
Micro F1 Train Dev:  0.7521607605877269
Micro F1 Test:  0.704611650485437
Weighted Recall Train Dev:  0.7521607605877269
Weighted Recall Test:  0.704611650485437
Macro Recall Train Dev:  0.7451816865348566
Macro Recall Test:  0.6942154151477405
Micro Recall Train Dev:  0.7521607605877269
Micro Recall Test:  0.704611650485437
Confusion Matrix Train Dev: 
[[11170  5947]
 [ 3229 16678]]
Confusion Matrix Test: 
[[1095  757]
 [ 460 1808]]


#### LatentHatred

In [17]:
hatebert_bertweet_interleaved_latenthatred_train_dev = np.concatenate((hatebert_bertweet_interleaved_latenthatred_train, hatebert_bertweet_interleaved_latenthatred_dev))
hatebert_bertweet_interleaved_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_interleaved_latenthatred_train_dev, hatebert_bertweet_interleaved_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_interleaved_latenthatred_train_dev)
test_preds = mlp.predict(hatebert_bertweet_interleaved_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/hatebert_bertweet_interleaved_latenthatred_seed_7")

save_model(mlp, "Saves/hatebert_bertweet_interleaved_latenthatred_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7150217256362508
Accuracy Test:  0.6964618249534451
Weighted F1 Train Dev:  0.6934980136822416
Weighted F1 Test:  0.6727028038051881
Macro F1 Train Dev:  0.5186072721279694
Macro F1 Test:  0.4972429294388078
Micro F1 Train Dev:  0.7150217256362508
Micro F1 Test:  0.6964618249534451
Weighted Recall Train Dev:  0.7150217256362508
Weighted Recall Test:  0.6964618249534451
Macro Recall Train Dev:  0.4982560833664416
Macro Recall Test:  0.478735434734008
Micro Recall Train Dev:  0.7150217256362508
Micro Recall Test:  0.6964618249534451
Confusion Matrix Train Dev: 
[[8789 1112   44]
 [2654 2633   60]
 [ 365  356   97]]
Confusion Matrix Test: 
[[2935  393   18]
 [ 955  773   25]
 [ 118  121   32]]


#### OLID

In [18]:
hatebert_bertweet_interleaved_olid_train_dev = np.concatenate((hatebert_bertweet_interleaved_olid_train, hatebert_bertweet_interleaved_olid_dev))
hatebert_bertweet_interleaved_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_interleaved_olid_train_dev, hatebert_bertweet_interleaved_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_interleaved_olid_train_dev)
test_preds = mlp.predict(hatebert_bertweet_interleaved_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/hatebert_bertweet_interleaved_olid_seed_7")

save_model(mlp, "Saves/hatebert_bertweet_interleaved_olid_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7786253776435045
Accuracy Test:  0.7930232558139535
Weighted F1 Train Dev:  0.7677824794822814
Weighted F1 Test:  0.7740537486870955
Macro F1 Train Dev:  0.7288007241496247
Macro F1 Test:  0.7004985169707073
Micro F1 Train Dev:  0.7786253776435045
Micro F1 Test:  0.7930232558139535
Weighted Recall Train Dev:  0.7786253776435045
Weighted Recall Test:  0.7930232558139535
Macro Recall Train Dev:  0.7153316536404772
Macro Recall Test:  0.6802419354838709
Micro Recall Train Dev:  0.7786253776435045
Micro Recall Test:  0.7930232558139535
Confusion Matrix Train Dev: 
[[7992  848]
 [2083 2317]]
Confusion Matrix Test: 
[[580  40]
 [138 102]]


### BERT-BERTweet-HateBERT

#### DynaHate

In [19]:
bert_bertweet_hatebert_interleaved_dynahate_train_dev = np.concatenate((bert_hatebert_bertweet_interleaved_dynahate_train, bert_hatebert_bertweet_interleaved_dynahate_dev))
bert_bertweet_hatebert_interleaved_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_interleaved_dynahate_train_dev, bert_bertweet_hatebert_interleaved_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_interleaved_dynahate_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_interleaved_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_bertweet_hatebert_interleaved_dynahate_seed_7")

save_model(mlp, "Saves/bert_bertweet_hatebert_interleaved_dynahate_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.759588375108038
Accuracy Test:  0.7157766990291262
Weighted F1 Train Dev:  0.7591964259814186
Weighted F1 Test:  0.7154759040343386
Macro F1 Train Dev:  0.7575010181313905
Macro F1 Test:  0.7122674240899366
Micro F1 Train Dev:  0.7595883751080381
Micro F1 Test:  0.7157766990291262
Weighted Recall Train Dev:  0.759588375108038
Weighted Recall Test:  0.7157766990291262
Macro Recall Train Dev:  0.7568950820826101
Macro Recall Test:  0.7118835255084355
Micro Recall Train Dev:  0.759588375108038
Micro Recall Test:  0.7157766990291262
Confusion Matrix Train Dev: 
[[12344  4773]
 [ 4128 15779]]
Confusion Matrix Test: 
[[1247  605]
 [ 566 1702]]


#### LatentHatred

In [20]:
bert_bertweet_hatebert_interleaved_latenthatred_train_dev = np.concatenate((bert_hatebert_bertweet_interleaved_latenthatred_train, bert_hatebert_bertweet_interleaved_latenthatred_dev))
bert_bertweet_hatebert_interleaved_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_interleaved_latenthatred_train_dev, bert_bertweet_hatebert_interleaved_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_interleaved_latenthatred_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_interleaved_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_bertweet_hatebert_interleaved_latenthatred_seed_7")

save_model(mlp, "Saves/bert_bertweet_hatebert_interleaved_latenthatred_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7247051520794537
Accuracy Test:  0.7048417132216015
Weighted F1 Train Dev:  0.7066521156087224
Weighted F1 Test:  0.6849885808113455
Macro F1 Train Dev:  0.526828210665315
Macro F1 Test:  0.5012917920432961
Micro F1 Train Dev:  0.7247051520794539
Micro F1 Test:  0.7048417132216015
Weighted Recall Train Dev:  0.7247051520794537
Weighted Recall Test:  0.7048417132216015
Macro Recall Train Dev:  0.5084494556195663
Macro Recall Test:  0.4854889323124001
Micro Recall Train Dev:  0.7247051520794537
Micro Recall Test:  0.7048417132216015
Confusion Matrix Train Dev: 
[[8653 1264   28]
 [2369 2935   43]
 [ 305  426   87]]
Confusion Matrix Test: 
[[2886  445   15]
 [ 865  873   15]
 [  99  146   26]]


#### OLID

In [21]:
bert_bertweet_hatebert_interleaved_olid_train_dev = np.concatenate((bert_hatebert_bertweet_interleaved_olid_train, bert_hatebert_bertweet_interleaved_olid_dev))
bert_bertweet_hatebert_interleaved_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_interleaved_olid_train_dev, bert_bertweet_hatebert_interleaved_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_interleaved_olid_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_interleaved_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_bertweet_hatebert_interleaved_olid_seed_7")

save_model(mlp, "Saves/bert_bertweet_hatebert_interleaved_olid_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7802114803625377
Accuracy Test:  0.8046511627906977
Weighted F1 Train Dev:  0.7698445597774969
Weighted F1 Test:  0.7830155377794796
Macro F1 Train Dev:  0.7314869536128457
Macro F1 Test:  0.7096089529199897
Micro F1 Train Dev:  0.7802114803625377
Micro F1 Test:  0.8046511627906977
Weighted Recall Train Dev:  0.7802114803625377
Weighted Recall Test:  0.8046511627906977
Macro Recall Train Dev:  0.7181175442204855
Macro Recall Test:  0.685752688172043
Micro Recall Train Dev:  0.7802114803625377
Micro Recall Test:  0.8046511627906977
Confusion Matrix Train Dev: 
[[7985  855]
 [2055 2345]]
Confusion Matrix Test: 
[[592  28]
 [140 100]]
