In [1]:
from utils import *
import numpy as np
import torch, os
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV

In [2]:
set_random_seed(42)

Seed: 42


In [3]:
# def scaling_embeddings(embeddings):
#     for i in range(len(embeddings)):
#         embeddings[i] = StandardScaler().fit_transform(embeddings[i])
#     return embeddings

def reshape_embeddings(embeddings):
    if embeddings.shape[1] == 1:
        embeddings = embeddings.squeeze(1)
    return embeddings

In [4]:
def interleave_2_embeddings(embeddings1, embeddings2):
    embeddings1 = reshape_embeddings(embeddings1)
    embeddings2 = reshape_embeddings(embeddings2)
    new_embeddings = []
    for i in range(len(embeddings1)):
        embedding = []
        for j in range(len(embeddings1[i])):
            embedding.append(embeddings1[i][j])
            embedding.append(embeddings2[i][j])
        new_embeddings.append(np.array(embedding))
    return np.array(new_embeddings)
    

def interleave_3_embeddings(embeddings1, embeddings2, embeddings3):
    embeddings1 = reshape_embeddings(embeddings1)
    embeddings2 = reshape_embeddings(embeddings2)
    embeddings3 = reshape_embeddings(embeddings3)
    new_embeddings = []
    for i in range(len(embeddings1)):
        embedding = []
        for j in range(len(embeddings1[i])):
            embedding.append(embeddings1[i][j])
            embedding.append(embeddings2[i][j])
            embedding.append(embeddings3[i][j])
        new_embeddings.append(np.array(embedding))
    return np.array(new_embeddings)

In [5]:
bert_hatebert_interleaved_dynahate_train = interleave_2_embeddings(bert_dynahate_train_embeddings, hatebert_dynahate_train_embeddings)
bert_hatebert_interleaved_dynahate_dev = interleave_2_embeddings(bert_dynahate_dev_embeddings, hatebert_dynahate_dev_embeddings)
bert_hatebert_interleaved_dynahate_test = interleave_2_embeddings(bert_dynahate_test_embeddings, hatebert_dynahate_test_embeddings)

bert_bertweet_interleaved_dynahate_train = interleave_2_embeddings(bert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
bert_bertweet_interleaved_dynahate_dev = interleave_2_embeddings(bert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
bert_bertweet_interleaved_dynahate_test = interleave_2_embeddings(bert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

hatebert_bertweet_interleaved_dynahate_train = interleave_2_embeddings(hatebert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
hatebert_bertweet_interleaved_dynahate_dev = interleave_2_embeddings(hatebert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
hatebert_bertweet_interleaved_dynahate_test = interleave_2_embeddings(hatebert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

bert_hatebert_bertweet_interleaved_dynahate_train = interleave_3_embeddings(bert_dynahate_train_embeddings, hatebert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
bert_hatebert_bertweet_interleaved_dynahate_dev = interleave_3_embeddings(bert_dynahate_dev_embeddings, hatebert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
bert_hatebert_bertweet_interleaved_dynahate_test = interleave_3_embeddings(bert_dynahate_test_embeddings, hatebert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

bert_hatebert_interleaved_olid_train = interleave_2_embeddings(bert_olid_train_embeddings, hatebert_olid_train_embeddings)
bert_hatebert_interleaved_olid_dev = interleave_2_embeddings(bert_olid_dev_embeddings, hatebert_olid_dev_embeddings)
bert_hatebert_interleaved_olid_test = interleave_2_embeddings(bert_olid_test_embeddings, hatebert_olid_test_embeddings)

bert_bertweet_interleaved_olid_train = interleave_2_embeddings(bert_olid_train_embeddings, bertweet_olid_train_embeddings)
bert_bertweet_interleaved_olid_dev = interleave_2_embeddings(bert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
bert_bertweet_interleaved_olid_test = interleave_2_embeddings(bert_olid_test_embeddings, bertweet_olid_test_embeddings)

hatebert_bertweet_interleaved_olid_train = interleave_2_embeddings(hatebert_olid_train_embeddings, bertweet_olid_train_embeddings)
hatebert_bertweet_interleaved_olid_dev = interleave_2_embeddings(hatebert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
hatebert_bertweet_interleaved_olid_test = interleave_2_embeddings(hatebert_olid_test_embeddings, bertweet_olid_test_embeddings)

bert_hatebert_bertweet_interleaved_olid_train = interleave_3_embeddings(bert_olid_train_embeddings, hatebert_olid_train_embeddings, bertweet_olid_train_embeddings)
bert_hatebert_bertweet_interleaved_olid_dev = interleave_3_embeddings(bert_olid_dev_embeddings, hatebert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
bert_hatebert_bertweet_interleaved_olid_test = interleave_3_embeddings(bert_olid_test_embeddings, hatebert_olid_test_embeddings, bertweet_olid_test_embeddings)

bert_hatebert_interleaved_latenthatred_train = interleave_2_embeddings(bert_latenthatred_train_embeddings, hatebert_latenthatred_train_embeddings)
bert_hatebert_interleaved_latenthatred_dev = interleave_2_embeddings(bert_latenthatred_dev_embeddings, hatebert_latenthatred_dev_embeddings)
bert_hatebert_interleaved_latenthatred_test = interleave_2_embeddings(bert_latenthatred_test_embeddings, hatebert_latenthatred_test_embeddings)

bert_bertweet_interleaved_latenthatred_train = interleave_2_embeddings(bert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
bert_bertweet_interleaved_latenthatred_dev = interleave_2_embeddings(bert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
bert_bertweet_interleaved_latenthatred_test = interleave_2_embeddings(bert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

hatebert_bertweet_interleaved_latenthatred_train = interleave_2_embeddings(hatebert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
hatebert_bertweet_interleaved_latenthatred_dev = interleave_2_embeddings(hatebert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
hatebert_bertweet_interleaved_latenthatred_test = interleave_2_embeddings(hatebert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

bert_hatebert_bertweet_interleaved_latenthatred_train = interleave_3_embeddings(bert_latenthatred_train_embeddings, hatebert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
bert_hatebert_bertweet_interleaved_latenthatred_dev = interleave_3_embeddings(bert_latenthatred_dev_embeddings, hatebert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
bert_hatebert_bertweet_interleaved_latenthatred_test = interleave_3_embeddings(bert_latenthatred_test_embeddings, hatebert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

In [6]:
bert_hatebert_bertweet_interleaved_latenthatred_test.shape

(5370, 2304)

In [7]:
dynahate_labels_train = process_labels(read_labels("dynahate", "train"))
dynahate_labels_dev = process_labels(read_labels("dynahate", "dev"))
dynahate_labels_test = process_labels(read_labels("dynahate", "test"))

latenthatred_labels_train = read_labels("latenthatred", "train")
latenthatred_labels_dev = read_labels("latenthatred", "dev")
latenthatred_labels_test = read_labels("latenthatred", "test")

olid_labels_train = read_labels("olid", "train")
olid_labels_dev = read_labels("olid", "dev")
olid_labels_test = read_labels("olid", "test")

In [8]:
mlp = MLPClassifier(random_state=42)
gridsearch = GridSearchCV(
    mlp,
    param_grid={
        "hidden_layer_sizes": [(128), (128,64)],
        "activation": ["relu"],
        "solver": ["adam"],
        "learning_rate_init": [0.001, 0.0001],
        "learning_rate": ["adaptive"],
        "early_stopping": [True],
        "max_iter": [10000]
    },
    verbose=4,
    n_jobs=os.cpu_count()//3,
    cv=5,
)

In [9]:
dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))
latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))
olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

### BERT-BERTweet

#### DynaHate

In [10]:
bert_bertweet_interleaved_dynahate_train_dev = np.concatenate((bert_bertweet_interleaved_dynahate_train, bert_bertweet_interleaved_dynahate_dev))
bert_bertweet_interleaved_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_interleaved_dynahate_train_dev, bert_bertweet_interleaved_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_interleaved_dynahate_train_dev)
test_preds = mlp.predict(bert_bertweet_interleaved_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_bertweet_interleaved_dynahate_seed_42")
save_model(mlp, "Saves/bert_bertweet_interleaved_dynahate_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.6924697493517719
Accuracy Test:  0.6696601941747573
Weighted F1 Train Dev:  0.6780999075257311
Weighted F1 Test:  0.6519720008415162
Macro F1 Train Dev:  0.6719109821329163
Macro F1 Test:  0.641905942802353
Micro F1 Train Dev:  0.6924697493517719
Micro F1 Test:  0.6696601941747573
Weighted Recall Train Dev:  0.6924697493517719
Weighted Recall Test:  0.6696601941747573
Macro Recall Train Dev:  0.6774531835346683
Macro Recall Test:  0.6481581473482122
Micro Recall Train Dev:  0.6924697493517719
Micro Recall Test:  0.6696601941747573
Confusion Matrix Train Dev: 
[[ 8185  8932]
 [ 2454 17453]]
Confusion Matrix Test: 
[[ 806 1046]
 [ 315 1953]]


#### LatentHatred

In [11]:
bert_bertweet_interleaved_latenthatred_train_dev = np.concatenate((bert_bertweet_interleaved_latenthatred_train, bert_bertweet_interleaved_latenthatred_dev))
bert_bertweet_interleaved_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_interleaved_latenthatred_train_dev, bert_bertweet_interleaved_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_interleaved_latenthatred_train_dev)
test_preds = mlp.predict(bert_bertweet_interleaved_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_bertweet_interleaved_latenthatred_seed_42")
save_model(mlp, "Saves/bert_bertweet_interleaved_latenthatred_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7279329608938547
Accuracy Test:  0.7080074487895717
Weighted F1 Train Dev:  0.7104410384280689
Weighted F1 Test:  0.6893742182444357
Macro F1 Train Dev:  0.5310261451092892
Macro F1 Test:  0.5103472377930791
Micro F1 Train Dev:  0.7279329608938547
Micro F1 Test:  0.7080074487895716
Weighted Recall Train Dev:  0.7279329608938547
Weighted Recall Test:  0.7080074487895717
Macro Recall Train Dev:  0.5123533547880236
Macro Recall Test:  0.4924747737351618
Micro Recall Train Dev:  0.7279329608938547
Micro Recall Test:  0.7080074487895717
Confusion Matrix Train Dev: 
[[8642 1281   22]
 [2306 2997   44]
 [ 316  414   88]]
Confusion Matrix Test: 
[[2879  459    8]
 [ 838  894   21]
 [ 107  135   29]]


#### OLID

In [12]:
bert_bertweet_interleaved_olid_train_dev = np.concatenate((bert_bertweet_interleaved_olid_train, bert_bertweet_interleaved_olid_dev))
bert_bertweet_interleaved_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_interleaved_olid_train_dev, bert_bertweet_interleaved_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_interleaved_olid_train_dev)
test_preds = mlp.predict(bert_bertweet_interleaved_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_bertweet_interleaved_olid_seed_42")

save_model(mlp, "Saves/bert_bertweet_interleaved_olid_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7759063444108761
Accuracy Test:  0.8174418604651162
Weighted F1 Train Dev:  0.7658267599180697
Weighted F1 Test:  0.8014139679674042
Macro F1 Train Dev:  0.7271462455290796
Macro F1 Test:  0.7373023979765554
Micro F1 Train Dev:  0.7759063444108761
Micro F1 Test:  0.8174418604651161
Weighted Recall Train Dev:  0.7759063444108761
Weighted Recall Test:  0.8174418604651162
Macro Recall Train Dev:  0.7144940353763883
Macro Recall Test:  0.7124999999999999
Micro Recall Train Dev:  0.7759063444108761
Micro Recall Test:  0.8174418604651162
Confusion Matrix Train Dev: 
[[7935  905]
 [2062 2338]]
Confusion Matrix Test: 
[[589  31]
 [126 114]]


### BERT-HateBERT

#### DynaHate

In [13]:
bert_hatebert_interleaved_dynahate_train_dev = np.concatenate((bert_hatebert_interleaved_dynahate_train, bert_hatebert_interleaved_dynahate_dev))
bert_hatebert_interleaved_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_interleaved_dynahate_train_dev, bert_hatebert_interleaved_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_interleaved_dynahate_train_dev)
test_preds = mlp.predict(bert_hatebert_interleaved_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_hatebert_interleaved_dynahate_seed_42")

save_model(mlp, "Saves/bert_hatebert_interleaved_dynahate_seed_42")



Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7144824978392394
Accuracy Test:  0.6861650485436893
Weighted F1 Train Dev:  0.710997684497674
Weighted F1 Test:  0.6829153382637936
Macro F1 Train Dev:  0.7076229433581505
Macro F1 Test:  0.6776138501209048
Micro F1 Train Dev:  0.7144824978392394
Micro F1 Test:  0.6861650485436893
Weighted Recall Train Dev:  0.7144824978392394
Weighted Recall Test:  0.6861650485436893
Macro Recall Train Dev:  0.7069545862995652
Macro Recall Test:  0.6766187276446456
Micro Recall Train Dev:  0.7144824978392394
Micro Recall Test:  0.6861650485436893
Confusion Matrix Train Dev: 
[[10391  6726]
 [ 3845 16062]]
Confusion Matrix Test: 
[[1078  774]
 [ 519 1749]]


#### LatentHatred

In [14]:
bert_hatebert_interleaved_latenthatred_train_dev = np.concatenate((bert_hatebert_interleaved_latenthatred_train, bert_hatebert_interleaved_latenthatred_dev))
bert_hatebert_interleaved_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_interleaved_latenthatred_train_dev, bert_hatebert_interleaved_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_interleaved_latenthatred_train_dev)
test_preds = mlp.predict(bert_hatebert_interleaved_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_hatebert_interleaved_latenthatred_seed_42")

save_model(mlp, "Saves/bert_hatebert_interleaved_latenthatred_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7148355058969584
Accuracy Test:  0.6972067039106146
Weighted F1 Train Dev:  0.6855581603234941
Weighted F1 Test:  0.6641530693568959
Macro F1 Train Dev:  0.5096210673617565
Macro F1 Test:  0.47755254086379395
Micro F1 Train Dev:  0.7148355058969585
Micro F1 Test:  0.6972067039106146
Weighted Recall Train Dev:  0.7148355058969584
Weighted Recall Test:  0.6972067039106146
Macro Recall Train Dev:  0.48832774625460357
Macro Recall Test:  0.46271147912393346
Micro Recall Train Dev:  0.7148355058969584
Micro Recall Test:  0.6972067039106146
Confusion Matrix Train Dev: 
[[9115  801   29]
 [2978 2305   64]
 [ 416  306   96]]
Confusion Matrix Test: 
[[3040  289   17]
 [1052  679   22]
 [ 151   95   25]]


#### OLID

In [15]:
bert_hatebert_interleaved_olid_train_dev = np.concatenate((bert_hatebert_interleaved_olid_train, bert_hatebert_interleaved_olid_dev))
bert_hatebert_interleaved_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_interleaved_olid_train_dev, bert_hatebert_interleaved_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_interleaved_olid_train_dev)
test_preds = mlp.predict(bert_hatebert_interleaved_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_hatebert_interleaved_olid_seed_42")

save_model(mlp, "Saves/bert_hatebert_interleaved_olid_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7608006042296073
Accuracy Test:  0.7965116279069767
Weighted F1 Train Dev:  0.759814110894104
Weighted F1 Test:  0.7834730123172956
Macro F1 Train Dev:  0.7283031007528467
Macro F1 Test:  0.7174106933295781
Micro F1 Train Dev:  0.7608006042296073
Micro F1 Test:  0.7965116279069767
Weighted Recall Train Dev:  0.7608006042296073
Weighted Recall Test:  0.7965116279069767
Macro Recall Train Dev:  0.7265256067461949
Macro Recall Test:  0.699260752688172
Micro Recall Train Dev:  0.7608006042296073
Micro Recall Test:  0.7965116279069767
Confusion Matrix Train Dev: 
[[7326 1514]
 [1653 2747]]
Confusion Matrix Test: 
[[570  50]
 [125 115]]


### BERTweet-HateBERT

#### DynaHate

In [16]:
hatebert_bertweet_interleaved_dynahate_train_dev = np.concatenate((hatebert_bertweet_interleaved_dynahate_train, hatebert_bertweet_interleaved_dynahate_dev))
hatebert_bertweet_interleaved_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_interleaved_dynahate_train_dev, hatebert_bertweet_interleaved_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_interleaved_dynahate_train_dev)
test_preds = mlp.predict(hatebert_bertweet_interleaved_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/hatebert_bertweet_interleaved_dynahate_seed_42")

save_model(mlp, "Saves/hatebert_bertweet_interleaved_dynahate_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7538623595505618
Accuracy Test:  0.7007281553398058
Weighted F1 Train Dev:  0.7529105823867874
Weighted F1 Test:  0.7000286058655765
Macro F1 Train Dev:  0.7508440778833396
Macro F1 Test:  0.6963449023050772
Micro F1 Train Dev:  0.7538623595505618
Micro F1 Test:  0.7007281553398058
Weighted Recall Train Dev:  0.7538623595505618
Weighted Recall Test:  0.7007281553398058
Macro Recall Train Dev:  0.7498263064513058
Macro Recall Test:  0.6956895829286038
Micro Recall Train Dev:  0.7538623595505618
Micro Recall Test:  0.7007281553398058
Confusion Matrix Train Dev: 
[[11918  5199]
 [ 3914 15993]]
Confusion Matrix Test: 
[[1196  656]
 [ 577 1691]]


#### LatentHatred

In [17]:
hatebert_bertweet_interleaved_latenthatred_train_dev = np.concatenate((hatebert_bertweet_interleaved_latenthatred_train, hatebert_bertweet_interleaved_latenthatred_dev))
hatebert_bertweet_interleaved_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_interleaved_latenthatred_train_dev, hatebert_bertweet_interleaved_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_interleaved_latenthatred_train_dev)
test_preds = mlp.predict(hatebert_bertweet_interleaved_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/hatebert_bertweet_interleaved_latenthatred_seed_42")

save_model(mlp, "Saves/hatebert_bertweet_interleaved_latenthatred_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7394165114835506
Accuracy Test:  0.7100558659217877
Weighted F1 Train Dev:  0.7195510009103481
Weighted F1 Test:  0.6874701121504219
Macro F1 Train Dev:  0.5427116404396695
Macro F1 Test:  0.5079223173799048
Micro F1 Train Dev:  0.7394165114835506
Micro F1 Test:  0.7100558659217877
Weighted Recall Train Dev:  0.7394165114835506
Weighted Recall Test:  0.7100558659217877
Macro Recall Train Dev:  0.5200731641078138
Macro Recall Test:  0.4889071584917131
Micro Recall Train Dev:  0.7394165114835506
Micro Recall Test:  0.7100558659217877
Confusion Matrix Train Dev: 
[[8918 1008   19]
 [2397 2894   56]
 [ 330  388  100]]
Confusion Matrix Test: 
[[2953  380   13]
 [ 902  830   21]
 [ 115  126   30]]


#### OLID

In [18]:
hatebert_bertweet_interleaved_olid_train_dev = np.concatenate((hatebert_bertweet_interleaved_olid_train, hatebert_bertweet_interleaved_olid_dev))
hatebert_bertweet_interleaved_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_interleaved_olid_train_dev, hatebert_bertweet_interleaved_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_interleaved_olid_train_dev)
test_preds = mlp.predict(hatebert_bertweet_interleaved_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/hatebert_bertweet_interleaved_olid_seed_42")

save_model(mlp, "Saves/hatebert_bertweet_interleaved_olid_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7757552870090635
Accuracy Test:  0.7953488372093023
Weighted F1 Train Dev:  0.7627573809101216
Weighted F1 Test:  0.7760572900491423
Macro F1 Train Dev:  0.721564873358871
Macro F1 Test:  0.7027494108405341
Micro F1 Train Dev:  0.7757552870090636
Micro F1 Test:  0.7953488372093023
Weighted Recall Train Dev:  0.7757552870090635
Weighted Recall Test:  0.7953488372093023
Macro Recall Train Dev:  0.7073606540518305
Macro Recall Test:  0.6818548387096774
Micro Recall Train Dev:  0.7757552870090635
Micro Recall Test:  0.7953488372093023
Confusion Matrix Train Dev: 
[[8056  784]
 [2185 2215]]
Confusion Matrix Test: 
[[582  38]
 [138 102]]


### BERT-BERTweet-HateBERT

#### DynaHate

In [19]:
bert_bertweet_hatebert_interleaved_dynahate_train_dev = np.concatenate((bert_hatebert_bertweet_interleaved_dynahate_train, bert_hatebert_bertweet_interleaved_dynahate_dev))
bert_bertweet_hatebert_interleaved_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_interleaved_dynahate_train_dev, bert_bertweet_hatebert_interleaved_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_interleaved_dynahate_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_interleaved_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_bertweet_hatebert_interleaved_dynahate_seed_42")

save_model(mlp, "Saves/bert_bertweet_hatebert_interleaved_dynahate_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7628835350043215
Accuracy Test:  0.7182038834951456
Weighted F1 Train Dev:  0.7606924889403566
Weighted F1 Test:  0.7156599759171588
Macro F1 Train Dev:  0.7581400803731488
Macro F1 Test:  0.711078739759399
Micro F1 Train Dev:  0.7628835350043215
Micro F1 Test:  0.7182038834951456
Weighted Recall Train Dev:  0.7628835350043215
Weighted Recall Test:  0.7182038834951456
Macro Recall Train Dev:  0.7566268693034224
Macro Recall Test:  0.7095818048841807
Micro Recall Train Dev:  0.7628835350043215
Micro Recall Test:  0.7182038834951456
Confusion Matrix Train Dev: 
[[11530  5587]
 [ 3192 16715]]
Confusion Matrix Test: 
[[1156  696]
 [ 465 1803]]


#### LatentHatred

In [20]:
bert_bertweet_hatebert_interleaved_latenthatred_train_dev = np.concatenate((bert_hatebert_bertweet_interleaved_latenthatred_train, bert_hatebert_bertweet_interleaved_latenthatred_dev))
bert_bertweet_hatebert_interleaved_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_interleaved_latenthatred_train_dev, bert_bertweet_hatebert_interleaved_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_interleaved_latenthatred_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_interleaved_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_bertweet_hatebert_interleaved_latenthatred_seed_42")

save_model(mlp, "Saves/bert_bertweet_hatebert_interleaved_latenthatred_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7129733085040347
Accuracy Test:  0.6893854748603352
Weighted F1 Train Dev:  0.6895555792164443
Weighted F1 Test:  0.6636341837855085
Macro F1 Train Dev:  0.4836559644927296
Macro F1 Test:  0.4541776833515045
Micro F1 Train Dev:  0.7129733085040346
Micro F1 Test:  0.6893854748603352
Weighted Recall Train Dev:  0.7129733085040347
Weighted Recall Test:  0.6893854748603352
Macro Recall Train Dev:  0.47831614403968237
Macro Recall Test:  0.4522563496184057
Micro Recall Train Dev:  0.7129733085040347
Micro Recall Test:  0.6893854748603352
Confusion Matrix Train Dev: 
[[8655 1276   14]
 [2542 2797    8]
 [ 353  431   34]]
Confusion Matrix Test: 
[[2872  469    5]
 [ 929  822    2]
 [ 126  137    8]]


#### OLID

In [21]:
bert_bertweet_hatebert_interleaved_olid_train_dev = np.concatenate((bert_hatebert_bertweet_interleaved_olid_train, bert_hatebert_bertweet_interleaved_olid_dev))
bert_bertweet_hatebert_interleaved_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_interleaved_olid_train_dev, bert_bertweet_hatebert_interleaved_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_interleaved_olid_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_interleaved_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_bertweet_hatebert_interleaved_olid_seed_42")

save_model(mlp, "Saves/bert_bertweet_hatebert_interleaved_olid_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7828549848942599
Accuracy Test:  0.8104651162790698
Weighted F1 Train Dev:  0.7784488909786428
Weighted F1 Test:  0.7965976255054642
Macro F1 Train Dev:  0.74600601040594
Macro F1 Test:  0.7331079087106436
Micro F1 Train Dev:  0.7828549848942599
Micro F1 Test:  0.8104651162790698
Weighted Recall Train Dev:  0.7828549848942599
Weighted Recall Test:  0.8104651162790698
Macro Recall Train Dev:  0.7381329699712053
Macro Recall Test:  0.7114919354838709
Micro Recall Train Dev:  0.7828549848942599
Micro Recall Test:  0.8104651162790698
Confusion Matrix Train Dev: 
[[7704 1136]
 [1739 2661]]
Confusion Matrix Test: 
[[580  40]
 [123 117]]
