In [1]:
from utils import *
import numpy as np
import torch, os
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV

In [2]:
set_random_seed(3)

Seed: 3


In [3]:
# def scaling_embeddings(embeddings):
#     for i in range(len(embeddings)):
#         embeddings[i] = StandardScaler().fit_transform(embeddings[i])
#     return embeddings

def reshape_embeddings(embeddings):
    if embeddings.shape[1] == 1:
        embeddings = embeddings.squeeze(1)
    return embeddings

In [4]:
def interleave_2_embeddings(embeddings1, embeddings2):
    embeddings1 = reshape_embeddings(embeddings1)
    embeddings2 = reshape_embeddings(embeddings2)
    new_embeddings = []
    for i in range(len(embeddings1)):
        embedding = []
        for j in range(len(embeddings1[i])):
            embedding.append(embeddings1[i][j])
            embedding.append(embeddings2[i][j])
        new_embeddings.append(np.array(embedding))
    return np.array(new_embeddings)
    

def interleave_3_embeddings(embeddings1, embeddings2, embeddings3):
    embeddings1 = reshape_embeddings(embeddings1)
    embeddings2 = reshape_embeddings(embeddings2)
    embeddings3 = reshape_embeddings(embeddings3)
    new_embeddings = []
    for i in range(len(embeddings1)):
        embedding = []
        for j in range(len(embeddings1[i])):
            embedding.append(embeddings1[i][j])
            embedding.append(embeddings2[i][j])
            embedding.append(embeddings3[i][j])
        new_embeddings.append(np.array(embedding))
    return np.array(new_embeddings)

In [5]:
bert_hatebert_interleaved_dynahate_train = interleave_2_embeddings(bert_dynahate_train_embeddings, hatebert_dynahate_train_embeddings)
bert_hatebert_interleaved_dynahate_dev = interleave_2_embeddings(bert_dynahate_dev_embeddings, hatebert_dynahate_dev_embeddings)
bert_hatebert_interleaved_dynahate_test = interleave_2_embeddings(bert_dynahate_test_embeddings, hatebert_dynahate_test_embeddings)

bert_bertweet_interleaved_dynahate_train = interleave_2_embeddings(bert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
bert_bertweet_interleaved_dynahate_dev = interleave_2_embeddings(bert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
bert_bertweet_interleaved_dynahate_test = interleave_2_embeddings(bert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

hatebert_bertweet_interleaved_dynahate_train = interleave_2_embeddings(hatebert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
hatebert_bertweet_interleaved_dynahate_dev = interleave_2_embeddings(hatebert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
hatebert_bertweet_interleaved_dynahate_test = interleave_2_embeddings(hatebert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

bert_hatebert_bertweet_interleaved_dynahate_train = interleave_3_embeddings(bert_dynahate_train_embeddings, hatebert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
bert_hatebert_bertweet_interleaved_dynahate_dev = interleave_3_embeddings(bert_dynahate_dev_embeddings, hatebert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
bert_hatebert_bertweet_interleaved_dynahate_test = interleave_3_embeddings(bert_dynahate_test_embeddings, hatebert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

bert_hatebert_interleaved_olid_train = interleave_2_embeddings(bert_olid_train_embeddings, hatebert_olid_train_embeddings)
bert_hatebert_interleaved_olid_dev = interleave_2_embeddings(bert_olid_dev_embeddings, hatebert_olid_dev_embeddings)
bert_hatebert_interleaved_olid_test = interleave_2_embeddings(bert_olid_test_embeddings, hatebert_olid_test_embeddings)

bert_bertweet_interleaved_olid_train = interleave_2_embeddings(bert_olid_train_embeddings, bertweet_olid_train_embeddings)
bert_bertweet_interleaved_olid_dev = interleave_2_embeddings(bert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
bert_bertweet_interleaved_olid_test = interleave_2_embeddings(bert_olid_test_embeddings, bertweet_olid_test_embeddings)

hatebert_bertweet_interleaved_olid_train = interleave_2_embeddings(hatebert_olid_train_embeddings, bertweet_olid_train_embeddings)
hatebert_bertweet_interleaved_olid_dev = interleave_2_embeddings(hatebert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
hatebert_bertweet_interleaved_olid_test = interleave_2_embeddings(hatebert_olid_test_embeddings, bertweet_olid_test_embeddings)

bert_hatebert_bertweet_interleaved_olid_train = interleave_3_embeddings(bert_olid_train_embeddings, hatebert_olid_train_embeddings, bertweet_olid_train_embeddings)
bert_hatebert_bertweet_interleaved_olid_dev = interleave_3_embeddings(bert_olid_dev_embeddings, hatebert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
bert_hatebert_bertweet_interleaved_olid_test = interleave_3_embeddings(bert_olid_test_embeddings, hatebert_olid_test_embeddings, bertweet_olid_test_embeddings)

bert_hatebert_interleaved_latenthatred_train = interleave_2_embeddings(bert_latenthatred_train_embeddings, hatebert_latenthatred_train_embeddings)
bert_hatebert_interleaved_latenthatred_dev = interleave_2_embeddings(bert_latenthatred_dev_embeddings, hatebert_latenthatred_dev_embeddings)
bert_hatebert_interleaved_latenthatred_test = interleave_2_embeddings(bert_latenthatred_test_embeddings, hatebert_latenthatred_test_embeddings)

bert_bertweet_interleaved_latenthatred_train = interleave_2_embeddings(bert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
bert_bertweet_interleaved_latenthatred_dev = interleave_2_embeddings(bert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
bert_bertweet_interleaved_latenthatred_test = interleave_2_embeddings(bert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

hatebert_bertweet_interleaved_latenthatred_train = interleave_2_embeddings(hatebert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
hatebert_bertweet_interleaved_latenthatred_dev = interleave_2_embeddings(hatebert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
hatebert_bertweet_interleaved_latenthatred_test = interleave_2_embeddings(hatebert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

bert_hatebert_bertweet_interleaved_latenthatred_train = interleave_3_embeddings(bert_latenthatred_train_embeddings, hatebert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
bert_hatebert_bertweet_interleaved_latenthatred_dev = interleave_3_embeddings(bert_latenthatred_dev_embeddings, hatebert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
bert_hatebert_bertweet_interleaved_latenthatred_test = interleave_3_embeddings(bert_latenthatred_test_embeddings, hatebert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

In [6]:
dynahate_labels_train = process_labels(read_labels("dynahate", "train"))
dynahate_labels_dev = process_labels(read_labels("dynahate", "dev"))
dynahate_labels_test = process_labels(read_labels("dynahate", "test"))

latenthatred_labels_train = read_labels("latenthatred", "train")
latenthatred_labels_dev = read_labels("latenthatred", "dev")
latenthatred_labels_test = read_labels("latenthatred", "test")

olid_labels_train = read_labels("olid", "train")
olid_labels_dev = read_labels("olid", "dev")
olid_labels_test = read_labels("olid", "test")

In [7]:
mlp = MLPClassifier(random_state=3)
gridsearch = GridSearchCV(
    mlp,
    param_grid={
        "hidden_layer_sizes": [(128), (128,64)],
        "activation": ["relu"],
        "solver": ["adam"],
        "learning_rate_init": [0.001, 0.0001],
        "learning_rate": ["adaptive"],
        "early_stopping": [True],
        "max_iter": [10000]
    },
    verbose=4,
    n_jobs=os.cpu_count()//3,
    cv=5,
)

In [8]:
dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))
latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))
olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

### BERT-BERTweet

#### DynaHate

In [9]:
bert_bertweet_interleaved_dynahate_train_dev = np.concatenate((bert_bertweet_interleaved_dynahate_train, bert_bertweet_interleaved_dynahate_dev))
bert_bertweet_interleaved_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_interleaved_dynahate_train_dev, bert_bertweet_interleaved_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_interleaved_dynahate_train_dev)
test_preds = mlp.predict(bert_bertweet_interleaved_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_bertweet_interleaved_dynahate_seed_3")
save_model(mlp, "Saves/bert_bertweet_interleaved_dynahate_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7314444684528955
Accuracy Test:  0.6847087378640777
Weighted F1 Train Dev:  0.7306682200919097
Weighted F1 Test:  0.6840992717101301
Macro F1 Train Dev:  0.7285594246419094
Macro F1 Test:  0.6803151236497984
Micro F1 Train Dev:  0.7314444684528956
Micro F1 Test:  0.6847087378640777
Weighted Recall Train Dev:  0.7314444684528955
Weighted Recall Test:  0.6847087378640777
Macro Recall Train Dev:  0.7278085033244159
Macro Recall Test:  0.6798022824840679
Micro Recall Train Dev:  0.7314444684528955
Micro Recall Test:  0.6847087378640777
Confusion Matrix Train Dev: 
[[11632  5485]
 [ 4458 15449]]
Confusion Matrix Test: 
[[1169  683]
 [ 616 1652]]


#### LatentHatred

In [10]:
bert_bertweet_interleaved_latenthatred_train_dev = np.concatenate((bert_bertweet_interleaved_latenthatred_train, bert_bertweet_interleaved_latenthatred_dev))
bert_bertweet_interleaved_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_interleaved_latenthatred_train_dev, bert_bertweet_interleaved_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_interleaved_latenthatred_train_dev)
test_preds = mlp.predict(bert_bertweet_interleaved_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_bertweet_interleaved_latenthatred_seed_3")
save_model(mlp, "Saves/bert_bertweet_interleaved_latenthatred_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.6987585350713842
Accuracy Test:  0.6864059590316574
Weighted F1 Train Dev:  0.6801955007408066
Weighted F1 Test:  0.6684773945150163
Macro F1 Train Dev:  0.4645488094132229
Macro F1 Test:  0.45374594714729916
Micro F1 Train Dev:  0.6987585350713842
Micro F1 Test:  0.6864059590316574
Weighted Recall Train Dev:  0.6987585350713842
Weighted Recall Test:  0.6864059590316574
Macro Recall Train Dev:  0.47111815904853915
Macro Recall Test:  0.4596296313962485
Micro Recall Train Dev:  0.6987585350713842
Micro Recall Test:  0.6864059590316574
Confusion Matrix Train Dev: 
[[8134 1807    4]
 [2233 3112    2]
 [ 320  487   11]]
Confusion Matrix Test: 
[[2711  633    2]
 [ 779  971    3]
 [  97  170    4]]


#### OLID

In [11]:
bert_bertweet_interleaved_olid_train_dev = np.concatenate((bert_bertweet_interleaved_olid_train, bert_bertweet_interleaved_olid_dev))
bert_bertweet_interleaved_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_interleaved_olid_train_dev, bert_bertweet_interleaved_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_interleaved_olid_train_dev)
test_preds = mlp.predict(bert_bertweet_interleaved_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_bertweet_interleaved_olid_seed_3")

save_model(mlp, "Saves/bert_bertweet_interleaved_olid_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7706948640483384
Accuracy Test:  0.8046511627906977
Weighted F1 Train Dev:  0.763554407803608
Weighted F1 Test:  0.7862365041378178
Macro F1 Train Dev:  0.7268603965459657
Macro F1 Test:  0.7162608012568735
Micro F1 Train Dev:  0.7706948640483384
Micro F1 Test:  0.8046511627906977
Weighted Recall Train Dev:  0.7706948640483384
Weighted Recall Test:  0.8046511627906977
Macro Recall Train Dev:  0.716983751542575
Macro Recall Test:  0.6934139784946236
Micro Recall Train Dev:  0.7706948640483384
Micro Recall Test:  0.8046511627906977
Confusion Matrix Train Dev: 
[[7754 1086]
 [1950 2450]]
Confusion Matrix Test: 
[[586  34]
 [134 106]]


### BERT-HateBERT

#### DynaHate

In [12]:
bert_hatebert_interleaved_dynahate_train_dev = np.concatenate((bert_hatebert_interleaved_dynahate_train, bert_hatebert_interleaved_dynahate_dev))
bert_hatebert_interleaved_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_interleaved_dynahate_train_dev, bert_hatebert_interleaved_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_interleaved_dynahate_train_dev)
test_preds = mlp.predict(bert_hatebert_interleaved_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_hatebert_interleaved_dynahate_seed_3")

save_model(mlp, "Saves/bert_hatebert_interleaved_dynahate_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7235847018150389
Accuracy Test:  0.6944174757281554
Weighted F1 Train Dev:  0.7220984050061429
Weighted F1 Test:  0.6928463955139764
Macro F1 Train Dev:  0.7195698878739356
Macro F1 Test:  0.6885181215464372
Micro F1 Train Dev:  0.7235847018150388
Micro F1 Test:  0.6944174757281554
Weighted Recall Train Dev:  0.7235847018150389
Weighted Recall Test:  0.6944174757281554
Macro Recall Train Dev:  0.7186490587788101
Macro Recall Test:  0.687531187981152
Micro Recall Train Dev:  0.7235847018150389
Micro Recall Test:  0.6944174757281554
Confusion Matrix Train Dev: 
[[11180  5937]
 [ 4297 15610]]
Confusion Matrix Test: 
[[1147  705]
 [ 554 1714]]


#### LatentHatred

In [13]:
bert_hatebert_interleaved_latenthatred_train_dev = np.concatenate((bert_hatebert_interleaved_latenthatred_train, bert_hatebert_interleaved_latenthatred_dev))
bert_hatebert_interleaved_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_interleaved_latenthatred_train_dev, bert_hatebert_interleaved_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_interleaved_latenthatred_train_dev)
test_preds = mlp.predict(bert_hatebert_interleaved_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_hatebert_interleaved_latenthatred_seed_3")

save_model(mlp, "Saves/bert_hatebert_interleaved_latenthatred_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.6975170701427684
Accuracy Test:  0.6797020484171322
Weighted F1 Train Dev:  0.6788462017400225
Weighted F1 Test:  0.6612729729479503
Macro F1 Train Dev:  0.4605000434898669
Macro F1 Test:  0.4422479697702408
Micro F1 Train Dev:  0.6975170701427684
Micro F1 Test:  0.6797020484171322
Weighted Recall Train Dev:  0.6975170701427684
Weighted Recall Test:  0.6797020484171322
Macro Recall Train Dev:  0.46883659401917455
Macro Recall Test:  0.45192785678315817
Micro Recall Train Dev:  0.6975170701427684
Micro Recall Test:  0.6797020484171322
Confusion Matrix Train Dev: 
[[8122 1818    5]
 [2239 3108    0]
 [ 294  517    7]]
Confusion Matrix Test: 
[[2686  660    0]
 [ 789  963    1]
 [ 102  168    1]]


#### OLID

In [14]:
bert_hatebert_interleaved_olid_train_dev = np.concatenate((bert_hatebert_interleaved_olid_train, bert_hatebert_interleaved_olid_dev))
bert_hatebert_interleaved_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_interleaved_olid_train_dev, bert_hatebert_interleaved_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_interleaved_olid_train_dev)
test_preds = mlp.predict(bert_hatebert_interleaved_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_hatebert_interleaved_olid_seed_3")

save_model(mlp, "Saves/bert_hatebert_interleaved_olid_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7705438066465257
Accuracy Test:  0.8046511627906977
Weighted F1 Train Dev:  0.7705175845084978
Weighted F1 Test:  0.7952057245080502
Macro F1 Train Dev:  0.7414110112974179
Macro F1 Test:  0.7353846153846154
Micro F1 Train Dev:  0.7705438066465257
Micro F1 Test:  0.8046511627906977
Weighted Recall Train Dev:  0.7705438066465257
Weighted Recall Test:  0.8046511627906977
Macro Recall Train Dev:  0.7413559234882765
Macro Recall Test:  0.7189516129032258
Micro Recall Train Dev:  0.7705438066465257
Micro Recall Test:  0.8046511627906977
Confusion Matrix Train Dev: 
[[7323 1517]
 [1521 2879]]
Confusion Matrix Test: 
[[566  54]
 [114 126]]


### BERTweet-HateBERT

#### DynaHate

In [15]:
hatebert_bertweet_interleaved_dynahate_train_dev = np.concatenate((hatebert_bertweet_interleaved_dynahate_train, hatebert_bertweet_interleaved_dynahate_dev))
hatebert_bertweet_interleaved_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_interleaved_dynahate_train_dev, hatebert_bertweet_interleaved_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_interleaved_dynahate_train_dev)
test_preds = mlp.predict(hatebert_bertweet_interleaved_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/hatebert_bertweet_interleaved_dynahate_seed_3")

save_model(mlp, "Saves/hatebert_bertweet_interleaved_dynahate_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7457324978392394
Accuracy Test:  0.7075242718446602
Weighted F1 Train Dev:  0.7447401568654528
Weighted F1 Test:  0.7067380390098837
Macro F1 Train Dev:  0.7426005654304721
Macro F1 Test:  0.7030630630630631
Micro F1 Train Dev:  0.7457324978392394
Micro F1 Test:  0.7075242718446602
Weighted Recall Train Dev:  0.7457324978392394
Weighted Recall Test:  0.7075242718446602
Macro Recall Train Dev:  0.7416315921027872
Macro Recall Test:  0.7023081010662005
Micro Recall Train Dev:  0.7457324978392394
Micro Recall Test:  0.7075242718446602
Confusion Matrix Train Dev: 
[[11763  5354]
 [ 4060 15847]]
Confusion Matrix Test: 
[[1205  647]
 [ 558 1710]]


#### LatentHatred

In [16]:
hatebert_bertweet_interleaved_latenthatred_train_dev = np.concatenate((hatebert_bertweet_interleaved_latenthatred_train, hatebert_bertweet_interleaved_latenthatred_dev))
hatebert_bertweet_interleaved_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_interleaved_latenthatred_train_dev, hatebert_bertweet_interleaved_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_interleaved_latenthatred_train_dev)
test_preds = mlp.predict(hatebert_bertweet_interleaved_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/hatebert_bertweet_interleaved_latenthatred_seed_3")

save_model(mlp, "Saves/hatebert_bertweet_interleaved_latenthatred_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7139664804469273
Accuracy Test:  0.7013035381750465
Weighted F1 Train Dev:  0.6905020285045007
Weighted F1 Test:  0.6758550239597128
Macro F1 Train Dev:  0.49343848084889386
Macro F1 Test:  0.4769551071780082
Micro F1 Train Dev:  0.7139664804469273
Micro F1 Test:  0.7013035381750465
Weighted Recall Train Dev:  0.7139664804469273
Weighted Recall Test:  0.7013035381750465
Macro Recall Train Dev:  0.4827313504846357
Macro Recall Test:  0.4672226046765739
Micro Recall Train Dev:  0.7139664804469273
Micro Recall Test:  0.7013035381750465
Confusion Matrix Train Dev: 
[[8740 1181   24]
 [2608 2711   28]
 [ 369  398   51]]
Confusion Matrix Test: 
[[2933  402   11]
 [ 926  817   10]
 [ 124  131   16]]


#### OLID

In [17]:
hatebert_bertweet_interleaved_olid_train_dev = np.concatenate((hatebert_bertweet_interleaved_olid_train, hatebert_bertweet_interleaved_olid_dev))
hatebert_bertweet_interleaved_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_interleaved_olid_train_dev, hatebert_bertweet_interleaved_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_interleaved_olid_train_dev)
test_preds = mlp.predict(hatebert_bertweet_interleaved_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/hatebert_bertweet_interleaved_olid_seed_3")

save_model(mlp, "Saves/hatebert_bertweet_interleaved_olid_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7848942598187311
Accuracy Test:  0.7965116279069767
Weighted F1 Train Dev:  0.7757232989184191
Weighted F1 Test:  0.7786461426388261
Macro F1 Train Dev:  0.73903945531717
Macro F1 Test:  0.707184201566224
Micro F1 Train Dev:  0.7848942598187311
Micro F1 Test:  0.7965116279069767
Weighted Recall Train Dev:  0.7848942598187311
Weighted Recall Test:  0.7965116279069767
Macro Recall Train Dev:  0.7259620526532291
Macro Recall Test:  0.686491935483871
Micro Recall Train Dev:  0.7848942598187311
Micro Recall Test:  0.7965116279069767
Confusion Matrix Train Dev: 
[[7971  869]
 [1979 2421]]
Confusion Matrix Test: 
[[580  40]
 [135 105]]


### BERT-BERTweet-HateBERT

#### DynaHate

In [18]:
bert_bertweet_hatebert_interleaved_dynahate_train_dev = np.concatenate((bert_hatebert_bertweet_interleaved_dynahate_train, bert_hatebert_bertweet_interleaved_dynahate_dev))
bert_bertweet_hatebert_interleaved_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_interleaved_dynahate_train_dev, bert_bertweet_hatebert_interleaved_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_interleaved_dynahate_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_interleaved_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_bertweet_hatebert_interleaved_dynahate_seed_3")

save_model(mlp, "Saves/bert_bertweet_hatebert_interleaved_dynahate_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7452463267070009
Accuracy Test:  0.7126213592233009
Weighted F1 Train Dev:  0.7430766439981099
Weighted F1 Test:  0.7106566851280632
Macro F1 Train Dev:  0.74040523413147
Macro F1 Test:  0.7063093211726434
Micro F1 Train Dev:  0.7452463267070009
Micro F1 Test:  0.7126213592233008
Weighted Recall Train Dev:  0.7452463267070009
Weighted Recall Test:  0.7126213592233009
Macro Recall Train Dev:  0.7391529929472627
Macro Recall Test:  0.705006456626327
Micro Recall Train Dev:  0.7452463267070009
Micro Recall Test:  0.7126213592233009
Confusion Matrix Train Dev: 
[[11268  5849]
 [ 3583 16324]]
Confusion Matrix Test: 
[[1166  686]
 [ 498 1770]]


#### LatentHatred

In [19]:
bert_bertweet_hatebert_interleaved_latenthatred_train_dev = np.concatenate((bert_hatebert_bertweet_interleaved_latenthatred_train, bert_hatebert_bertweet_interleaved_latenthatred_dev))
bert_bertweet_hatebert_interleaved_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_interleaved_latenthatred_train_dev, bert_bertweet_hatebert_interleaved_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_interleaved_latenthatred_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_interleaved_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_bertweet_hatebert_interleaved_latenthatred_seed_3")

save_model(mlp, "Saves/bert_bertweet_hatebert_interleaved_latenthatred_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7130974549968964
Accuracy Test:  0.6916201117318436
Weighted F1 Train Dev:  0.6937655655309716
Weighted F1 Test:  0.6701437256879693
Macro F1 Train Dev:  0.5050562930914425
Macro F1 Test:  0.47411488618264847
Micro F1 Train Dev:  0.7130974549968964
Micro F1 Test:  0.6916201117318436
Weighted Recall Train Dev:  0.7130974549968964
Weighted Recall Test:  0.6916201117318436
Macro Recall Train Dev:  0.49193650307247444
Macro Recall Test:  0.465482383518117
Micro Recall Train Dev:  0.7130974549968964
Micro Recall Test:  0.6916201117318436
Confusion Matrix Train Dev: 
[[8558 1354   33]
 [2450 2865   32]
 [ 340  413   65]]
Confusion Matrix Test: 
[[2843  496    7]
 [ 885  855   13]
 [ 116  139   16]]


#### OLID

In [20]:
bert_bertweet_hatebert_interleaved_olid_train_dev = np.concatenate((bert_hatebert_bertweet_interleaved_olid_train, bert_hatebert_bertweet_interleaved_olid_dev))
bert_bertweet_hatebert_interleaved_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_interleaved_olid_train_dev, bert_bertweet_hatebert_interleaved_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_interleaved_olid_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_interleaved_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_bertweet_hatebert_interleaved_olid_seed_3")

save_model(mlp, "Saves/bert_bertweet_hatebert_interleaved_olid_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7742447129909366
Accuracy Test:  0.8093023255813954
Weighted F1 Train Dev:  0.761561674471661
Weighted F1 Test:  0.7876314006704693
Macro F1 Train Dev:  0.7204274954902266
Macro F1 Test:  0.7153949843007159
Micro F1 Train Dev:  0.7742447129909366
Micro F1 Test:  0.8093023255813954
Weighted Recall Train Dev:  0.7742447129909366
Weighted Recall Test:  0.8093023255813954
Macro Recall Train Dev:  0.7065718839983546
Macro Recall Test:  0.6902553763440861
Micro Recall Train Dev:  0.7742447129909366
Micro Recall Test:  0.8093023255813954
Confusion Matrix Train Dev: 
[[8030  810]
 [2179 2221]]
Confusion Matrix Test: 
[[595  25]
 [139 101]]
