In [1]:
from utils import *
import numpy as np
import torch, os
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV

c:\Python310\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
set_random_seed(42)

Seed: 42


In [3]:
# def scaling_embeddings(embeddings):
#     for i in range(len(embeddings)):
#         embeddings[i] = StandardScaler().fit_transform(embeddings[i])
#     return embeddings

def reshape_embeddings(embeddings):
    if embeddings.shape[1] == 1:
        embeddings = embeddings.squeeze(1)
    return embeddings

In [4]:
def multiply_2_embeddings(embeddings1, embeddings2):
    embeddings1 = reshape_embeddings(embeddings1)
    embeddings2 = reshape_embeddings(embeddings2)
    # Numpy multiplication
    return np.multiply(embeddings1, embeddings2)

def multiply_3_embeddings(embeddings1, embeddings2, embeddings3):
    embeddings1 = reshape_embeddings(embeddings1)
    embeddings2 = reshape_embeddings(embeddings2)
    embeddings3 = reshape_embeddings(embeddings3)
    # Numpy multiplication
    return np.multiply(embeddings1, np.multiply(embeddings2, embeddings3))

In [5]:
bert_hatebert_multiplied_dynahate_train = multiply_2_embeddings(bert_dynahate_train_embeddings, hatebert_dynahate_train_embeddings)
bert_hatebert_multiplied_dynahate_dev = multiply_2_embeddings(bert_dynahate_dev_embeddings, hatebert_dynahate_dev_embeddings)
bert_hatebert_multiplied_dynahate_test = multiply_2_embeddings(bert_dynahate_test_embeddings, hatebert_dynahate_test_embeddings)

bert_bertweet_multiplied_dynahate_train = multiply_2_embeddings(bert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
bert_bertweet_multiplied_dynahate_dev = multiply_2_embeddings(bert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
bert_bertweet_multiplied_dynahate_test = multiply_2_embeddings(bert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

hatebert_bertweet_multiplied_dynahate_train = multiply_2_embeddings(hatebert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
hatebert_bertweet_multiplied_dynahate_dev = multiply_2_embeddings(hatebert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
hatebert_bertweet_multiplied_dynahate_test = multiply_2_embeddings(hatebert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

bert_hatebert_bertweet_multiplied_dynahate_train = multiply_3_embeddings(bert_dynahate_train_embeddings, hatebert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
bert_hatebert_bertweet_multiplied_dynahate_dev = multiply_3_embeddings(bert_dynahate_dev_embeddings, hatebert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
bert_hatebert_bertweet_multiplied_dynahate_test = multiply_3_embeddings(bert_dynahate_test_embeddings, hatebert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

bert_hatebert_multiplied_olid_train = multiply_2_embeddings(bert_olid_train_embeddings, hatebert_olid_train_embeddings)
bert_hatebert_multiplied_olid_dev = multiply_2_embeddings(bert_olid_dev_embeddings, hatebert_olid_dev_embeddings)
bert_hatebert_multiplied_olid_test = multiply_2_embeddings(bert_olid_test_embeddings, hatebert_olid_test_embeddings)

bert_bertweet_multiplied_olid_train = multiply_2_embeddings(bert_olid_train_embeddings, bertweet_olid_train_embeddings)
bert_bertweet_multiplied_olid_dev = multiply_2_embeddings(bert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
bert_bertweet_multiplied_olid_test = multiply_2_embeddings(bert_olid_test_embeddings, bertweet_olid_test_embeddings)

hatebert_bertweet_multiplied_olid_train = multiply_2_embeddings(hatebert_olid_train_embeddings, bertweet_olid_train_embeddings)
hatebert_bertweet_multiplied_olid_dev = multiply_2_embeddings(hatebert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
hatebert_bertweet_multiplied_olid_test = multiply_2_embeddings(hatebert_olid_test_embeddings, bertweet_olid_test_embeddings)

bert_hatebert_bertweet_multiplied_olid_train = multiply_3_embeddings(bert_olid_train_embeddings, hatebert_olid_train_embeddings, bertweet_olid_train_embeddings)
bert_hatebert_bertweet_multiplied_olid_dev = multiply_3_embeddings(bert_olid_dev_embeddings, hatebert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
bert_hatebert_bertweet_multiplied_olid_test = multiply_3_embeddings(bert_olid_test_embeddings, hatebert_olid_test_embeddings, bertweet_olid_test_embeddings)

bert_hatebert_multiplied_latenthatred_train = multiply_2_embeddings(bert_latenthatred_train_embeddings, hatebert_latenthatred_train_embeddings)
bert_hatebert_multiplied_latenthatred_dev = multiply_2_embeddings(bert_latenthatred_dev_embeddings, hatebert_latenthatred_dev_embeddings)
bert_hatebert_multiplied_latenthatred_test = multiply_2_embeddings(bert_latenthatred_test_embeddings, hatebert_latenthatred_test_embeddings)

bert_bertweet_multiplied_latenthatred_train = multiply_2_embeddings(bert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
bert_bertweet_multiplied_latenthatred_dev = multiply_2_embeddings(bert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
bert_bertweet_multiplied_latenthatred_test = multiply_2_embeddings(bert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

hatebert_bertweet_multiplied_latenthatred_train = multiply_2_embeddings(hatebert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
hatebert_bertweet_multiplied_latenthatred_dev = multiply_2_embeddings(hatebert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
hatebert_bertweet_multiplied_latenthatred_test = multiply_2_embeddings(hatebert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

bert_hatebert_bertweet_multiplied_latenthatred_train = multiply_3_embeddings(bert_latenthatred_train_embeddings, hatebert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
bert_hatebert_bertweet_multiplied_latenthatred_dev = multiply_3_embeddings(bert_latenthatred_dev_embeddings, hatebert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
bert_hatebert_bertweet_multiplied_latenthatred_test = multiply_3_embeddings(bert_latenthatred_test_embeddings, hatebert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

In [6]:
dynahate_labels_train = process_labels(read_labels("dynahate", "train"))
dynahate_labels_dev = process_labels(read_labels("dynahate", "dev"))
dynahate_labels_test = process_labels(read_labels("dynahate", "test"))

latenthatred_labels_train = read_labels("latenthatred", "train")
latenthatred_labels_dev = read_labels("latenthatred", "dev")
latenthatred_labels_test = read_labels("latenthatred", "test")

olid_labels_train = read_labels("olid", "train")
olid_labels_dev = read_labels("olid", "dev")
olid_labels_test = read_labels("olid", "test")

In [7]:
mlp = MLPClassifier(random_state=42)
gridsearch = GridSearchCV(
    mlp,
    param_grid={
        "hidden_layer_sizes": [(128), (128,64)],
        "activation": ["relu"],
        "solver": ["adam"],
        "learning_rate_init": [0.001, 0.0001],
        "learning_rate": ["adaptive"],
        "early_stopping": [True],
        "max_iter": [10000]
    },
    verbose=4,
    n_jobs=os.cpu_count()//3,
    cv=5,
)

In [8]:
dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))
latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))
olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

### BERT-BERTweet

#### DynaHate

In [9]:
bert_bertweet_multiplied_dynahate_train_dev = np.concatenate((bert_bertweet_multiplied_dynahate_train, bert_bertweet_multiplied_dynahate_dev))
bert_bertweet_multiplied_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_multiplied_dynahate_train_dev, bert_bertweet_multiplied_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_multiplied_dynahate_train_dev)
test_preds = mlp.predict(bert_bertweet_multiplied_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_bertweet_multiplied_dynahate_seed_42")
save_model(mlp, "Saves/bert_bertweet_multiplied_dynahate_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.737602636127917
Accuracy Test:  0.6604368932038835
Weighted F1 Train Dev:  0.7365245789824373
Weighted F1 Test:  0.6594007783149078
Macro F1 Train Dev:  0.7342883117438583
Macro F1 Test:  0.6550470026198182
Micro F1 Train Dev:  0.737602636127917
Micro F1 Test:  0.6604368932038835
Weighted Recall Train Dev:  0.737602636127917
Weighted Recall Test:  0.6604368932038835
Macro Recall Train Dev:  0.7333509051593621
Macro Recall Test:  0.654488117141105
Micro Recall Train Dev:  0.737602636127917
Micro Recall Test:  0.6604368932038835
Confusion Matrix Train Dev: 
[[11587  5530]
 [ 4185 15722]]
Confusion Matrix Test: 
[[1103  749]
 [ 650 1618]]


#### LatentHatred

In [10]:
bert_bertweet_multiplied_latenthatred_train_dev = np.concatenate((bert_bertweet_multiplied_latenthatred_train, bert_bertweet_multiplied_latenthatred_dev))
bert_bertweet_multiplied_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_multiplied_latenthatred_train_dev, bert_bertweet_multiplied_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_multiplied_latenthatred_train_dev)
test_preds = mlp.predict(bert_bertweet_multiplied_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_bertweet_multiplied_latenthatred_seed_42")
save_model(mlp, "Saves/bert_bertweet_multiplied_latenthatred_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7261949099937927
Accuracy Test:  0.6944134078212291
Weighted F1 Train Dev:  0.6947093083181946
Weighted F1 Test:  0.6591696217286133
Macro F1 Train Dev:  0.5299983498517727
Macro F1 Test:  0.4893958783206624
Micro F1 Train Dev:  0.7261949099937928
Micro F1 Test:  0.6944134078212291
Weighted Recall Train Dev:  0.7261949099937927
Weighted Recall Test:  0.6944134078212291
Macro Recall Train Dev:  0.5026847690373029
Macro Recall Test:  0.46980276497734813
Micro Recall Train Dev:  0.7261949099937927
Micro Recall Test:  0.6944134078212291
Confusion Matrix Train Dev: 
[[9348  568   29]
 [3057 2227   63]
 [ 414  280  124]]
Confusion Matrix Test: 
[[3068  263   15]
 [1100  624   29]
 [ 137   97   37]]


#### OLID

In [11]:
bert_bertweet_multiplied_olid_train_dev = np.concatenate((bert_bertweet_multiplied_olid_train, bert_bertweet_multiplied_olid_dev))
bert_bertweet_multiplied_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_multiplied_olid_train_dev, bert_bertweet_multiplied_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_multiplied_olid_train_dev)
test_preds = mlp.predict(bert_bertweet_multiplied_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_bertweet_multiplied_olid_seed_42")

save_model(mlp, "Saves/bert_bertweet_multiplied_olid_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7601208459214501
Accuracy Test:  0.7965116279069767
Weighted F1 Train Dev:  0.741275936417673
Weighted F1 Test:  0.7765173101393285
Macro F1 Train Dev:  0.6932441349269899
Macro F1 Test:  0.7027518659480043
Micro F1 Train Dev:  0.7601208459214501
Micro F1 Test:  0.7965116279069767
Weighted Recall Train Dev:  0.7601208459214501
Weighted Recall Test:  0.7965116279069767
Macro Recall Train Dev:  0.6800138831756479
Macro Recall Test:  0.6813844086021505
Micro Recall Train Dev:  0.7601208459214501
Micro Recall Test:  0.7965116279069767
Confusion Matrix Train Dev: 
[[8123  717]
 [2459 1941]]
Confusion Matrix Test: 
[[584  36]
 [139 101]]


### BERT-HateBERT

#### DynaHate

In [12]:
bert_hatebert_multiplied_dynahate_train_dev = np.concatenate((bert_hatebert_multiplied_dynahate_train, bert_hatebert_multiplied_dynahate_dev))
bert_hatebert_multiplied_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_multiplied_dynahate_train_dev, bert_hatebert_multiplied_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_multiplied_dynahate_train_dev)
test_preds = mlp.predict(bert_hatebert_multiplied_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_hatebert_multiplied_dynahate_seed_42")

save_model(mlp, "Saves/bert_hatebert_multiplied_dynahate_seed_42")



Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7115384615384616
Accuracy Test:  0.6825242718446602
Weighted F1 Train Dev:  0.7106994952366154
Weighted F1 Test:  0.681375208826411
Macro F1 Train Dev:  0.7084313595949965
Macro F1 Test:  0.6771821367598168
Micro F1 Train Dev:  0.7115384615384616
Micro F1 Test:  0.6825242718446602
Weighted Recall Train Dev:  0.7115384615384616
Weighted Recall Test:  0.6825242718446602
Macro Recall Train Dev:  0.7077785776419796
Macro Recall Test:  0.6764315997577337
Micro Recall Train Dev:  0.7115384615384616
Micro Recall Test:  0.6825242718446602
Confusion Matrix Train Dev: 
[[11261  5856]
 [ 4824 15083]]
Confusion Matrix Test: 
[[1141  711]
 [ 597 1671]]


#### LatentHatred

In [13]:
bert_hatebert_multiplied_latenthatred_train_dev = np.concatenate((bert_hatebert_multiplied_latenthatred_train, bert_hatebert_multiplied_latenthatred_dev))
bert_hatebert_multiplied_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_multiplied_latenthatred_train_dev, bert_hatebert_multiplied_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_multiplied_latenthatred_train_dev)
test_preds = mlp.predict(bert_hatebert_multiplied_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_hatebert_multiplied_latenthatred_seed_42")

save_model(mlp, "Saves/bert_hatebert_multiplied_latenthatred_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7063935443823712
Accuracy Test:  0.6905027932960894
Weighted F1 Train Dev:  0.6789544330264619
Weighted F1 Test:  0.6611802603184534
Macro F1 Train Dev:  0.4710106128185127
Macro F1 Test:  0.44867438510666685
Micro F1 Train Dev:  0.7063935443823712
Micro F1 Test:  0.6905027932960894
Weighted Recall Train Dev:  0.7063935443823712
Weighted Recall Test:  0.6905027932960894
Macro Recall Train Dev:  0.46637875393738143
Macro Recall Test:  0.44737830594133715
Micro Recall Train Dev:  0.7063935443823712
Micro Recall Test:  0.6905027932960894
Confusion Matrix Train Dev: 
[[8792 1132   21]
 [2782 2558    7]
 [ 376  412   30]]
Confusion Matrix Test: 
[[2927  414    5]
 [ 973  774    6]
 [ 139  125    7]]


#### OLID

In [14]:
bert_hatebert_multiplied_olid_train_dev = np.concatenate((bert_hatebert_multiplied_olid_train, bert_hatebert_multiplied_olid_dev))
bert_hatebert_multiplied_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_multiplied_olid_train_dev, bert_hatebert_multiplied_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_multiplied_olid_train_dev)
test_preds = mlp.predict(bert_hatebert_multiplied_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_hatebert_multiplied_olid_seed_42")

save_model(mlp, "Saves/bert_hatebert_multiplied_olid_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7577794561933535
Accuracy Test:  0.8034883720930233
Weighted F1 Train Dev:  0.7479382649828166
Weighted F1 Test:  0.7825598890216661
Macro F1 Train Dev:  0.7070637196369008
Macro F1 Test:  0.709598204919687
Micro F1 Train Dev:  0.7577794561933535
Micro F1 Test:  0.8034883720930233
Weighted Recall Train Dev:  0.7577794561933535
Weighted Recall Test:  0.8034883720930233
Macro Recall Train Dev:  0.6965816536404772
Macro Recall Test:  0.6862231182795699
Micro Recall Train Dev:  0.7577794561933535
Micro Recall Test:  0.8034883720930233
Confusion Matrix Train Dev: 
[[7771 1069]
 [2138 2262]]
Confusion Matrix Test: 
[[590  30]
 [139 101]]


### BERTweet-HateBERT

#### DynaHate

In [15]:
hatebert_bertweet_multiplied_dynahate_train_dev = np.concatenate((hatebert_bertweet_multiplied_dynahate_train, hatebert_bertweet_multiplied_dynahate_dev))
hatebert_bertweet_multiplied_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_multiplied_dynahate_train_dev, hatebert_bertweet_multiplied_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_multiplied_dynahate_train_dev)
test_preds = mlp.predict(hatebert_bertweet_multiplied_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev ,dynahate_labels_test, "Results/hatebert_bertweet_multiplied_dynahate_seed_42")

save_model(mlp, "Saves/hatebert_bertweet_multiplied_dynahate_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7588050993949871
Accuracy Test:  0.6912621359223301
Weighted F1 Train Dev:  0.7588255199045713
Weighted F1 Test:  0.6918402917827109
Macro F1 Train Dev:  0.7574690146250479
Macro F1 Test:  0.6894351634035265
Micro F1 Train Dev:  0.7588050993949871
Micro F1 Test:  0.6912621359223301
Weighted Recall Train Dev:  0.7588050993949871
Weighted Recall Test:  0.6912621359223301
Macro Recall Train Dev:  0.7575135990699335
Macro Recall Test:  0.6905580886862384
Micro Recall Train Dev:  0.7588050993949871
Micro Recall Test:  0.6912621359223301
Confusion Matrix Train Dev: 
[[12673  4444]
 [ 4486 15421]]
Confusion Matrix Test: 
[[1266  586]
 [ 686 1582]]


#### LatentHatred

In [16]:
hatebert_bertweet_multiplied_latenthatred_train_dev = np.concatenate((hatebert_bertweet_multiplied_latenthatred_train, hatebert_bertweet_multiplied_latenthatred_dev))
hatebert_bertweet_multiplied_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_multiplied_latenthatred_train_dev, hatebert_bertweet_multiplied_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_multiplied_latenthatred_train_dev)
test_preds = mlp.predict(hatebert_bertweet_multiplied_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/hatebert_bertweet_multiplied_latenthatred_seed_42")

save_model(mlp, "Saves/hatebert_bertweet_multiplied_latenthatred_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.737554314090627
Accuracy Test:  0.7068901303538175
Weighted F1 Train Dev:  0.7103921707160721
Weighted F1 Test:  0.6753662811167274
Macro F1 Train Dev:  0.5347752972046343
Macro F1 Test:  0.4964175898952261
Micro F1 Train Dev:  0.737554314090627
Micro F1 Test:  0.7068901303538175
Weighted Recall Train Dev:  0.737554314090627
Weighted Recall Test:  0.7068901303538175
Macro Recall Train Dev:  0.5093811098394735
Macro Recall Test:  0.4768468298205561
Micro Recall Train Dev:  0.737554314090627
Micro Recall Test:  0.7068901303538175
Confusion Matrix Train Dev: 
[[9260  664   21]
 [2777 2519   51]
 [ 394  321  103]]
Confusion Matrix Test: 
[[3062  271   13]
 [1028  703   22]
 [ 134  106   31]]


#### OLID

In [17]:
hatebert_bertweet_multiplied_olid_train_dev = np.concatenate((hatebert_bertweet_multiplied_olid_train, hatebert_bertweet_multiplied_olid_dev))
hatebert_bertweet_multiplied_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_multiplied_olid_train_dev, hatebert_bertweet_multiplied_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_multiplied_olid_train_dev)
test_preds = mlp.predict(hatebert_bertweet_multiplied_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/hatebert_bertweet_multiplied_olid_seed_42")

save_model(mlp, "Saves/hatebert_bertweet_multiplied_olid_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7682779456193354
Accuracy Test:  0.7883720930232558
Weighted F1 Train Dev:  0.7548855982024079
Weighted F1 Test:  0.7695220025066148
Macro F1 Train Dev:  0.7123519626293333
Macro F1 Test:  0.6949070608782435
Micro F1 Train Dev:  0.7682779456193355
Micro F1 Test:  0.7883720930232558
Weighted Recall Train Dev:  0.7682779456193354
Weighted Recall Test:  0.7883720930232558
Macro Recall Train Dev:  0.6990214932126697
Macro Recall Test:  0.675739247311828
Micro Recall Train Dev:  0.7682779456193354
Micro Recall Test:  0.7883720930232558
Confusion Matrix Train Dev: 
[[8005  835]
 [2233 2167]]
Confusion Matrix Test: 
[[577  43]
 [139 101]]


### BERT-BERTweet-HateBERT

#### DynaHate

In [18]:
bert_bertweet_hatebert_multiplied_dynahate_train_dev = np.concatenate((bert_hatebert_bertweet_multiplied_dynahate_train, bert_hatebert_bertweet_multiplied_dynahate_dev))
bert_bertweet_hatebert_multiplied_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_multiplied_dynahate_train_dev, bert_bertweet_hatebert_multiplied_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_multiplied_dynahate_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_multiplied_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_bertweet_hatebert_multiplied_dynahate_seed_42")

save_model(mlp, "Saves/bert_bertweet_hatebert_multiplied_dynahate_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7494868193604148
Accuracy Test:  0.6788834951456311
Weighted F1 Train Dev:  0.7485041215087284
Weighted F1 Test:  0.6787079120860618
Macro F1 Train Dev:  0.7463934771621501
Macro F1 Test:  0.6752296952869767
Micro F1 Train Dev:  0.7494868193604148
Micro F1 Test:  0.6788834951456311
Weighted Recall Train Dev:  0.7494868193604148
Weighted Recall Test:  0.6788834951456311
Macro Recall Train Dev:  0.7453971198590827
Macro Recall Test:  0.6750559955203583
Micro Recall Train Dev:  0.7494868193604148
Micro Recall Test:  0.6788834951456311
Confusion Matrix Train Dev: 
[[11830  5287]
 [ 3988 15919]]
Confusion Matrix Test: 
[[1180  672]
 [ 651 1617]]


#### LatentHatred

In [19]:
bert_bertweet_hatebert_multiplied_latenthatred_train_dev = np.concatenate((bert_hatebert_bertweet_multiplied_latenthatred_train, bert_hatebert_bertweet_multiplied_latenthatred_dev))
bert_bertweet_hatebert_multiplied_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_multiplied_latenthatred_train_dev, bert_bertweet_hatebert_multiplied_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_multiplied_latenthatred_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_multiplied_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_bertweet_hatebert_multiplied_latenthatred_seed_42")

save_model(mlp, "Saves/bert_bertweet_hatebert_multiplied_latenthatred_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7281191806331471
Accuracy Test:  0.6990689013035382
Weighted F1 Train Dev:  0.7116467296176724
Weighted F1 Test:  0.6821391820728786
Macro F1 Train Dev:  0.5230675503250849
Macro F1 Test:  0.4938795919430556
Micro F1 Train Dev:  0.7281191806331471
Micro F1 Test:  0.6990689013035382
Weighted Recall Train Dev:  0.7281191806331471
Weighted Recall Test:  0.6990689013035382
Macro Recall Train Dev:  0.5100470749554659
Macro Recall Test:  0.4823614977785413
Micro Recall Train Dev:  0.7281191806331471
Micro Recall Test:  0.6990689013035382
Confusion Matrix Train Dev: 
[[8489 1437   19]
 [2148 3173   26]
 [ 315  435   68]]
Confusion Matrix Test: 
[[2798  539    9]
 [ 806  935   12]
 [  99  151   21]]


#### OLID

In [20]:
bert_bertweet_hatebert_multiplied_olid_train_dev = np.concatenate((bert_hatebert_bertweet_multiplied_olid_train, bert_hatebert_bertweet_multiplied_olid_dev))
bert_bertweet_hatebert_multiplied_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_multiplied_olid_train_dev, bert_bertweet_hatebert_multiplied_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_multiplied_olid_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_multiplied_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_bertweet_hatebert_multiplied_olid_seed_42")

save_model(mlp, "Saves/bert_bertweet_hatebert_multiplied_olid_seed_42")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.8077039274924471
Accuracy Test:  0.7953488372093023
Weighted F1 Train Dev:  0.7972491869945597
Weighted F1 Test:  0.7755145265629444
Macro F1 Train Dev:  0.7625043907291249
Macro F1 Test:  0.7016219967039639
Micro F1 Train Dev:  0.8077039274924471
Micro F1 Test:  0.7953488372093023
Weighted Recall Train Dev:  0.8077039274924471
Weighted Recall Test:  0.7953488372093023
Macro Recall Train Dev:  0.7452123611682435
Macro Recall Test:  0.6805779569892473
Micro Recall Train Dev:  0.8077039274924471
Micro Recall Test:  0.7953488372093023
Confusion Matrix Train Dev: 
[[8235  605]
 [1941 2459]]
Confusion Matrix Test: 
[[583  37]
 [139 101]]
