In [1]:
from utils import *
import numpy as np
import torch, os
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV

c:\Python310\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
set_random_seed(3)

Seed: 3


In [3]:
# def scaling_embeddings(embeddings):
#     for i in range(len(embeddings)):
#         embeddings[i] = StandardScaler().fit_transform(embeddings[i])
#     return embeddings

def reshape_embeddings(embeddings):
    if embeddings.shape[1] == 1:
        embeddings = embeddings.squeeze(1)
    return embeddings

In [4]:
def multiply_2_embeddings(embeddings1, embeddings2):
    embeddings1 = reshape_embeddings(embeddings1)
    embeddings2 = reshape_embeddings(embeddings2)
    # Numpy multiplication
    return np.multiply(embeddings1, embeddings2)

def multiply_3_embeddings(embeddings1, embeddings2, embeddings3):
    embeddings1 = reshape_embeddings(embeddings1)
    embeddings2 = reshape_embeddings(embeddings2)
    embeddings3 = reshape_embeddings(embeddings3)
    # Numpy multiplication
    return np.multiply(embeddings1, np.multiply(embeddings2, embeddings3))

In [5]:
bert_hatebert_multiplied_dynahate_train = multiply_2_embeddings(bert_dynahate_train_embeddings, hatebert_dynahate_train_embeddings)
bert_hatebert_multiplied_dynahate_dev = multiply_2_embeddings(bert_dynahate_dev_embeddings, hatebert_dynahate_dev_embeddings)
bert_hatebert_multiplied_dynahate_test = multiply_2_embeddings(bert_dynahate_test_embeddings, hatebert_dynahate_test_embeddings)

bert_bertweet_multiplied_dynahate_train = multiply_2_embeddings(bert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
bert_bertweet_multiplied_dynahate_dev = multiply_2_embeddings(bert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
bert_bertweet_multiplied_dynahate_test = multiply_2_embeddings(bert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

hatebert_bertweet_multiplied_dynahate_train = multiply_2_embeddings(hatebert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
hatebert_bertweet_multiplied_dynahate_dev = multiply_2_embeddings(hatebert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
hatebert_bertweet_multiplied_dynahate_test = multiply_2_embeddings(hatebert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

bert_hatebert_bertweet_multiplied_dynahate_train = multiply_3_embeddings(bert_dynahate_train_embeddings, hatebert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
bert_hatebert_bertweet_multiplied_dynahate_dev = multiply_3_embeddings(bert_dynahate_dev_embeddings, hatebert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
bert_hatebert_bertweet_multiplied_dynahate_test = multiply_3_embeddings(bert_dynahate_test_embeddings, hatebert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

bert_hatebert_multiplied_olid_train = multiply_2_embeddings(bert_olid_train_embeddings, hatebert_olid_train_embeddings)
bert_hatebert_multiplied_olid_dev = multiply_2_embeddings(bert_olid_dev_embeddings, hatebert_olid_dev_embeddings)
bert_hatebert_multiplied_olid_test = multiply_2_embeddings(bert_olid_test_embeddings, hatebert_olid_test_embeddings)

bert_bertweet_multiplied_olid_train = multiply_2_embeddings(bert_olid_train_embeddings, bertweet_olid_train_embeddings)
bert_bertweet_multiplied_olid_dev = multiply_2_embeddings(bert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
bert_bertweet_multiplied_olid_test = multiply_2_embeddings(bert_olid_test_embeddings, bertweet_olid_test_embeddings)

hatebert_bertweet_multiplied_olid_train = multiply_2_embeddings(hatebert_olid_train_embeddings, bertweet_olid_train_embeddings)
hatebert_bertweet_multiplied_olid_dev = multiply_2_embeddings(hatebert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
hatebert_bertweet_multiplied_olid_test = multiply_2_embeddings(hatebert_olid_test_embeddings, bertweet_olid_test_embeddings)

bert_hatebert_bertweet_multiplied_olid_train = multiply_3_embeddings(bert_olid_train_embeddings, hatebert_olid_train_embeddings, bertweet_olid_train_embeddings)
bert_hatebert_bertweet_multiplied_olid_dev = multiply_3_embeddings(bert_olid_dev_embeddings, hatebert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
bert_hatebert_bertweet_multiplied_olid_test = multiply_3_embeddings(bert_olid_test_embeddings, hatebert_olid_test_embeddings, bertweet_olid_test_embeddings)

bert_hatebert_multiplied_latenthatred_train = multiply_2_embeddings(bert_latenthatred_train_embeddings, hatebert_latenthatred_train_embeddings)
bert_hatebert_multiplied_latenthatred_dev = multiply_2_embeddings(bert_latenthatred_dev_embeddings, hatebert_latenthatred_dev_embeddings)
bert_hatebert_multiplied_latenthatred_test = multiply_2_embeddings(bert_latenthatred_test_embeddings, hatebert_latenthatred_test_embeddings)

bert_bertweet_multiplied_latenthatred_train = multiply_2_embeddings(bert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
bert_bertweet_multiplied_latenthatred_dev = multiply_2_embeddings(bert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
bert_bertweet_multiplied_latenthatred_test = multiply_2_embeddings(bert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

hatebert_bertweet_multiplied_latenthatred_train = multiply_2_embeddings(hatebert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
hatebert_bertweet_multiplied_latenthatred_dev = multiply_2_embeddings(hatebert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
hatebert_bertweet_multiplied_latenthatred_test = multiply_2_embeddings(hatebert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

bert_hatebert_bertweet_multiplied_latenthatred_train = multiply_3_embeddings(bert_latenthatred_train_embeddings, hatebert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
bert_hatebert_bertweet_multiplied_latenthatred_dev = multiply_3_embeddings(bert_latenthatred_dev_embeddings, hatebert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
bert_hatebert_bertweet_multiplied_latenthatred_test = multiply_3_embeddings(bert_latenthatred_test_embeddings, hatebert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

In [6]:
dynahate_labels_train = process_labels(read_labels("dynahate", "train"))
dynahate_labels_dev = process_labels(read_labels("dynahate", "dev"))
dynahate_labels_test = process_labels(read_labels("dynahate", "test"))

latenthatred_labels_train = read_labels("latenthatred", "train")
latenthatred_labels_dev = read_labels("latenthatred", "dev")
latenthatred_labels_test = read_labels("latenthatred", "test")

olid_labels_train = read_labels("olid", "train")
olid_labels_dev = read_labels("olid", "dev")
olid_labels_test = read_labels("olid", "test")

In [7]:
mlp = MLPClassifier(random_state=3)
gridsearch = GridSearchCV(
    mlp,
    param_grid={
        "hidden_layer_sizes": [(128), (128,64)],
        "activation": ["relu"],
        "solver": ["adam"],
        "learning_rate_init": [0.001, 0.0001],
        "learning_rate": ["adaptive"],
        "early_stopping": [True],
        "max_iter": [10000]
    },
    verbose=4,
    n_jobs=os.cpu_count()//3,
    cv=5,
)

In [8]:
dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))
latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))
olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

### BERT-BERTweet

#### DynaHate

In [9]:
bert_bertweet_multiplied_dynahate_train_dev = np.concatenate((bert_bertweet_multiplied_dynahate_train, bert_bertweet_multiplied_dynahate_dev))
bert_bertweet_multiplied_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_multiplied_dynahate_train_dev, bert_bertweet_multiplied_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_multiplied_dynahate_train_dev)
test_preds = mlp.predict(bert_bertweet_multiplied_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_bertweet_multiplied_dynahate_seed_3")
save_model(mlp, "Saves/bert_bertweet_multiplied_dynahate_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7207216940363008
Accuracy Test:  0.6725728155339806
Weighted F1 Train Dev:  0.7172236453112285
Weighted F1 Test:  0.6679441853562256
Macro F1 Train Dev:  0.7138927388460574
Macro F1 Test:  0.6618700208327364
Micro F1 Train Dev:  0.7207216940363008
Micro F1 Test:  0.6725728155339806
Weighted Recall Train Dev:  0.7207216940363008
Weighted Recall Test:  0.6725728155339806
Macro Recall Train Dev:  0.7131291134141228
Macro Recall Test:  0.6613513776040774
Micro Recall Train Dev:  0.7207216940363008
Micro Recall Test:  0.6725728155339806
Confusion Matrix Train Dev: 
[[10482  6635]
 [ 3705 16202]]
Confusion Matrix Test: 
[[1019  833]
 [ 516 1752]]


#### LatentHatred

In [10]:
bert_bertweet_multiplied_latenthatred_train_dev = np.concatenate((bert_bertweet_multiplied_latenthatred_train, bert_bertweet_multiplied_latenthatred_dev))
bert_bertweet_multiplied_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_multiplied_latenthatred_train_dev, bert_bertweet_multiplied_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_multiplied_latenthatred_train_dev)
test_preds = mlp.predict(bert_bertweet_multiplied_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_bertweet_multiplied_latenthatred_seed_3")
save_model(mlp, "Saves/bert_bertweet_multiplied_latenthatred_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7608317815021726
Accuracy Test:  0.7014897579143389
Weighted F1 Train Dev:  0.7403282603721897
Weighted F1 Test:  0.6792742171171294
Macro F1 Train Dev:  0.5484093137663972
Macro F1 Test:  0.4818478077700079
Micro F1 Train Dev:  0.7608317815021727
Micro F1 Test:  0.7014897579143389
Weighted Recall Train Dev:  0.7608317815021726
Weighted Recall Test:  0.7014897579143389
Macro Recall Train Dev:  0.5295800808680616
Macro Recall Test:  0.4723918378029015
Micro Recall Train Dev:  0.7608317815021726
Micro Recall Test:  0.7014897579143389
Confusion Matrix Train Dev: 
[[9023  916    6]
 [2172 3160   15]
 [ 335  409   74]]
Confusion Matrix Test: 
[[2878  467    1]
 [ 867  873   13]
 [ 122  133   16]]


#### OLID

In [11]:
bert_bertweet_multiplied_olid_train_dev = np.concatenate((bert_bertweet_multiplied_olid_train, bert_bertweet_multiplied_olid_dev))
bert_bertweet_multiplied_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_multiplied_olid_train_dev, bert_bertweet_multiplied_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_multiplied_olid_train_dev)
test_preds = mlp.predict(bert_bertweet_multiplied_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_bertweet_multiplied_olid_seed_3")

save_model(mlp, "Saves/bert_bertweet_multiplied_olid_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7691842900302115
Accuracy Test:  0.7941860465116279
Weighted F1 Train Dev:  0.7522585133554481
Weighted F1 Test:  0.768650489389287
Macro F1 Train Dev:  0.70698715887596
Macro F1 Test:  0.6884561777654068
Micro F1 Train Dev:  0.7691842900302115
Micro F1 Test:  0.7941860465116279
Weighted Recall Train Dev:  0.7691842900302115
Weighted Recall Test:  0.7941860465116279
Macro Recall Train Dev:  0.6925658165364048
Macro Recall Test:  0.667002688172043
Micro Recall Train Dev:  0.7691842900302115
Micro Recall Test:  0.7941860465116279
Confusion Matrix Train Dev: 
[[8142  698]
 [2358 2042]]
Confusion Matrix Test: 
[[592  28]
 [149  91]]


### BERT-HateBERT

#### DynaHate

In [13]:
bert_hatebert_multiplied_dynahate_train_dev = np.concatenate((bert_hatebert_multiplied_dynahate_train, bert_hatebert_multiplied_dynahate_dev))
bert_hatebert_multiplied_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_multiplied_dynahate_train_dev, bert_hatebert_multiplied_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_multiplied_dynahate_train_dev)
test_preds = mlp.predict(bert_hatebert_multiplied_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_hatebert_multiplied_dynahate_seed_3")

save_model(mlp, "Saves/bert_hatebert_multiplied_dynahate_seed_3")



Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7281763180639585
Accuracy Test:  0.6849514563106797
Weighted F1 Train Dev:  0.7271756229432083
Weighted F1 Test:  0.6839314715619538
Macro F1 Train Dev:  0.7249204214998373
Macro F1 Test:  0.6798515325670499
Micro F1 Train Dev:  0.7281763180639587
Micro F1 Test:  0.6849514563106797
Weighted Recall Train Dev:  0.7281763180639585
Weighted Recall Test:  0.6849514563106797
Macro Recall Train Dev:  0.7240897784677133
Macro Recall Test:  0.6791313837750123
Micro Recall Train Dev:  0.7281763180639585
Micro Recall Test:  0.6849514563106797
Confusion Matrix Train Dev: 
[[11466  5651]
 [ 4413 15494]]
Confusion Matrix Test: 
[[1151  701]
 [ 597 1671]]


#### LatentHatred

In [14]:
bert_hatebert_multiplied_latenthatred_train_dev = np.concatenate((bert_hatebert_multiplied_latenthatred_train, bert_hatebert_multiplied_latenthatred_dev))
bert_hatebert_multiplied_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_multiplied_latenthatred_train_dev, bert_hatebert_multiplied_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_multiplied_latenthatred_train_dev)
test_preds = mlp.predict(bert_hatebert_multiplied_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_hatebert_multiplied_latenthatred_seed_3")

save_model(mlp, "Saves/bert_hatebert_multiplied_latenthatred_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7145872129112353
Accuracy Test:  0.6912476722532589
Weighted F1 Train Dev:  0.6911839326795488
Weighted F1 Test:  0.6670442950795114
Macro F1 Train Dev:  0.47341644492270235
Macro F1 Test:  0.4481639257107363
Micro F1 Train Dev:  0.7145872129112353
Micro F1 Test:  0.6912476722532589
Weighted Recall Train Dev:  0.7145872129112353
Weighted Recall Test:  0.6912476722532589
Macro Recall Train Dev:  0.4755118645083974
Macro Recall Test:  0.45257969260344916
Micro Recall Train Dev:  0.7145872129112353
Micro Recall Test:  0.6912476722532589
Confusion Matrix Train Dev: 
[[8581 1357    7]
 [2431 2916    0]
 [ 355  448   15]]
Confusion Matrix Test: 
[[2832  513    1]
 [ 875  877    1]
 [ 123  145    3]]


#### OLID

In [15]:
bert_hatebert_multiplied_olid_train_dev = np.concatenate((bert_hatebert_multiplied_olid_train, bert_hatebert_multiplied_olid_dev))
bert_hatebert_multiplied_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_multiplied_olid_train_dev, bert_hatebert_multiplied_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_multiplied_olid_train_dev)
test_preds = mlp.predict(bert_hatebert_multiplied_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_hatebert_multiplied_olid_seed_3")

save_model(mlp, "Saves/bert_hatebert_multiplied_olid_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7589123867069486
Accuracy Test:  0.8034883720930233
Weighted F1 Train Dev:  0.7416240701350088
Weighted F1 Test:  0.7797030464467334
Macro F1 Train Dev:  0.6946472490949764
Macro F1 Test:  0.7037499057274883
Micro F1 Train Dev:  0.7589123867069486
Micro F1 Test:  0.8034883720930233
Weighted Recall Train Dev:  0.7589123867069486
Weighted Recall Test:  0.8034883720930233
Macro Recall Train Dev:  0.6817343685726038
Macro Recall Test:  0.6798387096774194
Micro Recall Train Dev:  0.7589123867069486
Micro Recall Test:  0.8034883720930233
Confusion Matrix Train Dev: 
[[8061  779]
 [2413 1987]]
Confusion Matrix Test: 
[[595  25]
 [144  96]]


### BERTweet-HateBERT

#### DynaHate

In [16]:
hatebert_bertweet_multiplied_dynahate_train_dev = np.concatenate((hatebert_bertweet_multiplied_dynahate_train, hatebert_bertweet_multiplied_dynahate_dev))
hatebert_bertweet_multiplied_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_multiplied_dynahate_train_dev, hatebert_bertweet_multiplied_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_multiplied_dynahate_train_dev)
test_preds = mlp.predict(hatebert_bertweet_multiplied_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/hatebert_bertweet_multiplied_dynahate_seed_3")

save_model(mlp, "Saves/hatebert_bertweet_multiplied_dynahate_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7797104580812446
Accuracy Test:  0.6747572815533981
Weighted F1 Train Dev:  0.7799097162471168
Weighted F1 Test:  0.6755110563004881
Macro F1 Train Dev:  0.7789025961696104
Macro F1 Test:  0.6733334848088947
Micro F1 Train Dev:  0.7797104580812446
Micro F1 Test:  0.6747572815533981
Weighted Recall Train Dev:  0.7797104580812446
Weighted Recall Test:  0.6747572815533981
Macro Recall Train Dev:  0.779582301964226
Macro Recall Test:  0.6749726688531584
Micro Recall Train Dev:  0.7797104580812446
Micro Recall Test:  0.6747572815533981
Confusion Matrix Train Dev: 
[[13315  3802]
 [ 4354 15553]]
Confusion Matrix Test: 
[[1254  598]
 [ 742 1526]]


#### LatentHatred

In [17]:
hatebert_bertweet_multiplied_latenthatred_train_dev = np.concatenate((hatebert_bertweet_multiplied_latenthatred_train, hatebert_bertweet_multiplied_latenthatred_dev))
hatebert_bertweet_multiplied_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_multiplied_latenthatred_train_dev, hatebert_bertweet_multiplied_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_multiplied_latenthatred_train_dev)
test_preds = mlp.predict(hatebert_bertweet_multiplied_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/hatebert_bertweet_multiplied_latenthatred_seed_3")

save_model(mlp, "Saves/hatebert_bertweet_multiplied_latenthatred_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7238361266294228
Accuracy Test:  0.7003724394785847
Weighted F1 Train Dev:  0.702564221741285
Weighted F1 Test:  0.6765114491858124
Macro F1 Train Dev:  0.5168166280174501
Macro F1 Test:  0.4883063689144597
Micro F1 Train Dev:  0.7238361266294228
Micro F1 Test:  0.7003724394785847
Weighted Recall Train Dev:  0.7238361266294228
Weighted Recall Test:  0.7003724394785847
Macro Recall Train Dev:  0.499745510280051
Macro Recall Test:  0.4737784289938602
Micro Recall Train Dev:  0.7238361266294228
Micro Recall Test:  0.7003724394785847
Confusion Matrix Train Dev: 
[[8781 1139   25]
 [2506 2805   36]
 [ 358  385   75]]
Confusion Matrix Test: 
[[2919  419    8]
 [ 919  820   14]
 [ 128  121   22]]


#### OLID

In [18]:
hatebert_bertweet_multiplied_olid_train_dev = np.concatenate((hatebert_bertweet_multiplied_olid_train, hatebert_bertweet_multiplied_olid_dev))
hatebert_bertweet_multiplied_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_multiplied_olid_train_dev, hatebert_bertweet_multiplied_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_multiplied_olid_train_dev)
test_preds = mlp.predict(hatebert_bertweet_multiplied_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/hatebert_bertweet_multiplied_olid_seed_3")

save_model(mlp, "Saves/hatebert_bertweet_multiplied_olid_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.763821752265861
Accuracy Test:  0.8023255813953488
Weighted F1 Train Dev:  0.7533884257546595
Weighted F1 Test:  0.7885482734319943
Macro F1 Train Dev:  0.7127889781562944
Macro F1 Test:  0.7231060606060605
Micro F1 Train Dev:  0.763821752265861
Micro F1 Test:  0.8023255813953488
Weighted Recall Train Dev:  0.763821752265861
Weighted Recall Test:  0.8023255813953488
Macro Recall Train Dev:  0.7013348416289593
Macro Recall Test:  0.7032930107526881
Micro Recall Train Dev:  0.763821752265861
Micro Recall Test:  0.8023255813953488
Confusion Matrix Train Dev: 
[[7847  993]
 [2134 2266]]
Confusion Matrix Test: 
[[575  45]
 [125 115]]


### BERT-BERTweet-HateBERT

#### DynaHate

In [19]:
bert_bertweet_hatebert_multiplied_dynahate_train_dev = np.concatenate((bert_hatebert_bertweet_multiplied_dynahate_train, bert_hatebert_bertweet_multiplied_dynahate_dev))
bert_bertweet_hatebert_multiplied_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_multiplied_dynahate_train_dev, bert_bertweet_hatebert_multiplied_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_multiplied_dynahate_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_multiplied_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_bertweet_hatebert_multiplied_dynahate_seed_3")

save_model(mlp, "Saves/bert_bertweet_hatebert_multiplied_dynahate_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7270959377700951
Accuracy Test:  0.6774271844660195
Weighted F1 Train Dev:  0.725883298257661
Weighted F1 Test:  0.6764902469967116
Macro F1 Train Dev:  0.7235107426898552
Macro F1 Test:  0.6723874471311105
Micro F1 Train Dev:  0.7270959377700952
Micro F1 Test:  0.6774271844660195
Weighted Recall Train Dev:  0.7270959377700951
Weighted Recall Test:  0.6774271844660195
Macro Recall Train Dev:  0.7226183983718484
Macro Recall Test:  0.6717524502801681
Micro Recall Train Dev:  0.7270959377700951
Micro Recall Test:  0.6774271844660195
Confusion Matrix Train Dev: 
[[11352  5765]
 [ 4339 15568]]
Confusion Matrix Test: 
[[1140  712]
 [ 617 1651]]


#### LatentHatred

In [20]:
bert_bertweet_hatebert_multiplied_latenthatred_train_dev = np.concatenate((bert_hatebert_bertweet_multiplied_latenthatred_train, bert_hatebert_bertweet_multiplied_latenthatred_dev))
bert_bertweet_hatebert_multiplied_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_multiplied_latenthatred_train_dev, bert_bertweet_hatebert_multiplied_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_multiplied_latenthatred_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_multiplied_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_bertweet_hatebert_multiplied_latenthatred_seed_3")

save_model(mlp, "Saves/bert_bertweet_hatebert_multiplied_latenthatred_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7741154562383613
Accuracy Test:  0.7050279329608938
Weighted F1 Train Dev:  0.7591855032503969
Weighted F1 Test:  0.6863747011319468
Macro F1 Train Dev:  0.6050209277965567
Macro F1 Test:  0.5124896475292248
Micro F1 Train Dev:  0.7741154562383613
Micro F1 Test:  0.7050279329608938
Weighted Recall Train Dev:  0.7741154562383613
Weighted Recall Test:  0.7050279329608938
Macro Recall Train Dev:  0.5709637108896708
Macro Recall Test:  0.4936358640621181
Micro Recall Train Dev:  0.7741154562383613
Micro Recall Test:  0.7050279329608938
Confusion Matrix Train Dev: 
[[9044  883   18]
 [2038 3270   39]
 [ 280  381  157]]
Confusion Matrix Test: 
[[2890  439   17]
 [ 862  862   29]
 [ 108  129   34]]


#### OLID

In [21]:
bert_bertweet_hatebert_multiplied_olid_train_dev = np.concatenate((bert_hatebert_bertweet_multiplied_olid_train, bert_hatebert_bertweet_multiplied_olid_dev))
bert_bertweet_hatebert_multiplied_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_multiplied_olid_train_dev, bert_bertweet_hatebert_multiplied_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_multiplied_olid_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_multiplied_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_bertweet_hatebert_multiplied_olid_seed_3")

save_model(mlp, "Saves/bert_bertweet_hatebert_multiplied_olid_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.8029456193353475
Accuracy Test:  0.7930232558139535
Weighted F1 Train Dev:  0.7953743350133985
Weighted F1 Test:  0.7756326213530721
Macro F1 Train Dev:  0.7625136288653499
Macro F1 Test:  0.703801739884214
Micro F1 Train Dev:  0.8029456193353475
Micro F1 Test:  0.7930232558139535
Weighted Recall Train Dev:  0.8029456193353475
Weighted Recall Test:  0.7930232558139535
Macro Recall Train Dev:  0.748783422459893
Macro Recall Test:  0.6840725806451613
Micro Recall Train Dev:  0.8029456193353475
Micro Recall Test:  0.7930232558139535
Confusion Matrix Train Dev: 
[[8047  793]
 [1816 2584]]
Confusion Matrix Test: 
[[577  43]
 [135 105]]
