In [1]:
from utils import *
import numpy as np
import torch, os
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV

c:\Python310\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
set_random_seed(7)

Seed: 7


In [3]:
# def scaling_embeddings(embeddings):
#     for i in range(len(embeddings)):
#         embeddings[i] = StandardScaler().fit_transform(embeddings[i])
#     return embeddings

def reshape_embeddings(embeddings):
    if embeddings.shape[1] == 1:
        embeddings = embeddings.squeeze(1)
    return embeddings

In [4]:
def multiply_2_embeddings(embeddings1, embeddings2):
    embeddings1 = reshape_embeddings(embeddings1)
    embeddings2 = reshape_embeddings(embeddings2)
    # Numpy multiplication
    return np.multiply(embeddings1, embeddings2)

def multiply_3_embeddings(embeddings1, embeddings2, embeddings3):
    embeddings1 = reshape_embeddings(embeddings1)
    embeddings2 = reshape_embeddings(embeddings2)
    embeddings3 = reshape_embeddings(embeddings3)
    # Numpy multiplication
    return np.multiply(embeddings1, np.multiply(embeddings2, embeddings3))

In [5]:
bert_hatebert_multiplied_dynahate_train = multiply_2_embeddings(bert_dynahate_train_embeddings, hatebert_dynahate_train_embeddings)
bert_hatebert_multiplied_dynahate_dev = multiply_2_embeddings(bert_dynahate_dev_embeddings, hatebert_dynahate_dev_embeddings)
bert_hatebert_multiplied_dynahate_test = multiply_2_embeddings(bert_dynahate_test_embeddings, hatebert_dynahate_test_embeddings)

bert_bertweet_multiplied_dynahate_train = multiply_2_embeddings(bert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
bert_bertweet_multiplied_dynahate_dev = multiply_2_embeddings(bert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
bert_bertweet_multiplied_dynahate_test = multiply_2_embeddings(bert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

hatebert_bertweet_multiplied_dynahate_train = multiply_2_embeddings(hatebert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
hatebert_bertweet_multiplied_dynahate_dev = multiply_2_embeddings(hatebert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
hatebert_bertweet_multiplied_dynahate_test = multiply_2_embeddings(hatebert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

bert_hatebert_bertweet_multiplied_dynahate_train = multiply_3_embeddings(bert_dynahate_train_embeddings, hatebert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
bert_hatebert_bertweet_multiplied_dynahate_dev = multiply_3_embeddings(bert_dynahate_dev_embeddings, hatebert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
bert_hatebert_bertweet_multiplied_dynahate_test = multiply_3_embeddings(bert_dynahate_test_embeddings, hatebert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

bert_hatebert_multiplied_olid_train = multiply_2_embeddings(bert_olid_train_embeddings, hatebert_olid_train_embeddings)
bert_hatebert_multiplied_olid_dev = multiply_2_embeddings(bert_olid_dev_embeddings, hatebert_olid_dev_embeddings)
bert_hatebert_multiplied_olid_test = multiply_2_embeddings(bert_olid_test_embeddings, hatebert_olid_test_embeddings)

bert_bertweet_multiplied_olid_train = multiply_2_embeddings(bert_olid_train_embeddings, bertweet_olid_train_embeddings)
bert_bertweet_multiplied_olid_dev = multiply_2_embeddings(bert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
bert_bertweet_multiplied_olid_test = multiply_2_embeddings(bert_olid_test_embeddings, bertweet_olid_test_embeddings)

hatebert_bertweet_multiplied_olid_train = multiply_2_embeddings(hatebert_olid_train_embeddings, bertweet_olid_train_embeddings)
hatebert_bertweet_multiplied_olid_dev = multiply_2_embeddings(hatebert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
hatebert_bertweet_multiplied_olid_test = multiply_2_embeddings(hatebert_olid_test_embeddings, bertweet_olid_test_embeddings)

bert_hatebert_bertweet_multiplied_olid_train = multiply_3_embeddings(bert_olid_train_embeddings, hatebert_olid_train_embeddings, bertweet_olid_train_embeddings)
bert_hatebert_bertweet_multiplied_olid_dev = multiply_3_embeddings(bert_olid_dev_embeddings, hatebert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
bert_hatebert_bertweet_multiplied_olid_test = multiply_3_embeddings(bert_olid_test_embeddings, hatebert_olid_test_embeddings, bertweet_olid_test_embeddings)

bert_hatebert_multiplied_latenthatred_train = multiply_2_embeddings(bert_latenthatred_train_embeddings, hatebert_latenthatred_train_embeddings)
bert_hatebert_multiplied_latenthatred_dev = multiply_2_embeddings(bert_latenthatred_dev_embeddings, hatebert_latenthatred_dev_embeddings)
bert_hatebert_multiplied_latenthatred_test = multiply_2_embeddings(bert_latenthatred_test_embeddings, hatebert_latenthatred_test_embeddings)

bert_bertweet_multiplied_latenthatred_train = multiply_2_embeddings(bert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
bert_bertweet_multiplied_latenthatred_dev = multiply_2_embeddings(bert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
bert_bertweet_multiplied_latenthatred_test = multiply_2_embeddings(bert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

hatebert_bertweet_multiplied_latenthatred_train = multiply_2_embeddings(hatebert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
hatebert_bertweet_multiplied_latenthatred_dev = multiply_2_embeddings(hatebert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
hatebert_bertweet_multiplied_latenthatred_test = multiply_2_embeddings(hatebert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

bert_hatebert_bertweet_multiplied_latenthatred_train = multiply_3_embeddings(bert_latenthatred_train_embeddings, hatebert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
bert_hatebert_bertweet_multiplied_latenthatred_dev = multiply_3_embeddings(bert_latenthatred_dev_embeddings, hatebert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
bert_hatebert_bertweet_multiplied_latenthatred_test = multiply_3_embeddings(bert_latenthatred_test_embeddings, hatebert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

In [6]:
dynahate_labels_train = process_labels(read_labels("dynahate", "train"))
dynahate_labels_dev = process_labels(read_labels("dynahate", "dev"))
dynahate_labels_test = process_labels(read_labels("dynahate", "test"))

latenthatred_labels_train = read_labels("latenthatred", "train")
latenthatred_labels_dev = read_labels("latenthatred", "dev")
latenthatred_labels_test = read_labels("latenthatred", "test")

olid_labels_train = read_labels("olid", "train")
olid_labels_dev = read_labels("olid", "dev")
olid_labels_test = read_labels("olid", "test")

In [7]:
mlp = MLPClassifier(random_state=7)
gridsearch = GridSearchCV(
    mlp,
    param_grid={
        "hidden_layer_sizes": [(128), (128,64)],
        "activation": ["relu"],
        "solver": ["adam"],
        "learning_rate_init": [0.001, 0.0001],
        "learning_rate": ["adaptive"],
        "early_stopping": [True],
        "max_iter": [10000]
    },
    verbose=4,
    n_jobs=os.cpu_count()//3,
    cv=5,
)

In [8]:
dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))
latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))
olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

### BERT-BERTweet

#### DynaHate

In [9]:
bert_bertweet_multiplied_dynahate_train_dev = np.concatenate((bert_bertweet_multiplied_dynahate_train, bert_bertweet_multiplied_dynahate_dev))
bert_bertweet_multiplied_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_multiplied_dynahate_train_dev, bert_bertweet_multiplied_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_multiplied_dynahate_train_dev)
test_preds = mlp.predict(bert_bertweet_multiplied_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_bertweet_multiplied_dynahate_seed_7")
save_model(mlp, "Saves/bert_bertweet_multiplied_dynahate_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7621272687986171
Accuracy Test:  0.6555825242718447
Weighted F1 Train Dev:  0.7624575031321679
Weighted F1 Test:  0.6563858905283342
Macro F1 Train Dev:  0.7618841653657668
Macro F1 Test:  0.6551435099978522
Micro F1 Train Dev:  0.7621272687986171
Micro F1 Test:  0.6555825242718447
Weighted Recall Train Dev:  0.7621272687986171
Weighted Recall Test:  0.6555825242718447
Macro Recall Train Dev:  0.7640582441483705
Macro Recall Test:  0.6586953996061267
Micro Recall Train Dev:  0.7621272687986171
Micro Recall Test:  0.6555825242718447
Confusion Matrix Train Dev: 
[[13517  3600]
 [ 5207 14700]]
Confusion Matrix Test: 
[[1277  575]
 [ 844 1424]]


#### LatentHatred

In [10]:
bert_bertweet_multiplied_latenthatred_train_dev = np.concatenate((bert_bertweet_multiplied_latenthatred_train, bert_bertweet_multiplied_latenthatred_dev))
bert_bertweet_multiplied_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_multiplied_latenthatred_train_dev, bert_bertweet_multiplied_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_multiplied_latenthatred_train_dev)
test_preds = mlp.predict(bert_bertweet_multiplied_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_bertweet_multiplied_latenthatred_seed_7")
save_model(mlp, "Saves/bert_bertweet_multiplied_latenthatred_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7633767846058349
Accuracy Test:  0.6929236499068901
Weighted F1 Train Dev:  0.7494971443631945
Weighted F1 Test:  0.6746950668277012
Macro F1 Train Dev:  0.6101472763421486
Macro F1 Test:  0.5078609463519149
Micro F1 Train Dev:  0.7633767846058349
Micro F1 Test:  0.6929236499068901
Weighted Recall Train Dev:  0.7633767846058349
Weighted Recall Test:  0.6929236499068901
Macro Recall Train Dev:  0.5751394847022518
Macro Recall Test:  0.49018465246104626
Micro Recall Train Dev:  0.7633767846058349
Micro Recall Test:  0.6929236499068901
Confusion Matrix Train Dev: 
[[8980  931   34]
 [2146 3123   78]
 [ 339  284  195]]
Confusion Matrix Test: 
[[2872  448   26]
 [ 896  808   49]
 [ 112  118   41]]


#### OLID

In [11]:
bert_bertweet_multiplied_olid_train_dev = np.concatenate((bert_bertweet_multiplied_olid_train, bert_bertweet_multiplied_olid_dev))
bert_bertweet_multiplied_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_multiplied_olid_train_dev, bert_bertweet_multiplied_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_multiplied_olid_train_dev)
test_preds = mlp.predict(bert_bertweet_multiplied_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_bertweet_multiplied_olid_seed_7")

save_model(mlp, "Saves/bert_bertweet_multiplied_olid_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7766616314199396
Accuracy Test:  0.786046511627907
Weighted F1 Train Dev:  0.7660007456732917
Weighted F1 Test:  0.7721001618787737
Macro F1 Train Dev:  0.7269137657268695
Macro F1 Test:  0.7023684131331067
Micro F1 Train Dev:  0.7766616314199396
Micro F1 Test:  0.786046511627907
Weighted Recall Train Dev:  0.7766616314199396
Weighted Recall Test:  0.786046511627907
Macro Recall Train Dev:  0.7138039901275195
Macro Recall Test:  0.6856182795698925
Micro Recall Train Dev:  0.7766616314199396
Micro Recall Test:  0.786046511627907
Confusion Matrix Train Dev: 
[[7967  873]
 [2084 2316]]
Confusion Matrix Test: 
[[566  54]
 [130 110]]


### BERT-HateBERT

#### DynaHate

In [12]:
bert_hatebert_multiplied_dynahate_train_dev = np.concatenate((bert_hatebert_multiplied_dynahate_train, bert_hatebert_multiplied_dynahate_dev))
bert_hatebert_multiplied_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_multiplied_dynahate_train_dev, bert_hatebert_multiplied_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_multiplied_dynahate_train_dev)
test_preds = mlp.predict(bert_hatebert_multiplied_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_hatebert_multiplied_dynahate_seed_7")

save_model(mlp, "Saves/bert_hatebert_multiplied_dynahate_seed_7")



Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7265557476231633
Accuracy Test:  0.6771844660194175
Weighted F1 Train Dev:  0.7226675811641364
Weighted F1 Test:  0.6729315614391645
Macro F1 Train Dev:  0.7192562653085752
Macro F1 Test:  0.6670732557921938
Micro F1 Train Dev:  0.7265557476231633
Micro F1 Test:  0.6771844660194175
Weighted Recall Train Dev:  0.7265557476231633
Weighted Recall Test:  0.6771844660194175
Macro Recall Train Dev:  0.7184847438585567
Macro Recall Test:  0.6663819275410348
Micro Recall Train Dev:  0.7265557476231633
Micro Recall Test:  0.6771844660194175
Confusion Matrix Train Dev: 
[[10465  6652]
 [ 3472 16435]]
Confusion Matrix Test: 
[[1036  816]
 [ 514 1754]]


#### LatentHatred

In [13]:
bert_hatebert_multiplied_latenthatred_train_dev = np.concatenate((bert_hatebert_multiplied_latenthatred_train, bert_hatebert_multiplied_latenthatred_dev))
bert_hatebert_multiplied_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_multiplied_latenthatred_train_dev, bert_hatebert_multiplied_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_multiplied_latenthatred_train_dev)
test_preds = mlp.predict(bert_hatebert_multiplied_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_hatebert_multiplied_latenthatred_seed_7")

save_model(mlp, "Saves/bert_hatebert_multiplied_latenthatred_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7153941651148356
Accuracy Test:  0.6972067039106146
Weighted F1 Train Dev:  0.6942106835697914
Weighted F1 Test:  0.6755893285460162
Macro F1 Train Dev:  0.48833475817456784
Macro F1 Test:  0.4729291451827023
Micro F1 Train Dev:  0.7153941651148356
Micro F1 Test:  0.6972067039106146
Weighted Recall Train Dev:  0.7153941651148356
Weighted Recall Test:  0.6972067039106146
Macro Recall Train Dev:  0.48388907431585465
Macro Recall Test:  0.4674800856531944
Micro Recall Train Dev:  0.7153941651148356
Micro Recall Test:  0.6972067039106146
Confusion Matrix Train Dev: 
[[8546 1385   14]
 [2396 2945    6]
 [ 333  451   34]]
Confusion Matrix Test: 
[[2838  503    5]
 [ 856  894    3]
 [ 119  140   12]]


#### OLID

In [14]:
bert_hatebert_multiplied_olid_train_dev = np.concatenate((bert_hatebert_multiplied_olid_train, bert_hatebert_multiplied_olid_dev))
bert_hatebert_multiplied_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_multiplied_olid_train_dev, bert_hatebert_multiplied_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_multiplied_olid_train_dev)
test_preds = mlp.predict(bert_hatebert_multiplied_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_hatebert_multiplied_olid_seed_7")

save_model(mlp, "Saves/bert_hatebert_multiplied_olid_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7533232628398792
Accuracy Test:  0.7988372093023256
Weighted F1 Train Dev:  0.7325424156350877
Weighted F1 Test:  0.7693545362625241
Macro F1 Train Dev:  0.6820681478072577
Macro F1 Test:  0.6863662714097496
Micro F1 Train Dev:  0.7533232628398792
Micro F1 Test:  0.7988372093023256
Weighted Recall Train Dev:  0.7533232628398792
Weighted Recall Test:  0.7988372093023256
Macro Recall Train Dev:  0.6699007610037022
Macro Recall Test:  0.6638440860215054
Micro Recall Train Dev:  0.7533232628398792
Micro Recall Test:  0.7988372093023256
Confusion Matrix Train Dev: 
[[8121  719]
 [2547 1853]]
Confusion Matrix Test: 
[[601  19]
 [154  86]]


### BERTweet-HateBERT

#### DynaHate

In [15]:
hatebert_bertweet_multiplied_dynahate_train_dev = np.concatenate((hatebert_bertweet_multiplied_dynahate_train, hatebert_bertweet_multiplied_dynahate_dev))
hatebert_bertweet_multiplied_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_multiplied_dynahate_train_dev, hatebert_bertweet_multiplied_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_multiplied_dynahate_train_dev)
test_preds = mlp.predict(hatebert_bertweet_multiplied_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/hatebert_bertweet_multiplied_dynahate_seed_7")

save_model(mlp, "Saves/hatebert_bertweet_multiplied_dynahate_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7243409680207433
Accuracy Test:  0.6861650485436893
Weighted F1 Train Dev:  0.7242454438011822
Weighted F1 Test:  0.6867405954337112
Macro F1 Train Dev:  0.7225797402225869
Macro F1 Test:  0.6842722706270192
Micro F1 Train Dev:  0.7243409680207433
Micro F1 Test:  0.6861650485436893
Weighted Recall Train Dev:  0.7243409680207433
Weighted Recall Test:  0.6861650485436893
Macro Recall Train Dev:  0.7224391545357292
Macro Recall Test:  0.6853342208813771
Micro Recall Train Dev:  0.7243409680207433
Micro Recall Test:  0.6861650485436893
Confusion Matrix Train Dev: 
[[11934  5183]
 [ 5023 14884]]
Confusion Matrix Test: 
[[1254  598]
 [ 695 1573]]


#### LatentHatred

In [16]:
hatebert_bertweet_multiplied_latenthatred_train_dev = np.concatenate((hatebert_bertweet_multiplied_latenthatred_train, hatebert_bertweet_multiplied_latenthatred_dev))
hatebert_bertweet_multiplied_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_multiplied_latenthatred_train_dev, hatebert_bertweet_multiplied_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_multiplied_latenthatred_train_dev)
test_preds = mlp.predict(hatebert_bertweet_multiplied_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/hatebert_bertweet_multiplied_latenthatred_seed_7")

save_model(mlp, "Saves/hatebert_bertweet_multiplied_latenthatred_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7014897579143389
Accuracy Test:  0.6942271880819367
Weighted F1 Train Dev:  0.6594937368245172
Weighted F1 Test:  0.6501573523217258
Macro F1 Train Dev:  0.4344332572077865
Macro F1 Test:  0.4236403196224852
Micro F1 Train Dev:  0.7014897579143389
Micro F1 Test:  0.6942271880819367
Weighted Recall Train Dev:  0.7014897579143389
Weighted Recall Test:  0.6942271880819367
Macro Recall Train Dev:  0.43985548673182445
Macro Recall Test:  0.4299143603229869
Micro Recall Train Dev:  0.7014897579143389
Micro Recall Test:  0.6942271880819367
Confusion Matrix Train Dev: 
[[9230  715    0]
 [3279 2067    1]
 [ 488  326    4]]
Confusion Matrix Test: 
[[3093  253    0]
 [1119  634    0]
 [ 175   95    1]]


#### OLID

In [17]:
hatebert_bertweet_multiplied_olid_train_dev = np.concatenate((hatebert_bertweet_multiplied_olid_train, hatebert_bertweet_multiplied_olid_dev))
hatebert_bertweet_multiplied_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_multiplied_olid_train_dev, hatebert_bertweet_multiplied_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_multiplied_olid_train_dev)
test_preds = mlp.predict(hatebert_bertweet_multiplied_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/hatebert_bertweet_multiplied_olid_seed_7")

save_model(mlp, "Saves/hatebert_bertweet_multiplied_olid_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7843655589123867
Accuracy Test:  0.8116279069767441
Weighted F1 Train Dev:  0.7784809845932034
Weighted F1 Test:  0.8013725250341815
Macro F1 Train Dev:  0.7447680684936246
Macro F1 Test:  0.7423263865770025
Micro F1 Train Dev:  0.7843655589123867
Micro F1 Test:  0.8116279069767441
Weighted Recall Train Dev:  0.7843655589123867
Weighted Recall Test:  0.8116279069767441
Macro Recall Train Dev:  0.7349264705882352
Macro Recall Test:  0.7237903225806452
Micro Recall Train Dev:  0.7843655589123867
Micro Recall Test:  0.8116279069767441
Confusion Matrix Train Dev: 
[[7800 1040]
 [1815 2585]]
Confusion Matrix Test: 
[[572  48]
 [114 126]]


### BERT-BERTweet-HateBERT

#### DynaHate

In [18]:
bert_bertweet_hatebert_multiplied_dynahate_train_dev = np.concatenate((bert_hatebert_bertweet_multiplied_dynahate_train, bert_hatebert_bertweet_multiplied_dynahate_dev))
bert_bertweet_hatebert_multiplied_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_multiplied_dynahate_train_dev, bert_bertweet_hatebert_multiplied_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_multiplied_dynahate_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_multiplied_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_bertweet_hatebert_multiplied_dynahate_seed_7")

save_model(mlp, "Saves/bert_bertweet_hatebert_multiplied_dynahate_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7627484874675886
Accuracy Test:  0.6740291262135922
Weighted F1 Train Dev:  0.763005372075428
Weighted F1 Test:  0.674832096322329
Macro F1 Train Dev:  0.7619987596374058
Macro F1 Test:  0.6734797256128775
Micro F1 Train Dev:  0.7627484874675886
Micro F1 Test:  0.6740291262135922
Weighted Recall Train Dev:  0.7627484874675886
Weighted Recall Test:  0.6740291262135922
Macro Recall Train Dev:  0.7628509755618049
Macro Recall Test:  0.6767872855885815
Micro Recall Train Dev:  0.7627484874675886
Micro Recall Test:  0.6740291262135922
Confusion Matrix Train Dev: 
[[13081  4036]
 [ 4748 15159]]
Confusion Matrix Test: 
[[1304  548]
 [ 795 1473]]


#### LatentHatred

In [19]:
bert_bertweet_hatebert_multiplied_latenthatred_train_dev = np.concatenate((bert_hatebert_bertweet_multiplied_latenthatred_train, bert_hatebert_bertweet_multiplied_latenthatred_dev))
bert_bertweet_hatebert_multiplied_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_multiplied_latenthatred_train_dev, bert_bertweet_hatebert_multiplied_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_multiplied_latenthatred_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_multiplied_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_bertweet_hatebert_multiplied_latenthatred_seed_7")

save_model(mlp, "Saves/bert_bertweet_hatebert_multiplied_latenthatred_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.7095592799503414
Accuracy Test:  0.6966480446927374
Weighted F1 Train Dev:  0.6757358770726692
Weighted F1 Test:  0.6595785845129077
Macro F1 Train Dev:  0.47073886232245093
Macro F1 Test:  0.4510222965033594
Micro F1 Train Dev:  0.7095592799503414
Micro F1 Test:  0.6966480446927374
Weighted Recall Train Dev:  0.7095592799503414
Weighted Recall Test:  0.6966480446927374
Macro Recall Train Dev:  0.46301110391705474
Macro Recall Test:  0.4460904533454655
Micro Recall Train Dev:  0.7095592799503414
Micro Recall Test:  0.6966480446927374
Confusion Matrix Train Dev: 
[[9091  849    5]
 [3037 2304    6]
 [ 449  333   36]]
Confusion Matrix Test: 
[[3045  298    3]
 [1065  686    2]
 [ 161  100   10]]


#### OLID

In [20]:
bert_bertweet_hatebert_multiplied_olid_train_dev = np.concatenate((bert_hatebert_bertweet_multiplied_olid_train, bert_hatebert_bertweet_multiplied_olid_dev))
bert_bertweet_hatebert_multiplied_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_multiplied_olid_train_dev, bert_bertweet_hatebert_multiplied_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_multiplied_olid_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_multiplied_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_bertweet_hatebert_multiplied_olid_seed_7")

save_model(mlp, "Saves/bert_bertweet_hatebert_multiplied_olid_seed_7")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.8097432024169184
Accuracy Test:  0.7872093023255814
Weighted F1 Train Dev:  0.7981322801255034
Weighted F1 Test:  0.76271734364365
Macro F1 Train Dev:  0.762701012102216
Macro F1 Test:  0.6817873932163979
Micro F1 Train Dev:  0.8097432024169184
Micro F1 Test:  0.7872093023255814
Weighted Recall Train Dev:  0.8097432024169184
Weighted Recall Test:  0.7872093023255814
Macro Recall Train Dev:  0.744114047716989
Macro Recall Test:  0.6621639784946236
Micro Recall Train Dev:  0.8097432024169184
Micro Recall Test:  0.7872093023255814
Confusion Matrix Train Dev: 
[[8308  532]
 [1987 2413]]
Confusion Matrix Test: 
[[586  34]
 [149  91]]
