In [1]:
from utils import *
import numpy as np
import torch, os
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV

In [2]:
set_random_seed(3)

Seed: 3


In [3]:
# def scaling_embeddings(embeddings):
#     for i in range(len(embeddings)):
#         embeddings[i] = StandardScaler().fit_transform(embeddings[i])
#     return embeddings

def reshape_embeddings(embeddings):
    if embeddings.shape[1] == 1:
        embeddings = embeddings.squeeze(1)
    return embeddings

In [4]:
import random

def randomlycombined_2_embeddings(embeddings1, embeddings2):
    embeddings1 = reshape_embeddings(embeddings1)
    embeddings2 = reshape_embeddings(embeddings2)
    # new_embeddings = []
    # for i in range(len(embeddings1)):
    #     embedding = []
    #     elements = list(range(len(embeddings1[i])+len(embeddings2[i])))
    #     random.shuffle(elements)
    #     for j in elements:
    #         if j < len(embeddings1[i]):
    #             embedding.append(embeddings1[i][j])
    #         else:
    #             embedding.append(embeddings2[i][j-len(embeddings1[i])])
    #     new_embeddings.append(np.array(embedding))
    new_embeddings = np.concatenate((embeddings1, embeddings2), axis=1)
    # Shuffle values
    np.random.shuffle(new_embeddings)
    return np.array(new_embeddings)

def randomlycombined_3_embeddings(embeddings1, embeddings2, embeddings3):
    embeddings1 = reshape_embeddings(embeddings1)
    embeddings2 = reshape_embeddings(embeddings2)
    embeddings3 = reshape_embeddings(embeddings3)
    # new_embeddings = []
    # for i in range(len(embeddings1)):
    #     embedding = []
    #     elements = list(range(len(embeddings1[i])+len(embeddings2[i])+len(embeddings3[i])))
    #     random.shuffle(elements)
    #     for j in elements:
    #         if j < len(embeddings1[i]):
    #             embedding.append(embeddings1[i][j])
    #         elif j < len(embeddings1[i])+len(embeddings2[i]):
    #             embedding.append(embeddings2[i][j-len(embeddings1[i])])
    #         else:
    #             embedding.append(embeddings3[i][j-len(embeddings1[i])-len(embeddings2[i])])
    #     new_embeddings.append(np.array(embedding))
    new_embeddings = np.concatenate((embeddings1, embeddings2, embeddings3), axis=1)
    # Shuffle values
    np.random.shuffle(new_embeddings)
    return np.array(new_embeddings)

In [5]:
bert_hatebert_randomlycombined_dynahate_train = randomlycombined_2_embeddings(bert_dynahate_train_embeddings, hatebert_dynahate_train_embeddings)
bert_hatebert_randomlycombined_dynahate_dev = randomlycombined_2_embeddings(bert_dynahate_dev_embeddings, hatebert_dynahate_dev_embeddings)
bert_hatebert_randomlycombined_dynahate_test = randomlycombined_2_embeddings(bert_dynahate_test_embeddings, hatebert_dynahate_test_embeddings)

bert_bertweet_randomlycombined_dynahate_train = randomlycombined_2_embeddings(bert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
bert_bertweet_randomlycombined_dynahate_dev = randomlycombined_2_embeddings(bert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
bert_bertweet_randomlycombined_dynahate_test = randomlycombined_2_embeddings(bert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

hatebert_bertweet_randomlycombined_dynahate_train = randomlycombined_2_embeddings(hatebert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
hatebert_bertweet_randomlycombined_dynahate_dev = randomlycombined_2_embeddings(hatebert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
hatebert_bertweet_randomlycombined_dynahate_test = randomlycombined_2_embeddings(hatebert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

bert_hatebert_bertweet_randomlycombined_dynahate_train = randomlycombined_3_embeddings(bert_dynahate_train_embeddings, hatebert_dynahate_train_embeddings, bertweet_dynahate_train_embeddings)
bert_hatebert_bertweet_randomlycombined_dynahate_dev = randomlycombined_3_embeddings(bert_dynahate_dev_embeddings, hatebert_dynahate_dev_embeddings, bertweet_dynahate_dev_embeddings)
bert_hatebert_bertweet_randomlycombined_dynahate_test = randomlycombined_3_embeddings(bert_dynahate_test_embeddings, hatebert_dynahate_test_embeddings, bertweet_dynahate_test_embeddings)

bert_hatebert_randomlycombined_olid_train = randomlycombined_2_embeddings(bert_olid_train_embeddings, hatebert_olid_train_embeddings)
bert_hatebert_randomlycombined_olid_dev = randomlycombined_2_embeddings(bert_olid_dev_embeddings, hatebert_olid_dev_embeddings)
bert_hatebert_randomlycombined_olid_test = randomlycombined_2_embeddings(bert_olid_test_embeddings, hatebert_olid_test_embeddings)

bert_bertweet_randomlycombined_olid_train = randomlycombined_2_embeddings(bert_olid_train_embeddings, bertweet_olid_train_embeddings)
bert_bertweet_randomlycombined_olid_dev = randomlycombined_2_embeddings(bert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
bert_bertweet_randomlycombined_olid_test = randomlycombined_2_embeddings(bert_olid_test_embeddings, bertweet_olid_test_embeddings)

hatebert_bertweet_randomlycombined_olid_train = randomlycombined_2_embeddings(hatebert_olid_train_embeddings, bertweet_olid_train_embeddings)
hatebert_bertweet_randomlycombined_olid_dev = randomlycombined_2_embeddings(hatebert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
hatebert_bertweet_randomlycombined_olid_test = randomlycombined_2_embeddings(hatebert_olid_test_embeddings, bertweet_olid_test_embeddings)

bert_hatebert_bertweet_randomlycombined_olid_train = randomlycombined_3_embeddings(bert_olid_train_embeddings, hatebert_olid_train_embeddings, bertweet_olid_train_embeddings)
bert_hatebert_bertweet_randomlycombined_olid_dev = randomlycombined_3_embeddings(bert_olid_dev_embeddings, hatebert_olid_dev_embeddings, bertweet_olid_dev_embeddings)
bert_hatebert_bertweet_randomlycombined_olid_test = randomlycombined_3_embeddings(bert_olid_test_embeddings, hatebert_olid_test_embeddings, bertweet_olid_test_embeddings)

bert_hatebert_randomlycombined_latenthatred_train = randomlycombined_2_embeddings(bert_latenthatred_train_embeddings, hatebert_latenthatred_train_embeddings)
bert_hatebert_randomlycombined_latenthatred_dev = randomlycombined_2_embeddings(bert_latenthatred_dev_embeddings, hatebert_latenthatred_dev_embeddings)
bert_hatebert_randomlycombined_latenthatred_test = randomlycombined_2_embeddings(bert_latenthatred_test_embeddings, hatebert_latenthatred_test_embeddings)

bert_bertweet_randomlycombined_latenthatred_train = randomlycombined_2_embeddings(bert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
bert_bertweet_randomlycombined_latenthatred_dev = randomlycombined_2_embeddings(bert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
bert_bertweet_randomlycombined_latenthatred_test = randomlycombined_2_embeddings(bert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

hatebert_bertweet_randomlycombined_latenthatred_train = randomlycombined_2_embeddings(hatebert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
hatebert_bertweet_randomlycombined_latenthatred_dev = randomlycombined_2_embeddings(hatebert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
hatebert_bertweet_randomlycombined_latenthatred_test = randomlycombined_2_embeddings(hatebert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

bert_hatebert_bertweet_randomlycombined_latenthatred_train = randomlycombined_3_embeddings(bert_latenthatred_train_embeddings, hatebert_latenthatred_train_embeddings, bertweet_latenthatred_train_embeddings)
bert_hatebert_bertweet_randomlycombined_latenthatred_dev = randomlycombined_3_embeddings(bert_latenthatred_dev_embeddings, hatebert_latenthatred_dev_embeddings, bertweet_latenthatred_dev_embeddings)
bert_hatebert_bertweet_randomlycombined_latenthatred_test = randomlycombined_3_embeddings(bert_latenthatred_test_embeddings, hatebert_latenthatred_test_embeddings, bertweet_latenthatred_test_embeddings)

In [6]:
bert_hatebert_randomlycombined_dynahate_train.shape

(32924, 1536)

In [7]:
dynahate_labels_train = process_labels(read_labels("dynahate", "train"))
dynahate_labels_dev = process_labels(read_labels("dynahate", "dev"))
dynahate_labels_test = process_labels(read_labels("dynahate", "test"))

latenthatred_labels_train = read_labels("latenthatred", "train")
latenthatred_labels_dev = read_labels("latenthatred", "dev")
latenthatred_labels_test = read_labels("latenthatred", "test")

olid_labels_train = read_labels("olid", "train")
olid_labels_dev = read_labels("olid", "dev")
olid_labels_test = read_labels("olid", "test")

In [8]:
len(dynahate_labels_train)

32924

In [9]:
mlp = MLPClassifier(random_state=3)
gridsearch = GridSearchCV(
    mlp,
    param_grid={
        "hidden_layer_sizes": [(128), (128,64)],
        "activation": ["relu"],
        "solver": ["adam"],
        "learning_rate_init": [0.001, 0.0001],
        "learning_rate": ["adaptive"],
        "early_stopping": [True],
        "max_iter": [10000]
    },
    verbose=4,
    n_jobs=os.cpu_count()//3,
    cv=5
)

In [10]:
dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))
latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))
olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

### BERT-BERTweet

#### DynaHate

In [11]:
bert_bertweet_randomlycombined_dynahate_train_dev = np.concatenate((bert_bertweet_randomlycombined_dynahate_train, bert_bertweet_randomlycombined_dynahate_dev))
bert_bertweet_randomlycombined_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_randomlycombined_dynahate_train_dev, dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_randomlycombined_dynahate_train_dev)
test_preds = mlp.predict(bert_bertweet_randomlycombined_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_bertweet_randomlycombined_dynahate_seed_3")
save_model(mlp, "Saves/bert_bertweet_randomlycombined_dynahate_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.538812662057044
Accuracy Test:  0.5519417475728156
Weighted F1 Train Dev:  0.3834773659375844
Weighted F1 Test:  0.39757309923045403
Macro F1 Train Dev:  0.35778308265227626
Macro F1 Test:  0.36248164692967677
Micro F1 Train Dev:  0.538812662057044
Micro F1 Test:  0.5519417475728156
Weighted Recall Train Dev:  0.538812662057044
Weighted Recall Test:  0.5519417475728156
Macro Recall Train Dev:  0.501652619540946
Macro Recall Test:  0.502016029193855
Micro Recall Train Dev:  0.538812662057044
Micro Recall Test:  0.5519417475728156
Confusion Matrix Train Dev: 
[[  146 16971]
 [  104 19803]]
Confusion Matrix Test: 
[[  14 1838]
 [   8 2260]]


In [12]:
len(dynahate_labels_train_dev)

37024

In [13]:
len(bert_bertweet_randomlycombined_dynahate_train), len(bert_bertweet_randomlycombined_dynahate_dev)

(32924, 4100)

#### LatentHatred

In [14]:
bert_bertweet_randomlycombined_latenthatred_train_dev = np.concatenate((bert_bertweet_randomlycombined_latenthatred_train, bert_bertweet_randomlycombined_latenthatred_dev))
bert_bertweet_randomlycombined_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_randomlycombined_latenthatred_train_dev, bert_bertweet_randomlycombined_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_randomlycombined_latenthatred_train_dev)
test_preds = mlp.predict(bert_bertweet_randomlycombined_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_bertweet_randomlycombined_latenthatred_seed_3")
save_model(mlp, "Saves/bert_bertweet_randomlycombined_latenthatred_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.61731843575419
Accuracy Test:  0.6230912476722532
Weighted F1 Train Dev:  0.471251724703544
Weighted F1 Test:  0.47839910846979333
Macro F1 Train Dev:  0.25446171560161196
Macro F1 Test:  0.25592779562490436
Micro F1 Train Dev:  0.61731843575419
Micro F1 Test:  0.6230912476722532
Weighted Recall Train Dev:  0.61731843575419
Weighted Recall Test:  0.6230912476722532
Macro Recall Train Dev:  0.3333333333333333
Macro Recall Test:  0.3333333333333333
Micro Recall Train Dev:  0.61731843575419
Micro Recall Test:  0.6230912476722532
Confusion Matrix Train Dev: 
[[9945    0    0]
 [5347    0    0]
 [ 818    0    0]]
Confusion Matrix Test: 
[[3346    0    0]
 [1753    0    0]
 [ 271    0    0]]


#### OLID

In [15]:
bert_bertweet_randomlycombined_olid_train_dev = np.concatenate((bert_bertweet_randomlycombined_olid_train, bert_bertweet_randomlycombined_olid_dev))
bert_bertweet_randomlycombined_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_randomlycombined_olid_train_dev, bert_bertweet_randomlycombined_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_randomlycombined_olid_train_dev)
test_preds = mlp.predict(bert_bertweet_randomlycombined_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_bertweet_randomlycombined_olid_seed_3")

save_model(mlp, "Saves/bert_bertweet_randomlycombined_olid_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.6676737160120846
Accuracy Test:  0.7209302325581395
Weighted F1 Train Dev:  0.5346227943430097
Weighted F1 Test:  0.6040226272784412
Macro F1 Train Dev:  0.4003623188405797
Macro F1 Test:  0.4189189189189189
Micro F1 Train Dev:  0.6676737160120846
Micro F1 Test:  0.7209302325581395
Weighted Recall Train Dev:  0.6676737160120846
Weighted Recall Test:  0.7209302325581395
Macro Recall Train Dev:  0.5
Macro Recall Test:  0.5
Micro Recall Train Dev:  0.6676737160120846
Micro Recall Test:  0.7209302325581395
Confusion Matrix Train Dev: 
[[8840    0]
 [4400    0]]
Confusion Matrix Test: 
[[620   0]
 [240   0]]


### BERT-HateBERT

#### DynaHate

In [16]:
bert_hatebert_randomlycombined_dynahate_train_dev = np.concatenate((bert_hatebert_randomlycombined_dynahate_train, bert_hatebert_randomlycombined_dynahate_dev))
bert_hatebert_randomlycombined_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_randomlycombined_dynahate_train_dev, bert_hatebert_randomlycombined_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_randomlycombined_dynahate_train_dev)
test_preds = mlp.predict(bert_hatebert_randomlycombined_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_hatebert_randomlycombined_dynahate_seed_3")

save_model(mlp, "Saves/bert_hatebert_randomlycombined_dynahate_seed_3")



Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.5377322817631807
Accuracy Test:  0.5504854368932038
Weighted F1 Train Dev:  0.37642965923534055
Weighted F1 Test:  0.3908894711564766
Macro F1 Train Dev:  0.35011647927552797
Macro F1 Test:  0.3550407013149655
Micro F1 Train Dev:  0.5377322817631807
Micro F1 Test:  0.5504854368932038
Weighted Recall Train Dev:  0.5377322817631807
Weighted Recall Test:  0.5504854368932038
Macro Recall Train Dev:  0.5000829850509021
Macro Recall Test:  0.5
Micro Recall Train Dev:  0.5377322817631807
Micro Recall Test:  0.5504854368932038
Confusion Matrix Train Dev: 
[[    8 17109]
 [    6 19901]]
Confusion Matrix Test: 
[[   0 1852]
 [   0 2268]]


#### LatentHatred

In [17]:
bert_hatebert_randomlycombined_latenthatred_train_dev = np.concatenate((bert_hatebert_randomlycombined_latenthatred_train, bert_hatebert_randomlycombined_latenthatred_dev))
bert_hatebert_randomlycombined_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_randomlycombined_latenthatred_train_dev, bert_hatebert_randomlycombined_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_randomlycombined_latenthatred_train_dev)
test_preds = mlp.predict(bert_hatebert_randomlycombined_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_hatebert_randomlycombined_latenthatred_seed_3")

save_model(mlp, "Saves/bert_hatebert_randomlycombined_latenthatred_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.61731843575419
Accuracy Test:  0.6230912476722532
Weighted F1 Train Dev:  0.471251724703544
Weighted F1 Test:  0.47839910846979333
Macro F1 Train Dev:  0.25446171560161196
Macro F1 Test:  0.25592779562490436
Micro F1 Train Dev:  0.61731843575419
Micro F1 Test:  0.6230912476722532
Weighted Recall Train Dev:  0.61731843575419
Weighted Recall Test:  0.6230912476722532
Macro Recall Train Dev:  0.3333333333333333
Macro Recall Test:  0.3333333333333333
Micro Recall Train Dev:  0.61731843575419
Micro Recall Test:  0.6230912476722532
Confusion Matrix Train Dev: 
[[9945    0    0]
 [5347    0    0]
 [ 818    0    0]]
Confusion Matrix Test: 
[[3346    0    0]
 [1753    0    0]
 [ 271    0    0]]


#### OLID

In [18]:
bert_hatebert_randomlycombined_olid_train_dev = np.concatenate((bert_hatebert_randomlycombined_olid_train, bert_hatebert_randomlycombined_olid_dev))
bert_hatebert_randomlycombined_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_hatebert_randomlycombined_olid_train_dev, bert_hatebert_randomlycombined_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_hatebert_randomlycombined_olid_train_dev)
test_preds = mlp.predict(bert_hatebert_randomlycombined_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_hatebert_randomlycombined_olid_seed_3")

save_model(mlp, "Saves/bert_hatebert_randomlycombined_olid_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.6676737160120846
Accuracy Test:  0.7209302325581395
Weighted F1 Train Dev:  0.5346227943430097
Weighted F1 Test:  0.6040226272784412
Macro F1 Train Dev:  0.4003623188405797
Macro F1 Test:  0.4189189189189189
Micro F1 Train Dev:  0.6676737160120846
Micro F1 Test:  0.7209302325581395
Weighted Recall Train Dev:  0.6676737160120846
Weighted Recall Test:  0.7209302325581395
Macro Recall Train Dev:  0.5
Macro Recall Test:  0.5
Micro Recall Train Dev:  0.6676737160120846
Micro Recall Test:  0.7209302325581395
Confusion Matrix Train Dev: 
[[8840    0]
 [4400    0]]
Confusion Matrix Test: 
[[620   0]
 [240   0]]


### BERTweet-HateBERT

#### DynaHate

In [19]:
hatebert_bertweet_randomlycombined_dynahate_train_dev = np.concatenate((hatebert_bertweet_randomlycombined_dynahate_train, hatebert_bertweet_randomlycombined_dynahate_dev))
hatebert_bertweet_randomlycombined_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_randomlycombined_dynahate_train_dev, hatebert_bertweet_randomlycombined_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_randomlycombined_dynahate_train_dev)
test_preds = mlp.predict(hatebert_bertweet_randomlycombined_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/hatebert_bertweet_randomlycombined_dynahate_seed_3")

save_model(mlp, "Saves/hatebert_bertweet_randomlycombined_dynahate_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.5376782627484875
Accuracy Test:  0.5504854368932038
Weighted F1 Train Dev:  0.3760187306224777
Weighted F1 Test:  0.3908894711564766
Macro F1 Train Dev:  0.3496688974372486
Macro F1 Test:  0.3550407013149655
Micro F1 Train Dev:  0.5376782627484875
Micro F1 Test:  0.5504854368932038
Weighted Recall Train Dev:  0.5376782627484875
Weighted Recall Test:  0.5504854368932038
Macro Recall Train Dev:  0.5
Macro Recall Test:  0.5
Micro Recall Train Dev:  0.5376782627484875
Micro Recall Test:  0.5504854368932038
Confusion Matrix Train Dev: 
[[    0 17117]
 [    0 19907]]
Confusion Matrix Test: 
[[   0 1852]
 [   0 2268]]


#### LatentHatred

In [20]:
hatebert_bertweet_randomlycombined_latenthatred_train_dev = np.concatenate((hatebert_bertweet_randomlycombined_latenthatred_train, hatebert_bertweet_randomlycombined_latenthatred_dev))
hatebert_bertweet_randomlycombined_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_randomlycombined_latenthatred_train_dev, hatebert_bertweet_randomlycombined_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_randomlycombined_latenthatred_train_dev)
test_preds = mlp.predict(hatebert_bertweet_randomlycombined_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/hatebert_bertweet_randomlycombined_latenthatred_seed_3")

save_model(mlp, "Saves/hatebert_bertweet_randomlycombined_latenthatred_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.61731843575419
Accuracy Test:  0.6230912476722532
Weighted F1 Train Dev:  0.471251724703544
Weighted F1 Test:  0.47839910846979333
Macro F1 Train Dev:  0.25446171560161196
Macro F1 Test:  0.25592779562490436
Micro F1 Train Dev:  0.61731843575419
Micro F1 Test:  0.6230912476722532
Weighted Recall Train Dev:  0.61731843575419
Weighted Recall Test:  0.6230912476722532
Macro Recall Train Dev:  0.3333333333333333
Macro Recall Test:  0.3333333333333333
Micro Recall Train Dev:  0.61731843575419
Micro Recall Test:  0.6230912476722532
Confusion Matrix Train Dev: 
[[9945    0    0]
 [5347    0    0]
 [ 818    0    0]]
Confusion Matrix Test: 
[[3346    0    0]
 [1753    0    0]
 [ 271    0    0]]


#### OLID

In [21]:
hatebert_bertweet_randomlycombined_olid_train_dev = np.concatenate((hatebert_bertweet_randomlycombined_olid_train, hatebert_bertweet_randomlycombined_olid_dev))
hatebert_bertweet_randomlycombined_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(hatebert_bertweet_randomlycombined_olid_train_dev, hatebert_bertweet_randomlycombined_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(hatebert_bertweet_randomlycombined_olid_train_dev)
test_preds = mlp.predict(hatebert_bertweet_randomlycombined_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/hatebert_bertweet_randomlycombined_olid_seed_3")

save_model(mlp, "Saves/hatebert_bertweet_randomlycombined_olid_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.6676737160120846
Accuracy Test:  0.7209302325581395
Weighted F1 Train Dev:  0.5346227943430097
Weighted F1 Test:  0.6040226272784412
Macro F1 Train Dev:  0.4003623188405797
Macro F1 Test:  0.4189189189189189
Micro F1 Train Dev:  0.6676737160120846
Micro F1 Test:  0.7209302325581395
Weighted Recall Train Dev:  0.6676737160120846
Weighted Recall Test:  0.7209302325581395
Macro Recall Train Dev:  0.5
Macro Recall Test:  0.5
Micro Recall Train Dev:  0.6676737160120846
Micro Recall Test:  0.7209302325581395
Confusion Matrix Train Dev: 
[[8840    0]
 [4400    0]]
Confusion Matrix Test: 
[[620   0]
 [240   0]]


### BERT-BERTweet-HateBERT

#### DynaHate

In [22]:
bert_bertweet_hatebert_randomlycombined_dynahate_train_dev = np.concatenate((bert_hatebert_bertweet_randomlycombined_dynahate_train, bert_hatebert_bertweet_randomlycombined_dynahate_dev))
bert_bertweet_hatebert_randomlycombined_dynahate_labels_train_dev = np.concatenate((dynahate_labels_train, dynahate_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_randomlycombined_dynahate_train_dev, bert_bertweet_hatebert_randomlycombined_dynahate_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_randomlycombined_dynahate_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_randomlycombined_dynahate_test)

computeAllScores(train_dev_preds, test_preds, dynahate_labels_train_dev, dynahate_labels_test, "Results/bert_bertweet_hatebert_randomlycombined_dynahate_seed_3")

save_model(mlp, "Saves/bert_bertweet_hatebert_randomlycombined_dynahate_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.0001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.5377592912705272
Accuracy Test:  0.5504854368932038
Weighted F1 Train Dev:  0.37620057475830937
Weighted F1 Test:  0.3908894711564766
Macro F1 Train Dev:  0.34986255798437643
Macro F1 Test:  0.3550407013149655
Micro F1 Train Dev:  0.5377592912705272
Micro F1 Test:  0.5504854368932038
Weighted Recall Train Dev:  0.5377592912705272
Weighted Recall Test:  0.5504854368932038
Macro Recall Train Dev:  0.5000876321785359
Macro Recall Test:  0.5
Micro Recall Train Dev:  0.5377592912705272
Micro Recall Test:  0.5504854368932038
Confusion Matrix Train Dev: 
[[    3 17114]
 [    0 19907]]
Confusion Matrix Test: 
[[   0 1852]
 [   0 2268]]


#### LatentHatred

In [23]:
bert_bertweet_hatebert_randomlycombined_latenthatred_train_dev = np.concatenate((bert_hatebert_bertweet_randomlycombined_latenthatred_train, bert_hatebert_bertweet_randomlycombined_latenthatred_dev))
bert_bertweet_hatebert_randomlycombined_latenthatred_labels_train_dev = np.concatenate((latenthatred_labels_train, latenthatred_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_randomlycombined_latenthatred_train_dev, bert_bertweet_hatebert_randomlycombined_latenthatred_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_randomlycombined_latenthatred_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_randomlycombined_latenthatred_test)

computeAllScores(train_dev_preds, test_preds, latenthatred_labels_train_dev, latenthatred_labels_test, "Results/bert_bertweet_hatebert_randomlycombined_latenthatred_seed_3")

save_model(mlp, "Saves/bert_bertweet_hatebert_randomlycombined_latenthatred_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': (128, 64), 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.61731843575419
Accuracy Test:  0.6230912476722532
Weighted F1 Train Dev:  0.471251724703544
Weighted F1 Test:  0.47839910846979333
Macro F1 Train Dev:  0.25446171560161196
Macro F1 Test:  0.25592779562490436
Micro F1 Train Dev:  0.61731843575419
Micro F1 Test:  0.6230912476722532
Weighted Recall Train Dev:  0.61731843575419
Weighted Recall Test:  0.6230912476722532
Macro Recall Train Dev:  0.3333333333333333
Macro Recall Test:  0.3333333333333333
Micro Recall Train Dev:  0.61731843575419
Micro Recall Test:  0.6230912476722532
Confusion Matrix Train Dev: 
[[9945    0    0]
 [5347    0    0]
 [ 818    0    0]]
Confusion Matrix Test: 
[[3346    0    0]
 [1753    0    0]
 [ 271    0    0]]


#### OLID

In [24]:
bert_bertweet_hatebert_randomlycombined_olid_train_dev = np.concatenate((bert_hatebert_bertweet_randomlycombined_olid_train, bert_hatebert_bertweet_randomlycombined_olid_dev))
bert_bertweet_hatebert_randomlycombined_olid_labels_train_dev = np.concatenate((olid_labels_train, olid_labels_dev))

grid_results = gridsearch.fit(bert_bertweet_hatebert_randomlycombined_olid_train_dev, bert_bertweet_hatebert_randomlycombined_olid_labels_train_dev)

best_params = grid_results.best_params_
mlp = grid_results.best_estimator_

print("Best params: ", best_params)

train_dev_preds = mlp.predict(bert_bertweet_hatebert_randomlycombined_olid_train_dev)
test_preds = mlp.predict(bert_hatebert_bertweet_randomlycombined_olid_test)

computeAllScores(train_dev_preds, test_preds, olid_labels_train_dev, olid_labels_test, "Results/bert_bertweet_hatebert_randomlycombined_olid_seed_3")

save_model(mlp, "Saves/bert_bertweet_hatebert_randomlycombined_olid_seed_3")

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best params:  {'activation': 'relu', 'early_stopping': True, 'hidden_layer_sizes': 128, 'learning_rate': 'adaptive', 'learning_rate_init': 0.001, 'max_iter': 10000, 'solver': 'adam'}
Accuracy Train Dev:  0.6676737160120846
Accuracy Test:  0.7209302325581395
Weighted F1 Train Dev:  0.5346227943430097
Weighted F1 Test:  0.6040226272784412
Macro F1 Train Dev:  0.4003623188405797
Macro F1 Test:  0.4189189189189189
Micro F1 Train Dev:  0.6676737160120846
Micro F1 Test:  0.7209302325581395
Weighted Recall Train Dev:  0.6676737160120846
Weighted Recall Test:  0.7209302325581395
Macro Recall Train Dev:  0.5
Macro Recall Test:  0.5
Micro Recall Train Dev:  0.6676737160120846
Micro Recall Test:  0.7209302325581395
Confusion Matrix Train Dev: 
[[8840    0]
 [4400    0]]
Confusion Matrix Test: 
[[620   0]
 [240   0]]
